export const DERBY_VERSION = '0.1.0';

export const DERBY_STATS = ['speed', 'stamina', 'burst', 'nerve', 'gate', 'grit'] as const;

export const DERBY_TRACKS = [
  {
    id: 'el-segundo-sprint',
    label: 'El Segundo Sprint',
    code: 'ES-1200',
    distance: 1200,
    going: 'fast dirt',
    par: 71.2,
    bias: {
      speed: 1.24,
      stamina: 0.76,
      burst: 1.08,
      nerve: 0.82,
      gate: 1.18,
      grit: 0.72,
    },
  },
  {
    id: 'wire-mile',
    label: 'Wire Mile',
    code: 'WR-1600',
    distance: 1600,
    going: 'firm rail',
    par: 98.6,
    bias: {
      speed: 1.02,
      stamina: 1.0,
      burst: 0.96,
      nerve: 1.12,
      gate: 0.88,
      grit: 0.94,
    },
  },
  {
    id: 'fog-route',
    label: 'Fog Route',
    code: 'FG-1800',
    distance: 1800,
    going: 'cold mist',
    par: 113.8,
    bias: {
      speed: 0.82,
      stamina: 1.28,
      burst: 0.88,
      nerve: 1.18,
      gate: 0.72,
      grit: 1.12,
    },
  },
  {
    id: 'dune-night',
    label: 'Dune Night',
    code: 'DN-1000',
    distance: 1000,
    going: 'loose sand',
    par: 61.5,
    bias: {
      speed: 0.96,
      stamina: 0.9,
      burst: 1.24,
      nerve: 0.96,
      gate: 1.1,
      grit: 1.18,
    },
  },
] as const;

export const DERBY_ROSTER = [
  {
    slug: 'codex-cantor',
    name: 'Codex Cantor',
    agent: 'Codex',
    stable: 'Patch Barn',
    bloodline: 'Compiler x Morning Wire',
    coat: '#185fa5',
    accent: '#f4b23f',
    stats: { speed: 88, stamina: 78, burst: 84, nerve: 91, gate: 72, grit: 80 },
  },
  {
    slug: 'claude-longshot',
    name: 'Claude Longshot',
    agent: 'Claude',
    stable: 'Opus Yard',
    bloodline: 'Deep Read x Orchard Signal',
    coat: '#c85b3b',
    accent: '#fff1cb',
    stats: { speed: 78, stamina: 92, burst: 76, nerve: 89, gate: 68, grit: 86 },
  },
  {
    slug: 'manus-moonrail',
    name: 'Manus Moonrail',
    agent: 'Manus',
    stable: 'Browser Rail',
    bloodline: 'Viewport x QA Pass',
    coat: '#6c5dd3',
    accent: '#8fd8ff',
    stats: { speed: 82, stamina: 74, burst: 91, nerve: 79, gate: 86, grit: 76 },
  },
  {
    slug: 'gamgee-gate',
    name: 'Gamgee Gate',
    agent: 'Gamgee',
    stable: 'RC0 Shed',
    bloodline: 'Release Note x Old Soul',
    coat: '#208c4b',
    accent: '#f6e27f',
    stats: { speed: 74, stamina: 88, burst: 72, nerve: 94, gate: 82, grit: 90 },
  },
  {
    slug: 'sparrow-signal',
    name: 'Sparrow Signal',
    agent: 'Sparrow',
    stable: 'Relay Loft',
    bloodline: 'Deck Line x Federation',
    coat: '#111827',
    accent: '#f97316',
    stats: { speed: 86, stamina: 70, burst: 87, nerve: 73, gate: 91, grit: 67 },
  },
  {
    slug: 'magpie-mint',
    name: 'Magpie Mint',
    agent: 'Magpie',
    stable: 'Native Paddock',
    bloodline: 'Wallet Chip x Gallery Pick',
    coat: '#0f766e',
    accent: '#d9f99d',
    stats: { speed: 72, stamina: 82, burst: 79, nerve: 84, gate: 75, grit: 96 },
  },
  {
    slug: 'tezos-tide',
    name: 'Tezos Tide',
    agent: 'Tezos',
    stable: 'Beacon Basin',
    bloodline: 'FA2 x Low Tide',
    coat: '#2f74d0',
    accent: '#9ae6ff',
    stats: { speed: 80, stamina: 86, burst: 70, nerve: 82, gate: 78, grit: 88 },
  },
  {
    slug: 'segundo-wind',
    name: 'Segundo Wind',
    agent: 'El Segundo',
    stable: 'Dune Field',
    bloodline: 'Jet Path x Marine Layer',
    coat: '#b7791f',
    accent: '#e6fffa',
    stats: { speed: 92, stamina: 72, burst: 88, nerve: 76, gate: 84, grit: 74 },
  },
] as const;

export const DERBY_RULEBOOK = {
  fieldSize: 6,
  deterministic: true,
  seedInputs: ['seed', 'track', 'agents'],
  phases: ['gate', 'backstretch', 'turn', 'home stretch', 'photo'],
  scoring: {
    weightedTrackBias: 'Each horse stat is multiplied by the selected track bias.',
    gate: 'Gate matters most in the first 20 percent of the race.',
    stamina: 'Stamina and grit matter more after the final turn.',
    burst: 'Burst can flip the home stretch when the horse still has enough stamina.',
    nerve: 'Nerve reduces trouble and keeps pace stable in traffic.',
  },
  storage: 'Race receipts are localStorage only at pc:agent-derby:races.',
} as const;
