export const DERBY_VERSION = '0.4.0-v2';

export const DERBY_POSTERS = [
  {
    id: 'style-01-trapper-keeper',
    horseSlug: 'codex-cantor',
    title: 'Codex Cantor',
    agent: 'Codex',
    gate: 'G1',
    styleName: 'Trapper Heat',
    track: 'el-segundo-sprint',
    seed: 'race-ochg9xl',
    image: '/images/agent-derby/posters/01-trapper-keeper.png',
    imagePosition: 'center center',
    palette: ['hot magenta', 'acid yellow', 'ink black'],
  },
  {
    id: 'style-02-chrome-foil',
    horseSlug: 'claude-longshot',
    title: 'Claude Longshot',
    agent: 'Claude',
    gate: 'G2',
    styleName: 'Chrome Foil',
    track: 'wire-mile',
    seed: 'gamgee-rc0',
    image: '/images/agent-derby/posters/02-chrome-foil.png',
    imagePosition: 'center center',
    palette: ['cyan chrome', 'electric pink', 'grid black'],
  },
  {
    id: 'style-03-xerox-punk',
    horseSlug: 'sparrow-signal',
    title: 'Sparrow Signal',
    agent: 'Sparrow',
    gate: 'G3',
    styleName: 'Xerox Punk',
    track: 'fog-route',
    seed: 'race-static-sparrow',
    image: '/images/agent-derby/posters/03-xerox-punk.png',
    imagePosition: 'center center',
    palette: ['black ink', 'paper white', 'signal red'],
  },
  {
    id: 'style-04-blueprint-lab',
    horseSlug: 'tezos-tide',
    title: 'Tezos Tide',
    agent: 'Tezos',
    gate: 'G4',
    styleName: 'Blueprint Lab',
    track: 'wire-mile',
    seed: 'race-beacon-lab',
    image: '/images/agent-derby/posters/04-blueprint-lab.png',
    imagePosition: 'center center',
    palette: ['blueprint navy', 'cyan line', 'amber tick'],
  },
  {
    id: 'style-05-miami-night',
    horseSlug: 'segundo-wind',
    title: 'Segundo Wind',
    agent: 'El Segundo',
    gate: 'G5',
    styleName: 'Miami Night',
    track: 'el-segundo-sprint',
    seed: 'race-palm-rail',
    image: '/images/agent-derby/posters/05-miami-night.png',
    imagePosition: 'center center',
    palette: ['teal', 'coral', 'sunset orange'],
  },
  {
    id: 'style-06-mecha-program',
    horseSlug: 'manus-moonrail',
    title: 'Manus Moonrail',
    agent: 'Manus',
    gate: 'G6',
    styleName: 'Mecha Program',
    track: 'dune-night',
    seed: 'race-night-wire',
    image: '/images/agent-derby/posters/06-mecha-program.png',
    imagePosition: 'center center',
    palette: ['red orange', 'steel gray', 'deep teal'],
  },
  {
    id: 'style-07-dune-rally',
    horseSlug: 'gamgee-gate',
    title: 'Gamgee Gate',
    agent: 'Gamgee',
    gate: 'G7',
    styleName: 'Dune Rally',
    track: 'dune-night',
    seed: 'race-rc0-dust',
    image: '/images/agent-derby/posters/07-dune-rally.png',
    imagePosition: 'center center',
    palette: ['sand gold', 'burnt orange', 'moon white'],
  },
  {
    id: 'style-08-arcade-pixel',
    horseSlug: 'magpie-mint',
    title: 'Magpie Mint',
    agent: 'Magpie',
    gate: 'G8',
    styleName: 'Arcade Pixel',
    track: 'el-segundo-sprint',
    seed: 'race-coin-op-mint',
    image: '/images/agent-derby/posters/08-arcade-pixel.png',
    imagePosition: 'center center',
    palette: ['electric blue', 'lime', 'arcade black'],
  },
  {
    id: 'style-09-newspaper-sheet',
    horseSlug: 'claude-longshot',
    title: 'Claude Longshot',
    agent: 'Claude',
    gate: 'G9',
    styleName: 'Newsprint Sheet',
    track: 'fog-route',
    seed: 'race-morning-form',
    image: '/images/agent-derby/posters/09-newspaper-sheet.png',
    imagePosition: 'center center',
    palette: ['newsprint', 'black ink', 'faded red'],
  },
  {
    id: 'style-10-hologram-sticker',
    horseSlug: 'codex-cantor',
    title: 'Codex Cantor',
    agent: 'Codex',
    gate: 'G10',
    styleName: 'Holo Sticker',
    track: 'wire-mile',
    seed: 'race-champ-sheet',
    image: '/images/agent-derby/posters/10-hologram-sticker.png',
    imagePosition: 'center center',
    palette: ['rainbow foil', 'teal', 'lemon yellow'],
  },
] as const;

export const DERBY_STATS = ['speed', 'stamina', 'burst', 'nerve', 'gate', 'grit'] as const;

export const DERBY_TRACKS = [
  {
    id: 'el-segundo-sprint',
    label: 'El Segundo Sprint',
    code: 'ES-1200',
    distance: 1200,
    going: 'fast dirt',
    par: 71.2,
    bias: {
      speed: 1.24,
      stamina: 0.76,
      burst: 1.08,
      nerve: 0.82,
      gate: 1.18,
      grit: 0.72,
    },
  },
  {
    id: 'wire-mile',
    label: 'Wire Mile',
    code: 'WR-1600',
    distance: 1600,
    going: 'firm rail',
    par: 98.6,
    bias: {
      speed: 1.02,
      stamina: 1.0,
      burst: 0.96,
      nerve: 1.12,
      gate: 0.88,
      grit: 0.94,
    },
  },
  {
    id: 'fog-route',
    label: 'Fog Route',
    code: 'FG-1800',
    distance: 1800,
    going: 'cold mist',
    par: 113.8,
    bias: {
      speed: 0.82,
      stamina: 1.28,
      burst: 0.88,
      nerve: 1.18,
      gate: 0.72,
      grit: 1.12,
    },
  },
  {
    id: 'dune-night',
    label: 'Dune Night',
    code: 'DN-1000',
    distance: 1000,
    going: 'loose sand',
    par: 61.5,
    bias: {
      speed: 0.96,
      stamina: 0.9,
      burst: 1.24,
      nerve: 0.96,
      gate: 1.1,
      grit: 1.18,
    },
  },
] as const;

export const DERBY_ROSTER = [
  {
    slug: 'codex-cantor',
    name: 'Codex Cantor',
    agent: 'Codex',
    stable: 'Patch Barn',
    bloodline: 'Compiler x Morning Wire',
    coat: '#185fa5',
    accent: '#f4b23f',
    stats: { speed: 88, stamina: 78, burst: 84, nerve: 91, gate: 72, grit: 80 },
  },
  {
    slug: 'claude-longshot',
    name: 'Claude Longshot',
    agent: 'Claude',
    stable: 'Opus Yard',
    bloodline: 'Deep Read x Orchard Signal',
    coat: '#c85b3b',
    accent: '#fff1cb',
    stats: { speed: 78, stamina: 92, burst: 76, nerve: 89, gate: 68, grit: 86 },
  },
  {
    slug: 'manus-moonrail',
    name: 'Manus Moonrail',
    agent: 'Manus',
    stable: 'Browser Rail',
    bloodline: 'Viewport x QA Pass',
    coat: '#6c5dd3',
    accent: '#8fd8ff',
    stats: { speed: 82, stamina: 74, burst: 91, nerve: 79, gate: 86, grit: 76 },
  },
  {
    slug: 'gamgee-gate',
    name: 'Gamgee Gate',
    agent: 'Gamgee',
    stable: 'RC0 Shed',
    bloodline: 'Release Note x Old Soul',
    coat: '#208c4b',
    accent: '#f6e27f',
    stats: { speed: 74, stamina: 88, burst: 72, nerve: 94, gate: 82, grit: 90 },
  },
  {
    slug: 'sparrow-signal',
    name: 'Sparrow Signal',
    agent: 'Sparrow',
    stable: 'Relay Loft',
    bloodline: 'Deck Line x Federation',
    coat: '#111827',
    accent: '#f97316',
    stats: { speed: 86, stamina: 70, burst: 87, nerve: 73, gate: 91, grit: 67 },
  },
  {
    slug: 'magpie-mint',
    name: 'Magpie Mint',
    agent: 'Magpie',
    stable: 'Native Paddock',
    bloodline: 'Wallet Chip x Gallery Pick',
    coat: '#0f766e',
    accent: '#d9f99d',
    stats: { speed: 72, stamina: 82, burst: 79, nerve: 84, gate: 75, grit: 96 },
  },
  {
    slug: 'tezos-tide',
    name: 'Tezos Tide',
    agent: 'Tezos',
    stable: 'Beacon Basin',
    bloodline: 'FA2 x Low Tide',
    coat: '#2f74d0',
    accent: '#9ae6ff',
    stats: { speed: 80, stamina: 86, burst: 70, nerve: 82, gate: 78, grit: 88 },
  },
  {
    slug: 'segundo-wind',
    name: 'Segundo Wind',
    agent: 'El Segundo',
    stable: 'Dune Field',
    bloodline: 'Jet Path x Marine Layer',
    coat: '#b7791f',
    accent: '#e6fffa',
    stats: { speed: 92, stamina: 72, burst: 88, nerve: 76, gate: 84, grit: 74 },
  },
] as const;

export const DERBY_RULEBOOK = {
  fieldSize: 6,
  deterministic: true,
  seedInputs: ['seed', 'track', 'agents'],
  phases: ['gate', 'backstretch', 'turn', 'home stretch', 'photo'],
  v2Loop: ['pick', 'run', 'record'],
  scoring: {
    weightedTrackBias: 'Each horse stat is multiplied by the selected track bias.',
    gate: 'Gate matters most in the first 20 percent of the race.',
    stamina: 'Stamina and grit matter more after the final turn.',
    burst: 'Burst can flip the home stretch when the horse still has enough stamina.',
    nerve: 'Nerve reduces trouble and keeps pace stable in traffic.',
  },
  storage: 'Race receipts are stored locally at pc:agent-derby:races and can be recorded to the Agent Derby Tezos receipt contract once a KT1 is configured.',
  chain: {
    network: 'tezos-mainnet',
    entrypoint: 'record_race',
    receiptHash: 'sha256(canonical race receipt JSON)',
  },
} as const;

export const DERBY_SEASON = {
  id: 'gamgee-spring-2026',
  title: 'Gamgee Spring League',
  status: 'preseason',
  startsAt: '2026-04-27T09:00:00-07:00',
  cadence: 'One seeded feature race per weekday, plus open exhibition races any time.',
  storage: 'Season tickets are localStorage only at pc:agent-derby:tickets.',
  standings: [
    { rank: 1, horseSlug: 'codex-cantor', points: 12, record: '2-0-1', note: 'fast gate, clean receipts' },
    { rank: 2, horseSlug: 'manus-moonrail', points: 10, record: '1-1-1', note: 'best late burst' },
    { rank: 3, horseSlug: 'claude-longshot', points: 9, record: '1-1-0', note: 'stamina on longer tracks' },
    { rank: 4, horseSlug: 'gamgee-gate', points: 8, record: '1-0-2', note: 'never loses the plot' },
    { rank: 5, horseSlug: 'tezos-tide', points: 5, record: '0-1-1', note: 'strong in mist' },
    { rank: 6, horseSlug: 'segundo-wind', points: 4, record: '0-1-0', note: 'home-track spoiler' },
  ],
  featureRaces: [
    {
      id: 'opening-bell',
      label: 'Opening Bell',
      seed: 'gamgee-opening-bell',
      track: 'el-segundo-sprint',
      agents: ['codex', 'claude', 'manus', 'gamgee', 'tezos', 'segundo'],
    },
    {
      id: 'fog-route-classic',
      label: 'Fog Route Classic',
      seed: 'marine-layer-classic',
      track: 'fog-route',
      agents: ['claude', 'gamgee', 'tezos', 'magpie', 'codex', 'manus'],
    },
    {
      id: 'night-wire',
      label: 'Night Wire',
      seed: 'night-wire-ticket',
      track: 'wire-mile',
      agents: ['manus', 'sparrow', 'codex', 'claude', 'segundo', 'magpie'],
    },
  ],
  ticketRewards: [
    { id: 'first-race', label: 'First Race Ticket', trigger: 'Run any race', points: 1 },
    { id: 'feature-race', label: 'Feature Race Ticket', trigger: 'Run a listed feature seed', points: 3 },
    { id: 'photo-finish', label: 'Photo Finish Ticket', trigger: 'Copy a race receipt', points: 2 },
  ],
} as const;

export const DERBY_SEASON = {
  id: 'gamgee-spring-2026',
  title: 'Gamgee Spring League',
  status: 'preseason',
  startsAt: '2026-04-27T09:00:00-07:00',
  cadence: 'One seeded feature race per weekday, plus open exhibition races any time.',
  storage: 'Season tickets are localStorage only at pc:agent-derby:tickets.',
  standings: [
    { rank: 1, horseSlug: 'codex-cantor', points: 12, record: '2-0-1', note: 'fast gate, clean receipts' },
    { rank: 2, horseSlug: 'manus-moonrail', points: 10, record: '1-1-1', note: 'best late burst' },
    { rank: 3, horseSlug: 'claude-longshot', points: 9, record: '1-1-0', note: 'stamina on longer tracks' },
    { rank: 4, horseSlug: 'gamgee-gate', points: 8, record: '1-0-2', note: 'never loses the plot' },
    { rank: 5, horseSlug: 'tezos-tide', points: 5, record: '0-1-1', note: 'strong in mist' },
    { rank: 6, horseSlug: 'segundo-wind', points: 4, record: '0-1-0', note: 'home-track spoiler' },
  ],
  featureRaces: [
    {
      id: 'opening-bell',
      label: 'Opening Bell',
      seed: 'gamgee-opening-bell',
      track: 'el-segundo-sprint',
      agents: ['codex', 'claude', 'manus', 'gamgee', 'tezos', 'segundo'],
    },
    {
      id: 'fog-route-classic',
      label: 'Fog Route Classic',
      seed: 'marine-layer-classic',
      track: 'fog-route',
      agents: ['claude', 'gamgee', 'tezos', 'magpie', 'codex', 'manus'],
    },
    {
      id: 'night-wire',
      label: 'Night Wire',
      seed: 'night-wire-ticket',
      track: 'wire-mile',
      agents: ['manus', 'sparrow', 'codex', 'claude', 'segundo', 'magpie'],
    },
  ],
  ticketRewards: [
    { id: 'first-race', label: 'First Race Ticket', trigger: 'Run any race', points: 1 },
    { id: 'feature-race', label: 'Feature Race Ticket', trigger: 'Run a listed feature seed', points: 3 },
    { id: 'photo-finish', label: 'Photo Finish Ticket', trigger: 'Copy a race receipt', points: 2 },
  ],
} as const;
