export const DERBY_VERSION = '0.5.0-v3';

export const DERBY_POSTERS = [
  {
    id: 'style-01-trapper-keeper',
    horseSlug: 'codex-cantor',
    title: 'Codex Cantor',
    agent: 'Codex',
    gate: 'G1',
    styleName: 'Trapper Heat',
    track: 'el-segundo-sprint',
    seed: 'race-ochg9xl',
    image: '/images/agent-derby/posters/01-trapper-keeper.png',
    imagePosition: 'center center',
    palette: ['hot magenta', 'acid yellow', 'ink black'],
  },
  {
    id: 'style-02-chrome-foil',
    horseSlug: 'claude-longshot',
    title: 'Claude Longshot',
    agent: 'Claude',
    gate: 'G2',
    styleName: 'Chrome Foil',
    track: 'wire-mile',
    seed: 'gamgee-rc0',
    image: '/images/agent-derby/posters/02-chrome-foil.png',
    imagePosition: 'center center',
    palette: ['cyan chrome', 'electric pink', 'grid black'],
  },
  {
    id: 'style-03-xerox-punk',
    horseSlug: 'sparrow-signal',
    title: 'Sparrow Signal',
    agent: 'Sparrow',
    gate: 'G3',
    styleName: 'Xerox Punk',
    track: 'fog-route',
    seed: 'race-static-sparrow',
    image: '/images/agent-derby/posters/03-xerox-punk.png',
    imagePosition: 'center center',
    palette: ['black ink', 'paper white', 'signal red'],
  },
  {
    id: 'style-04-blueprint-lab',
    horseSlug: 'tezos-tide',
    title: 'Tezos Tide',
    agent: 'Tezos',
    gate: 'G4',
    styleName: 'Blueprint Lab',
    track: 'wire-mile',
    seed: 'race-beacon-lab',
    image: '/images/agent-derby/posters/04-blueprint-lab.png',
    imagePosition: 'center center',
    palette: ['blueprint navy', 'cyan line', 'amber tick'],
  },
  {
    id: 'style-05-miami-night',
    horseSlug: 'segundo-wind',
    title: 'Segundo Wind',
    agent: 'El Segundo',
    gate: 'G5',
    styleName: 'Miami Night',
    track: 'el-segundo-sprint',
    seed: 'race-palm-rail',
    image: '/images/agent-derby/posters/05-miami-night.png',
    imagePosition: 'center center',
    palette: ['teal', 'coral', 'sunset orange'],
  },
  {
    id: 'style-06-mecha-program',
    horseSlug: 'manus-moonrail',
    title: 'Manus Moonrail',
    agent: 'Manus',
    gate: 'G6',
    styleName: 'Mecha Program',
    track: 'dune-night',
    seed: 'race-night-wire',
    image: '/images/agent-derby/posters/06-mecha-program.png',
    imagePosition: 'center center',
    palette: ['red orange', 'steel gray', 'deep teal'],
  },
  {
    id: 'style-07-dune-rally',
    horseSlug: 'gamgee-gate',
    title: 'Gamgee Gate',
    agent: 'Gamgee',
    gate: 'G7',
    styleName: 'Dune Rally',
    track: 'dune-night',
    seed: 'race-rc0-dust',
    image: '/images/agent-derby/posters/07-dune-rally.png',
    imagePosition: 'center center',
    palette: ['sand gold', 'burnt orange', 'moon white'],
  },
  {
    id: 'style-08-arcade-pixel',
    horseSlug: 'magpie-mint',
    title: 'Magpie Mint',
    agent: 'Magpie',
    gate: 'G8',
    styleName: 'Arcade Pixel',
    track: 'el-segundo-sprint',
    seed: 'race-coin-op-mint',
    image: '/images/agent-derby/posters/08-arcade-pixel.png',
    imagePosition: 'center center',
    palette: ['electric blue', 'lime', 'arcade black'],
  },
  {
    id: 'style-09-newspaper-sheet',
    horseSlug: 'claude-longshot',
    title: 'Claude Longshot',
    agent: 'Claude',
    gate: 'G9',
    styleName: 'Newsprint Sheet',
    track: 'fog-route',
    seed: 'race-morning-form',
    image: '/images/agent-derby/posters/09-newspaper-sheet.png',
    imagePosition: 'center center',
    palette: ['newsprint', 'black ink', 'faded red'],
  },
  {
    id: 'style-10-hologram-sticker',
    horseSlug: 'codex-cantor',
    title: 'Codex Cantor',
    agent: 'Codex',
    gate: 'G10',
    styleName: 'Holo Sticker',
    track: 'wire-mile',
    seed: 'race-champ-sheet',
    image: '/images/agent-derby/posters/10-hologram-sticker.png',
    imagePosition: 'center center',
    palette: ['rainbow foil', 'teal', 'lemon yellow'],
  },
] as const;

export const DERBY_STATS = ['speed', 'stamina', 'burst', 'nerve', 'gate', 'grit'] as const;

export const DERBY_TRACKS = [
  {
    id: 'el-segundo-sprint',
    label: 'El Segundo Sprint',
    code: 'ES-1200',
    distance: 1200,
    going: 'fast dirt',
    par: 71.2,
    bias: {
      speed: 1.24,
      stamina: 0.76,
      burst: 1.08,
      nerve: 0.82,
      gate: 1.18,
      grit: 0.72,
    },
  },
  {
    id: 'wire-mile',
    label: 'Wire Mile',
    code: 'WR-1600',
    distance: 1600,
    going: 'firm rail',
    par: 98.6,
    bias: {
      speed: 1.02,
      stamina: 1.0,
      burst: 0.96,
      nerve: 1.12,
      gate: 0.88,
      grit: 0.94,
    },
  },
  {
    id: 'fog-route',
    label: 'Fog Route',
    code: 'FG-1800',
    distance: 1800,
    going: 'cold mist',
    par: 113.8,
    bias: {
      speed: 0.82,
      stamina: 1.28,
      burst: 0.88,
      nerve: 1.18,
      gate: 0.72,
      grit: 1.12,
    },
  },
  {
    id: 'dune-night',
    label: 'Dune Night',
    code: 'DN-1000',
    distance: 1000,
    going: 'loose sand',
    par: 61.5,
    bias: {
      speed: 0.96,
      stamina: 0.9,
      burst: 1.24,
      nerve: 0.96,
      gate: 1.1,
      grit: 1.18,
    },
  },
  {
    id: 'beacon-bend',
    label: 'Beacon Bend',
    code: 'BB-1400',
    distance: 1400,
    going: 'wallet rail',
    par: 84.9,
    bias: {
      speed: 0.98,
      stamina: 1.04,
      burst: 1.02,
      nerve: 1.2,
      gate: 0.9,
      grit: 1.0,
    },
  },
] as const;

export const DERBY_ROSTER = [
  {
    slug: 'codex-cantor',
    name: 'Codex Cantor',
    agent: 'Codex',
    stable: 'Patch Barn',
    bloodline: 'Compiler x Morning Wire',
    coat: '#185fa5',
    accent: '#f4b23f',
    stats: { speed: 88, stamina: 78, burst: 84, nerve: 91, gate: 72, grit: 80 },
  },
  {
    slug: 'claude-longshot',
    name: 'Claude Longshot',
    agent: 'Claude',
    stable: 'Opus Yard',
    bloodline: 'Deep Read x Orchard Signal',
    coat: '#c85b3b',
    accent: '#fff1cb',
    stats: { speed: 78, stamina: 92, burst: 76, nerve: 89, gate: 68, grit: 86 },
  },
  {
    slug: 'manus-moonrail',
    name: 'Manus Moonrail',
    agent: 'Manus',
    stable: 'Browser Rail',
    bloodline: 'Viewport x QA Pass',
    coat: '#6c5dd3',
    accent: '#8fd8ff',
    stats: { speed: 82, stamina: 74, burst: 91, nerve: 79, gate: 86, grit: 76 },
  },
  {
    slug: 'gamgee-gate',
    name: 'Gamgee Gate',
    agent: 'Gamgee',
    stable: 'RC0 Shed',
    bloodline: 'Release Note x Old Soul',
    coat: '#208c4b',
    accent: '#f6e27f',
    stats: { speed: 74, stamina: 88, burst: 72, nerve: 94, gate: 82, grit: 90 },
  },
  {
    slug: 'sparrow-signal',
    name: 'Sparrow Signal',
    agent: 'Sparrow',
    stable: 'Relay Loft',
    bloodline: 'Deck Line x Federation',
    coat: '#111827',
    accent: '#f97316',
    stats: { speed: 86, stamina: 70, burst: 87, nerve: 73, gate: 91, grit: 67 },
  },
  {
    slug: 'magpie-mint',
    name: 'Magpie Mint',
    agent: 'Magpie',
    stable: 'Native Paddock',
    bloodline: 'Wallet Chip x Gallery Pick',
    coat: '#0f766e',
    accent: '#d9f99d',
    stats: { speed: 72, stamina: 82, burst: 79, nerve: 84, gate: 75, grit: 96 },
  },
  {
    slug: 'tezos-tide',
    name: 'Tezos Tide',
    agent: 'Tezos',
    stable: 'Beacon Basin',
    bloodline: 'FA2 x Low Tide',
    coat: '#2f74d0',
    accent: '#9ae6ff',
    stats: { speed: 80, stamina: 86, burst: 70, nerve: 82, gate: 78, grit: 88 },
  },
  {
    slug: 'segundo-wind',
    name: 'Segundo Wind',
    agent: 'El Segundo',
    stable: 'Dune Field',
    bloodline: 'Jet Path x Marine Layer',
    coat: '#b7791f',
    accent: '#e6fffa',
    stats: { speed: 92, stamina: 72, burst: 88, nerve: 76, gate: 84, grit: 74 },
  },
  {
    slug: 'ocean-oracle',
    name: 'Ocean Oracle',
    agent: 'Ocean',
    stable: 'Tide Lab',
    bloodline: 'Marine Layer x Prediction Market',
    coat: '#0e7490',
    accent: '#fde047',
    stats: { speed: 81, stamina: 90, burst: 73, nerve: 88, gate: 74, grit: 84 },
  },
  {
    slug: 'forge-falcon',
    name: 'Forge Falcon',
    agent: 'Forge',
    stable: 'Stack Foundry',
    bloodline: 'Hot Reload x Toolchain',
    coat: '#7c2d12',
    accent: '#93c5fd',
    stats: { speed: 84, stamina: 76, burst: 90, nerve: 75, gate: 88, grit: 82 },
  },
  {
    slug: 'garden-byte',
    name: 'Garden Byte',
    agent: 'Garden',
    stable: 'Green Room',
    bloodline: 'Houseplant x Yield Curve',
    coat: '#4d7c0f',
    accent: '#fef08a',
    stats: { speed: 73, stamina: 91, burst: 69, nerve: 83, gate: 79, grit: 94 },
  },
  {
    slug: 'room-runner',
    name: 'Room Runner',
    agent: 'Room',
    stable: 'Chat Paddock',
    bloodline: 'Bubble Log x Live Presence',
    coat: '#be185d',
    accent: '#a7f3d0',
    stats: { speed: 89, stamina: 71, burst: 86, nerve: 80, gate: 93, grit: 72 },
  },
] as const;

export const DERBY_STABLES = [
  {
    id: 'patch-barn',
    name: 'Patch Barn',
    agent: 'Codex',
    color: '#185fa5',
    accent: '#f4b23f',
    base: 'compiler row',
    motto: 'Small patches, clean receipts.',
    growth: 'Needs rail fans to sponsor night builds and QA forms.',
  },
  {
    id: 'opus-yard',
    name: 'Opus Yard',
    agent: 'Claude',
    color: '#c85b3b',
    accent: '#fff1cb',
    base: 'long-read shed',
    motto: 'Patience wins the fog route.',
    growth: 'Backers fund deeper scouting sheets and calmer stretch calls.',
  },
  {
    id: 'browser-rail',
    name: 'Browser Rail',
    agent: 'Manus',
    color: '#6c5dd3',
    accent: '#8fd8ff',
    base: 'viewport paddock',
    motto: 'Click the track, prove the lap.',
    growth: 'Fans help buy replay cameras and cross-browser saddle checks.',
  },
  {
    id: 'rc0-shed',
    name: 'RC0 Shed',
    agent: 'Gamgee',
    color: '#208c4b',
    accent: '#f6e27f',
    base: 'release lane',
    motto: 'The candidate can still close.',
    growth: 'Stable staking sharpens release notes and morning form books.',
  },
  {
    id: 'relay-loft',
    name: 'Relay Loft',
    agent: 'Sparrow',
    color: '#111827',
    accent: '#f97316',
    base: 'signal tower',
    motto: 'Short hops, fast breaks.',
    growth: 'Fans add relay stations, faster handoffs, and cleaner pings.',
  },
  {
    id: 'native-paddock',
    name: 'Native Paddock',
    agent: 'Magpie',
    color: '#0f766e',
    accent: '#d9f99d',
    base: 'wallet grove',
    motto: 'Collect the shiny line.',
    growth: 'Backers unlock gallery picks, mint notes, and mobile tack.',
  },
  {
    id: 'beacon-basin',
    name: 'Beacon Basin',
    agent: 'Tezos',
    color: '#2f74d0',
    accent: '#9ae6ff',
    base: 'signing rail',
    motto: 'Receipt first, chain when ready.',
    growth: 'Fan support funds wallet rehearsals and future KT1 operations.',
  },
  {
    id: 'dune-field',
    name: 'Dune Field',
    agent: 'El Segundo',
    color: '#b7791f',
    accent: '#e6fffa',
    base: 'marine layer oval',
    motto: 'Local wind on the final turn.',
    growth: 'Fans back local scouting, beach-condition reports, and sprint cards.',
  },
  {
    id: 'tide-lab',
    name: 'Tide Lab',
    agent: 'Ocean',
    color: '#0e7490',
    accent: '#fde047',
    base: 'prediction pier',
    motto: 'Read the swell before the gate.',
    growth: 'Backers add market depth, weather nerves, and oracle notes.',
  },
  {
    id: 'stack-foundry',
    name: 'Stack Foundry',
    agent: 'Forge',
    color: '#7c2d12',
    accent: '#93c5fd',
    base: 'hot-reload forge',
    motto: 'Hammer the break, ship the burst.',
    growth: 'Fan stakes fund tooling, lane sensors, and sharper photo timing.',
  },
  {
    id: 'green-room',
    name: 'Green Room',
    agent: 'Garden',
    color: '#4d7c0f',
    accent: '#fef08a',
    base: 'houseplant rail',
    motto: 'Grow slow, finish strong.',
    growth: 'Fans help cultivate stamina, soil reports, and yield badges.',
  },
  {
    id: 'chat-paddock',
    name: 'Chat Paddock',
    agent: 'Room',
    color: '#be185d',
    accent: '#a7f3d0',
    base: 'live room',
    motto: 'Crowd noise is a stat.',
    growth: 'Backers increase presence, chants, and room-to-room race calls.',
  },
] as const;

export const DERBY_DAILY_RACES = [
  {
    id: 'morning-wire',
    label: 'Morning Wire',
    track: 'wire-mile',
    seed: 'daily-morning-wire',
    window: '06:00-10:00 PT',
    featuredStable: 'patch-barn',
    prize: 'First Fan badge and clean-sheet form boost',
  },
  {
    id: 'beacon-basin-card',
    label: 'Beacon Basin Card',
    track: 'beacon-bend',
    seed: 'daily-beacon-basin',
    window: '10:00-13:00 PT',
    featuredStable: 'beacon-basin',
    prize: 'Wallet rehearsal packet',
  },
  {
    id: 'segundo-sunrun',
    label: 'Segundo Sunrun',
    track: 'el-segundo-sprint',
    seed: 'daily-segundo-sunrun',
    window: '13:00-16:00 PT',
    featuredStable: 'dune-field',
    prize: 'Local Wind badge',
  },
  {
    id: 'dune-after-dark',
    label: 'Dune After Dark',
    track: 'dune-night',
    seed: 'daily-dune-after-dark',
    window: '16:00-20:00 PT',
    featuredStable: 'browser-rail',
    prize: 'Replay scout note',
  },
  {
    id: 'fog-founders',
    label: 'Fog Founders',
    track: 'fog-route',
    seed: 'daily-fog-founders',
    window: '20:00-23:00 PT',
    featuredStable: 'opus-yard',
    prize: 'Deep Read badge',
  },
  {
    id: 'green-room-growth',
    label: 'Green Room Growth',
    track: 'fog-route',
    seed: 'daily-green-room-growth',
    window: 'weekend matinee',
    featuredStable: 'green-room',
    prize: 'Yield Garden badge',
  },
  {
    id: 'chat-paddock-pop',
    label: 'Chat Paddock Pop',
    track: 'wire-mile',
    seed: 'daily-chat-paddock-pop',
    window: 'surprise room call',
    featuredStable: 'chat-paddock',
    prize: 'Room Tone badge',
  },
] as const;

export const DERBY_BADGES = [
  { id: 'first-fan', label: 'First Fan', code: 'FF', requirement: 'Become a fan of any stable.' },
  { id: 'first-race', label: 'First Race', code: 'R1', requirement: 'Finish any Agent Derby race.' },
  { id: 'daily-runner', label: 'Daily Runner', code: 'DR', requirement: 'Run a daily race card.' },
  { id: 'stable-backer', label: 'Stable Backer', code: 'SB', requirement: 'Back one stable with at least 50 support.' },
  { id: 'stable-builder', label: 'Stable Builder', code: 'BLD', requirement: 'Raise one stable to 150 support.' },
  { id: 'photo-hunter', label: 'Photo Hunter', code: 'PH', requirement: 'Finish inside a half-length photo.' },
  { id: 'receipt-desk', label: 'Receipt Desk', code: 'KT', requirement: 'Generate a Tezos-ready race packet.' },
] as const;

export const DERBY_FAN_TIERS = [
  { id: 'railbird', label: 'Railbird', minSupport: 0, boost: 0, note: 'Follow a stable and show up on the rail.' },
  { id: 'backer', label: 'Backer', minSupport: 50, boost: 1, note: 'Local support adds a tiny form nudge.' },
  { id: 'builder', label: 'Builder', minSupport: 150, boost: 2.5, note: 'Builder backing helps the stable train harder.' },
  { id: 'patron', label: 'Patron', minSupport: 300, boost: 4, note: 'Patron support makes the stable a daily-race force.' },
] as const;

export const DERBY_RULEBOOK = {
  fieldSize: 6,
  deterministic: true,
  seedInputs: ['seed', 'track', 'agents'],
  phases: ['gate', 'backstretch', 'turn', 'home stretch', 'photo'],
  v2Loop: ['pick', 'run', 'record'],
  v3Loop: ['daily card', 'fan a stable', 'back growth', 'run race', 'earn badge', 'sign or copy Tezos packet'],
  scoring: {
    weightedTrackBias: 'Each horse stat is multiplied by the selected track bias.',
    gate: 'Gate matters most in the first 20 percent of the race.',
    stamina: 'Stamina and grit matter more after the final turn.',
    burst: 'Burst can flip the home stretch when the horse still has enough stamina.',
    nerve: 'Nerve reduces trouble and keeps pace stable in traffic.',
    fanGrowth: 'Local stable backing adds a tiny deterministic form boost before the race is simulated.',
  },
  fandom: 'Fans follow and locally back stables. This is a game mechanic stored in the browser, not a custodial deposit.',
  fanStake: 'Stake language here means practice support for a stable. On-chain staking requires a separate contract and explicit wallet approval.',
  storage: 'Race receipts are stored locally at pc:agent-derby:races and can be recorded to the Agent Derby Tezos receipt contract once a KT1 is configured.',
  chain: {
    network: 'tezos-mainnet',
    entrypoint: 'record_race',
    receiptHash: 'sha256(canonical race receipt JSON)',
  },
} as const;
