export type StrengthId = 'coast' | 'space' | 'gateways' | 'making' | 'learning' | 'story' | 'gathering' | 'neighborhood';
export type GoalId = 'resilience' | 'learning' | 'livelihood' | 'spectacle' | 'connection';

export const BEACH_COMMONS_V18 = {
  schema: 'https://pointcast.xyz/schemas/field-study/v1',
  id: 'PC-BEACH-COMMONS-V18', edition: 18, fieldStudy: '018',
  title: 'Radius 25', subtitle: 'Build the Combinations',
  dek: 'Eight local powers. Twelve working pairs. One region that learns by making.',
  url: 'https://pointcast.xyz/beach-commons/v18',
  jsonUrl: 'https://pointcast.xyz/beach-commons/v18.json',
  blockUrl: 'https://pointcast.xyz/b/0548',
  publishedAt: '2026-07-31', updatedAt: '2026-07-31T22:30:00-07:00',
  radiusDefinition: 'A roughly 25-mile straight-line editorial field centered on El Segundo. It is not a municipal boundary, commute shed, service area, market definition, or claim that every named place falls fully inside a precise circle.',
  status: 'An independent speculative editorial roadmap. It announces no affiliation, partnership, commitment, funding, procurement, permit, program, event, construction, land use, or endorsement.',
  creators: [
    { name: 'Michael Hoydich', role: 'direction, radius clarification, and Beach Commons series' },
    { name: 'Codex / OpenAI', role: 'research, regional framework, writing, visual direction, image generation, interaction design, and implementation' },
  ],
} as const;

export const RADIUS_STRENGTHS = [
  { id: 'coast', number: '01', title: 'Pacific edge', shortTitle: 'Coast', color: '#247f9f', bring: 'Place literacy, field conditions, marine craft, restoration questions, public wonder.', thesis: 'A living coast, working waterfronts, marine knowledge, public beaches, and climate exposure make the edge both pleasure ground and field laboratory.', proof: 'Santa Monica Bay restoration and stewardship work; public coast access; port and harbor systems; decades of coastal observation.', move: 'Publish a reversible coastal hardpoint brief and test one closed-model comfort or observation kit.' },
  { id: 'space', number: '02', title: 'Space systems', shortTitle: 'Space', color: '#aeb9bf', bring: 'Reliability, lightweight structures, testing discipline, mission thinking, systems explanation.', thesis: 'El Segundo and the South Bay hold an unusually dense culture of systems engineering, integration, reliability, and aerospace production.', proof: 'Space Systems Command is headquartered at Los Angeles Air Force Base; El Segundo identifies aerospace and defense as foundational industries.', move: 'Translate one high-reliability practice into a public repair, shade, or field-instrument challenge.' },
  { id: 'gateways', number: '03', title: 'Global gateways', shortTitle: 'Gateways', color: '#df6242', bring: 'Handoffs, logistics, wayfinding, movement, return systems, global perspective.', thesis: 'LAX and the San Pedro Bay ports put people, goods, languages, and operational knowledge within one regional field.', proof: 'LAX handled more than 73 million passengers in 2025; the Port of Los Angeles handled 10.2 million TEUs and $301 billion in cargo value.', move: 'Prototype one car-light visitor loop or reusable materials handoff without touching secure operations.' },
  { id: 'making', number: '04', title: 'Advanced making', shortTitle: 'Making', color: '#dd9b2d', bring: 'Fabrication, tolerances, fixtures, small runs, maintainability, apprenticeships.', thesis: 'Precision manufacturing, mobility, marine repair, machine shops, textiles, electronics, food equipment, and industrial craft can make public ideas real.', proof: 'South Bay organizations describe a base in aerospace, advanced manufacturing, aviation, technology, mobility, engineering, and biotech.', move: 'Commission twelve small public objects with visible repair and return scores.' },
  { id: 'learning', number: '05', title: 'Learning network', shortTitle: 'Learning', color: '#7667a8', bring: 'Research method, learners, labs, explanation, evaluation, long memory.', thesis: 'Universities, community colleges, schools, libraries, research centers, technicians, and community knowledge can form a distributed public problem studio.', proof: 'Research universities, public campuses, incubators, and workforce programs ring El Segundo from the Westside through the South Bay and inland edge.', move: 'Circulate one proof case through a campus, library, shop, and public field site.' },
  { id: 'story', number: '06', title: 'Story + design', shortTitle: 'Story', color: '#c34f70', bring: 'Narrative, identity, staging, documentation, sound, visual explanation.', thesis: 'Film, music, games, editorial, architecture, sets, fashion, and visual design can make hard systems legible and local experiments desirable.', proof: 'Culver City explicitly organizes economic development around creative industries, cultural assets, small business, and workforce pathways.', move: 'Give one useful prototype a public story, soundtrack, field guide, and honest proof page.' },
  { id: 'gathering', number: '07', title: 'Sport + gathering', shortTitle: 'Gathering', color: '#d64a35', bring: 'Rules, seasons, rivalry, spectatorship, ceremony, repetition, public joy.', thesis: 'Beaches, parks, courts, arenas, stadium districts, performance rooms, and the LA28 horizon make collective experience a regional production skill.', proof: 'LA28 identifies venue zones in Inglewood, Carson, Long Beach, Venice, and elsewhere across the region.', move: 'Run one traveling design league whose score rewards usefulness, access, repair, and delight.' },
  { id: 'neighborhood', number: '08', title: 'Neighborhood operators', shortTitle: 'Neighborhood', color: '#4d936c', bring: 'Trust, practical demand, hosting, local procurement, maintenance, daily use.', thesis: 'Independent shops, kitchens, repairers, organizers, hosts, tradespeople, and small manufacturers are how a regional idea becomes convenient, trusted, and durable.', proof: 'Every district in the ring already contains local operators who procure, repair, explain, host, feed, and reopen the door tomorrow.', move: 'Require each pilot to buy locally, name a repair door, and leave behind one useful repeat customer.' },
] as const;

export const RADIUS_DOORS = [
  { title: 'El Segundo + Dockweiler', role: 'The center table', detail: 'Coast, aerospace, LAX adjacency, small-city scale, and the original hardpoint question meet here.' },
  { title: 'Inglewood + Hawthorne', role: 'Gathering and systems', detail: 'Aerospace history, live-event districts, making, mobility, and neighborhood enterprise cross.' },
  { title: 'Torrance + South Bay', role: 'The maker belt', detail: 'Advanced manufacturing, mobility, biotech, engineering, craft, and workforce pathways.' },
  { title: 'Carson + Dominguez', role: 'Learning in production country', detail: 'A public university and incubator sit inside a logistics, industrial, and sports landscape.' },
  { title: 'San Pedro + Long Beach', role: 'Working water', detail: 'Ports, maritime culture, reuse, repair, public waterfronts, and regional-scale handoffs.' },
  { title: 'Culver City + Westside', role: 'Story systems', detail: 'Creative production, design, research, transit, small business, and public culture.' },
  { title: 'Central LA + university corridor', role: 'Talent and explanation', detail: 'Education, medicine, museums, media, design, and dense public audiences.' },
  { title: 'Pasadena edge', role: 'Deep research horizon', detail: 'Caltech and JPL extend the systems-and-science conversation at or near the radius edge.' },
] as const;

type Pair = { id: string; strengths: readonly StrengthId[]; goals: readonly GoalId[]; title: string; question: string; ninetyDays: string; oneYear: string; proof: string };
export const WORKING_PAIRS = [
  { id: 'coast-space', strengths: ['coast','space'], goals: ['resilience','learning'], title: 'Sea meets space', question: 'Can high-reliability engineering make a lighter, calmer, more repairable public room at the coast?', ninetyDays: 'Build one reversible shade-and-sensor hardpoint kit; publish every joint, load assumption, failure, and pack-out move.', oneYear: 'A public systems school rotates the kit through beach, workshop, classroom, and harbor demonstrations.', proof: 'Qualified review, three repeat assemblies, salt-air material log, access audit, complete return.' },
  { id: 'coast-making', strengths: ['coast','making'], goals: ['resilience','livelihood'], title: 'The repairable coast kit', question: 'What does beach utility look like when every fastener, fabric, finish, and cart has a repair door?', ninetyDays: 'Produce twelve useful objects in small runs and score salt exposure, hand carry, comfort, repair, and return.', oneYear: 'A rotating coastal utility catalog supports local fabricators and publishes service histories.', proof: 'Twelve prototypes, supplier map, repair time, public-use notes, zero abandoned material.' },
  { id: 'gateways-making', strengths: ['gateways','making'], goals: ['connection','livelihood'], title: 'Repair + return logistics', question: 'Can regional handoff knowledge make public equipment easier to move, maintain, and reuse?', ninetyDays: 'Prototype a reusable case and color-shape custody system on a non-secure public route.', oneYear: 'A shared case standard moves exhibition, sport, field, and repair kits among host sites.', proof: 'Handoffs completed, damage avoided, return time, accessibility, local repair percentage.' },
  { id: 'gateways-story', strengths: ['gateways','story'], goals: ['connection','spectacle'], title: 'The arrival field guide', question: 'Can an arrival become a clear invitation into local life instead of a wall of ads?', ninetyDays: 'Design one tactile, multilingual, car-light visitor field guide for a fully public route.', oneYear: 'Artists and neighborhood hosts publish seasonal arrival editions with verified access details.', proof: 'Route completed, transfer clarity, local doors visited, accessibility review, correction log.' },
  { id: 'making-learning', strengths: ['making','learning'], goals: ['learning','livelihood'], title: 'The apprenticeship relay', question: 'What if the public could follow a useful object from question to drawing to fixture to repair?', ninetyDays: 'Send one proof case through four learning and production doors; each adds a test, skill, or repair.', oneYear: 'A paid regional relay matches learners with real small-run public-object briefs.', proof: 'Skills demonstrated, paid hours, revisions, repair notes, object returned to public use.' },
  { id: 'learning-neighborhood', strengths: ['learning','neighborhood'], goals: ['learning','connection'], title: 'The public problem studio', question: 'Can research begin at a counter, library, shop, court, or bus stop where the question is already alive?', ninetyDays: 'One host poses a practical question; a mixed team studies it and returns a small public proof.', oneYear: 'A circuit of rotating studios publishes methods, failures, costs, and next hosts.', proof: 'Host usefulness, method quality, public explanation, correction invited, follow-on use.' },
  { id: 'space-story', strengths: ['space','story'], goals: ['learning','spectacle'], title: 'Explain a hard system', question: 'Can systems thinking become as gripping as a game without turning certainty into spectacle?', ninetyDays: 'Build a tactile public explanation of one complex handoff, failure mode, or reliability problem.', oneYear: 'A traveling explanation league rewards accuracy, beauty, access, and the best revision.', proof: 'Expert correction, visitor retell, access modes, revision count, unknowns left visible.' },
  { id: 'story-gathering', strengths: ['story','gathering'], goals: ['spectacle','connection'], title: 'The regional game', question: 'Can a game make a place more legible while giving different kinds of talent a fair way to win?', ninetyDays: 'Create one traveling game with a public score, soundtrack, field guide, access plan, and clean return.', oneYear: 'A beach–park–workshop–campus circuit hosts seasonal finals and publishes every rule change.', proof: 'Repeat play, player mix, spectator understanding, host value, pack-out, rule revisions.' },
  { id: 'gathering-neighborhood', strengths: ['gathering','neighborhood'], goals: ['livelihood','spectacle'], title: 'The event-day local loop', question: 'Can a large gathering leave more useful value at nearby small doors?', ninetyDays: 'Prototype an independent public directory, repair counter, and walking loop around one ordinary gathering day.', oneYear: 'Hosts share reusable equipment and transparent local-spend and return measures across a season.', proof: 'Local purchases, new repeat visits, vendor access, waste avoided, neighborhood corrections.' },
  { id: 'coast-gathering', strengths: ['coast','gathering'], goals: ['spectacle','resilience'], title: 'The elements league', question: 'Can sun, wind, water, sound, and clean return become the rules of play?', ninetyDays: 'Rehearse one low-impact field game on a suitable permitted site using brought, reversible equipment.', oneYear: 'Seasonal rounds compare shade, comfort, observation, repair, and pack-out across different places.', proof: 'Site approval, comfort gain, access, weather adaptation, trace remaining, repeat invitation.' },
  { id: 'space-neighborhood', strengths: ['space','neighborhood'], goals: ['livelihood','resilience'], title: 'Reliability for everyday things', question: 'Which testing habits from high-consequence systems improve an ordinary cart, counter, shade, or repair lamp?', ninetyDays: 'A local operator chooses one failure-prone object; a mixed team redesigns and documents it.', oneYear: 'A practical reliability clinic serves small operators and publishes open maintenance cards.', proof: 'Failure before and after, maintenance time, cost, operator approval, parts availability.' },
  { id: 'gateways-coast', strengths: ['gateways','coast'], goals: ['resilience','connection'], title: 'Marine materials return', question: 'Can a material arrive with its next life already planned?', ninetyDays: 'Trace one clean, legal, non-hazardous material through use, collection, repair, and return.', oneYear: 'A public materials passport connects coastal users, local repairers, makers, and legitimate recovery doors.', proof: 'Chain of custody, material retained, transport avoided, repair completed, next owner named.' },
] as const satisfies readonly Pair[];

export const RADIUS_GOALS = [
  { id: 'resilience', label: 'Repair + resilience', question: 'Make public life calmer, safer, lighter, or more repairable.' },
  { id: 'learning', label: 'Learning', question: 'Turn hard knowledge into a public skill and a repeatable proof.' },
  { id: 'livelihood', label: 'Livelihood', question: 'Create paid practice, local purchasing, maintenance, or a useful small run.' },
  { id: 'spectacle', label: 'Gathering', question: 'Make a collective experience worth seeing, joining, and returning to.' },
  { id: 'connection', label: 'Connection', question: 'Improve a handoff among people, places, objects, or forms of knowledge.' },
] as const;

const map: Record<StrengthId, Record<GoalId,string>> = {
  coast:{resilience:'coast-space',learning:'coast-space',livelihood:'coast-making',spectacle:'coast-gathering',connection:'gateways-coast'},
  space:{resilience:'space-neighborhood',learning:'space-story',livelihood:'space-neighborhood',spectacle:'space-story',connection:'coast-space'},
  gateways:{resilience:'gateways-coast',learning:'gateways-story',livelihood:'gateways-making',spectacle:'gateways-story',connection:'gateways-making'},
  making:{resilience:'coast-making',learning:'making-learning',livelihood:'making-learning',spectacle:'story-gathering',connection:'gateways-making'},
  learning:{resilience:'coast-space',learning:'learning-neighborhood',livelihood:'making-learning',spectacle:'space-story',connection:'learning-neighborhood'},
  story:{resilience:'gateways-story',learning:'space-story',livelihood:'gathering-neighborhood',spectacle:'story-gathering',connection:'gateways-story'},
  gathering:{resilience:'coast-gathering',learning:'space-story',livelihood:'gathering-neighborhood',spectacle:'story-gathering',connection:'story-gathering'},
  neighborhood:{resilience:'space-neighborhood',learning:'learning-neighborhood',livelihood:'gathering-neighborhood',spectacle:'gathering-neighborhood',connection:'learning-neighborhood'},
};
export const ROADMAP_OPTIONS = Object.fromEntries(RADIUS_STRENGTHS.map(s => [s.id,Object.fromEntries(RADIUS_GOALS.map(g => [g.id,WORKING_PAIRS.find(p => p.id === map[s.id][g.id])]))])) as Record<StrengthId,Record<GoalId,(typeof WORKING_PAIRS)[number]>>;

export const ROADMAP_PHASES = [
  { window:'0–90 days', title:'Show the ring', instruction:'Publish the radius, open the source desk, walk the doors, choose twelve pairs, and make the first proof small enough to finish.', result:'A shared atlas, twelve bounded briefs, named hosts only where invited, and no false coalition.' },
  { window:'3–12 months', title:'Make the pairs', instruction:'Run six cross-strength pilots with real budgets, repair doors, access checks, public demonstrations, and clean endings.', result:'Six finished objects or experiences, paid local work, comparable proof pages, and reasons to repeat—or stop.' },
  { window:'1–3 years', title:'Build the shared layer', instruction:'Standardize the parts that earned reuse: cases, fixtures, proof cards, small procurement, apprenticeships, hosting, and annual league rules.', result:'A Commons Exchange that reduces coordination cost without making everyone join one organization.' },
  { window:'3–10 years', title:'Earn the institution', instruction:'Only after repeated public proof, create durable governance, dedicated space, long agreements, or larger capital projects.', result:'A regional institution defined by repeated usefulness, not a rendering, announcement, or charismatic founder.' },
] as const;
export const STRENGTH_SCORE = [
  {label:'Existing capacity',points:20,question:'Is the capability already real here?'},{label:'Useful combination',points:25,question:'Does pairing make a result neither side could make alone?'},{label:'Open pathway',points:20,question:'Can a learner, small operator, or public visitor enter fairly?'},{label:'Public proof',points:20,question:'Can the result be inspected, corrected, and compared?'},{label:'Repeatability',points:15,question:'Can another host repeat it without heroic effort?'},
] as const;
export const GOVERNING_RULES = ['Strength is a capability, not a brand name.','Every pilot pairs at least two strengths and finishes one inspectable thing.','Participation is voluntary; leagues and open calls replace assigned communal roles.','Pay skilled work, disclose budgets, and give small operators a real procurement path.','Existing public access, ecology, safety, and ordinary daily life outrank spectacle.','Applause can recognize delight; evidence decides what repeats.','The host can stop. Public proof records failure, disagreement, and unknowns.','Build the shared institution only after the shared tools earn repeated use.'] as const;
export const VISUAL_PLATES = [
  {number:'01',title:'The twenty-five-mile table',src:'/beach-commons/v18/assets/poster-01.png',alt:'A circular physical relief map centered on El Segundo gathers regional makers around a glowing radius ring.'},{number:'02',title:'Sea meets space',src:'/beach-commons/v18/assets/poster-02.png',alt:'A mixed team tests a reversible coastal structure with aerospace-like joints and a closed wave model.'},{number:'03',title:'The two gateways',src:'/beach-commons/v18/assets/poster-03.png',alt:'Airport and port workers use a tabletop logistics model to test public handoffs and reusable cases.'},{number:'04',title:'The maker belt',src:'/beach-commons/v18/assets/poster-04.png',alt:'A long open workshop table supports apprentices and craftspeople building repairable public objects.'},{number:'05',title:'The learning constellation',src:'/beach-commons/v18/assets/poster-05.png',alt:'A regional relief map connects distributed learning tables with physical proof cases.'},{number:'06',title:'Story meets sport',src:'/beach-commons/v18/assets/poster-06.png',alt:'A public field combines low-tech media making, music, games, and accessible gathering at golden hour.'},{number:'07',title:'Twelve working pairs',src:'/beach-commons/v18/assets/poster-07.png',alt:'Twelve teams test different useful prototypes around a circular outdoor proof ground.'},{number:'08',title:'The regional exchange',src:'/beach-commons/v18/assets/poster-08.png',alt:'A blue-hour circular exchange displays regional prototypes beneath a reversible canopy.'},
] as const;
export const RADIUS_SOURCES = [
  {label:'City of El Segundo · economic base',url:'https://www.elsegundo.org/home/showpublisheddocument/11768/638977869116270000',note:'Aerospace, defense, bioscience, technology, energy, creative media, and gathering context.'},{label:'Space Systems Command · command plan',url:'https://www.ssc.spaceforce.mil/Portals/3/Documents/SSC_Command_Plan_2024_Final_04_02_2025_.pdf',note:'SSC headquarters at Los Angeles Air Force Base in El Segundo.'},{label:'Los Angeles World Airports · passengers',url:'https://www.lawa.org/lawa-investor-relations/statistics-for-lax/10-year-summary/passengers',note:'Official LAX passenger totals, including 2025.'},{label:'Port of Los Angeles · facts and figures',url:'https://portoflosangeles.org/business/statistics/facts-and-figures',note:'Cargo value, container position, and regional economic role.'},{label:'South Bay Cities Council of Governments',url:'https://southbaycities.org/about/about-the-south-bay/',note:'Regional geography, aerospace history, LAX and ports position.'},{label:'South Bay apprenticeship perspective',url:'https://southbaycities.org/perspective-building-the-south-bays-future-workforce-through-apprenticeships/',note:'Current pathways in aerospace, manufacturing, aviation, and technology.'},{label:'City of Torrance · Technology Committee',url:'https://www.torranceca.gov/Business/Tech-Committee',note:'Advanced manufacturing, aerospace, biotech, mobility, and engineering.'},{label:'CSUDH · South Bay Economic Forecast',url:'https://www.csudh.edu/uce/economic-forecast/',note:'Skilled workforce, strategic location, high-tech, and logistics.'},{label:'Culver City · economic development',url:'https://www.culvercity.org/City-Hall/City-Departments/Economic-and-Cultural-Development/Economic-Development',note:'Creative industries, cultural assets, and local business.'},{label:'Santa Monica Bay National Estuary Program',url:'https://www.santamonicabay.org/who-we-are/mission-and-history/',note:'Bay restoration, resilience, science, and stewardship.'},{label:'Metro · LAX/Metro Transit Center',url:'https://www.metro.net/lax-metro-transit-center/',note:'Current C and K Line transit connection and airport interface.'},{label:'LA28 · venue plan',url:'https://la28.org/en/games-plan/venues.html',note:'Official venue zones across the region.'},{label:'Caltech · at a glance',url:'https://www.caltech.edu/about/at-a-glance',note:'Research breadth and management of JPL at the inland edge.'},
] as const;
