export type GearRole = 'carry' | 'sit' | 'serve' | 'shade' | 'light' | 'store';

export type GearPick = {
  id: string;
  rank: number;
  maker: string;
  name: string;
  role: GearRole;
  priceUsd: number;
  priceLabel: string;
  url: string;
  badge: string;
  verdict: string;
  useful: string;
  pleasant: string;
  durable: string;
  caveat: string;
  specs: readonly string[];
  scores: {
    utility: number;
    carry: number;
    durability: number;
    pleasure: number;
    commons: number;
    value: number;
    total: number;
  };
};

export const BEACH_COMMONS_V15 = {
  schema: 'https://pointcast.xyz/schemas/shopping-desk/v1',
  id: 'PC-FIELD-STUDY-015',
  edition: 15,
  title: 'THE GOOD GEAR',
  subtitle: 'Beach Commons V15',
  dek: 'Fifteen objects that earn the cart.',
  url: 'https://pointcast.xyz/beach-commons/v15',
  jsonUrl: 'https://pointcast.xyz/beach-commons/v15.json',
  blockUrl: 'https://pointcast.xyz/b/0542',
  blockId: '0542',
  publishedAt: '2026-07-29',
  priceCheckedAt: '2026-07-29T11:45:00-07:00',
  priceBoundary:
    'Prices and availability are USD editorial snapshots before tax, shipping, membership pricing, color-specific discounts, and local stock. Re-check the official product page before buying.',
  affiliateBoundary:
    'PointCast is not enrolled in a merchant affiliate program for this edition and earns $0 from every product link. Every shopping link is a plain direct link to the maker with no referral or affiliate parameter.',
  testingBoundary:
    'This is a specification-led editorial review, not a hands-on test. Rankings use current official specifications, packability, service or warranty information, public-use logic, value, and design judgment. No maker supplied a sample, paid for placement, reviewed copy, or determined a score.',
  fieldBoundary:
    'Beach Commons remains an unofficial editorial prototype, not an announced Dockweiler event. Organized activity, commercial activity, structures, amplified sound, fire, and other uses can require separate rules or permission. Keep public passage, habitat, dunes, emergency routes, fire-ring clearances, and the waterline clear.',
  previousEdition: {
    title: 'The Hardpoint League — Beach Commons V14',
    url: 'https://pointcast.xyz/beach-commons/v14',
    jsonUrl: 'https://pointcast.xyz/beach-commons/v14.json',
  },
  creators: [
    {
      name: 'Michael Hoydich',
      role: 'direction, utility-gear assignment, playlist and Pinterest companion premise, and Beach Commons series',
    },
    {
      name: 'Codex / OpenAI',
      role: 'current official-source research, scoring, original visual series, local Cart Composer, playlist curation, and PointCast edition',
    },
  ],
} as const;

export const GEAR_SCORE_WEIGHTS = [
  { id: 'utility', label: 'Utility', points: 25 },
  { id: 'carry', label: 'Carry + pack', points: 20 },
  { id: 'durability', label: 'Durability + service', points: 20 },
  { id: 'pleasure', label: 'Pleasure', points: 15 },
  { id: 'commons', label: 'Commons multiplier', points: 10 },
  { id: 'value', label: 'Value', points: 10 },
] as const;

export const GEAR_PICKS: readonly GearPick[] = [
  {
    id: 'gear-tie',
    rank: 1,
    maker: 'Nite Ize',
    name: 'Gear Tie Original, 18-inch 2-pack',
    role: 'carry',
    priceUsd: 9.99,
    priceLabel: '$9.99 snapshot',
    url: 'https://niteize.com/gear-tie-reusable-rubber-twist-tie',
    badge: 'Best ten-dollar multiplier',
    verdict: 'The least glamorous object improves every other object.',
    useful: 'Color-code, bundle, hang, tether, and tame long awkward pieces without single-use tape.',
    pleasant: 'The grippy rubber jacket and bendable wire make organization feel immediate rather than procedural.',
    durable: 'Waterproof, UV-resistant, saltwater-safe, reusable, and made in the USA.',
    caveat: 'Not weight-rated. Do not use for climbing, overhead loads, hot or sharp objects, or shifting vehicle cargo.',
    specs: ['18 in · 2 pack', 'waterproof + UV resistant', 'not weight-rated'],
    scores: { utility: 25, carry: 20, durability: 18, pleasure: 12, commons: 10, value: 9, total: 94 },
  },
  {
    id: 'frakta',
    rank: 2,
    maker: 'IKEA',
    name: 'FRAKTA large shopping bag',
    role: 'carry',
    priceUsd: 0.99,
    priceLabel: '$0.99',
    url: 'https://www.ikea.com/us/en/p/frakta-shopping-bag-large-blue-20611108/',
    badge: 'Best dollar in the whole review',
    verdict: 'A room-sized idea hiding in a one-dollar bag.',
    useful: 'Carry loose textiles, collect returns, separate wet from dry, and make pack-down failures visible.',
    pleasant: 'The loud blue is instant group wayfinding; the bag folds nearly out of existence.',
    durable: 'IKEA lists a 55-pound maximum load and at least 90% recycled polypropylene.',
    caveat: 'It is not approved for food contact. A one-dollar bag is a soft container, not protective storage.',
    specs: ['19 gal', '55 lb max load', '4 oz · folds flat'],
    scores: { utility: 25, carry: 20, durability: 16, pleasure: 11, commons: 10, value: 10, total: 92 },
  },
  {
    id: 'matador',
    rank: 3,
    maker: 'Matador',
    name: 'Pocket Blanket',
    role: 'sit',
    priceUsd: 35,
    priceLabel: '$35',
    url: 'https://www.matadorequipment.com/products/pocket-blanket-slate-blue',
    badge: 'Best room in a pocket',
    verdict: 'The clean boundary you can carry even when a picnic was not the plan.',
    useful: 'A 63-by-44-inch water-resistant surface with corner stakes and sand pockets seats two to four.',
    pleasant: 'It turns an incidental stop into a deliberate room without asking anyone to haul upholstery.',
    durable: 'Recycled nylon construction and a one-year manufacturing-defect warranty.',
    caveat: 'It is thin by design. Check local anchoring rules and conditions; use its sand pockets only as directed.',
    specs: ['63 × 44 in', '3.9 oz', 'seats 2–4'],
    scores: { utility: 23, carry: 20, durability: 15, pleasure: 14, commons: 10, value: 9, total: 91 },
  },
  {
    id: 'klean-cups',
    rank: 4,
    maker: 'Klean Kanteen',
    name: '16 oz Steel Pint Cup, 4-pack',
    role: 'serve',
    priceUsd: 35.96,
    priceLabel: '$35.96 sale snapshot',
    url: 'https://www.kleankanteen.com/collections/cups-mugs/products/stainless-steel-pint-cup-16oz-4-pack',
    badge: 'Best cup system',
    verdict: 'A stack is more useful than four personality objects.',
    useful: 'Four durable cups nest into a single narrow cylinder and make the shared water station obvious.',
    pleasant: 'Rolled rims, clean stainless surfaces, and no disposable-cup drift.',
    durable: '90% post-consumer recycled 18/8 stainless steel, dishwasher-safe, with a limited lifetime warranty.',
    caveat: 'These are single-wall cups. They can feel hot or cold in the hand and are not the pick for very hot drinks.',
    specs: ['16 oz × 4', 'nestable', 'dishwasher safe'],
    scores: { utility: 23, carry: 18, durability: 19, pleasure: 13, commons: 10, value: 8, total: 91 },
  },
  {
    id: 'range-500',
    rank: 5,
    maker: 'BioLite',
    name: 'Range 500 Headlamp',
    role: 'light',
    priceUsd: 69.95,
    priceLabel: '$69.95',
    url: 'https://www.bioliteenergy.com/products/range-500',
    badge: 'Best 2026 utility light',
    verdict: 'The light that helps the work without becoming the event.',
    useful: 'Five hundred lumens, white and red modes, USB-C fast charging, and IP67 protection in a 2.6-ounce headlamp.',
    pleasant: 'Hands-free light makes repair, inventory, and departure calmer; red mode preserves a lower-key atmosphere.',
    durable: 'Dust-tight, water-resistant to IP67, and covered by a three-year warranty.',
    caveat: 'Maximum brightness is rarely the public-life answer. Aim carefully, use the lowest effective mode, and respect wildlife and neighbors.',
    specs: ['500 lumens', '2.6 oz', 'USB-C · IP67'],
    scores: { utility: 24, carry: 19, durability: 18, pleasure: 12, commons: 8, value: 8, total: 89 },
  },
  {
    id: 'z-seat',
    rank: 6,
    maker: 'Therm-a-Rest',
    name: 'Z Seat',
    role: 'sit',
    priceUsd: 33.95,
    priceLabel: '$33.95',
    url: 'https://cascadedesigns.com/products/seats/z-seat/z-seat.html',
    badge: 'Best democratic chair',
    verdict: 'Two ounces of comfort beats an extra empty chair no one carried.',
    useful: 'Accordion-fold closed-cell foam creates a dry-ish, insulated seat without legs, hardware, or assembly.',
    pleasant: 'It is easy to hand to a child, an elder waiting for a higher chair, or the person who arrived with nothing.',
    durable: 'Closed-cell foam, no moving parts, and a limited lifetime warranty.',
    caveat: 'The 13-by-16-inch low seat is not accessible or comfortable for everyone; mix low pads with real chairs.',
    specs: ['13 × 16 × .75 in', '2 oz', 'closed-cell foam'],
    scores: { utility: 21, carry: 20, durability: 18, pleasure: 12, commons: 10, value: 7, total: 88 },
  },
  {
    id: 'neso-1',
    rank: 7,
    maker: 'Neso',
    name: 'Neso 1',
    role: 'shade',
    priceUsd: 120,
    priceLabel: '$120',
    url: 'https://www.neso.com/products/neso-tent',
    badge: 'Best light shade room',
    verdict: 'Four pounds can change the entire day—when the conditions and rules agree.',
    useful: 'A seven-by-seven-foot UPF 50+ shade sized for roughly two to four people.',
    pleasant: 'The open-sided plane preserves horizon, conversation, and airflow instead of making a private tent.',
    durable: 'Rust-proof aluminum poles and a simple fabric-and-anchor-bag system.',
    caveat: 'Shade is a wind load. Follow the maker’s setup and weather limits, fill all anchor bags as directed, never improvise stakes, and confirm site rules.',
    specs: ['7 × 7 ft', '4 lb', 'UPF 50+'],
    scores: { utility: 24, carry: 17, durability: 15, pleasure: 15, commons: 9, value: 7, total: 87 },
  },
  {
    id: 'stanley-jug',
    rank: 8,
    maker: 'Stanley',
    name: 'Adventure Fast Flow Water Jug, 2 gal',
    role: 'serve',
    priceUsd: 55,
    priceLabel: '$55',
    url: 'https://www.stanley1913.com/products/adventure-fast-flow-water-jug-2g',
    badge: 'Best hydration anchor',
    verdict: 'The most useful object is the one everyone walks back toward.',
    useful: 'Two gallons, a removable easy-clean spigot, leakproof latches, and a serious handle make water a visible shared service.',
    pleasant: 'A good spigot turns filling a cup into a small ritual and reduces the parade of disposable bottles.',
    durable: 'Double-wall foam insulation, rugged latches, and robust molded construction.',
    caveat: 'At 4.4 pounds empty, it belongs low in the cart. Selected colors may move in and out of stock.',
    specs: ['2 gal', '4.4 lb empty', 'removable spigot'],
    scores: { utility: 25, carry: 13, durability: 18, pleasure: 12, commons: 10, value: 8, total: 86 },
  },
  {
    id: 'helinox-one',
    rank: 9,
    maker: 'Helinox',
    name: 'Chair One (re)',
    role: 'sit',
    priceUsd: 139.95,
    priceLabel: '$139.95',
    url: 'https://helinox.com/products/chair-one-re-lp',
    badge: 'Best rational real chair',
    verdict: 'Bring fewer chairs; make at least one of them easy to rise from.',
    useful: 'A higher seat than the original Chair One, a 320-pound capacity, and a 2-pound 7.5-ounce packed weight.',
    pleasant: 'The tensioned sling and elevated frame feel like furniture without hauling patio furniture.',
    durable: 'DAC aluminum poles, recycled 300D fabric, replaceable construction logic, and a five-year warranty.',
    caveat: 'One expensive chair does not create access by itself. Preserve firm routes, turning space, choice of seat heights, and stable table positions.',
    specs: ['2 lb 7.5 oz packed', '320 lb capacity', '5-year warranty'],
    scores: { utility: 22, carry: 18, durability: 18, pleasure: 15, commons: 8, value: 5, total: 86 },
  },
  {
    id: 'aeropress-go-plus',
    rank: 10,
    maker: 'AeroPress',
    name: 'Go Plus',
    role: 'serve',
    priceUsd: 89.95,
    priceLabel: '$89.95',
    url: 'https://aeropress.com/products/aeropress-go-plus',
    badge: 'Best complete coffee ritual',
    verdict: 'A cafe collapses into its own cup, minus the hot-water problem.',
    useful: 'A complete manual 3-in-1 travel system packs into its stainless tumbler and brews about 10 ounces.',
    pleasant: 'Pressing one cup at a time naturally makes people slow down, talk, and pass the tool.',
    durable: 'Dishwasher-safe components and a one-year warranty.',
    caveat: 'It does not heat water. Bring already-hot water in a closed insulated vessel; do not infer a beach burner from this recommendation.',
    specs: ['10 oz brew', '1 lb 4 oz', 'packs into tumbler'],
    scores: { utility: 19, carry: 17, durability: 15, pleasure: 15, commons: 9, value: 7, total: 82 },
  },
  {
    id: 'alpenglow',
    rank: 11,
    maker: 'BioLite',
    name: 'AlpenGlow 500 Lantern',
    role: 'light',
    priceUsd: 79.95,
    priceLabel: '$79.95',
    url: 'https://www.bioliteenergy.com/products/alpenglow-500',
    badge: 'Best delight light',
    verdict: 'The joyful lantern wins the evening and loses one point to its old port.',
    useful: 'Five hundred lumens, warm and cool white, color modes, a 6,400 mAh battery, and USB-A charge-out.',
    pleasant: 'Warm dim light makes blue hour feel designed without introducing a screen.',
    durable: 'IPX4 weather resistance and a sturdy freestanding format.',
    caveat: 'The listed input is Micro USB, not USB-C. Keep output low, shielded, attended, and appropriate to wildlife and neighboring users.',
    specs: ['500 lumens', '13.4 oz', 'IPX4 · Micro USB input'],
    scores: { utility: 20, carry: 17, durability: 15, pleasure: 15, commons: 8, value: 6, total: 81 },
  },
  {
    id: 'moonlander',
    rank: 12,
    maker: 'NEMO Equipment',
    name: 'Moonlander Table',
    role: 'serve',
    priceUsd: 159.95,
    priceLabel: '$159.95',
    url: 'https://www.nemoequipment.com/products/moonlander-portable-camp-table',
    badge: 'Best tiny public desk',
    verdict: 'An expensive small surface that keeps finding jobs.',
    useful: 'Two height modes support ground sitting and chair sitting; the top measures 19 by 15 inches.',
    pleasant: 'The heat-stabilized easy-clean surface and beautifully resolved folding action invite coffee, repair, cards, drawing, or cups.',
    durable: 'Overmolded aluminum hinges and a hard nylon top are built for repeated setup.',
    caveat: 'Four pounds 13 ounces and nearly $160 is a lot for a small table. It earns the cart only if the group uses both heights.',
    specs: ['19 × 15 × 16 in', '4 lb 13 oz', 'dual height'],
    scores: { utility: 20, carry: 14, durability: 18, pleasure: 15, commons: 8, value: 4, total: 79 },
  },
  {
    id: 'rux-70',
    rank: 13,
    maker: 'RUX',
    name: '70L',
    role: 'store',
    priceUsd: 298,
    priceLabel: '$298',
    url: 'https://rux.life/products/rux-70l',
    badge: 'Best soft architecture',
    verdict: 'A box while working, almost nothing while stored.',
    useful: 'A 70-liter weatherproof soft box carries awkward group gear, opens wide, and collapses when the room disappears.',
    pleasant: 'Handles, wide mouth, clean geometry, and color make inventory visible instead of buried.',
    durable: 'Field-repairable construction and a lifetime guarantee are unusually strong service signals.',
    caveat: 'Very expensive. RUX has disclosed a lid-tunnel weakness in specific prior manufacturing runs; verify the current product and warranty terms before relying on it.',
    specs: ['70 L', '15.7 × 19.5 × 13.8 in', 'collapsible + field repairable'],
    scores: { utility: 22, carry: 16, durability: 16, pleasure: 14, commons: 8, value: 2, total: 78 },
  },
  {
    id: 'snow-peak-take',
    rank: 14,
    maker: 'Snow Peak',
    name: 'Renewed Take! Bamboo Chair Long',
    role: 'sit',
    priceUsd: 169.95,
    priceLabel: '$169.95',
    url: 'https://www.snowpeak.com/products/take-bamboo-chair-long-lv-086',
    badge: 'Best pleasure pick',
    verdict: 'Not the rational default. Absolutely the chair people remember.',
    useful: 'A full-height bamboo, aluminum, and canvas lounge chair folds and includes a carry strap.',
    pleasant: 'Warm touch surfaces and a relaxed angle make this the rare portable chair that changes the social temperature.',
    durable: 'Bamboo arms, aluminum frame, and replaceable-looking canvas construction reward care.',
    caveat: 'Eight pounds and about 50 inches long when stowed. Bring one as the generous seat, not twelve as the default system.',
    specs: ['8 lb', 'bamboo + aluminum + canvas', '50.4 in stowed length'],
    scores: { utility: 17, carry: 9, durability: 16, pleasure: 15, commons: 8, value: 4, total: 69 },
  },
  {
    id: 'yeti-gobox',
    rank: 15,
    maker: 'YETI',
    name: 'LoadOut GoBox 30',
    role: 'store',
    priceUsd: 250,
    priceLabel: '$250',
    url: 'https://www.yeti.com/cases-and-storage/hard-cases',
    badge: 'Best hard boundary',
    verdict: 'A very expensive answer to water, grit, and mysterious loose parts.',
    useful: 'A stackable hard case gives repair kits, lights, or electronics a visible protected home.',
    pleasant: 'A good latch and strict interior can turn closing inventory into a satisfying final act.',
    durable: 'IP65 and IP67 ratings and an overbuilt shell support wet, dusty, repeated transport.',
    caveat: 'It is not a cooler and YETI says it is not for food storage. For soft goods, a one-dollar bag is usually smarter.',
    specs: ['30-size hard case', 'IP65 + IP67', 'not a cooler'],
    scores: { utility: 19, carry: 9, durability: 20, pleasure: 12, commons: 6, value: 2, total: 68 },
  },
] as const;

export const GEAR_CARTS = [
  {
    id: 'start',
    title: 'Start Here',
    budget: '$100 ceiling',
    total: 79.93,
    itemIds: ['frakta', 'gear-tie', 'z-seat', 'matador'],
    thesis: 'Carry, organize, sit, and make one clean room. Borrow water and shade before buying more.',
    omission: 'No water service, real chair, light, or shade.',
  },
  {
    id: 'actual-day',
    title: 'The Actual Day',
    budget: '$500 ceiling',
    total: 466.84,
    itemIds: ['frakta', 'gear-tie', 'matador', 'klean-cups', 'stanley-jug', 'range-500', 'neso-1', 'helinox-one'],
    thesis: 'One useful public room: carry, ground, cups, water, work light, shade, and one higher seat.',
    omission: 'No table, coffee system, atmospheric lantern, or protective hard storage.',
  },
  {
    id: 'long-view',
    title: 'The Long View',
    budget: '$1,000 ceiling',
    total: 925.79,
    itemIds: ['frakta', 'gear-tie', 'matador', 'klean-cups', 'stanley-jug', 'range-500', 'neso-1', 'helinox-one', 'moonlander', 'rux-70'],
    thesis: 'A durable mixed-price kit with a real surface, repairable soft storage, and no redundant luxury.',
    omission: 'Still skips the second lantern, coffee ritual, lounge chair, and hard case on purpose.',
  },
] as const;

export const GEAR_PLATES = [
  {
    id: 'utility-parade',
    number: '01',
    title: 'The Utility Parade',
    image: '/beach-commons/v15/assets/01-utility-parade.png',
    alt: 'An intergenerational group arrives by handcart while fifteen brand-neutral public-life objects form a precise coastal inventory.',
    caption: 'Abundance of possibility, strict compactness.',
  },
  {
    id: 'one-good-cart',
    number: '02',
    title: 'One Good Cart',
    image: '/beach-commons/v15/assets/02-one-good-cart.png',
    alt: 'An elder and child inventory a tightly packed blue handcart using reusable ties and colored ceramic tokens.',
    caption: 'The kit begins with how it leaves.',
  },
  {
    id: 'first-light-coffee',
    number: '03',
    title: 'First-Light Coffee',
    image: '/beach-commons/v15/assets/03-first-light-coffee.png',
    alt: 'Two people make manual coffee from already-hot water beside a compact loaded cart on a clear coastal path.',
    caption: 'One press, four cups, no beach burner.',
  },
  {
    id: 'portable-room',
    number: '04',
    title: 'A Portable Room',
    image: '/beach-commons/v15/assets/04-portable-room.png',
    alt: 'A compact shade, table, low seats, blanket, and water station make a social room on a firm coastal hardscape.',
    caption: 'Comfort comes from arrangement, not volume.',
  },
  {
    id: 'repair-light',
    number: '05',
    title: 'Repair Light',
    image: '/beach-commons/v15/assets/05-repair-light.png',
    alt: 'Adults, an elder, and a child clean cups and repair soft gear together under small rechargeable headlamps.',
    caption: 'Maintenance is part of the pleasure.',
  },
  {
    id: 'blue-hour',
    number: '06',
    title: 'Blue-Hour Lantern',
    image: '/beach-commons/v15/assets/06-blue-hour-lantern.png',
    alt: 'A small circle gathers under the moon with one warm low lantern and an unamplified instrument.',
    caption: 'The smallest complete evening.',
  },
  {
    id: 'mixed-price',
    number: '07',
    title: 'Cheap / Sweet / Lifetime',
    image: '/beach-commons/v15/assets/07-cheap-sweet-lifetime.png',
    alt: 'A golden-hour still life compares inexpensive carry gear, mid-price utility objects, and long-life chairs and storage.',
    caption: 'The smartest kit mixes price levels.',
  },
  {
    id: 'goes-home',
    number: '08',
    title: 'All Gear Goes Home',
    image: '/beach-commons/v15/assets/08-all-gear-goes-home.png',
    alt: 'At sunset a group inventories one packed handcart and cleans the public ground before departure.',
    caption: 'The final score is an empty site.',
  },
] as const;

export const GEAR_PLAYLIST = {
  title: 'PACK LIGHT, STAY LONG',
  subtitle: 'Twelve tracks for carrying, unfolding, making coffee, fixing one thing, and staying until blue hour.',
  status:
    'Editorial sequence resolved against Spotify search on July 29, 2026. PointCast did not create, save, or modify a Spotify playlist or library.',
  tracks: [
    { number: '01', title: 'Sketch for Summer', artist: 'The Durutti Column', phase: 'arrive', url: 'https://open.spotify.com/track/2oeLt7N1amHZiev27FvKE2' },
    { number: '02', title: 'Water Copy', artist: 'Hiroshi Yoshimura', phase: 'unfold', url: 'https://open.spotify.com/track/5gKNq9RT6xg0dO4pvRXks0' },
    { number: '03', title: 'A Calf Born In Winter', artist: 'Khruangbin', phase: 'settle', url: 'https://open.spotify.com/track/3uR4I2H3X3CwNiwJOUPqlq' },
    { number: '04', title: 'Fantastic Man', artist: 'William Onyeabor', phase: 'carry', url: 'https://open.spotify.com/track/1ETZhP9orTkDclKEyt0xqm' },
    { number: '05', title: 'Genius of Love', artist: 'Tom Tom Club', phase: 'share', url: 'https://open.spotify.com/track/6UBQONiLH8kNmmB8UrV2Ef' },
    { number: '06', title: 'Brakhage', artist: 'Stereolab', phase: 'make', url: 'https://open.spotify.com/track/6Wi3gizHOtRi7DSsX3XWZA' },
    { number: '07', title: "La femme d'argent", artist: 'Air', phase: 'drift', url: 'https://open.spotify.com/track/6tEaLXZlN8b71vWV1SSsRf' },
    { number: '08', title: 'Turiya & Ramakrishna', artist: 'Alice Coltrane', phase: 'listen', url: 'https://open.spotify.com/track/4DVu7YgHVJaeN0C7HNpy2q' },
    { number: '09', title: 'Black Classical Music (feat. Venna & Charlie Stacey)', artist: 'Yussef Dayes, Venna, Charlie Stacey', phase: 'move', url: 'https://open.spotify.com/track/3hmCHZFkgE4tkJKSqpOUhz' },
    { number: '10', title: 'Time Moves Slow', artist: 'BADBADNOTGOOD, Samuel T. Herring', phase: 'repair', url: 'https://open.spotify.com/track/1IqF5PUDUnaykHLs0RWbDO' },
    { number: '11', title: 'This Must Be the Place (Naive Melody) – 2005 Remaster', artist: 'Talking Heads', phase: 'gather', url: 'https://open.spotify.com/track/6aBUnkXuCEQQHAlTokv9or' },
    { number: '12', title: 'Music for 18 Musicians: Pulses', artist: 'Steve Reich', phase: 'return', url: 'https://open.spotify.com/track/3qeXCVaC4tO4gS2aPdlRmc' },
  ],
} as const;

export const GEAR_RULES = [
  'Buy the missing capability, not the fantasy version of the day. Borrow, share, rent, repair, and reuse first.',
  'At least one higher stable seat and a firm clear route matter more than a matching chair fleet.',
  'Shade is a wind load. Use only maker-directed anchoring in lawful conditions and close it before conditions exceed the product or site limits.',
  'Bring already-hot water for the manual coffee setup; this review does not recommend or imply a beach stove or burner.',
  'Use the lowest effective light, aim and shield it, preserve neighboring darkness, and respect habitat and wildlife.',
  'Inventory before departure. Every tie, cup, cloth, anchor bag, small part, and wrapper goes home.',
] as const;
