export const BELLFLOWER_STORAGE_KEY = 'pc:bellflower:v1';
export const BELLFLOWER_RECEIPT_KEY = 'pc:bellflower:receipt:v1';
export const BELLFLOWER_RECEIPT_SCHEMA = 'pointcast.bellflower.receipt.v1';

export const BELLFLOWER_META = {
  version: 1,
  title: 'Bellflower',
  subtitle: 'A Noun listening game in ten blooms',
  description:
    'Ten full-screen listening visits. Ring an original browser-synthesized bell, let the scene bloom, and carry the resonance into a final garden.',
  route: '/bellflower',
  jsonRoute: '/bellflower.json',
  credit: 'Created for Michael Hoydich',
  stageCount: 10,
};

const prompt = (scene, light, materials, seed) =>
  `Bellflower listening-game environment, ${scene}, one clear ceremonial place for a pixel Noun character, ${light}, ${materials}, gentle botanical bloom emerging from digital signals, cinematic full-screen composition, generous negative space for minimal interface, no readable text, no logos, no watermark --ar 16:9 --stylize 360 --chaos 10 --seed ${seed}`;

export const BELLFLOWER_STAGES = [
  {
    id: 'hush-gate',
    number: 1,
    title: 'Hush Gate',
    whisper: 'Arrive before the sound does.',
    ritual: 'One clear press opens the listening path.',
    completion: 'The room has heard you.',
    background: '/images/shrines/block-shrine-bg.png',
    backgroundAlt: 'A pale gallery threshold with a luminous display and warm stone forms.',
    nounId: 3,
    accent: '#ffd166',
    bloom: '#fff2b2',
    shadow: '#17120f',
    strikesRequired: 1,
    sound: {
      id: 'bronze-arrival',
      label: 'Bronze arrival',
      baseHz: 293.66,
      partials: [0.5, 1, 1.19, 1.51, 2.03, 2.71],
      sequence: [1],
      decay: 3.2,
      attack: 0.004,
      brightness: 0.72,
      noise: 0.008,
      wet: 0.42,
    },
    midjourney: prompt(
      'a quiet limestone gate at first light with one small brass bell',
      'a single diagonal beam of warm morning light',
      'limestone, brushed brass, pale ash wood, tiny yellow bellflowers',
      8101,
    ),
  },
  {
    id: 'first-answer',
    number: 2,
    title: 'First Answer',
    whisper: 'A reply can be smaller than a sentence.',
    ritual: 'Ring twice, leaving a breath between answers.',
    completion: 'Two points of light remain.',
    background: '/images/shrines/campaign-shrine-bg.png',
    backgroundAlt: 'A warm desk of books, paper, stone, and a glowing display.',
    nounId: 22,
    accent: '#ff9f68',
    bloom: '#ffd5bd',
    shadow: '#21130e',
    strikesRequired: 2,
    sound: {
      id: 'paper-lantern',
      label: 'Paper lantern',
      baseHz: 329.63,
      partials: [1, 2.01, 2.98, 4.08],
      sequence: [1, 1.5],
      decay: 2.5,
      attack: 0.008,
      brightness: 0.58,
      noise: 0.018,
      wet: 0.34,
    },
    midjourney: prompt(
      'an intimate writing desk sanctuary with two paper lantern bells',
      'low amber afternoon light passing across a blank page',
      'rice paper, walnut, river stone, peach bellflowers',
      8102,
    ),
  },
  {
    id: 'water-table',
    number: 3,
    title: 'Water Table',
    whisper: 'Touch the surface; listen below it.',
    ritual: 'Make two ripples from different parts of the room.',
    completion: 'The ripples agree.',
    background: '/images/shrines/element-balance-shrine-bg.png',
    backgroundAlt: 'A bright Japanese-inspired desk with an ocean image, stones, and vessels.',
    nounId: 41,
    accent: '#65d6ce',
    bloom: '#b9fff6',
    shadow: '#0d2526',
    strikesRequired: 2,
    sound: {
      id: 'water-glass',
      label: 'Water glass',
      baseHz: 392,
      partials: [1, 2.04, 3.11, 4.23, 6.08],
      sequence: [1, 1.125],
      decay: 3.6,
      attack: 0.012,
      brightness: 0.62,
      noise: 0.012,
      wet: 0.58,
    },
    midjourney: prompt(
      'a shallow water table with two floating glass bells and a place for quiet reflection',
      'clean sea light reflected onto a plaster wall',
      'clear glass, water, sea-worn stone, pale aqua bellflowers',
      8103,
    ),
  },
  {
    id: 'ember-room',
    number: 4,
    title: 'Ember Room',
    whisper: 'Warmth is a frequency you can share.',
    ritual: 'Offer three low tones to the fire.',
    completion: 'The ember answers without hurry.',
    background: '/images/shrines/element-fire-shrine-bg.png',
    backgroundAlt: 'A dark timber room warmed by firelight, red foliage, and a glowing display.',
    nounId: 79,
    accent: '#ff735d',
    bloom: '#ffc2a8',
    shadow: '#260d0a',
    strikesRequired: 3,
    sound: {
      id: 'ember-bowl',
      label: 'Ember bowl',
      baseHz: 164.81,
      partials: [0.5, 1, 1.49, 2.02, 2.67],
      sequence: [1, 1.25, 1.5],
      decay: 4.1,
      attack: 0.018,
      brightness: 0.48,
      noise: 0.028,
      wet: 0.5,
    },
    midjourney: prompt(
      'a dark cedar listening room with a low ember bowl and a suspended bell',
      'soft hearth glow with quiet red reflections',
      'charred cedar, blackened bronze, ash, vermilion bellflowers',
      8104,
    ),
  },
  {
    id: 'listening-grid',
    number: 5,
    title: 'Listening Grid',
    whisper: 'The circuit becomes gentle when you enter it.',
    ritual: 'Place three signals across the field.',
    completion: 'The line is open.',
    background: '/images/shrines/system-shrine-bg.png',
    backgroundAlt: 'A dark luminous circuit landscape with small lights and a green display.',
    nounId: 98,
    accent: '#77e6b6',
    bloom: '#c9ffe5',
    shadow: '#061814',
    strikesRequired: 3,
    sound: {
      id: 'soft-signal',
      label: 'Soft signal',
      baseHz: 440,
      partials: [1, 2, 3, 4.01],
      sequence: [1, 1.5, 2],
      decay: 1.8,
      attack: 0.005,
      brightness: 0.46,
      noise: 0.006,
      wet: 0.28,
    },
    midjourney: prompt(
      'a floor-level listening grid where small signal lamps grow into flowers',
      'emerald points of light in a near-black room',
      'black glass, fine copper traces, frosted lamps, mint bellflowers',
      8105,
    ),
  },
  {
    id: 'four-elements',
    number: 6,
    title: 'Four Elements',
    whisper: 'Air, water, stone, fire: none sings alone.',
    ritual: 'Sound each corner once.',
    completion: 'Four rooms become one chord.',
    background: '/images/shrines/element-shrine-background-sheet.png',
    backgroundAlt: 'Four elemental listening rooms arranged as one visual field.',
    nounId: 164,
    accent: '#f4dd75',
    bloom: '#fff6bd',
    shadow: '#17170c',
    strikesRequired: 4,
    sound: {
      id: 'element-chord',
      label: 'Element chord',
      baseHz: 220,
      partials: [0.5, 1, 1.19, 1.5, 2.03],
      sequence: [1, 1.125, 1.5, 2],
      decay: 3.4,
      attack: 0.014,
      brightness: 0.55,
      noise: 0.02,
      wet: 0.48,
    },
    midjourney: prompt(
      'four connected elemental alcoves around a shared listening bell',
      'balanced dawn, water reflection, ember glow, and mineral sparkle',
      'air-washed linen, water glass, basalt, bronze, four colors of bellflower',
      8106,
    ),
  },
  {
    id: 'stone-choir',
    number: 7,
    title: 'Stone Choir',
    whisper: 'Weight can make a very tender note.',
    ritual: 'Wake three stones, then let the floor hold the tail.',
    completion: 'The old room is humming.',
    background: '/images/shrines/element-stone-shrine-bg.png',
    backgroundAlt: 'A mineral cabinet of stones, crystals, plants, and a green display.',
    nounId: 387,
    accent: '#9bd3c2',
    bloom: '#d8fff2',
    shadow: '#0b1c18',
    strikesRequired: 3,
    sound: {
      id: 'stone-choir',
      label: 'Stone choir',
      baseHz: 110,
      partials: [0.5, 1, 1.25, 1.51, 2.02],
      sequence: [1, 1.333, 1.5],
      decay: 5.2,
      attack: 0.032,
      brightness: 0.38,
      noise: 0.034,
      wet: 0.64,
    },
    midjourney: prompt(
      'a mineral archive where three resonant stones face a small garden bell',
      'cool museum daylight with crystal refractions',
      'granite, quartz, smoky glass, celadon bellflowers',
      8107,
    ),
  },
  {
    id: 'night-room',
    number: 8,
    title: 'Night Room',
    whisper: 'Darkness gives the long tone somewhere to go.',
    ritual: 'Send three lights into the distance.',
    completion: 'The dark is not empty.',
    background: '/images/shrines/room-shrine-bg.png',
    backgroundAlt: 'A dark cosmic room with floor cushions and a rose-lit display.',
    nounId: 512,
    accent: '#f0a7dc',
    bloom: '#ffd0ef',
    shadow: '#180b1a',
    strikesRequired: 3,
    sound: {
      id: 'night-lantern',
      label: 'Night lantern',
      baseHz: 246.94,
      partials: [1, 2.01, 3.02, 4.07, 5.12],
      sequence: [1, 1.5, 1.875],
      decay: 4.8,
      attack: 0.02,
      brightness: 0.5,
      noise: 0.014,
      wet: 0.72,
    },
    midjourney: prompt(
      'an open night sanctuary with three distant lantern bells and a view into stars',
      'deep indigo starlight with restrained rose illumination',
      'ink silk, dark walnut, frosted glass, blush bellflowers',
      8108,
    ),
  },
  {
    id: 'many-doors',
    number: 9,
    title: 'Many Doors',
    whisper: 'Every room you crossed is still sounding.',
    ritual: 'Ring four thresholds in any order.',
    completion: 'The path has become an instrument.',
    background: '/images/shrines/shrine-background-sheet.png',
    backgroundAlt: 'Four PointCast listening environments arranged as one field.',
    nounId: 925,
    accent: '#92bfff',
    bloom: '#d2e6ff',
    shadow: '#091429',
    strikesRequired: 4,
    sound: {
      id: 'thresholds',
      label: 'Four thresholds',
      baseHz: 261.63,
      partials: [0.5, 1, 1.19, 1.51, 2.04],
      sequence: [1, 1.25, 1.5, 2],
      decay: 3.8,
      attack: 0.009,
      brightness: 0.66,
      noise: 0.012,
      wet: 0.54,
    },
    midjourney: prompt(
      'four open doorways from a listening pilgrimage converging around one Noun',
      'a continuous path of dawn, amber, green signal, and night light',
      'stone thresholds, paper lanterns, fine circuitry, blue bellflowers',
      8109,
    ),
  },
  {
    id: 'resonant-garden',
    number: 10,
    title: 'Resonant Garden',
    whisper: 'Nothing to solve. Let the garden receive you.',
    ritual: 'Grow five bells into one final bloom.',
    completion: 'The garden keeps the sound.',
    background: '/images/shrines/element-nature-shrine-bg.png',
    backgroundAlt: 'A sunlit green studio opening into a mossy garden.',
    nounId: 1111,
    accent: '#d8f56c',
    bloom: '#efffb2',
    shadow: '#10210b',
    strikesRequired: 5,
    sound: {
      id: 'garden-resonance',
      label: 'Garden resonance',
      baseHz: 196,
      partials: [0.5, 1, 1.19, 1.5, 2.03, 2.72],
      sequence: [1, 1.125, 1.25, 1.5, 2],
      decay: 5.6,
      attack: 0.024,
      brightness: 0.7,
      noise: 0.026,
      wet: 0.68,
    },
    midjourney: prompt(
      'a luminous indoor-outdoor bellflower garden at the end of a listening path',
      'late morning leaf light with soft reflections from ten small bells',
      'moss, pale oak, clear glass, brass, an abundance of living bellflowers',
      8110,
    ),
  },
];
