import { POINTCAST_25, type PointCast25Team } from './pointcast-25';
import { POINTCAST_25_TEAMS } from './pointcast-25-audience';

export type MascotClass =
  | 'flora'
  | 'aerial'
  | 'apex'
  | 'hound'
  | 'range'
  | 'colossus'
  | 'folklore'
  | 'null';

export interface MascotClassDefinition {
  id: MascotClass;
  name: string;
  fieldName: string;
  art: string;
  color: string;
  instinct: string;
  strongAgainst: MascotClass;
}

export const MASCOT_CLASSES: MascotClassDefinition[] = [
  {
    id: 'flora',
    name: 'Flora',
    fieldName: 'The Buckeye Engine',
    art: '/images/mascot-battler/type-flora.png',
    color: '#bb2f24',
    instinct: 'Roots turn patience into late-round force.',
    strongAgainst: 'colossus',
  },
  {
    id: 'aerial',
    name: 'Aerial',
    fieldName: 'Storm Bird Parliament',
    art: '/images/mascot-battler/type-aerial.png',
    color: '#185d8c',
    instinct: 'Weather changes are information, not interruption.',
    strongAgainst: 'range',
  },
  {
    id: 'apex',
    name: 'Apex',
    fieldName: 'Night-Cat Territory',
    art: '/images/mascot-battler/type-apex.png',
    color: '#d76027',
    instinct: 'Pressure increases when the lights get smaller.',
    strongAgainst: 'hound',
  },
  {
    id: 'hound',
    name: 'Hound',
    fieldName: 'The Loyal Weather Pack',
    art: '/images/mascot-battler/type-hound.png',
    color: '#334f6c',
    instinct: 'Continuity compounds; the pack remembers the assignment.',
    strongAgainst: 'folklore',
  },
  {
    id: 'range',
    name: 'Range',
    fieldName: 'Hoof and Horizon',
    art: '/images/mascot-battler/type-range.png',
    color: '#c56a19',
    instinct: 'Space becomes speed before the defense can name it.',
    strongAgainst: 'flora',
  },
  {
    id: 'colossus',
    name: 'Colossus',
    fieldName: 'Old Power Country',
    art: '/images/mascot-battler/type-colossus.png',
    color: '#476942',
    instinct: 'Ancient mass wins the part of the game that cannot be rushed.',
    strongAgainst: 'apex',
  },
  {
    id: 'folklore',
    name: 'Folklore',
    fieldName: 'Saturday Tricksters',
    art: '/images/mascot-battler/type-folklore.png',
    color: '#6e4b77',
    instinct: 'A good story changes what the opponent thinks is possible.',
    strongAgainst: 'null',
  },
  {
    id: 'null',
    name: 'Null',
    fieldName: 'The Mascot That Is Not There',
    art: '/images/mascot-battler/type-null.png',
    color: '#202733',
    instinct: 'You cannot scout an absence.',
    strongAgainst: 'aerial',
  },
];

export const MASCOT_ARENAS = [
  {
    id: 'rain',
    name: 'Rain Game',
    note: 'Lake weather, soaked paper, bad footing.',
    favored: ['aerial', 'hound'] as MascotClass[],
  },
  {
    id: 'altitude',
    name: 'Thin Air',
    note: 'The field tilts uphill after halftime.',
    favored: ['aerial', 'apex'] as MascotClass[],
  },
  {
    id: 'heat',
    name: 'Heat Index',
    note: 'Old power and open-range legs survive.',
    favored: ['colossus', 'range'] as MascotClass[],
  },
  {
    id: 'night',
    name: 'Night Kick',
    note: 'Myth gets louder when the edges disappear.',
    favored: ['apex', 'folklore', 'null'] as MascotClass[],
  },
  {
    id: 'prairie',
    name: 'Crosswind',
    note: 'Nothing hides on a horizon this wide.',
    favored: ['range', 'flora'] as MascotClass[],
  },
  {
    id: 'archive',
    name: 'Archive Field',
    note: 'History, absence, and plant memory become playable.',
    favored: ['flora', 'folklore', 'null'] as MascotClass[],
  },
] as const;

interface MascotProfile {
  slug: string;
  mascot: string;
  mascotClass: MascotClass;
  officialStatus: 'official' | 'live-and-costumed' | 'identity-only';
  city: string;
  state: string;
  stadium: string;
  localResource: string;
  tradition: string;
  ability: string;
  abilityText: string;
  locality: number;
  legacy: number;
  myth: number;
  balance: number;
  sourceLabel: string;
  sourceUrl: string;
}

const profiles: MascotProfile[] = [
  {
    slug: 'ohio-state',
    mascot: 'Brutus Buckeye',
    mascotClass: 'flora',
    officialStatus: 'official',
    city: 'Columbus',
    state: 'Ohio',
    stadium: 'Ohio Stadium',
    localResource: 'Buckeye groves · Olentangy River · central-Ohio limestone',
    tradition: 'A state-tree seed became one of the sport’s rare botanical mascots.',
    ability: 'ROOT SYSTEM',
    abilityText: 'Gains eight Locality in an archive or prairie field.',
    locality: 84,
    legacy: 96,
    myth: 91,
    balance: 83,
    sourceLabel: 'Ohio State Buckeyes',
    sourceUrl: 'https://ohiostatebuckeyes.com',
  },
  {
    slug: 'notre-dame',
    mascot: 'The Leprechaun',
    mascotClass: 'folklore',
    officialStatus: 'official',
    city: 'Notre Dame',
    state: 'Indiana',
    stadium: 'Notre Dame Stadium',
    localResource: 'St. Joseph lakes · northern-Indiana winters · golden-hour campus light',
    tradition: 'A live student performer carries a folklore identity rather than an animal one.',
    ability: 'GOLDEN HOUR',
    abilityText: 'Turns one losing Myth round into a tie during a night kick.',
    locality: 78,
    legacy: 98,
    myth: 96,
    balance: 86,
    sourceLabel: 'Notre Dame Athletics',
    sourceUrl: 'https://fightingirish.com',
  },
  {
    slug: 'texas',
    mascot: 'Bevo',
    mascotClass: 'range',
    officialStatus: 'live-and-costumed',
    city: 'Austin',
    state: 'Texas',
    stadium: 'Darrell K Royal–Texas Memorial Stadium',
    localResource: 'Hill Country limestone · live-oak shade · Colorado River heat',
    tradition: 'A live longhorn turns Texas ranch history into a sideline presence.',
    ability: 'OPEN RANGE',
    abilityText: 'Adds six Form when the arena favors Range.',
    locality: 93,
    legacy: 96,
    myth: 94,
    balance: 82,
    sourceLabel: 'Texas Athletics',
    sourceUrl: 'https://texaslonghorns.com',
  },
  {
    slug: 'oregon',
    mascot: 'The Oregon Duck',
    mascotClass: 'aerial',
    officialStatus: 'official',
    city: 'Eugene',
    state: 'Oregon',
    stadium: 'Autzen Stadium',
    localResource: 'Willamette rain · Cascades timber · river-valley wind',
    tradition: 'A waterfowl identity became a national design laboratory without losing its regional joke.',
    ability: 'WEATHER SHIFT',
    abilityText: 'Rain Game activates Aerial instinct twice.',
    locality: 91,
    legacy: 83,
    myth: 90,
    balance: 91,
    sourceLabel: 'Oregon Athletics',
    sourceUrl: 'https://goducks.com',
  },
  {
    slug: 'georgia',
    mascot: 'Uga',
    mascotClass: 'hound',
    officialStatus: 'live-and-costumed',
    city: 'Athens',
    state: 'Georgia',
    stadium: 'Sanford Stadium',
    localResource: 'Georgia red clay · Athens tree canopy · Oconee heat',
    tradition: 'A live English bulldog lineage makes continuity itself part of the mascot.',
    ability: 'KENNEL STAND',
    abilityText: 'Never loses more than four points to a class disadvantage.',
    locality: 86,
    legacy: 94,
    myth: 95,
    balance: 88,
    sourceLabel: 'Georgia Bulldogs',
    sourceUrl: 'https://georgiadogs.com',
  },
  {
    slug: 'indiana',
    mascot: 'Hoosier the Bison',
    mascotClass: 'range',
    officialStatus: 'official',
    city: 'Bloomington',
    state: 'Indiana',
    stadium: 'Memorial Stadium',
    localResource: 'Indiana limestone · Brown County woods · state-seal bison history',
    tradition: 'The bison returned in 2025 after a nearly sixty-year official hiatus.',
    ability: 'BACK FROM HIATUS',
    abilityText: 'Receives ten Myth the first time it appears in a battle.',
    locality: 96,
    legacy: 79,
    myth: 97,
    balance: 84,
    sourceLabel: 'Indiana Athletics · Bison restoration',
    sourceUrl: 'https://iuhoosiers.com/news/2025/7/14/general-iu-reinstates-the-bison-as-the-official-iu-bloomington-mascot-hoosier-the-bison-to-make-first-public-appearance-on-aug-30-at-iu-football-season-opener',
  },
  {
    slug: 'miami',
    mascot: 'Sebastian the Ibis',
    mascotClass: 'aerial',
    officialStatus: 'official',
    city: 'Coral Gables',
    state: 'Florida',
    stadium: 'Hard Rock Stadium',
    localResource: 'Biscayne storm water · Everglades wetland · Atlantic pressure',
    tradition: 'The ibis is cast as the storm bird that knows when danger is coming and when to return.',
    ability: 'STORM FEEDER',
    abilityText: 'Adds nine Myth in rain and five Form at night.',
    locality: 95,
    legacy: 91,
    myth: 96,
    balance: 76,
    sourceLabel: 'Miami Hurricanes',
    sourceUrl: 'https://miamihurricanes.com',
  },
  {
    slug: 'lsu',
    mascot: 'Mike the Tiger',
    mascotClass: 'apex',
    officialStatus: 'live-and-costumed',
    city: 'Baton Rouge',
    state: 'Louisiana',
    stadium: 'Tiger Stadium',
    localResource: 'Mississippi floodplain · live-oak shade · humid night air',
    tradition: 'A live tiger habitat and costumed counterpart make Saturday night feel zoological.',
    ability: 'SATURDAY NIGHT EYES',
    abilityText: 'Adds twelve Form at night, but loses four Balance in heat.',
    locality: 92,
    legacy: 94,
    myth: 98,
    balance: 74,
    sourceLabel: 'LSU Athletics',
    sourceUrl: 'https://lsusports.net',
  },
  {
    slug: 'texas-tech',
    mascot: 'The Masked Rider + Raider Red',
    mascotClass: 'folklore',
    officialStatus: 'live-and-costumed',
    city: 'Lubbock',
    state: 'Texas',
    stadium: 'Jones AT&T Stadium',
    localResource: 'Llano Estacado wind · red dirt · huge western sky',
    tradition: 'The Masked Rider’s 1954 entrance and Raider Red’s 1971 portability form a dual-mascot system.',
    ability: 'TWO TEMPOS',
    abilityText: 'Uses the better of Myth or Locality in every first round.',
    locality: 97,
    legacy: 84,
    myth: 98,
    balance: 81,
    sourceLabel: 'Texas Tech Athletics · Masked Rider history',
    sourceUrl: 'https://texastech.com/news/2003/9/8/1954_Gator_Bowl_Team',
  },
  {
    slug: 'usc',
    mascot: 'Traveler',
    mascotClass: 'range',
    officialStatus: 'live-and-costumed',
    city: 'Los Angeles',
    state: 'California',
    stadium: 'Los Angeles Memorial Coliseum',
    localResource: 'Los Angeles basin light · Coliseum concrete · coastal evening air',
    tradition: 'A white horse circles the Coliseum as an old-Hollywood piece of live theater.',
    ability: 'COLISEUM GATE',
    abilityText: 'Adds seven Legacy when battling a top-ten PointCast card.',
    locality: 82,
    legacy: 97,
    myth: 93,
    balance: 79,
    sourceLabel: 'USC Athletics',
    sourceUrl: 'https://usctrojans.com',
  },
  {
    slug: 'alabama',
    mascot: 'Big Al',
    mascotClass: 'colossus',
    officialStatus: 'official',
    city: 'Tuscaloosa',
    state: 'Alabama',
    stadium: 'Bryant–Denny Stadium',
    localResource: 'Black Warrior River · red clay · dense southern heat',
    tradition: 'The elephant identity grew from the scale and force observers saw in Alabama football.',
    ability: 'MEMORY OF GIANTS',
    abilityText: 'Legacy cannot be reduced below ninety.',
    locality: 80,
    legacy: 99,
    myth: 92,
    balance: 88,
    sourceLabel: 'Alabama Athletics',
    sourceUrl: 'https://rolltide.com',
  },
  {
    slug: 'penn-state',
    mascot: 'The Nittany Lion',
    mascotClass: 'apex',
    officialStatus: 'official',
    city: 'University Park',
    state: 'Pennsylvania',
    stadium: 'Beaver Stadium',
    localResource: 'Nittany Mountain · central-Pennsylvania limestone · cold valley air',
    tradition: 'A mountain-lion identity gives an inland campus its own guardian species.',
    ability: 'MOUNTAIN ECHO',
    abilityText: 'Gains eight Balance after losing a round.',
    locality: 91,
    legacy: 94,
    myth: 93,
    balance: 90,
    sourceLabel: 'Penn State Athletics',
    sourceUrl: 'https://gopsusports.com',
  },
  {
    slug: 'texas-a-and-m',
    mascot: 'Reveille',
    mascotClass: 'hound',
    officialStatus: 'live-and-costumed',
    city: 'College Station',
    state: 'Texas',
    stadium: 'Kyle Field',
    localResource: 'Brazos heat · post-oak country · prairie thunder',
    tradition: 'The highest-ranking member of the Corps is also a live rough collie.',
    ability: 'HOME OF THE 12TH',
    abilityText: 'Adds eight Locality whenever its conference deck trails.',
    locality: 96,
    legacy: 91,
    myth: 95,
    balance: 84,
    sourceLabel: 'Texas A&M Athletics',
    sourceUrl: 'https://12thman.com',
  },
  {
    slug: 'oklahoma',
    mascot: 'Boomer + Sooner',
    mascotClass: 'range',
    officialStatus: 'live-and-costumed',
    city: 'Norman',
    state: 'Oklahoma',
    stadium: 'Gaylord Family Oklahoma Memorial Stadium',
    localResource: 'Red River wind · prairie grass · cross-state horizon',
    tradition: 'Two white ponies animate the Sooner Schooner and the land-run identity around it.',
    ability: 'TWIN PONIES',
    abilityText: 'The second round repeats half of the first round’s arena bonus.',
    locality: 91,
    legacy: 97,
    myth: 94,
    balance: 82,
    sourceLabel: 'Oklahoma Athletics',
    sourceUrl: 'https://soonersports.com',
  },
  {
    slug: 'michigan',
    mascot: 'No official mascot',
    mascotClass: 'null',
    officialStatus: 'identity-only',
    city: 'Ann Arbor',
    state: 'Michigan',
    stadium: 'Michigan Stadium',
    localResource: 'Huron River · Great Lakes winter · glacial terrain',
    tradition: 'The Wolverine is the nickname and visual identity; Michigan still fields no official mascot.',
    ability: 'ABSENCE IS ARMOR',
    abilityText: 'Opponents receive no class advantage against this card.',
    locality: 88,
    legacy: 99,
    myth: 99,
    balance: 93,
    sourceLabel: 'Michigan Athletics · no-mascot note',
    sourceUrl: 'https://mgoblue.com/news/2010/9/25/football-field-pass-with-richard-retyi-bowling-green',
  },
  {
    slug: 'byu',
    mascot: 'Cosmo the Cougar',
    mascotClass: 'apex',
    officialStatus: 'official',
    city: 'Provo',
    state: 'Utah',
    stadium: 'LaVell Edwards Stadium',
    localResource: 'Wasatch altitude · Provo River · dry mountain light',
    tradition: 'A cougar identity becomes especially convincing when the mountains are physically behind it.',
    ability: 'ALTITUDE DISCIPLINE',
    abilityText: 'Adds ten Balance in Thin Air.',
    locality: 98,
    legacy: 82,
    myth: 88,
    balance: 94,
    sourceLabel: 'BYU Athletics',
    sourceUrl: 'https://byucougars.com',
  },
  {
    slug: 'ole-miss',
    mascot: 'Tony the Landshark',
    mascotClass: 'colossus',
    officialStatus: 'official',
    city: 'Oxford',
    state: 'Mississippi',
    stadium: 'Vaught–Hemingway Stadium',
    localResource: 'North-Mississippi clay · cypress water · hill-country humidity',
    tradition: 'Introduced in 2018, Tony honors Tony Fein and a defensive “Fins Up” gesture born in 2008.',
    ability: 'FINS UP',
    abilityText: 'Adds nine Myth when an opponent’s Form is higher.',
    locality: 79,
    legacy: 83,
    myth: 94,
    balance: 75,
    sourceLabel: 'Ole Miss Athletics · Tony introduction',
    sourceUrl: 'https://olemisssports.com/news/2018/8/11/football-ole-miss-holds-meet-the-rebels-introduces-new-on-field-mascot',
  },
  {
    slug: 'tennessee',
    mascot: 'Smokey',
    mascotClass: 'hound',
    officialStatus: 'live-and-costumed',
    city: 'Knoxville',
    state: 'Tennessee',
    stadium: 'Neyland Stadium',
    localResource: 'Tennessee River · Smoky Mountain fog · orange clay',
    tradition: 'A bluetick coonhound lineage links the stadium to Appalachian working-dog country.',
    ability: 'RIVER HOUND',
    abilityText: 'Rain turns Locality into an attacking stat.',
    locality: 99,
    legacy: 91,
    myth: 96,
    balance: 82,
    sourceLabel: 'Tennessee Athletics',
    sourceUrl: 'https://utsports.com',
  },
  {
    slug: 'clemson',
    mascot: 'The Tiger',
    mascotClass: 'apex',
    officialStatus: 'official',
    city: 'Clemson',
    state: 'South Carolina',
    stadium: 'Memorial Stadium',
    localResource: 'Lake Hartwell · Carolina granite · humid foothills',
    tradition: 'A tiger, a hill, and a rock turn the entrance itself into the mascot’s first move.',
    ability: 'HILL CHARGE',
    abilityText: 'Adds eight Form in the opening round.',
    locality: 91,
    legacy: 93,
    myth: 92,
    balance: 80,
    sourceLabel: 'Clemson Athletics',
    sourceUrl: 'https://clemsontigers.com',
  },
  {
    slug: 'utah',
    mascot: 'Swoop',
    mascotClass: 'aerial',
    officialStatus: 'official',
    city: 'Salt Lake City',
    state: 'Utah',
    stadium: 'Rice–Eccles Stadium',
    localResource: 'Wasatch thermals · Salt Lake basin · red-tailed-hawk country',
    tradition: 'Swoop is a red-tailed hawk; the Utes nickname is used with tribal permission.',
    ability: 'REDTAIL THERMAL',
    abilityText: 'Adds six Locality in heat and ten in Thin Air.',
    locality: 99,
    legacy: 84,
    myth: 91,
    balance: 89,
    sourceLabel: 'Utah Athletics · traditions',
    sourceUrl: 'https://utahutes.com/sports/2016/6/10/trads-ute-trads-what-html',
  },
  {
    slug: 'washington',
    mascot: 'Dubs II',
    mascotClass: 'hound',
    officialStatus: 'live-and-costumed',
    city: 'Seattle',
    state: 'Washington',
    stadium: 'Husky Stadium',
    localResource: 'Lake Washington rain · cedar air · Puget Sound weather',
    tradition: 'Dubs II is the university’s fourteenth live mascot and is an Alaskan malamute.',
    ability: 'RAIN PACK',
    abilityText: 'Adds twelve Balance in rain.',
    locality: 99,
    legacy: 87,
    myth: 93,
    balance: 92,
    sourceLabel: 'Washington Athletics · mascot history',
    sourceUrl: 'https://gohuskies.com/sports/2013/4/18/208229209',
  },
  {
    slug: 'florida',
    mascot: 'Albert + Alberta',
    mascotClass: 'colossus',
    officialStatus: 'official',
    city: 'Gainesville',
    state: 'Florida',
    stadium: 'Ben Hill Griffin Stadium',
    localResource: 'Paynes Prairie · subtropical wetland · limestone springs',
    tradition: 'A paired alligator identity makes the swamp both habitat and tactical concept.',
    ability: 'SWAMP CLOCK',
    abilityText: 'Heat adds nine Balance; rain adds six Myth.',
    locality: 99,
    legacy: 89,
    myth: 94,
    balance: 83,
    sourceLabel: 'Florida Gators',
    sourceUrl: 'https://floridagators.com',
  },
  {
    slug: 'south-carolina',
    mascot: 'Cocky',
    mascotClass: 'aerial',
    officialStatus: 'official',
    city: 'Columbia',
    state: 'South Carolina',
    stadium: 'Williams–Brice Stadium',
    localResource: 'Congaree heat · palmetto shade · Carolina sandhills',
    tradition: 'A gamecock identity turns noise, timing, and local agricultural history into personality.',
    ability: 'DAWN CROW',
    abilityText: 'Wins exact ties and receives five Myth in heat.',
    locality: 89,
    legacy: 79,
    myth: 96,
    balance: 78,
    sourceLabel: 'South Carolina Athletics',
    sourceUrl: 'https://gamecocksonline.com',
  },
  {
    slug: 'boise-state',
    mascot: 'Buster Bronco',
    mascotClass: 'range',
    officialStatus: 'official',
    city: 'Boise',
    state: 'Idaho',
    stadium: 'Albertsons Stadium',
    localResource: 'Boise River · high desert · blue-turf mirage',
    tradition: 'A bronco on an impossible blue field makes place and spectacle inseparable.',
    ability: 'BLUE MIRAGE',
    abilityText: 'Adds eleven Myth when facing a higher-ranked card.',
    locality: 98,
    legacy: 84,
    myth: 97,
    balance: 89,
    sourceLabel: 'Boise State Athletics · Buster Bronco',
    sourceUrl: 'https://broncosports.com/news/2008/8/28/Buster_Bronco_Selected_To_Capital_One_Mascot_Team',
  },
  {
    slug: 'iowa',
    mascot: 'Herky the Hawk',
    mascotClass: 'aerial',
    officialStatus: 'official',
    city: 'Iowa City',
    state: 'Iowa',
    stadium: 'Kinnick Stadium',
    localResource: 'Iowa River · black prairie soil · cold western wind',
    tradition: 'A cartoon hawk named for Hercules became a friendly face for a notably stern football place.',
    ability: 'KINNICK DUSK',
    abilityText: 'Adds ten Legacy at night and five Balance in crosswind.',
    locality: 91,
    legacy: 91,
    myth: 88,
    balance: 95,
    sourceLabel: 'Iowa Athletics',
    sourceUrl: 'https://hawkeyesports.com',
  },
];

const classById = new Map(MASCOT_CLASSES.map((entry) => [entry.id, entry]));
const teamBySlug = new Map(POINTCAST_25_TEAMS.map((team) => [team.slug, team]));

export const MASCOT_CARDS = profiles.map((profile) => {
  const team = teamBySlug.get(profile.slug);
  const mascotClass = classById.get(profile.mascotClass);
  if (!team) throw new Error(`Mascot profile has no PointCast 25 team: ${profile.slug}`);
  if (!mascotClass) throw new Error(`Unknown mascot class: ${profile.mascotClass}`);

  return {
    ...profile,
    school: team.school,
    short: team.short,
    conference: team.conference,
    rank: team.rank,
    accent: team.accent,
    form: Math.max(46, 96 - team.rank * 2),
    pointcastReason: team.reason,
    pointcastProof: team.proof,
    art: mascotClass.art,
    className: mascotClass.name,
    classFieldName: mascotClass.fieldName,
    classInstinct: mascotClass.instinct,
    sourceCheckedAt: '2026-07-27',
    canonical: `https://pointcast.xyz/mascot-battler/${profile.slug}`,
    machineEdition: `https://pointcast.xyz/mascot-battler/${profile.slug}.json`,
  };
});

export type MascotCard = (typeof MASCOT_CARDS)[number];

export const MASCOT_BATTLER = {
  spec: 'pointcast.saturday-myth-machine/v1',
  title: 'SATURDAY MYTH MACHINE',
  subtitle: 'A mascot atlas that knows how to fight.',
  canonical: 'https://pointcast.xyz/mascot-battler',
  machineEdition: 'https://pointcast.xyz/mascot-battler.json',
  season: POINTCAST_25.season,
  board: POINTCAST_25.board,
  publishedAt: '2026-07-27T20:30:00-07:00',
  cardCount: MASCOT_CARDS.length,
  classCount: MASCOT_CLASSES.length,
  rules: [
    'Pick a conference deck and a creature-class deck.',
    'Three deterministic rounds test place, lore, and Saturday force.',
    'Arena weather, class advantage, conference chemistry, and type instinct modify the cards.',
    'Every number is editorial game balance, not a claim about living animals, students, or institutions.',
    'Collection state stays in this browser. No signup, wallet, wager, or purchase is required.',
  ],
  boundary:
    'Unofficial editorial game. PointCast is not affiliated with, endorsed by, or sponsored by any school, conference, mascot program, or athletic association. Original illustrations depict broad creature archetypes and do not reproduce official mascot costume designs or logos.',
} as const;

export const MASCOT_CONFERENCES = Array.from(new Set(MASCOT_CARDS.map((card) => card.conference)));

export function getMascotCard(slug: string) {
  return MASCOT_CARDS.find((card) => card.slug === slug);
}

export function mascotCardPower(card: MascotCard) {
  return card.locality + card.legacy + card.myth + card.balance + card.form;
}

export function mascotCardFromTeam(team: PointCast25Team) {
  return MASCOT_CARDS.find((card) => card.school === team.school);
}
