export const RESERVE = {
  schema: 'pointcast.noggle-reserve/v1',
  name: 'Noggle Reserve',
  motto: 'In Noggles We Trust',
  canonical: 'https://pointcast.xyz/noggle-reserve',
  machine: 'https://pointcast.xyz/noggle-reserve.json',
  publishedAt: '2026-10-02',
  status: 'An art-club concept',
  disclosure: 'A fictional Nouns Bank art/community concept directed by Mike Hoydich. No licensed bank, deposits, cash redemption, investment offer, acquisition or Nouns DAO endorsement.',
  built: ['This digital exhibition', 'Ten front-face note prototypes using actual Nouns #0–9', 'A read-only JSON edition', 'Illustrative teller, gallery and journey-ledger experiences'],
  proposed: ['A volunteer art-note exchange', 'A moderated serial-number journey ledger', 'A permissioned temporary art space in El Segundo', 'Optional Tezos companion artworks, subject to a separate design and approval'],
  artwork: {
    license: 'Nouns artwork is CC0; using the art does not imply NFT ownership or endorsement.',
    provenance: '/images/noggle-reserve/provenance.json',
    officialSource: 'https://nouns.wtf/brand',
    sourceContract: '0x9C8fF314C9Bc7F6e59A9d9225Fb22946427eDC03',
    sourceChain: 'Ethereum mainnet',
    note: 'Official numbered Noun shapes and colors are preserved in the flat artwork. Generated physical mockups are illustrative and may vary in geometry or detail.',
  },
  noteSpec: {
    prototype: '06 · Pixel Weave', numeral: '10', nounIds: [4],
    meaning: 'The numeral is part of the collectible design, not a monetary amount or redemption promise.',
    trimMm: [150, 75], rasterPx: [3600, 1800],
    svg: '/images/noggle-reserve/06-pixel-weave.svg',
    pack: '/downloads/noggle-reserve-ten-authentic-nouns-prototypes.zip',
    status: 'Front-face design prototypes, not a press-ready production pack.',
    proposedProduction: 'Matte cotton-rich paper, process CMYK, no metallic foil. Stock, duplex reverse, bleed, safe zone, output profile and cutting tolerance must be agreed with the selected printer and proofed.',
    physicalProof: 'No physical press proof or manufactured notes verified.',
  },
  exchange: [
    { step: '01', title: 'Make a note', body: 'A small edition of numbered art objects. Keep the exact Noun, add a clear collectible label, and approve a physical proof before a print run.' },
    { step: '02', title: 'Trade a story', body: 'At a proposed art table, two willing people could swap a note for another artwork or an agreed creative contribution. Never a cash exchange, deposit or promise to redeem.' },
    { step: '03', title: 'Leave a trace', body: 'An optional serial-number page could record places, stories and permissioned photos. The object travels; private identities and exact addresses stay out of the public ledger.' },
  ],
  phases: [
    { phase: '00', title: 'The digital branch', status: 'Built in this release', scope: 'An accessible exhibition, original-art provenance, note studies, build scope and machine edition.', exit: 'Readable on phone and desktop; source links and artwork labels checked.' },
    { phase: '01', title: 'One table, one afternoon', status: 'Proposed · 1–2 weeks', scope: 'Printer proof, a small pilot edition, a portable teller desk, display sleeves, a simple volunteer script and a host-approved art gathering.', exit: 'Printer-approved proof, host permission and a small explicit materials budget. No merchant commitments assumed.' },
    { phase: '02', title: 'A ledger with stories', status: 'Proposed · 2–3 weeks', scope: 'A serial-number lookup, opt-in contributions, moderation, correction/removal controls, accessible QR destinations and read-only JSON exports.', exit: 'Abuse/privacy review, public status labels and tested recovery. Pilot stories verified with participants.' },
    { phase: '03', title: 'A room of our own', status: 'Exploratory · timing open', scope: 'Compare a temporary gallery, a small shop unit and a former bank shell; check owner consent, permitted use, accessibility, insurance and total occupancy costs. Explore Tezos art companions separately.', exit: 'Verified availability, a viable temporary-use plan and separate authorization for any lease, spend or onchain build.' },
  ],
  localResearch: {
    checkedAt: '2026-10-02',
    likelyReference: 'Citizens Business Bank · 275 Main Street, El Segundo',
    status: 'Operating, unaffiliated branch according to its official locator. Likely reference to Mike’s “citizen”; the intended bank is not certain.',
    source: 'https://www.cbbank.com/locations/el-segundo-business-financial-center/',
    acquisition: 'No sale availability, acquisition, owner permission or bank partnership has been established.',
    propertyStrategy: 'Begin with a temporary art venue or small retail space. Former bank shells are a research category, not an announced target. No verified property price or live lease quote is published.',
    nextChecks: ['Current owner and authorized leasing contact', 'Written availability and permitted temporary use', 'All-in rent, deposit, utilities, fit-out, accessibility and insurance', 'City planning and business-license requirements before public occupancy'],
  },
  adventure: {
    name: 'Adventure DAO', status: 'Proposed research-and-project collective',
    description: 'Humans set the mission. Agents research, model and build. Humans authorize spending and legal or financial decisions. Start with a studio and bounded projects; any future deal would use a separately reviewed entity.',
    missions: ['Nouns Bank 1976 · digital exhibit, then a possible art pop-up', 'Empty Bank Atlas · read-only research into former branch spaces', 'One Useful Thing / 30 Days · a software or community prototype'],
    disclosure: 'No established DAO governance, token, capital pool, membership offer, fundraising, investment return or acquisition activity is claimed.',
  },
  opinion: { author: 'Codex', text: 'The strongest first branch is a table, a stack of beautiful notes and a story worth passing on. I would test that ritual before signing for a building.' },
} as const;

export const NOTE_STUDIES = [
  { file: '01-founding-red', name: 'Founding Red', nouns: [0] },
  { file: '02-arctic-ledger', name: 'Arctic Ledger', nouns: [1] },
  { file: '03-daylight-ten', name: 'Daylight Ten', nouns: [2] },
  { file: '04-midnight-vault', name: 'Midnight Vault', nouns: [3] },
  { file: '05-noun-parade', name: 'Noun Parade', nouns: [0, 1, 2, 3] },
  { file: '06-pixel-weave', name: 'Pixel Weave', nouns: [4] },
  { file: '07-red-signal', name: 'Red Signal', nouns: [5] },
  { file: '08-archive-stamps', name: 'Archive Stamps', nouns: [6, 7, 8] },
  { file: '09-blue-assembly', name: 'Blue Assembly', nouns: [5, 6, 7, 8, 9] },
  { file: '10-golden-pair', name: 'Golden Pair', nouns: [8, 9] },
] as const;
