export const CALENDAR_APPENDIX = {
  id: '04.A',
  title: 'The movable treaty',
  dek: 'The essay leaves the page and becomes a listening room, an image field, a paper object, and a small circulating edition.',
  why: [
    'A useful idea should be able to change rooms without losing its shape. The calendar began as a grid, became an argument, and now becomes a set of things you can play, pin, print, pass along, and keep.',
    'These companions are not promotion pasted onto the issue. They are other ways to practice it: music gives the week weather, images make its edges visible, the PDF lets a hand revise the treaty, and the edition gives the document a modest public life.',
  ],
  flow: [
    { number: '01', verb: 'Listen', note: 'Choose the room that matches the week: shadow work for protected attention, or commons music for shared and unclaimed time.' },
    { number: '02', verb: 'Look', note: 'Walk either fifty-image board slowly. Save only what changes how you see the next seven days.' },
    { number: '03', verb: 'Carry', note: 'Download the twelve-page field edition. Print one page, fold a corner, write in the weather.' },
    { number: '04', verb: 'Circulate', note: 'The OBJKT campaign treats an edition as a reading circle: one hundred issues, with the first sixty offered free.' },
  ],
  spotify: [
    {
      id: '38YzecNFRdDVnDAxZcHV9d',
      title: 'A TREATY WITH THE DAY — SHADOW WORK',
      url: 'https://open.spotify.com/playlist/38YzecNFRdDVnDAxZcHV9d',
      embedUrl: 'https://open.spotify.com/embed/playlist/38YzecNFRdDVnDAxZcHV9d',
      tracks: 18,
      duration: '53 min',
      movements: ['ARRIVE', 'ANCHOR', 'INTERRUPTION', 'RETURN'],
      why: 'For work whose visible rectangle hides an approach and a return. The sequence begins with an arrival, gathers concentration, admits interruption, and gives the nervous system a way back.',
    },
    {
      id: '02VSkAD9uXGZYi1aUVKV5B',
      title: 'LEAVE A SQUARE — COMMONS MUSIC',
      url: 'https://open.spotify.com/playlist/02VSkAD9uXGZYi1aUVKV5B',
      embedUrl: 'https://open.spotify.com/embed/playlist/02VSkAD9uXGZYi1aUVKV5B',
      tracks: 18,
      duration: '1 hr 2 min',
      movements: ['TIDE', 'DRIFT', 'GATHER', 'OPEN AIR'],
      why: 'For time that is allowed to remain hospitable. The room moves from tide to drift, gathers company without crowding it, and ends in open air.',
    },
  ],
  pinterest: [
    {
      title: 'A CALENDAR IS A TREATY — SHADOWS & WEATHER',
      url: 'https://www.pinterest.com/hoydich/a-calendar-is-a-treaty-shadows-weather/',
      pins: 50,
      field: 'Long shadows, marked paper, changing light, weather systems, thresholds, and the invisible edges around a promise.',
    },
    {
      title: 'LEAVE A SQUARE — TIDES & COMMONS',
      url: 'https://www.pinterest.com/hoydich/leave-a-square-tides-commons/',
      pins: 50,
      field: 'Tide tables, shared tables, open fields, public rooms, soft boundaries, and places kept available for arrival.',
    },
  ],
  pdf: {
    title: 'A Calendar Is a Treaty — Field Edition',
    url: '/downloads/a-calendar-is-a-treaty-field-edition.pdf',
    pages: 12,
    price: 'free',
    format: 'US Letter PDF',
  },
  objkt: {
    title: 'A Calendar Is a Treaty — Field Edition',
    status: 'live',
    platform: 'OBJKT',
    url: 'https://objkt.com/tokens/open_objkt/41360',
    tokenId: '41360',
    contract: 'KT1XaCf6gkjFnKg3QmPfn6gep53moMvjkj1E',
    operationHash: 'ooUkysuqT5uPyMK5Qt64qYvhR8o1k6TmEkucKLdqKe4mKYGGFUQ',
    listingOperationHash: 'ooTMAhrAyhp7U2am6gDy3wi64CrtSw7Z1rkwGNkEpf6yhEpN6Ti',
    supply: 100,
    free: 60,
    retained: 40,
    priceTez: 0,
    rationale: 'One hundred is enough to feel finite without pretending the work is scarce. Sixty free issues make access the opening gesture; forty stay with the studio for future readers, exchanges, exhibitions, and gifts.',
  },
} as const;
