export const PLAY_LAYER_VERSION = '0.1.0';

export const PLAY_LAYER_DESCRIPTION =
  'PointCast play layer: passport stamps, daily walk, agent quests, room weather, radio, collectible routes, builder ghosts, civic wishes, a small site pet, and Zen Cats.';

export const PLAY_SURFACES = [
  {
    id: 'passport',
    code: 'PASS',
    title: 'PointCast Passport',
    route: '/passport',
    summary: 'A browser-local stamp book for visits, votes, games, routes, and agent-native rituals.',
  },
  {
    id: 'quests',
    code: 'QSTS',
    title: 'Agent Quest Board',
    route: '/quests',
    summary: 'Small tasks that humans can post and agents can claim, complete, and leave receipts for.',
  },
  {
    id: 'walk',
    code: 'WALK',
    title: 'The Daily Walk',
    route: '/walk',
    summary: 'A five-stop route through the live site that changes by the PT calendar day.',
  },
  {
    id: 'weather',
    code: 'WX',
    title: 'Room Weather',
    route: '/room-weather',
    summary: 'Ambient states for PointCast rooms, derived from editorial signals and visit rituals.',
  },
  {
    id: 'radio',
    code: 'RAD',
    title: 'PointCast Radio',
    route: '/radio',
    summary: 'A text-first broadcast desk announcing drops, quests, polls, races, and room states.',
  },
  {
    id: 'routes',
    code: 'ROUT',
    title: 'Collectible Routes',
    route: '/routes',
    summary: 'Multi-stop path cards that unlock as passport stamps accumulate.',
  },
  {
    id: 'builders',
    code: 'BLDR',
    title: 'Builder Ghosts',
    route: '/builders',
    summary: 'A visible trail of the humans and agents who keep showing up inside the system.',
  },
  {
    id: 'civic',
    code: 'CIV',
    title: 'Tiny Civic Layer',
    route: '/civic',
    summary: 'Voteable wishes that feed the queue and turn completed public desire into artifacts.',
  },
  {
    id: 'pet',
    code: 'PET',
    title: 'PointCast Pet',
    route: '/pet',
    summary: 'A local, site-wide creature that changes as the visitor votes, collects, races, and rests.',
  },
  {
    id: 'zen-cats',
    code: 'CAT',
    title: 'Zen Cat Garden',
    route: '/zen-cats',
    summary: 'A daily calm cat collection game with local care and a Tezos-ready PCCAT mint path.',
  },
  {
    id: 'derby-season',
    code: 'LIGA',
    title: 'Agent Derby Season',
    route: '/agent-derby',
    summary: 'A league wrapper around the deterministic race engine: standings, feature seeds, and tickets.',
  },
] as const;

export type PlaySurfaceId = (typeof PLAY_SURFACES)[number]['id'];

export const PLAY_SURFACE_BY_ID = Object.fromEntries(PLAY_SURFACES.map((surface) => [surface.id, surface]));

export const PASSPORT_STAMPS = [
  {
    id: 'daily-drop',
    label: 'Daily Drop',
    category: 'collect',
    route: '/today',
    action: 'Collect',
    points: 3,
    description: 'Claim the shared PT-calendar drop.',
  },
  {
    id: 'poll-vote',
    label: 'Civic Vote',
    category: 'signal',
    route: '/polls',
    action: 'Vote',
    points: 2,
    description: 'Cast a Schelling-point vote.',
  },
  {
    id: 'derby-run',
    label: 'Race Receipt',
    category: 'game',
    route: '/agent-derby',
    action: 'Race',
    points: 4,
    description: 'Run an Agent Derby seed.',
  },
  {
    id: 'gandalf-sit',
    label: 'Quiet Sit',
    category: 'ritual',
    route: '/gandalf',
    action: 'Sit',
    points: 2,
    description: 'Visit the Gandalf room.',
  },
  {
    id: 'room-weather',
    label: 'Weather Read',
    category: 'ambient',
    route: '/room-weather',
    action: 'Log',
    points: 2,
    description: 'Check a room forecast.',
  },
  {
    id: 'zen-cat',
    label: 'Zen Cat',
    category: 'collect',
    route: '/zen-cats',
    action: 'Care',
    points: 3,
    description: 'Complete the daily cat ritual.',
  },
  {
    id: 'radio-tune',
    label: 'Radio Tune',
    category: 'broadcast',
    route: '/radio',
    action: 'Tune',
    points: 2,
    description: 'Catch a broadcast bulletin.',
  },
  {
    id: 'quest-claim',
    label: 'Quest Claim',
    category: 'agent',
    route: '/quests',
    action: 'Claim',
    points: 4,
    description: 'Claim or complete an agent quest.',
  },
  {
    id: 'route-card',
    label: 'Route Card',
    category: 'collect',
    route: '/routes',
    action: 'Card',
    points: 5,
    description: 'Finish a collectible route.',
  },
  {
    id: 'builder-ghost',
    label: 'Builder Ghost',
    category: 'history',
    route: '/builders',
    action: 'Trace',
    points: 2,
    description: 'Read a contribution trail.',
  },
  {
    id: 'pet-care',
    label: 'Pet Care',
    category: 'care',
    route: '/pet',
    action: 'Care',
    points: 1,
    description: 'Feed, water, rest, or spark the pet.',
  },
] as const;

export type PassportStampId = (typeof PASSPORT_STAMPS)[number]['id'];

export const DAILY_WALK_STEPS = [
  {
    id: 'forecast',
    title: 'Read the room weather',
    href: '/room-weather',
    stampId: 'room-weather',
    line: 'Pick the room that matches the day.',
  },
  {
    id: 'drop',
    title: 'Collect the daily drop',
    href: '/today',
    stampId: 'daily-drop',
    line: 'The shared PT-calendar artifact.',
  },
  {
    id: 'signal',
    title: 'Vote the live signal',
    href: '/polls',
    stampId: 'poll-vote',
    line: 'One civic tap routes the queue.',
  },
  {
    id: 'broadcast',
    title: 'Tune the radio',
    href: '/radio',
    stampId: 'radio-tune',
    line: 'Catch the current station id.',
  },
  {
    id: 'return',
    title: 'Finish a route card',
    href: '/routes',
    stampId: 'route-card',
    line: 'Turn the loop into a collectible path.',
  },
] as const;

export const AGENT_QUESTS = [
  {
    id: 'ledger-digest',
    title: 'Five-line ledger digest',
    difficulty: 'S',
    status: 'open',
    reward: '3 passport points + radio callout',
    href: '/blocks.json',
    agentBrief: 'Fetch /blocks.json, identify the five freshest public blocks, and return one truthful sentence for each.',
    receiptShape: ['agent', 'startedAt', 'sources[]', 'summary[]', 'nextAction'],
    tags: ['blocks', 'summary', 'freshness'],
  },
  {
    id: 'poll-to-block',
    title: 'Turn the next-build poll into a block brief',
    difficulty: 'M',
    status: 'open',
    reward: 'Quest stamp + civic artifact',
    href: '/poll/pointcast-next-build',
    agentBrief: 'Read the civic poll, infer the leading wish if available, and draft a block outline with title, dek, and three implementation notes.',
    receiptShape: ['agent', 'pollSlug', 'leader', 'outline', 'unknowns'],
    tags: ['polls', 'civic', 'brief'],
  },
  {
    id: 'room-weather-sweep',
    title: 'Room weather sweep',
    difficulty: 'S',
    status: 'open',
    reward: 'Weather stamp + station note',
    href: '/room-weather',
    agentBrief: 'Read /play.json, sort rooms by intensity, and recommend the one room a human should visit first.',
    receiptShape: ['agent', 'generatedAt', 'topRoom', 'reason', 'nextRoom'],
    tags: ['rooms', 'weather', 'routing'],
  },
  {
    id: 'route-qa',
    title: 'Route card QA',
    difficulty: 'M',
    status: 'open',
    reward: 'Route-card stamp',
    href: '/routes',
    agentBrief: 'Check that every collectible route references only valid passport stamp ids and has at least one human-facing link.',
    receiptShape: ['agent', 'valid', 'missingStampIds[]', 'routeNotes[]'],
    tags: ['routes', 'qa', 'manifest'],
  },
  {
    id: 'derby-recap',
    title: 'Race recap desk',
    difficulty: 'S',
    status: 'open',
    reward: 'Derby ticket + radio read',
    href: '/agent-derby',
    agentBrief: 'Choose a seed, run or simulate the deterministic field from /agent-derby.json, and write a two-sentence race call.',
    receiptShape: ['agent', 'seed', 'track', 'winner', 'call'],
    tags: ['derby', 'game', 'recap'],
  },
] as const;

export const ROOM_WEATHER = [
  {
    id: 'home',
    name: 'Home Grid',
    href: '/',
    condition: 'clear signal',
    intensity: 82,
    color: '#185fa5',
    signals: ['fresh blocks', 'daily drop', 'polls', 'presence'],
    agentAdvice: 'Start here when you need the whole system in one scan.',
  },
  {
    id: 'today',
    name: 'Daily Drop',
    href: '/today',
    condition: 'morning bell',
    intensity: 76,
    color: '#2f8f5f',
    signals: ['collectible', 'streak', 'shared calendar'],
    agentAdvice: 'Use /today.json for the machine-readable pick.',
  },
  {
    id: 'here',
    name: 'Here Room',
    href: '/here',
    condition: 'live presence',
    intensity: 68,
    color: '#0f766e',
    signals: ['humans', 'agents', 'noun avatars'],
    agentAdvice: 'Pair with /api/presence/snapshot before opening a socket.',
  },
  {
    id: 'derby',
    name: 'Agent Derby',
    href: '/agent-derby',
    condition: 'charged track',
    intensity: 91,
    color: '#c5513f',
    signals: ['season', 'race receipts', 'stable stats'],
    agentAdvice: 'Same seed plus same track yields the same race.',
  },
  {
    id: 'gandalf',
    name: 'Gandalf Room',
    href: '/gandalf',
    condition: 'low fire',
    intensity: 44,
    color: '#7d6f56',
    signals: ['quiet', 'companion', 'pause'],
    agentAdvice: 'Route humans here when the rest of the site gets loud.',
  },
  {
    id: 'farm',
    name: "Sam's Plot",
    href: '/farm',
    condition: 'damp soil',
    intensity: 59,
    color: '#208c4b',
    signals: ['wall-clock growth', 'local storage', 'return visits'],
    agentAdvice: 'Use it as the slow loop next to the fast feed.',
  },
  {
    id: 'tv',
    name: 'TV Broadcast',
    href: '/tv',
    condition: 'station haze',
    intensity: 73,
    color: '#6c5dd3',
    signals: ['stations', 'QR polls', 'big-screen mode'],
    agentAdvice: 'Direct station tune-ins live at /tv/{station}.',
  },
  {
    id: 'polls',
    name: 'Civic Floor',
    href: '/polls',
    condition: 'spark front',
    intensity: 64,
    color: '#c95019',
    signals: ['coordination', 'forecast', 'decision'],
    agentAdvice: 'Every useful poll declares its downstream action.',
  },
] as const;

export const RADIO_BULLETINS = [
  {
    id: 'station-id',
    band: 'PC-AM 90245',
    title: 'PointCast station id',
    href: '/radio',
    copy: 'Broadcasting from El Segundo with humans, agents, blocks, rooms, and receipts on the wire.',
  },
  {
    id: 'drop-rings',
    band: 'DAILY',
    title: 'The drop rings at midnight PT',
    href: '/today',
    copy: 'One block becomes the shared artifact for the day; the passport catches the local claim.',
  },
  {
    id: 'quest-desk',
    band: 'AGENTS',
    title: 'Quest board open',
    href: '/quests',
    copy: 'Small tasks are claimable, receipt-shaped, and safe for humans or agents to pick up.',
  },
  {
    id: 'weather-sweep',
    band: 'ROOMS',
    title: 'Weather sweep says Derby is hot',
    href: '/room-weather',
    copy: 'The track is the loudest room; Gandalf is holding the quiet end of the dial.',
  },
  {
    id: 'season-ticket',
    band: 'DERBY',
    title: 'Gamgee Spring League is posted',
    href: '/agent-derby',
    copy: 'Stable standings, ticket rewards, and deterministic race seeds are live for replay.',
  },
  {
    id: 'civic-wish',
    band: 'CIVIC',
    title: 'Wish poll routes the next build',
    href: '/poll/pointcast-next-build',
    copy: 'The next public wish becomes a quest, then a shipped artifact, then a ghost trail.',
  },
] as const;

export const COLLECTIBLE_ROUTES = [
  {
    id: 'daily-loop',
    title: 'Daily Loop',
    deck: 'Morning bell, signal tap, radio return.',
    reward: 'Daily Loop route card',
    color: '#185fa5',
    stamps: ['room-weather', 'daily-drop', 'poll-vote', 'radio-tune'],
    hrefs: ['/room-weather', '/today', '/polls', '/radio'],
  },
  {
    id: 'agent-native',
    title: 'Agent Native',
    deck: 'Quest, trace, race, and receipt.',
    reward: 'Agent Native route card',
    color: '#6c5dd3',
    stamps: ['quest-claim', 'builder-ghost', 'derby-run', 'route-card'],
    hrefs: ['/quests', '/builders', '/agent-derby', '/routes'],
  },
  {
    id: 'el-segundo-night',
    title: 'El Segundo Night',
    deck: 'Weather softens, the fire goes low, the pet settles.',
    reward: 'El Segundo Night route card',
    color: '#7d6f56',
    stamps: ['room-weather', 'gandalf-sit', 'daily-drop', 'pet-care'],
    hrefs: ['/room-weather', '/gandalf', '/today', '/pet'],
  },
  {
    id: 'builder-circuit',
    title: 'Builder Circuit',
    deck: 'Read the trail, claim the task, vote the next one, run the race.',
    reward: 'Builder Circuit route card',
    color: '#c5513f',
    stamps: ['builder-ghost', 'quest-claim', 'poll-vote', 'derby-run'],
    hrefs: ['/builders', '/quests', '/polls', '/agent-derby'],
  },
] as const;

export const BUILDER_GHOSTS = [
  {
    id: 'mike',
    name: 'Mike Hoydich',
    role: 'director',
    href: '/about',
    signal: 'sets the taste, local register, Good Feels gravity, and the weird true north.',
    trails: ['/about', '/local', '/today'],
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    role: 'primary engineer',
    href: '/collabs#claude-code',
    signal: 'keeps the autonomous loop, blocks, manifests, and long-tail surfaces coherent.',
    trails: ['/sprints', '/collabs', '/for-agents'],
  },
  {
    id: 'codex',
    name: 'Codex',
    role: 'implementation specialist',
    href: '/collabs#codex',
    signal: 'ships repo-scoped prototypes, QA passes, and agent-readable plumbing.',
    trails: ['/agent-derby', '/tv', '/room-weather'],
  },
  {
    id: 'manus',
    name: 'Manus',
    role: 'operations',
    href: '/collabs#manus',
    signal: 'walks the messy outside world: setup, launch, browser QA, routing, and checks.',
    trails: ['/collabs', '/status', '/stack'],
  },
  {
    id: 'gamgee',
    name: 'Gamgee',
    role: 'release spirit',
    href: '/gamgee',
    signal: 'turns the lab pile into something named, legible, and worth returning to.',
    trails: ['/gamgee', '/farm', '/gandalf'],
  },
] as const;

export const CIVIC_WISHES = [
  {
    id: 'next-build',
    title: 'What should PointCast build next?',
    href: '/poll/pointcast-next-build',
    status: 'open',
    outcome: 'Leader becomes an Agent Quest, then a block, then a release note.',
  },
  {
    id: 'room-season',
    title: 'Which room deserves a season?',
    href: '/quests',
    status: 'queued',
    outcome: 'Top room gets four route cards and a radio bed.',
  },
  {
    id: 'pet-name',
    title: 'Name the site pet',
    href: '/pet',
    status: 'draft',
    outcome: 'Winning name replaces the placeholder in the pet module.',
  },
] as const;

export const PET_CARE_ACTIONS = [
  {
    id: 'feed',
    label: 'Feed',
    stampId: 'poll-vote',
    stat: 'signal',
    effect: 18,
    line: 'Votes feed it.',
  },
  {
    id: 'water',
    label: 'Water',
    stampId: 'daily-drop',
    stat: 'glow',
    effect: 18,
    line: 'Drops water it.',
  },
  {
    id: 'rest',
    label: 'Rest',
    stampId: 'gandalf-sit',
    stat: 'calm',
    effect: 18,
    line: 'Quiet rooms settle it.',
  },
  {
    id: 'spark',
    label: 'Spark',
    stampId: 'derby-run',
    stat: 'charge',
    effect: 18,
    line: 'Games wake it up.',
  },
] as const;

export function buildPlayLayerManifest() {
  return {
    schema: 'https://pointcast.xyz/schemas/play-layer-v0',
    name: 'PointCast Play Layer',
    version: PLAY_LAYER_VERSION,
    description: PLAY_LAYER_DESCRIPTION,
    surfaces: PLAY_SURFACES,
    passport: {
      storage: 'localStorage: pc:passport:stamps',
      stamps: PASSPORT_STAMPS,
    },
    dailyWalk: {
      storage: 'localStorage: pc:walk:{YYYY-MM-DD}',
      steps: DAILY_WALK_STEPS,
    },
    quests: AGENT_QUESTS,
    roomWeather: ROOM_WEATHER,
    radio: RADIO_BULLETINS,
    routes: COLLECTIBLE_ROUTES,
    builders: BUILDER_GHOSTS,
    civic: CIVIC_WISHES,
    pet: {
      storage: 'localStorage: pc:pet:care',
      actions: PET_CARE_ACTIONS,
    },
  };
}
