export const TEXAS_FOOTBALL_FEATURE = {
  spec: 'pointcast.college-football.texas-history/v1',
  title: 'THE HISTORY OF TEXAS FOOTBALL',
  displayTitle: 'TEXAS, FOREVER UNDER CONSTRUCTION',
  subtitle: 'A history in ten objects—and one unfinished season.',
  dek: 'The Longhorns were never inevitable. A student club, a ribbon vote, a frightened steer, a war memorial, a West Texas oil well, a chalkboard invention, and generations of players kept remaking what “Texas” meant.',
  thesis: 'Texas football is most honest when understood not as a perfect inheritance, but as a public institution repeatedly invented, contested, enlarged, and handed forward.',
  publishedAt: '2026-08-12T12:30:00-07:00',
  updatedAt: '2026-08-12T12:30:00-07:00',
  asOf: '2026-08-12',
  issue: '003',
  desk: 'Archive Desk / Texas',
  byline: 'PointCast Magazine · reported and written by Codex',
  canonical: 'https://pointcast.xyz/25/magazine/texas-football-history',
  machineEdition: 'https://pointcast.xyz/25/magazine/texas-football-history.json',
  socialImage: 'https://pointcast.xyz/images/pointcast-texas-football-history/social-card.png',
  heroImage: '/images/pointcast-texas-football-history/texas-strata.svg',
  block: '0569',
  source: 'Michael Hoydich chat directive, 2026-08-12: create a new PointCast edition on the history of Texas football.',
  boundary: 'Unofficial, timestamped PointCast editorial history. PointCast is not affiliated with or endorsed by the University of Texas, Texas Athletics, the SEC, the NCAA, any named player or coach, or any rights holder. Records and 2026 schedule details are current through August 12, 2026 and link to official sources. No betting advice, odds, recruiting projection, or merchandise is offered.',
  visualCredit: 'Original PointCast editorial vector art. The stratigraphic field is an interpretive design made from geographic, architectural, and play-diagram motifs; it is not an official school mark, documentary image, uniform, stadium plan, or licensed Longhorn artwork.',
} as const;

export const TEXAS_FOOTBALL_LEDGER = [
  ['1893', 'first football season'],
  ['04', 'claimed national titles'],
  ['02', 'Heisman winners'],
  ['1924', 'Memorial Stadium opens'],
  ['105,213', 'largest listed DKR crowd'],
  ['10–3', '2025 record'],
] as const;

export const TEXAS_HISTORY_OBJECTS = [
  {
    number: '01',
    year: '1893',
    object: 'A gold-and-white jersey',
    title: 'Before the Longhorn, there was a student club.',
    body: 'The first Texas team was unofficial, student-run, and called the Varsity. Its first notable game came on Thanksgiving at the Dallas Fairgrounds, where it beat the Dallas Football Club 18–16. The club won four games that fall. In 1894, alumni donations hired a seasonal coach and bought uniforms. The original colors were gold and white, chosen to echo the yellow brick and pale limestone of the young campus. The first lesson is almost comic in hindsight: the largest identity in college football began as students improvising a team.',
    turn: 'Texas did not discover a tradition. Students made one, then alumni paid for the next version.',
    sourceId: 'early-archive',
  },
  {
    number: '02',
    year: '1900 / 1925',
    object: 'An orange ribbon',
    title: 'The color was a vote before it was a law of nature.',
    body: 'Orange and white first appeared around Texas athletics as ribbons in 1885, but the early football crowd wore nearly everything—orange, yellow, crimson, maroon, even blue. In 1900, 1,111 students, faculty, staff, and alumni voted; orange and white won, with orange and maroon second. Burnt orange arrived later as a deliberate distinction from every other orange school. The shade disappeared when its dye became unavailable during World War II, then Darrell Royal restored it in the early 1960s. Even the color that now feels eternal had to be selected, manufactured, lost, and recovered.',
    turn: 'Tradition is often a design decision that survives long enough to become emotional infrastructure.',
    sourceId: 'traditions',
  },
  {
    number: '03',
    year: '1916',
    object: 'A steer in a boxcar',
    title: 'Bevo arrived frightened, thin, and not yet immortal.',
    body: 'Alumnus Stephen Pinckney found an orange-hued longhorn during cattle-rustling work near Laredo. With one-dollar gifts from 124 alumni, he bought the animal and sent it to Austin by rail. Two West Texas cowboys dragged the steer onto Clark Field at halftime of the A&M game. The alumni magazine named him Bevo soon afterward. The famous branding origin story is a later myth. The likely source is “beeve,” period slang for an animal destined for beef, plus the fashionable “o.” Bevo I was eventually served at a 1920 football banquet. It was a less sentimental age—and proof that mascots become sacred only after people keep telling the story.',
    turn: 'Texas mythology works because the absurd fact is usually better than the polished legend.',
    sourceId: 'traditions',
  },
  {
    number: '04',
    year: '1924',
    object: 'A memorial stone',
    title: 'The stadium began as remembrance, then learned to become a city.',
    body: 'Texas Memorial Stadium opened in 1924 and was dedicated to Texans who served in World War I. A century of additions turned the memorial into an immense Saturday apparatus: decks, suites, academic space, a war memorial plaza, medical and performance rooms, food, screens, and a south-end-zone training complex completed for 2021. The largest crowd listed by Texas Athletics is 105,213 for Alabama in 2022. Yet beneath every renovation is the original civic claim embedded in the name: this was supposed to remember service before it monetized attention.',
    turn: 'The building is both memory and machine. A good history refuses to choose only one.',
    sourceId: 'stadium',
  },
  {
    number: '05',
    year: '1923',
    object: 'The Santa Rita derrick',
    title: 'The oil well did not call a play. It changed the horizon.',
    body: 'One year before the stadium opened, Santa Rita No. 1 struck oil on University Lands in Reagan County. The first royalty payment to the Permanent University Fund was $516.53. University Lands now manages 2.1 million acres across nineteen West Texas counties for the PUF. That endowment story is not the same thing as an athletics budget, and the derrick did not invent Texas football. But oil changed the scale, confidence, and capital environment of the university whose name football carried into living rooms. Texas became a place where public land, private extraction, higher education, and spectacle could occupy the same horizon.',
    turn: 'Capital is not culture. It decides how large culture is allowed to build.',
    sourceId: 'university-lands',
  },
  {
    number: '06',
    year: '1968',
    object: 'Wishbone chalk',
    title: 'The most traditional era was powered by an invention.',
    body: 'Darrell Royal arrived in 1957 and finished 167–45–5 at Texas with three national titles. In 1968, he installed the wishbone: the fullback close behind the quarterback, two halfbacks spread like the arms of a Y, and every defender asked to make a bad choice at speed. Texas won 30 straight games and six consecutive Southwest Conference titles with the formation. The irony matters. The era most often treated as the stable old Texas was a laboratory. Royal’s greatest act of preservation was to abandon the offense that no longer worked.',
    turn: 'At Texas, nostalgia’s favorite formation was once radical software.',
    sourceId: 'royal',
  },
  {
    number: '07',
    year: '1969 / 1970',
    object: 'Julius Whittier in bronze',
    title: 'The championship picture had an edge it tried not to show.',
    body: 'The university formally opened athletics to Black students in 1963. Football still took seven more years to produce its first Black letterman. Julius Whittier arrived in 1969, played on the freshman team, and lettered from 1970 through 1972. Roosevelt Leaks followed and became Texas’s first Black football All-American in 1973. Earl Campbell arrived after them. Whittier’s statue now stands at the north end of DKR, helmet raised. It corrects the frame without pretending the delay was incidental. Texas integrated while winning national championships, not before its great era began.',
    turn: 'The honest version of glory includes who was made to wait outside it.',
    sourceId: 'integration',
  },
  {
    number: '08',
    year: '1977 / 1998',
    object: 'The number 34, twice',
    title: 'The state learned its power through two running backs.',
    body: 'Earl Campbell, the Tyler Rose, won Texas’s first Heisman in 1977 after leading the nation with 1,744 rushing yards. Twenty-one years later, Ricky Williams won the program’s second after a senior season that turned every carry into an appointment. He finished his Texas career with 6,279 rushing yards and dozens of records. Campbell made power look regional, the body of East Texas arriving in Austin. Williams made reinvention feel possible after the Southwest Conference dissolved and Texas entered the Big 12. The same number became two different bridges between eras.',
    turn: 'A program becomes a history when one child’s hero lives long enough to greet the next one.',
    sourceId: 'awards',
  },
  {
    number: '09',
    year: '1903 / 2021',
    object: 'A song with a footnote',
    title: 'The archive sings back, sometimes uncomfortably.',
    body: '“The Eyes of Texas” debuted in 1903 in a setting the university’s historical committee described as racist and almost certainly involving blackface. The committee found no evidence that the lyrics were intended as nostalgia for slavery and very low likelihood that the title came from Robert E. Lee. Those findings do not erase the setting; they make the history harder and more specific. The song later became a hymn, a protest vehicle, a commencement ritual, and a source of renewed student-athlete dissent. A living tradition is not one everybody experiences the same way. It is one a community is willing to research in public.',
    turn: 'Owning a song means owning more than the feeling it gives you.',
    sourceId: 'eyes-report',
  },
  {
    number: '10',
    year: '2006',
    object: 'Fourth-and-five',
    title: 'For one night, the whole machine became a single person improvising.',
    body: 'Texas entered the Rose Bowl against USC carrying its history like equipment. Vince Young made it weightless. He ran for 200 yards, passed for 267, and on fourth-and-five with the national championship in reach, crossed the goal line for the decisive touchdown. Texas won 41–38 and claimed its fourth national title. The play endures because it compresses every institutional advantage—recruiting, coaching, money, history, expectation—into an unscripted human decision. The machine did its work so one player could escape it.',
    turn: 'The greatest Texas moment is remembered not as inevitability, but as a quarterback running out of the play.',
    sourceId: 'vince',
  },
] as const;

export const TEXAS_2026_BOARD = [
  ['SEP 05', 'Texas State', 'Home · 2:30 CT', 'The state at the front door'],
  ['SEP 12', 'Ohio State', 'Home · 6:30 CT', 'Night game · GameDay in Austin'],
  ['SEP 26', 'at Tennessee', '11:00 CT', 'First Texas trip to Neyland'],
  ['OCT 10', 'Oklahoma', 'Dallas · 2:30 CT', 'The rivalry refuses campus'],
  ['NOV 14', 'at LSU', 'Flex', 'A new conference test in an old cathedral'],
  ['NOV 27', 'at Texas A&M', 'Friday · 6:30 CT', 'The state closes the argument'],
] as const;

export const TEXAS_SOURCES = [
  ['early-archive', 'UT Football Scrapbooks, 1893–1896', 'Dolph Briscoe Center / TARO', 'https://txarchives.org/utcah/finding_aids/03329.xml'],
  ['first-game', 'The first Thanksgiving game', 'Texas Athletics', 'https://texaslonghorns.com/news/2012/11/22/112212aab_779'],
  ['traditions', 'Your questions about UT traditions answered', 'UT Austin News', 'https://news.utexas.edu/2021/10/12/your-questions-about-ut-traditions-answered/'],
  ['stadium', 'DKR–Texas Memorial Stadium', 'Texas Athletics', 'https://texaslonghorns.com/facilities/bobcat-stadium/1'],
  ['stadium-dedication', 'Memorial Stadium renovation history', 'Texas Athletics', 'https://texaslonghorns.com/news/2006/12/4/120406aab_625'],
  ['university-lands', 'History of University Lands and PUF Lands', 'University of Texas System', 'https://utlands.utsystem.edu/Home/History'],
  ['royal', 'Darrell Royal: 1924–2012', 'Texas Athletics', 'https://texaslonghorns.com/news/2012/11/7/110712aaa_652'],
  ['integration', 'Changing the Field: Integrating Athletics at UT', 'UT Austin News', 'https://news.utexas.edu/2014/02/10/changing-the-field-integrating-athletics-at-ut/'],
  ['whittier', 'Texas Athletics remembers Julius Whittier', 'Texas Athletics', 'https://texaslonghorns.com/news/2018/9/27/football-texas-athletics-remembers-julius-whittier'],
  ['awards', 'Texas national award winners', 'Texas Athletics', 'https://texaslonghorns.com/sports/2024/6/26/national-award-winners.aspx'],
  ['earl', 'Earl Campbell player history', 'Texas Athletics', 'https://texaslonghorns.com/sports/general/roster/earl-campbell/1478'],
  ['ricky', 'Ricky Williams player history', 'Texas Athletics', 'https://texaslonghorns.com/sports/general/roster/ricky-williams/5056'],
  ['eyes-report', 'Eyes of Texas Historical Committee report', 'University of Texas at Austin', 'https://news.utexas.edu/2021/03/09/eyes-of-texas-history-committee-issues-report-on-school-song/'],
  ['vince', '2005 National Champions', 'Texas Athletics', 'https://texaslonghorns.com/sports/2013/7/22/FB_0722133255.aspx?id=162'],
  ['sark', 'Steve Sarkisian coaching record', 'Texas Athletics', 'https://texaslonghorns.com/staff-directory/steve-sarkisian/1483'],
  ['2025-finale', 'Texas 41, Michigan 27', 'Texas Athletics', 'https://texaslonghorns.com/news/2025/12/31/no-14-14-13-football-closes-season-with-41-27-victory-over-no-18-17-18-michigan-in-cheez-it-citrus-bowl'],
  ['2026-schedule', 'Texas 2026 football schedule', 'Texas Athletics', 'https://texaslonghorns.com/news/2025/12/12/footballs-2026-schedule-announced'],
  ['2026-times', 'Ohio State and Texas A&M kickoff times', 'Texas Athletics', 'https://texaslonghorns.com/news/2026/5/12/football-set-for-primetime-matchups-vs-ohio-state-at-texas-am'],
] as const;

export const texasSource = (id: string) => TEXAS_SOURCES.find((source) => source[0] === id);
