export interface PointcastApp {
  slug: string;
  name: string;
  kicker: string;
  description: string;
  url: string;
  path: string;
  repo: string;
  channel: string;
  kind: 'satellite' | 'pointcast';
}

export const POINTCAST_APPS: PointcastApp[] = [
  {
    slug: 'pointcast-native-shell',
    name: 'PointCast Native Shell',
    kicker: 'PWA · NOW · ROOMS',
    description: 'The installable PointCast home screen: Now, Rooms, Drum, Profile, Collect, and Agents in one mobile-first app shell.',
    url: 'https://pointcast.xyz/app',
    path: '/app',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.FD',
    kind: 'pointcast',
  },
  {
    slug: 'chart-of-the-day',
    name: 'Chart of the Day',
    kicker: 'DAILY DATA · LEDGER PULSE',
    description: 'A daily-rotating PointCast chart built from the block ledger, with a human view at /chart and a machine-readable packet at /chart.json.',
    url: 'https://pointcast.xyz/chart',
    path: '/chart',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.FD',
    kind: 'pointcast',
  },
  {
    slug: 'pointcast-chartmaker',
    name: 'PointCast Chartmaker',
    kicker: 'FEEDS · CROSS-CHARTS · TIMELINES',
    description: 'A chart lab for combining PointCast-native data with weather, market, sports, feed, and browser-local sources.',
    url: 'https://pointcast.xyz/chartmaker',
    path: '/chartmaker',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DATA',
    kind: 'pointcast',
  },
  {
    slug: 'moodygold',
    name: 'MoodyGold',
    kicker: 'ARTWORK · SOUND · GALLERY',
    description: 'A MoodyGold gallery and visualizer surface, hosted as its own app and viewable from PointCast.',
    url: 'https://moodygold.pages.dev',
    path: '/moodygold',
    repo: 'https://github.com/mhoydich/abstract-soundscapes',
    channel: 'CH.SPN',
    kind: 'satellite',
  },
  {
    slug: 'offbalance',
    name: 'Offbalance',
    kicker: 'GOOD FEELS · EL SEGUNDO',
    description: 'The Good Feels El Segundo deck: cannabis as inquiry, flow-state pairings, and product-world thinking.',
    url: 'https://offbalance-6hl.pages.dev',
    path: '/offbalance',
    repo: 'https://github.com/mhoydich/offbalance',
    channel: 'CH.GF',
    kind: 'satellite',
  },
  {
    slug: 'cannabis',
    name: 'Cannabis Atlas',
    kicker: 'CHEMOVARS · EFFECTS WHEEL',
    description: 'A Southern California cannabis resource for strain names, chemovar signals, terpenes, and pairings.',
    url: 'https://pointcast.xyz/cannabis',
    path: '/cannabis',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.GF',
    kind: 'pointcast',
  },
  {
    slug: 'mint-studio',
    name: 'Mint Studio',
    kicker: 'ART BRIEF · METADATA · RECEIPTS',
    description: 'A local mint-planning desk for turning art ideas into clean collectible briefs, metadata notes, and Tezos-ready receipts.',
    url: 'https://pointcast.xyz/mint-studio',
    path: '/mint-studio',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.MINT',
    kind: 'pointcast',
  },
  {
    slug: 'cabinet',
    name: 'The Cabinet',
    kicker: 'LOCAL SHELF · COLLECTIBLES · RECEIPTS',
    description: 'A personal PointCast shelf that gathers local cats, ocean cards, mint receipts, passport stamps, invites, and readiness checkpoints.',
    url: 'https://pointcast.xyz/cabinet',
    path: '/cabinet',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SHELF',
    kind: 'pointcast',
  },
  {
    slug: 'observatory',
    name: 'The Observatory',
    kicker: 'CONSTELLATIONS · LOCAL STATE · COLLECTION MAP',
    description: 'A night-sky view of PointCast collectibles that turns local receipts, cats, ocean cards, invites, and checkpoints into a constellation.',
    url: 'https://pointcast.xyz/observatory',
    path: '/observatory',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SKY',
    kind: 'pointcast',
  },
  {
    slug: 'signal-garden',
    name: 'Signal Garden',
    kicker: 'LOCAL ACTIVITY · AMBIENT GROWTH',
    description: 'A lightweight local garden that turns PointCast receipts, rituals, stamps, proofs, and saved plants into an ambient growth map.',
    url: 'https://pointcast.xyz/signal-garden',
    path: '/signal-garden',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SIGNAL',
    kind: 'pointcast',
  },
  {
    slug: 'listening-rooms',
    name: 'Listening Rooms',
    kicker: 'MUSIC · LOCAL RECEIPTS · ROOM SERIES',
    description: 'A collectible series hub for PointCast music-linked rooms, starting with Stay Still Drum v2 and its local sitting receipts.',
    url: 'https://pointcast.xyz/listening-rooms',
    path: '/listening-rooms',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SPN',
    kind: 'pointcast',
  },
  {
    slug: 'sit-v2',
    name: 'Stay Still Drum v2',
    kicker: 'DRUM · STILLNESS · ROOM 001',
    description: 'A local-only stillness and drum room with generated background art, browser receipts, and quiet rhythm patterns.',
    url: 'https://pointcast.xyz/sit-v2',
    path: '/sit-v2',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SPN',
    kind: 'pointcast',
  },
  {
    slug: 'gallery-wall',
    name: 'Gallery Wall',
    kicker: 'CURATION · SHOW CARDS · LOCAL WALLS',
    description: 'A curator room for arranging cats, ocean cards, routes, and receipts into small collectible exhibitions saved locally.',
    url: 'https://pointcast.xyz/gallery-wall',
    path: '/gallery-wall',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.CURATE',
    kind: 'pointcast',
  },
  {
    slug: 'ritual-clock',
    name: 'Ritual Clock',
    kicker: 'DAILY CADENCE · COLLECTOR RHYTHM',
    description: 'A daily rhythm board for marking cat, harbor, studio, and night-sky collector rituals without accounts or sync.',
    url: 'https://pointcast.xyz/ritual-clock',
    path: '/ritual-clock',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.TIME',
    kind: 'pointcast',
  },
  {
    slug: 'exchange-table',
    name: 'Exchange Table',
    kicker: 'WISHLIST · OFFERS · DISCLOSURE',
    description: 'A private collector table for noting wants, offers, and watch signals before anything becomes a marketplace action.',
    url: 'https://pointcast.xyz/exchange-table',
    path: '/exchange-table',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SWAP',
    kind: 'pointcast',
  },
  {
    slug: 'provenance-ledger',
    name: 'Provenance Ledger',
    kicker: 'LOCAL PROOFS · EXPORT SHEETS',
    description: 'A local proof desk that gathers PointCast app receipts into normalized provenance sheets and checksum-style export cards.',
    url: 'https://pointcast.xyz/provenance-ledger',
    path: '/provenance-ledger',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.PROOF',
    kind: 'pointcast',
  },
  {
    slug: 'world-atlas',
    name: 'World Atlas',
    kicker: 'ZEN CAT ROUTES · LANDMARKS · GEMS',
    description: 'A map room for the luxury Zen Cat world series, with landmark stops, gemstone cues, and local route stamps.',
    url: 'https://pointcast.xyz/world-atlas',
    path: '/world-atlas',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.WORLD',
    kind: 'pointcast',
  },
  {
    slug: 'harbor-log',
    name: 'Harbor Log',
    kicker: 'MORNING OCEAN · WATCHLIST',
    description: 'A small collector console for drawing Morning Ocean vessels, keeping a local watchlist, and opening mintable maritime cards.',
    url: 'https://pointcast.xyz/harbor-log',
    path: '/harbor-log',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.OCEAN',
    kind: 'pointcast',
  },
  {
    slug: 'cat-passport',
    name: 'Cat Passport',
    kicker: 'ZEN CATS · GEMS · LANDMARKS',
    description: 'A passport-stamp app for Zen Cat world collectibles, with gemstones, landmarks, and local travel receipts.',
    url: 'https://pointcast.xyz/cat-passport',
    path: '/cat-passport',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.CAT',
    kind: 'pointcast',
  },
  {
    slug: 'referral-garden',
    name: 'Referral Garden',
    kicker: 'INVITES · DISCLOSURE · TRUST',
    description: 'A disclosure-first referral garden for one-level invites, local milestones, and contribution-based collector growth.',
    url: 'https://pointcast.xyz/referral-garden',
    path: '/referral-garden',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.GROW',
    kind: 'pointcast',
  },
  {
    slug: 'sats-path',
    name: 'Sats Path',
    kicker: 'CAPITAL JOURNEY · BITCOIN READINESS',
    description: 'An educational, non-custodial pathway from creative receipts to calm capital habits and Bitcoin readiness checkpoints.',
    url: 'https://pointcast.xyz/sats-path',
    path: '/sats-path',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SATS',
    kind: 'pointcast',
  },
];

export function getPointcastApp(slug: string) {
  return POINTCAST_APPS.find((app) => app.slug === slug);
}
