export type PointCast25Signal =
  | 'title-weather'
  | 'playoff-weather'
  | 'fault-line'
  | 'outsider';

export type PointCast25Movement = 'NEW' | 'UP' | 'DOWN' | 'HOLD';

export interface PointCast25Team {
  rank: number;
  /** Rank on the previous board; null when the team is NEW. */
  previousRank: number | null;
  movement: PointCast25Movement;
  school: string;
  short: string;
  conference: string;
  signal: PointCast25Signal;
  accent: string;
  reason: string;
  case: string;
  doubt: string;
  proof: string;
  /** Result since the previous board, or null when the team has not played. */
  result: string | null;
  /** The change receipt: what happened, why the number did or did not move. */
  change: string;
  sources: readonly string[];
}

export const POINTCAST_25 = {
  spec: 'pointcast.25-for-reasons/v1',
  season: 2026,
  board: '001',
  previousBoard: '000',
  status: 'week-1',
  title: '25 FOR REASONS',
  subtitle: 'A college-football poll with receipts. One game in; the numbers hold.',
  question: 'Only one team on this board has played; which of the other 24 cases survives Labor Day weekend intact?',
  publishedAt: '2026-09-01T17:00:00-07:00',
  nextBoardAt: '2026-09-08T08:08:00-07:00',
  block: '0582',
  cadence: {
    sunday: 'Proof, complication, or death markers on every live claim.',
    tuesday: 'The new 25, full reasons, movement ledger, and one published dissent.',
    thursday: 'Three games capable of changing the board.',
    saturday: 'A quiet watch order built for one good window, not an endless feed.',
  },
  methodology: [
    {
      label: 'Strength',
      note: 'Who we would trust on a neutral field next Saturday.',
    },
    {
      label: 'Continuity',
      note: 'Quarterback, line, coordinator, and returning-production evidence.',
    },
    {
      label: 'Path',
      note: 'Schedule leverage and the real route into the 12-team playoff.',
    },
    {
      label: 'Accountability',
      note: 'Every case, doubt, and proof stays attached to the team all season.',
    },
  ],
  editorsNote:
    'This board was assembled from public box scores and official schedules with a source attached to every line; only USC had played by press time, so the other 24 teams carry the preseason case forward unchanged. Movement is deliberately conservative: a number moves only when a game shows something the case or doubt already named, and an expected win holds. Mike reads and signs off before anything is published, and Board 002 lands Tuesday, Sept. 8 at 8:08 PT with the Labor Day weekend results. — cc',
  sale: {
    name: 'PointCast 25 / 2026 Founding Season Ticket',
    priceUsd: 25,
    recurring: false,
    checkout: 'https://pointcast.xyz/api/25/checkout',
    checkoutMode: 'hosted-external',
    pointCastCardCapture: false,
    promise:
      'Back the complete 2026 editorial season. The ranking and its receipts remain public; the ticket funds the weekly research, the Tuesday boards, and the permanent season ledger.',
  },
  sources: [
    {
      label: 'Week 1 2026 scoreboard',
      publisher: 'ESPN',
      url: 'https://www.espn.com/college-football/scoreboard/_/week/1/year/2026/seasontype/2',
      checkedAt: '2026-09-01',
    },
    {
      label: 'USC 42, San José State 26 — AP recap',
      publisher: 'USC Athletics',
      url: 'https://usctrojans.com/news/2026/8/29/usc-trojans-football-game-recap-associated-press-ap-san-jose-state-spartants-jayden-maiava-trent-mosley-luke-wafle',
      checkedAt: '2026-09-01',
    },
    {
      label: 'Clemson at LSU game page and line',
      publisher: 'ESPN',
      url: 'https://www.espn.com/college-football/game/_/gameId/401856660/clemson-lsu',
      checkedAt: '2026-09-01',
    },
    {
      label: '2026 College Football Playoff format',
      publisher: 'College Football Playoff',
      url: 'https://collegefootballplayoff.com/news/2026/1/23/2627-format.aspx',
      checkedAt: '2026-07-27',
    },
    {
      label: '2026 preseason FPI board (Board 000 reference)',
      publisher: 'ESPN / Sports Illustrated',
      url: 'https://www.si.com/fannation/college/cfb-hq/rankings/college-football-rankings-espn-top-25-preseason-poll-2026',
      checkedAt: '2026-07-27',
    },
  ],
  teams: [
    {
      rank: 1,
      previousRank: 1,
      movement: 'HOLD',
      school: 'Ohio State',
      short: 'OSU',
      conference: 'Big Ten',
      signal: 'title-weather',
      accent: '#ba0c2f',
      reason: 'The highest quarterback–receiver ceiling in the sport, carrying the season’s nastiest road schedule.',
      case: 'Julian Sayin and Jeremiah Smith make every snap expandable; the roster still has national-title depth.',
      doubt: 'The defense has real holes, and road trips to Texas, Indiana, Iowa, Nebraska, and USC leave no soft month.',
      proof: 'Win an early road game without asking the passing game to be perfect.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Ball State at Ohio Stadium on Saturday, Sept. 5, with the trip to Texas one week later.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/194',
        'https://www.espn.com/college-football/scoreboard/_/week/1/year/2026/seasontype/2',
      ],
    },
    {
      rank: 2,
      previousRank: 2,
      movement: 'HOLD',
      school: 'Notre Dame',
      short: 'ND',
      conference: 'Independent',
      signal: 'title-weather',
      accent: '#c99700',
      reason: 'Unusual defensive continuity and fewer imaginary preseason dependencies than anyone else.',
      case: 'CJ Carr leads a talented offense while nine of the ten leading tacklers return.',
      doubt: 'The two-back engine is gone, and the playoff path now begins with championship expectations.',
      proof: 'Show that the new run game can finish drives instead of merely protecting the defense.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens Sunday, Sept. 6 against Wisconsin at Lambeau Field, the neutral-site game that gives the first look at the new run game.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/87',
        'https://www.espn.com/college-football/scoreboard/_/week/1/year/2026/seasontype/2',
      ],
    },
    {
      rank: 3,
      previousRank: 3,
      movement: 'HOLD',
      school: 'Texas',
      short: 'TEX',
      conference: 'SEC',
      signal: 'title-weather',
      accent: '#bf5700',
      reason: 'The Arch Manning window is now; the unresolved run game keeps this from being No. 1.',
      case: 'Manning finished 2025 as an efficient, dangerous passer with another elite skill group around him.',
      doubt: 'A contender this expensive cannot keep treating ordinary rushing success as an optional feature.',
      proof: 'Control one serious opponent on the ground when the box knows what is coming.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Texas State in Austin on Saturday, Sept. 5; Ohio State comes to DKR on Sept. 12.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/251',
        'https://www.espn.com/college-football/scoreboard/_/week/1/year/2026/seasontype/2',
      ],
    },
    {
      rank: 4,
      previousRank: 4,
      movement: 'HOLD',
      school: 'Oregon',
      short: 'ORE',
      conference: 'Big Ten',
      signal: 'title-weather',
      accent: '#148e3d',
      reason: 'Dante Moore, deep talent, championship capacity—and two new coordinators to assimilate.',
      case: 'The quarterback and blue-chip skill core survived another playoff run.',
      doubt: 'Coordinator turnover can turn a complete roster into a September installation project.',
      proof: 'Look like the same adult operation before the conference schedule becomes cruel.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Boise State at Autzen Stadium on Saturday, Sept. 5, the first live look at both new coordinators.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/2483',
        'https://www.espn.com/college-football/scoreboard/_/week/1/year/2026/seasontype/2',
      ],
    },
    {
      rank: 5,
      previousRank: 5,
      movement: 'HOLD',
      school: 'Georgia',
      short: 'UGA',
      conference: 'SEC',
      signal: 'title-weather',
      accent: '#ba0c2f',
      reason: 'Back-to-back SEC champions receive institutional trust until the rebuilt secondary spends it.',
      case: 'Gunner Stockton, Nate Frazier, and the sport’s most reliable contender infrastructure return.',
      doubt: 'New defensive backs meet road tests at Alabama and Ole Miss before they can hide.',
      proof: 'Survive one explosive passing offense without retreating into conservative coverage.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Tennessee State in Athens on Saturday, Sept. 5, which will not test the rebuilt secondary.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/61',
        'https://www.espn.com/college-football/scoreboard/_/week/1/year/2026/seasontype/2',
      ],
    },
    {
      rank: 6,
      previousRank: 6,
      movement: 'HOLD',
      school: 'Indiana',
      short: 'IND',
      conference: 'Big Ten',
      signal: 'title-weather',
      accent: '#990000',
      reason: 'The undefeated champion deserves deference; repeating after turnover would change the sport permanently.',
      case: 'Curt Cignetti just produced a 16–0 champion and added a 31-game starting quarterback in Josh Hoover.',
      doubt: 'The exact continuity that made Indiana feel older than everybody else has been broken up.',
      proof: 'Run the same calm, grown-up offense with different people in the most important chairs.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against North Texas in Bloomington at noon ET on Saturday, Sept. 5, Josh Hoover’s first game in the champion’s chair.',
      sources: [
        'https://en.wikipedia.org/wiki/2026_Indiana_Hoosiers_football_team',
        'https://www.espn.com/college-football/team/schedule/_/id/84/indiana-hoosiers',
      ],
    },
    {
      rank: 7,
      previousRank: 7,
      movement: 'HOLD',
      school: 'Miami',
      short: 'MIA',
      conference: 'ACC',
      signal: 'title-weather',
      accent: '#f47321',
      reason: 'A national finalist plus Darian Mensah creates an immediate return path; the defensive reconstruction is real.',
      case: 'Mensah joins Mark Fletcher and Malachi Toney in an offense with title-game memory.',
      doubt: 'The defensive front seven lost too many answers to assume another January run.',
      proof: 'Create pressure without selling out the secondary.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens Friday night, Sept. 4 at Stanford, a road game and the first look at the rebuilt front seven.',
      sources: [
        'https://miamihurricanes.com/sports/football/schedule',
        'https://en.wikipedia.org/wiki/2026_Miami_Hurricanes_football_team',
      ],
    },
    {
      rank: 8,
      previousRank: 8,
      movement: 'HOLD',
      school: 'LSU',
      short: 'LSU',
      conference: 'SEC',
      signal: 'playoff-weather',
      accent: '#461d7c',
      reason: 'Lane Kiffin, Sam Leavitt, and the leading transfer class: enormous ceiling, delicious combustion potential.',
      case: 'The new quarterback and receiver room can become the country’s fastest offensive installation.',
      doubt: 'A roster assembled at speed still has to become a team while the SEC watches.',
      proof: 'Win a game that requires patience rather than a track meet.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Clemson in Tiger Stadium on Saturday, Sept. 5 with College GameDay on site, the one Week 1 game that can move two numbers on this board at once.',
      sources: [
        'https://lsusports.net/sports/fb/schedule',
        'https://en.wikipedia.org/wiki/2026_LSU_Tigers_football_team',
        'https://www.espn.com/college-football/game/_/gameId/401856660/clemson-lsu',
      ],
    },
    {
      rank: 9,
      previousRank: 9,
      movement: 'HOLD',
      school: 'Texas Tech',
      short: 'TTU',
      conference: 'Big 12',
      signal: 'playoff-weather',
      accent: '#cc0000',
      reason: 'The Big 12 champion has a serious floor; quarterback health determines whether the ceiling survives.',
      case: 'The run game and recent championship evidence make the Red Raiders the league’s adult.',
      doubt: 'Will Hammond returns from an ACL injury while the defense replaces its loudest playmakers.',
      proof: 'Let Hammond be efficient without turning every drive into a medical suspense film.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against FCS Abilene Christian in Lubbock on Saturday, Sept. 5, which should show whether Hammond is healthy without showing much else.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/2641/texas-tech-red-raiders',
        'https://en.wikipedia.org/wiki/2026_Texas_Tech_Red_Raiders_football_team',
      ],
    },
    {
      rank: 10,
      previousRank: 10,
      movement: 'HOLD',
      school: 'USC',
      short: 'USC',
      conference: 'Big Ten',
      signal: 'playoff-weather',
      accent: '#990000',
      reason: 'Five returning blockers, a huge recruiting class, and Gary Patterson. The excuse inventory is empty.',
      case: 'Jayden Maiava finally gets continuity in front of him while the defense gains an adult architect.',
      doubt: 'USC has been winning the offseason longer than it has been winning important November games.',
      proof: 'Tackle well and close a one-score conference game without theater.',
      result: 'W 42-26 vs. San José State, Aug. 29',
      change: 'Beat San José State 42-26 at the Coliseum on Aug. 29: Maiava went 25 of 29 for 286 yards with two passing touchdowns and a rushing score, freshman Trent Mosley caught seven passes for 118 yards, and the lead was 28-0 at halftime. Holds at 10 because a comfortable win over a Mountain West opponent is the expected result; the three fourth-quarter touchdowns came against reserves, so the tackling question in the proof line stays open.',
      sources: [
        'https://usctrojans.com/news/2026/8/29/usc-trojans-football-game-recap-associated-press-ap-san-jose-state-spartants-jayden-maiava-trent-mosley-luke-wafle',
        'https://dailytrojan.com/2026/08/29/no-14-usc-football-handles-san-jose-state-for-42-26-season-opening-win/',
        'https://sports.yahoo.com/articles/trojans-kick-off-2026-campaign-003700465.html',
        'https://www.espn.com/college-football/team/schedule/_/id/30/usc-trojans',
      ],
    },
    {
      rank: 11,
      previousRank: 11,
      movement: 'HOLD',
      school: 'Alabama',
      short: 'ALA',
      conference: 'SEC',
      signal: 'playoff-weather',
      accent: '#9e1b32',
      reason: 'This is no longer a brand ranking. It is a referendum on whether Alabama can become physically frightening again.',
      case: 'Kalen DeBoer has won 20 games in two seasons and still recruits like Alabama.',
      doubt: 'The quarterback changes, the 2025 run game ranked near the bottom of FBS, and Indiana exposed the distance.',
      proof: 'Move a good defensive front when everybody in the stadium expects run.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against East Carolina at Bryant-Denny Stadium at noon on Saturday, Sept. 5.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/333/alabama-crimson-tide',
        'https://en.wikipedia.org/wiki/2026_Alabama_Crimson_Tide_football_team',
      ],
    },
    {
      rank: 12,
      previousRank: 12,
      movement: 'HOLD',
      school: 'Penn State',
      short: 'PSU',
      conference: 'Big Ten',
      signal: 'playoff-weather',
      accent: '#041e42',
      reason: 'Matt Campbell and 39 transfers: either an intelligently assembled machine or a very expensive group project.',
      case: 'Rocco Becht brings 26 starts, Carson Hansen brings production, and Campbell knows how to organize scarcity.',
      doubt: 'The number 39 is also a warning about shared language, role clarity, and September chemistry.',
      proof: 'Look connected on third down before talent can cover the seams.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Marshall at Beaver Stadium on Saturday, Sept. 5, Matt Campbell’s first game as Penn State head coach.',
      sources: [
        'https://gopsusports.com/sports/football/schedule',
        'https://www.espn.com/college-football/team/schedule/_/id/213/penn-state-nittany-lions',
        'https://www.cbssports.com/betting/news/college-football-score-predictions-lines-spreads-for-week-1-2026/',
      ],
    },
    {
      rank: 13,
      previousRank: 13,
      movement: 'HOLD',
      school: 'Texas A&M',
      short: 'A&M',
      conference: 'SEC',
      signal: 'playoff-weather',
      accent: '#500000',
      reason: 'Eleven straight wins proved the shape; the ending proved the fragility.',
      case: 'Marcel Reed returns to an offense that already knows it can sustain a serious run.',
      doubt: 'Both lines lost answers, the schedule stiffens, and Reed still owes the ball better care.',
      proof: 'Finish a close game after the first plan stops working.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Missouri State at Kyle Field on Saturday, Sept. 5.',
      sources: [
        'https://12thman.com/sports/football/schedule',
        'https://www.espn.com/college-football/team/schedule/_/id/245',
      ],
    },
    {
      rank: 14,
      previousRank: 14,
      movement: 'HOLD',
      school: 'Oklahoma',
      short: 'OU',
      conference: 'SEC',
      signal: 'playoff-weather',
      accent: '#841617',
      reason: 'A championship defense being asked to carry an offense that must finally become ordinary-good.',
      case: 'Brent Venables can build a suffocating defense with replacement parts.',
      doubt: 'John Mateer, the line, and the run game all need improvement at the same time.',
      proof: 'Create four reliable yards without requiring quarterback improvisation.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against UTEP in Norman on Friday, Sept. 4; the trip to Michigan follows on Sept. 12.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/201/oklahoma-sooners',
        'https://en.wikipedia.org/wiki/2026_Oklahoma_Sooners_football_team',
      ],
    },
    {
      rank: 15,
      previousRank: 15,
      movement: 'HOLD',
      school: 'Michigan',
      short: 'MICH',
      conference: 'Big Ten',
      signal: 'playoff-weather',
      accent: '#00274c',
      reason: 'Kyle Whittingham plus Bryce Underwood is the season’s strangest and most compelling culture experiment.',
      case: 'A veteran defensive program-builder inherits a rare quarterback and a roster built for contact.',
      doubt: 'A new sideline does not instantly erase the program’s recent on- and off-field instability.',
      proof: 'Give Underwood a coherent game rather than a weekly rescue assignment.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Western Michigan at Michigan Stadium on Saturday, Sept. 5, Kyle Whittingham’s first game on the Michigan sideline.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/130/michigan-wolverines',
        'https://en.wikipedia.org/wiki/2026_Michigan_Wolverines_football_team',
        'https://mgoblue.com/sports/2026/8/31/michigan-monday-game-1-vs-western-michigan',
      ],
    },
    {
      rank: 16,
      previousRank: 16,
      movement: 'HOLD',
      school: 'BYU',
      short: 'BYU',
      conference: 'Big 12',
      signal: 'playoff-weather',
      accent: '#002e5d',
      reason: 'Consecutive 11-win seasons are evidence, not atmosphere.',
      case: 'Bear Bachmeier and LJ Martin return to the league’s preseason favorite.',
      doubt: 'New defensive leadership has to preserve the thing that made the last two seasons travel.',
      proof: 'Win when the offense is merely normal.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Utah Tech in Provo on Saturday, Sept. 5; Utah Tech arrives 0-1 after a 54-0 loss to Montana State in Week 0.',
      sources: [
        'https://byucougars.com/news/2026/08/31/byu-football-game-week-2026-utah-tech',
        'https://www.deseret.com/sports/2026/08/31/college-football-byu-utah-utah-state-week-1-week-0/',
      ],
    },
    {
      rank: 17,
      previousRank: 17,
      movement: 'HOLD',
      school: 'Ole Miss',
      short: 'MISS',
      conference: 'SEC',
      signal: 'fault-line',
      accent: '#ce1126',
      reason: 'Enough offensive continuity to matter; an entire post-Kiffin identity still to invent.',
      case: 'Trinidad Chambliss and Kewan Lacy give Pete Golding two honest offensive anchors.',
      doubt: 'The staff and defense changed around them, and every close call becomes a referendum on the succession.',
      proof: 'Show an offensive identity that is not a tribute act.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens Sunday, Sept. 6 against Louisville at Nissan Stadium in Nashville, Pete Golding’s first game as head coach.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/145/ole-miss-rebels',
        'https://en.wikipedia.org/wiki/2026_Ole_Miss_Rebels_football_team',
      ],
    },
    {
      rank: 18,
      previousRank: 18,
      movement: 'HOLD',
      school: 'Tennessee',
      short: 'TENN',
      conference: 'SEC',
      signal: 'fault-line',
      accent: '#ff8200',
      reason: 'Jim Knowles can make the defense serious immediately. Nobody has earned certainty at quarterback.',
      case: 'A more disciplined defense can keep the season alive while the offense chooses its operator.',
      doubt: 'George MacIntyre and Faizon Brandon enter without the experience a contender normally buys.',
      proof: 'Produce boring, repeatable quarterback decisions for four quarters.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against FCS Furman at Neyland Stadium on Saturday, Sept. 5, which will show who takes the first snap and little else.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/2633/tennessee-volunteers',
        'https://www.cbssports.com/college-football/teams/TENN/tennessee-volunteers/schedule/',
      ],
    },
    {
      rank: 19,
      previousRank: 19,
      movement: 'HOLD',
      school: 'Clemson',
      short: 'CLEM',
      conference: 'ACC',
      signal: 'fault-line',
      accent: '#f56600',
      reason: 'Potentially exceptional receivers, a new quarterback, and the clearest Dabo inflection point yet.',
      case: 'Chad Morris returns to an offense that can put Christopher Vizzina inside an unusually good receiver room.',
      doubt: 'A 7–6 season made “the old Clemson” an argument instead of a baseline.',
      proof: 'Turn receiver talent into explosive points before the crowd starts remembering 2018.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens at LSU on Saturday, Sept. 5 as a 10-point underdog on ESPN’s line, the hardest opener on this board.',
      sources: [
        'https://www.espn.com/college-football/game/_/gameId/401856660/clemson-lsu',
      ],
    },
    {
      rank: 20,
      previousRank: 20,
      movement: 'HOLD',
      school: 'Utah',
      short: 'UTAH',
      conference: 'Big 12',
      signal: 'fault-line',
      accent: '#cc0000',
      reason: 'Can the infrastructure survive the end of the Whittingham era? We believe it can—barely.',
      case: 'Years of developmental competence remain in the building even after the defining coach leaves.',
      doubt: 'Institutional memory is not play-calling, recruiting, or fourth-quarter authority.',
      proof: 'Look unmistakably like Utah after the person most associated with “Utah football” is gone.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens Thursday, Sept. 3 against Idaho at Rice-Eccles Stadium, Morgan Scalley’s first game as head coach; Idaho threw for 363 yards in a 38-34 Week 0 loss to Cal Poly.',
      sources: [
        'https://www.espn.com/college-football/team/schedule/_/id/254/utah-utes',
        'https://en.wikipedia.org/wiki/2026_Utah_Utes_football_team',
        'https://www.deseret.com/sports/2026/08/31/college-football-byu-utah-utah-state-week-1-week-0/',
      ],
    },
    {
      rank: 21,
      previousRank: 21,
      movement: 'HOLD',
      school: 'Washington',
      short: 'WASH',
      conference: 'Big Ten',
      signal: 'fault-line',
      accent: '#4b2e83',
      reason: 'Quietly respected by models and preseason consensus; a perfect early candidate for “we noticed first.”',
      case: 'The underlying roster and returning structure grade better than the national conversation.',
      doubt: 'Big Ten travel turns respectable depth into a weekly stress test.',
      proof: 'Carry offensive efficiency across one cross-country conference trip.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens Sunday, Sept. 6 against Washington State in the Apple Cup at Husky Stadium, moved to Sunday and serving as a season opener for the first time in the series.',
      sources: [
        'https://en.wikipedia.org/wiki/2026_Washington_Huskies_football_team',
        'https://www.fox13seattle.com/sports/apple-cup-scheduled-sunday-labor-day-weekend-2026',
        'https://www.kiro7.com/news/local/wsu-uw-announce-change-apple-cup-schedule/ZSACJV2IEBEFTADL4ZBIG6QYVA/',
      ],
    },
    {
      rank: 22,
      previousRank: 22,
      movement: 'HOLD',
      school: 'Florida',
      short: 'FLA',
      conference: 'SEC',
      signal: 'fault-line',
      accent: '#fa4616',
      reason: 'Jon Sumrall inherits real talent and an SEC-sized proof requirement.',
      case: 'The receiver room gives the new staff enough speed to make the reset visible quickly.',
      doubt: 'Talent at key positions is not the same thing as a complete line-to-line football team.',
      proof: 'Beat a good opponent without making the new-coach story the entire offense.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Florida Atlantic in Gainesville on Saturday, Sept. 5 at 7:45 p.m. ET, Jon Sumrall’s first game as Florida head coach.',
      sources: [
        'https://en.wikipedia.org/wiki/2026_Florida_Gators_football_team',
        'https://247sports.com/college/florida/article/flordia-gators-football-kickoff-times-announced-first-three-games-2026-season-286653863/',
      ],
    },
    {
      rank: 23,
      previousRank: 23,
      movement: 'HOLD',
      school: 'South Carolina',
      short: 'SC',
      conference: 'SEC',
      signal: 'fault-line',
      accent: '#73000a',
      reason: 'LaNorris Sellers is the reason; whether anybody can protect him is the entire ranking.',
      case: 'Sellers returned with the talent to make Kendal Briles’ reset immediately dangerous.',
      doubt: 'The 2025 line was disastrous, and quarterback brilliance cannot be the pass-protection plan.',
      proof: 'Let a deep concept develop without asking Sellers to escape first.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Kent State at Williams-Brice Stadium on Saturday, Sept. 5, the first live look at the line in front of Sellers.',
      sources: [
        'https://gamecocksonline.com/sports/football/schedule/',
        'https://gamecocksonline.com/news/2026/08/31/know-before-you-go-kent-state-2026/',
      ],
    },
    {
      rank: 24,
      previousRank: 24,
      movement: 'HOLD',
      school: 'Boise State',
      short: 'BOI',
      conference: 'Pac-12',
      signal: 'outsider',
      accent: '#0033a0',
      reason: 'The outsider benchmark: the team that reveals whether this poll actually watches beyond the power brands.',
      case: 'Boise remains the cleanest preseason proxy for the strongest program outside the Power Four.',
      doubt: 'The new Pac-12 carries opportunity and a weekly credibility tax.',
      proof: 'Beat the kind of opponent whose logo normally wins the argument before kickoff.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens at Oregon on Saturday, Sept. 5, the first game as a Pac-12 member and exactly the kind of logo the proof line asks for.',
      sources: [
        'https://en.wikipedia.org/wiki/2026_Boise_State_Broncos_football_team',
        'https://www.si.com/college/boise-state/football/boise-state-football-2026-opponent-preview-oregon-ducks',
        'https://sports.yahoo.com/articles/kickoff-times-tv-channels-revealed-204436728.html',
      ],
    },
    {
      rank: 25,
      previousRank: 25,
      movement: 'HOLD',
      school: 'Iowa',
      short: 'IOWA',
      conference: 'Big Ten',
      signal: 'outsider',
      accent: '#fcd116',
      reason: 'An elite imported runner, institutional defensive competence, and the possibility of extremely strange winning.',
      case: 'LJ Phillips arrives after 1,920 rushing yards at South Dakota, attached to Iowa’s usual floor.',
      doubt: 'A new quarterback and a wave of new starters can turn “usual floor” into nostalgia.',
      proof: 'Score enough early that the punter does not become the offensive identity again.',
      result: null,
      change: 'Not yet played; holds on the preseason case. Opens against Northern Illinois at Kinnick Stadium on Saturday, Sept. 5 with Hank Brown and Jeremy Hecklinski listed as co-starters at quarterback and both expected to play.',
      sources: [
        'https://hawkeyesports.com/sports/football/schedule/',
        'https://hawkeyesports.com/sports/football/',
        'https://sports.yahoo.com/articles/iowa-football-still-undecided-starting-193523032.html',
      ],
    },
  ] satisfies PointCast25Team[],
  dropped: [],
  unverified: [
    'Ohio State — vs. Ball State, Sat. Sept. 5 (not yet played)',
    'Notre Dame — vs. Wisconsin at Lambeau Field, Sun. Sept. 6 (not yet played)',
    'Texas — vs. Texas State, Sat. Sept. 5 (not yet played)',
    'Oregon — vs. Boise State, Sat. Sept. 5 (not yet played)',
    'Georgia — vs. Tennessee State, Sat. Sept. 5 (not yet played)',
    'Indiana — vs. North Texas, Sat. Sept. 5 (not yet played)',
    'Miami — at Stanford, Fri. Sept. 4 (not yet played)',
    'LSU — vs. Clemson, Sat. Sept. 5 (not yet played)',
    'Texas Tech — vs. Abilene Christian, Sat. Sept. 5 (not yet played)',
    'Alabama — vs. East Carolina, Sat. Sept. 5 (not yet played)',
    'Penn State — vs. Marshall, Sat. Sept. 5 (not yet played)',
    'Texas A&M — vs. Missouri State, Sat. Sept. 5 (not yet played)',
    'Oklahoma — vs. UTEP, Fri. Sept. 4 (not yet played)',
    'Michigan — vs. Western Michigan, Sat. Sept. 5 (not yet played)',
    'BYU — vs. Utah Tech, Sat. Sept. 5 (not yet played)',
    'Ole Miss — vs. Louisville in Nashville, Sun. Sept. 6 (not yet played)',
    'Tennessee — vs. Furman, Sat. Sept. 5 (not yet played)',
    'Clemson — at LSU, Sat. Sept. 5 (not yet played)',
    'Utah — vs. Idaho, Thu. Sept. 3 (not yet played)',
    'Washington — vs. Washington State, Apple Cup, Sun. Sept. 6 (not yet played)',
    'Florida — vs. Florida Atlantic, Sat. Sept. 5 (not yet played)',
    'South Carolina — vs. Kent State, Sat. Sept. 5 (not yet played)',
    'Boise State — at Oregon, Sat. Sept. 5 (not yet played)',
    'Iowa — vs. Northern Illinois, Sat. Sept. 5 (not yet played)',
  ],
} as const;

export const POINTCAST_25_SIGNAL_LABELS: Record<PointCast25Signal, string> = {
  'title-weather': 'Title weather',
  'playoff-weather': 'Playoff weather',
  'fault-line': 'Fault line',
  outsider: 'Outsider',
};

// Ledger entries are frozen literals, never derived from the live POINTCAST_25
// object — a published board's row must not move when the next board edits the lib.
export const POINTCAST_25_EDITIONS = [
  {
    board: '000',
    status: 'preseason',
    publishedAt: '2026-07-27T11:25:00-07:00',
    question: 'If everybody played next Saturday, which 25 teams would we believe in most?',
    leaders: [
      { rank: 1, school: 'Ohio State', reason: 'The highest quarterback–receiver ceiling in the sport, carrying the season’s nastiest road schedule.' },
      { rank: 2, school: 'Notre Dame', reason: 'Unusual defensive continuity and fewer imaginary preseason dependencies than anyone else.' },
      { rank: 3, school: 'Texas', reason: 'The Arch Manning window is now; the unresolved run game keeps this from being No. 1.' },
      { rank: 4, school: 'Oregon', reason: 'Dante Moore, deep talent, championship capacity—and two new coordinators to assimilate.' },
      { rank: 5, school: 'Georgia', reason: 'Back-to-back SEC champions receive institutional trust until the rebuilt secondary spends it.' },
    ],
    integrity: 'sha256:2b34a571dfe7063517a8405a801b5b7c544f97f3d4b8a2feec4336cdfdf3333f',
    human: 'https://pointcast.xyz/b/0510',
    snapshot: 'https://pointcast.xyz/25/boards/000',
    machine: 'https://pointcast.xyz/25/boards/000.json',
    current: 'https://pointcast.xyz/25',
    block: '0510',
  },
  {
    board: '001',
    previous: '000',
    status: 'week-1',
    publishedAt: '2026-09-01T17:00:00-07:00',
    question: 'Only one team on this board has played; which of the other 24 cases survives Labor Day weekend intact?',
    leaders: [
      { rank: 1, school: 'Ohio State', reason: 'The highest quarterback–receiver ceiling in the sport, carrying the season’s nastiest road schedule.' },
      { rank: 2, school: 'Notre Dame', reason: 'Unusual defensive continuity and fewer imaginary preseason dependencies than anyone else.' },
      { rank: 3, school: 'Texas', reason: 'The Arch Manning window is now; the unresolved run game keeps this from being No. 1.' },
      { rank: 4, school: 'Oregon', reason: 'Dante Moore, deep talent, championship capacity—and two new coordinators to assimilate.' },
      { rank: 5, school: 'Georgia', reason: 'Back-to-back SEC champions receive institutional trust until the rebuilt secondary spends it.' },
    ],
    movements: { up: 0, down: 0, hold: 25, new: 0, dropped: 0, gamesPlayed: 1 },
    biggestMove:
      'None. USC (No. 10) beat San José State 42-26 on Aug. 29 and held; the other 24 had not played, so every number carried over from Board 000.',
    integrity: 'sha256:2a95780cd7f7fc52153b9c29d40060332b5ff98f97b8ebc6a2e36e41114adf83',
    human: 'https://pointcast.xyz/b/0582',
    snapshot: 'https://pointcast.xyz/25/boards/001',
    machine: 'https://pointcast.xyz/25/boards/001.json',
    current: 'https://pointcast.xyz/25',
    block: '0582',
  },
] as const;
