export interface PointcastApp {
  slug: string;
  name: string;
  kicker: string;
  description: string;
  url: string;
  path: string;
  repo: string;
  channel: string;
  kind: 'satellite' | 'pointcast';
}

export const POINTCAST_APPS: PointcastApp[] = [
  {
    slug: 'common-hours',
    name: 'Common Hours',
    kicker: 'BELLS · ALTARS · SHRINES · DAILY RITUALS',
    description: 'A PointCast door into a wider living index of ordinary ceremony: Daily Chimes, prayer bells, morning and evening altars, drum shrines, Stampz, Passportz weather, and small gatherings.',
    url: 'https://common-hours.mhoydich.chatgpt.site',
    path: '/common-hours',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'corner-engineering',
    name: 'Corner Engineering Pulse',
    kicker: 'CREW MISSIONS · WORKCELLS · DIGITAL THREAD',
    description: 'A playful mission layer for traceable engineering signals, crew quests, workcell check-ins, controlled risks, and digital-thread momentum.',
    url: 'https://pointcast.xyz/corner',
    path: '/corner',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DATA',
    kind: 'pointcast',
  },
  {
    slug: 'radius-90245',
    name: 'RADIUS / 90245',
    kicker: 'RF FIELD BENCH · 25-MILE LAYER · SIGNAL AUDIO',
    description: 'A shareable free-space RF link bench centered on El Segundo, with path loss, received power, noise, SNR, Fresnel clearance, light-time, ideal capacity, and optional sonification.',
    url: 'https://pointcast.xyz/ues/radius',
    path: '/ues/radius',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DATA',
    kind: 'pointcast',
  },
  {
    slug: 'noun-battler-pacific-48',
    name: 'Noun Battler — Pacific 48',
    kicker: '48 BATTLERS · LOCAL STAMPS · PASSPORT CARD',
    description: 'A five-round CC0 Noun stat battle with a local stamp book, printable Passport card, and an optional Tezos Passport signature handoff.',
    url: 'https://pointcast.xyz/noun-battler',
    path: '/noun-battler',
    repo: 'https://github.com/mhoydich/noun-battler',
    channel: 'CH.BTL',
    kind: 'satellite',
  },
  {
    slug: 'arcade-60',
    name: 'Arcade 60',
    kicker: '50 MINI GAMES · 10 NOUN PRESSES',
    description: 'A PointCast cabinet for fifty one-minute games and ten CC0 Noun mint drafts, with the wallet approval boundary preserved in Nounfound.',
    url: 'https://pointcast.xyz/arcade-60',
    path: '/arcade-60',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.PLAY',
    kind: 'pointcast',
  },
  {
    slug: 'el-segundo-school',
    name: 'The El Segundo School',
    kicker: '652 WORKS · PASSPORT · STAMPZ · TEZOS',
    description: 'Michael Hoydich’s full Midjourney field archive as a three-dimensional gallery, with high-resolution Passport postcards, custom Stampz objects, physical-production briefs, and 1 tez Mainnet collector editions.',
    url: 'https://pointcast.xyz/el-segundo-school',
    path: '/el-segundo-school',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.ESS',
    kind: 'pointcast',
  },
  {
    slug: 'afterimage',
    name: 'Afterimage Relay',
    kicker: 'IMAGE SIGNAL · MUSIC ROOM · TEZOS HANDOFF',
    description: 'A PointCast receiver for public Afterimage cuts and Mood Rooms: paste a Passport room URL, play it as a broadcast, share the relay, or return to Passport to remix and mint.',
    url: 'https://pointcast.xyz/afterimage',
    path: '/afterimage',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.AF',
    kind: 'pointcast',
  },
  {
    slug: 'pointcast-native-shell',
    name: 'PointCast Native Shell',
    kicker: 'PWA · NOW · ROOMS',
    description: 'The installable PointCast home screen: Now, Rooms, Drum, Profile, Collect, and Agents in one mobile-first app shell.',
    url: 'https://pointcast.xyz/app',
    path: '/app',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.FD',
    kind: 'pointcast',
  },
  {
    slug: 'pointcast-pet',
    name: 'PointCast Pet',
    kicker: 'LOCAL COMPANION · CARE · RECEIPTS',
    description: 'Your selected site companion, with local care, changing signal state, and a small receipt trail shared with the PointCast dock.',
    url: 'https://pointcast.xyz/pet',
    path: '/pet',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.PET',
    kind: 'pointcast',
  },
  {
    slug: 'pointcast-passport',
    name: 'PointCast Tezos Passport',
    kicker: 'LOCAL STAMPS · TEZOS VISAS · SIGNED SEALS',
    description: 'A dual-ledger passport that keeps PointCast rituals private, reads public collection holdings from TzKT, and can seal a journey with one optional wallet signature.',
    url: 'https://pointcast.xyz/passport',
    path: '/passport',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.PASS',
    kind: 'pointcast',
  },
  {
    slug: 'chart-of-the-day',
    name: 'Chart of the Day',
    kicker: 'DAILY DATA · LEDGER PULSE',
    description: 'A daily-rotating PointCast chart built from the block ledger, with a human view at /chart and a machine-readable packet at /chart.json.',
    url: 'https://pointcast.xyz/chart',
    path: '/chart',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.FD',
    kind: 'pointcast',
  },
  {
    slug: 'pointcast-chartmaker',
    name: 'PointCast Chartmaker',
    kicker: 'FEEDS · CROSS-CHARTS · TIMELINES',
    description: 'A chart lab for combining PointCast-native data with weather, market, sports, feed, and browser-local sources.',
    url: 'https://pointcast.xyz/chartmaker',
    path: '/chartmaker',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DATA',
    kind: 'pointcast',
  },
  {
    slug: 'solitaire-v2',
    name: 'Solitaire v2',
    kicker: 'WINDOWS 95 · NOUNS · CARDS',
    description: 'A playable Nouns-flavored Klondike table with better cards, generated felt art, and a Windows 95 worthy PointCast skin.',
    url: 'https://pointcast.xyz/solitaire-v2',
    path: '/solitaire-v2',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.BTL',
    kind: 'pointcast',
  },
  {
    slug: 'drum-games',
    name: 'Drum Arcade',
    kicker: 'FIVE GAMES · MEMORY · POCKET',
    description: 'Five instant PointCast drum games for memory, restraint, groove completion, beat-running, and silent-tempo control.',
    url: 'https://pointcast.xyz/drum-games',
    path: '/drum-games',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'elemental-shrine',
    name: 'Elemental Shrine',
    kicker: 'STONE · LIGHT · FIRE · WATER',
    description: 'A quiet interactive altar of four elemental presences, with an original opt-in soundscape created in ElevenLabs.',
    url: 'https://pointcast.xyz/elemental-shrine',
    path: '/elemental-shrine',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'open-road-shrine',
    name: 'Open Road Shrine',
    kicker: 'ONE MINUTE · BREATH · VOTIVE',
    description: 'A quiet shrine built around a 1955 Chevrolet painting: enter one minute of stillness, breathe slowly, and offer a light.',
    url: 'https://pointcast.xyz/open-road',
    path: '/open-road',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'open-road-v2',
    name: 'Open Road II',
    kicker: 'TWO PASSAGES · TEN PAINTINGS · BREATH',
    description: 'Ten 1955 Chevrolet paintings become two five-station passages, with each complete breath revealing the next image.',
    url: 'https://pointcast.xyz/open-road-v2',
    path: '/open-road-v2',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'open-road-v3',
    name: 'Open Road III',
    kicker: 'BEYOND THE WINDSHIELD · TWO PASSAGES · BREATH',
    description: 'Ten landscapes, figures, scores, and atmospheric collages form two five-station passages beyond the car and into the wider world.',
    url: 'https://pointcast.xyz/open-road-v3',
    path: '/open-road-v3',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'open-road-v4',
    name: 'Open Road IV',
    kicker: 'FIVE CALL · FIVE ANSWER · GENTLE BELLS',
    description: 'Ten older works form five visual call-and-response pairs, with drifting motion and optional bells sounding the space between them.',
    url: 'https://pointcast.xyz/open-road-v4',
    path: '/open-road-v4',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'open-road-v5',
    name: 'Open Road V',
    kicker: 'TEN FRAGMENTS · FIVE PETALS · MAKE A WINDOW',
    description: 'Ten older works become fragments for a five-petal window you can compose, revise, complete, and share.',
    url: 'https://pointcast.xyz/open-road-v5',
    path: '/open-road-v5',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'open-road-v6',
    name: 'Open Road VI',
    kicker: 'ONE QUIET MINUTE · TEN IMAGES · FOR PETE',
    description: 'A one-minute vigil for Pete moves through ten archive images, with quiet controls, optional bells, and a final light held still.',
    url: 'https://pointcast.xyz/open-road-v6',
    path: '/open-road-v6',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'open-road-v7',
    name: 'Open Road VII',
    kicker: 'SIXTEEN WITNESSES · FOUR WATCHES · KEEP ONE LIGHT',
    description: 'A time-aware book of hours moves through sixteen quiet witnesses across dawn, day, dusk, and night, with one private light to keep.',
    url: 'https://pointcast.xyz/open-road-v7',
    path: '/open-road-v7',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.DR',
    kind: 'pointcast',
  },
  {
    slug: 'win95-games',
    name: 'Windows 95 Games',
    kicker: 'NOUNS · CARDS · DESKTOP',
    description: 'A small PointCast game shelf for Windows 95 worthy Nouns card games: Solitaire, Memory, and Pyramid.',
    url: 'https://pointcast.xyz/win95-games',
    path: '/win95-games',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.BTL',
    kind: 'pointcast',
  },
  {
    slug: 'nouns-memory-v2',
    name: 'Nouns Memory v2',
    kicker: 'PAIRS · LOCAL BEST · NOUNS',
    description: 'A quick Windows 95 style Nouns memory tray with local best score and a generated desktop table.',
    url: 'https://pointcast.xyz/nouns-memory-v2',
    path: '/nouns-memory-v2',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.BTL',
    kind: 'pointcast',
  },
  {
    slug: 'nouns-pyramid-v2',
    name: 'Nouns Pyramid v2',
    kicker: 'ADD TO 13 · CARD TABLE',
    description: 'A pyramid card game with Nouns card faces, Win95 chrome, and a simple add-to-thirteen loop.',
    url: 'https://pointcast.xyz/nouns-pyramid-v2',
    path: '/nouns-pyramid-v2',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.BTL',
    kind: 'pointcast',
  },
  {
    slug: 'nouns-mines-v2',
    name: 'Nouns Mines v2',
    kicker: 'MINES · FLAGS · NOUNS',
    description: 'A Minesweeper-style Windows 95 Nouns board with local clear tracking and reward tiles.',
    url: 'https://pointcast.xyz/nouns-mines-v2',
    path: '/nouns-mines-v2',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.BTL',
    kind: 'pointcast',
  },
  {
    slug: 'moodygold',
    name: 'MoodyGold',
    kicker: 'ARTWORK · SOUND · GALLERY',
    description: 'A MoodyGold gallery and visualizer surface, hosted as its own app and viewable from PointCast.',
    url: 'https://moodygold.pages.dev',
    path: '/moodygold',
    repo: 'https://github.com/mhoydich/abstract-soundscapes',
    channel: 'CH.SPN',
    kind: 'satellite',
  },
  {
    slug: 'offbalance',
    name: 'Offbalance',
    kicker: 'GOOD FEELS · EL SEGUNDO',
    description: 'The Good Feels El Segundo deck: cannabis as inquiry, flow-state pairings, and product-world thinking.',
    url: 'https://offbalance-6hl.pages.dev',
    path: '/offbalance',
    repo: 'https://github.com/mhoydich/offbalance',
    channel: 'CH.GF',
    kind: 'satellite',
  },
  {
    slug: 'cannabis',
    name: 'Cannabis Atlas',
    kicker: 'CHEMOVARS · EFFECTS WHEEL',
    description: 'A Southern California cannabis resource for strain names, chemovar signals, terpenes, and pairings.',
    url: 'https://pointcast.xyz/cannabis',
    path: '/cannabis',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.GF',
    kind: 'pointcast',
  },
  {
    slug: 'mint-studio',
    name: 'Mint Studio',
    kicker: 'ART BRIEF · METADATA · RECEIPTS',
    description: 'A local mint-planning desk for turning art ideas into clean collectible briefs, metadata notes, and Tezos-ready receipts.',
    url: 'https://pointcast.xyz/mint-studio',
    path: '/mint-studio',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.MINT',
    kind: 'pointcast',
  },
  {
    slug: 'cabinet',
    name: 'The Cabinet',
    kicker: 'LOCAL SHELF · COLLECTIBLES · RECEIPTS',
    description: 'A personal PointCast shelf that gathers local cats, ocean cards, mint receipts, passport stamps, invites, and readiness checkpoints.',
    url: 'https://pointcast.xyz/cabinet',
    path: '/cabinet',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SHELF',
    kind: 'pointcast',
  },
  {
    slug: 'observatory',
    name: 'The Observatory',
    kicker: 'CONSTELLATIONS · LOCAL STATE · COLLECTION MAP',
    description: 'A night-sky view of PointCast collectibles that turns local receipts, cats, ocean cards, invites, and checkpoints into a constellation.',
    url: 'https://pointcast.xyz/observatory',
    path: '/observatory',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SKY',
    kind: 'pointcast',
  },
  {
    slug: 'signal-garden',
    name: 'Signal Garden',
    kicker: 'LOCAL ACTIVITY · AMBIENT GROWTH',
    description: 'A lightweight local garden that turns PointCast receipts, rituals, stamps, proofs, and saved plants into an ambient growth map.',
    url: 'https://pointcast.xyz/signal-garden',
    path: '/signal-garden',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SIGNAL',
    kind: 'pointcast',
  },
  {
    slug: 'gallery-wall',
    name: 'Gallery Wall',
    kicker: 'CURATION · SHOW CARDS · LOCAL WALLS',
    description: 'A curator room for arranging cats, ocean cards, routes, and receipts into small collectible exhibitions saved locally.',
    url: 'https://pointcast.xyz/gallery-wall',
    path: '/gallery-wall',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.CURATE',
    kind: 'pointcast',
  },
  {
    slug: 'ritual-clock',
    name: 'Ritual Clock',
    kicker: 'DAILY CADENCE · COLLECTOR RHYTHM',
    description: 'A daily rhythm board for marking cat, harbor, studio, and night-sky collector rituals without accounts or sync.',
    url: 'https://pointcast.xyz/ritual-clock',
    path: '/ritual-clock',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.TIME',
    kind: 'pointcast',
  },
  {
    slug: 'exchange-table',
    name: 'Exchange Table',
    kicker: 'WISHLIST · OFFERS · DISCLOSURE',
    description: 'A private collector table for noting wants, offers, and watch signals before anything becomes a marketplace action.',
    url: 'https://pointcast.xyz/exchange-table',
    path: '/exchange-table',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SWAP',
    kind: 'pointcast',
  },
  {
    slug: 'provenance-ledger',
    name: 'Provenance Ledger',
    kicker: 'LOCAL PROOFS · EXPORT SHEETS',
    description: 'A local proof desk that gathers PointCast app receipts into normalized provenance sheets and checksum-style export cards.',
    url: 'https://pointcast.xyz/provenance-ledger',
    path: '/provenance-ledger',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.PROOF',
    kind: 'pointcast',
  },
  {
    slug: 'world-atlas',
    name: 'World Atlas',
    kicker: 'ZEN CAT ROUTES · LANDMARKS · GEMS',
    description: 'A map room for the luxury Zen Cat world series, with landmark stops, gemstone cues, and local route stamps.',
    url: 'https://pointcast.xyz/world-atlas',
    path: '/world-atlas',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.WORLD',
    kind: 'pointcast',
  },
  {
    slug: 'harbor-log',
    name: 'Harbor Log',
    kicker: 'MORNING OCEAN · WATCHLIST',
    description: 'A small collector console for drawing Morning Ocean vessels, keeping a local watchlist, and opening mintable maritime cards.',
    url: 'https://pointcast.xyz/harbor-log',
    path: '/harbor-log',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.OCEAN',
    kind: 'pointcast',
  },
  {
    slug: 'cat-passport',
    name: 'Cat Passport',
    kicker: 'ZEN CATS · GEMS · LANDMARKS',
    description: 'A passport-stamp app for Zen Cat world collectibles, with gemstones, landmarks, and local travel receipts.',
    url: 'https://pointcast.xyz/cat-passport',
    path: '/cat-passport',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.CAT',
    kind: 'pointcast',
  },
  {
    slug: 'referral-garden',
    name: 'Referral Garden',
    kicker: 'INVITES · DISCLOSURE · TRUST',
    description: 'A disclosure-first referral garden for one-level invites, local milestones, and contribution-based collector growth.',
    url: 'https://pointcast.xyz/referral-garden',
    path: '/referral-garden',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.GROW',
    kind: 'pointcast',
  },
  {
    slug: 'sats-path',
    name: 'Sats Path',
    kicker: 'CAPITAL JOURNEY · BITCOIN READINESS',
    description: 'An educational, non-custodial pathway from creative receipts to calm capital habits and Bitcoin readiness checkpoints.',
    url: 'https://pointcast.xyz/sats-path',
    path: '/sats-path',
    repo: 'https://github.com/mhoydich/pointcast',
    channel: 'CH.SATS',
    kind: 'pointcast',
  },
];

export function getPointcastApp(slug: string) {
  return POINTCAST_APPS.find((app) => app.slug === slug);
}
