/**
 * Practice — UES Working Paper 2026-20.
 *
 * V2 of /living-body. Where the Living Body paper documents the three
 * traditions of mapped body-energy (TCM meridians, Yogic chakras,
 * modern integrated acupuncture) at the foremost-resource level, this
 * paper translates the traditions into everyday practice — movement,
 * stillness, breath, self-acupressure — with specific instructions
 * accessible to a corridor cohort member with no prior experience.
 *
 * Department of Local Inquiry. The seventh paper in the body-practice
 * sequence after Marine Layer, Bath House, Time, Sabbatical, P2P AI,
 * Living Body, and Civic Federation. The corridor's working position
 * is that practice is what makes traditions real; documentation is
 * the floor, not the ceiling.
 */

export const PAPER_META = {
  title: 'Practice',
  subtitle: 'Movement, stillness, breath, self-acupressure · everyday practice translating the Living Body traditions into corridor-cohort form · UES Working Paper 2026-20',
  thesis: 'Documentation of the three traditions (per /living-body, UES-WP-2026-18) is the floor, not the ceiling. Practice is what makes traditions real. This paper translates the traditions into everyday accessible practice across four modes — movement (walking, qi gong, tai chi, yoga asana, pickleball-as-attention-practice), stillness (sitting, body scan, yoga nidra, savasana), breath (4-7-8, box, alternate nostril, kapalabhati, coherent), self-acupressure (10 foundational points with technique notes) — paired with a daily practice atlas, an 8-week beginner ladder, expanded cohort offerings, and a vetted teacher-and-practitioner directory. The corridor\'s working position is that practice is small, daily, embodied, integrated rather than additive, and held by a cohort. Solo practice is sustainable for some; cohort practice is sustainable for nearly all. This paper makes the cohort form available to anyone in the corridor who wants to begin.',
  paperNumber: 'UES-WP-2026-20',
  date: '2026-05-08',
  authors: [
    { name: 'Michael Hoydich (UES Convener)', dept: 'Department of Local Inquiry', email: 'mh@pointcast.xyz' },
  ],
  keywords: ['practice', 'movement', 'stillness', 'breath', 'pranayama', 'qi gong', 'tai chi', 'yoga asana', 'self-acupressure', 'meditation', 'body scan', 'University of El Segundo', 'cohort practice'],
  parentPaper: 'UES-WP-2026-18 The Living Body',
  relatedSurfaces: ['UES-WP-2026-01 Marine Layer', 'UES-WP-2026-14 The Bath House', 'UES-WP-2026-16 Time', 'UES-Federation-07 Sabbatical Infrastructure'],
};

export const FOUNDATIONAL_PRINCIPLES = [
  { principle: 'Small and daily over big and occasional', detail: 'A 15-minute daily practice over 90 days produces more lasting change than a 2-hour weekly practice over the same period. The body learns by repetition; the nervous system retunes by frequency. Federation cohort offerings default to short-and-frequent rather than long-and-rare for this reason.' },
  { principle: 'Embodied not theoretical', detail: 'Reading about practice is not practice. The federation library documents the traditions; the practices live only in bodies. A cohort member who reads /living-body and never sits, walks, breathes, or presses any point has not begun practice.' },
  { principle: 'Integrated not additive', detail: 'Practice that adds another item to a busy day is unlikely to last. Practice that integrates with existing patterns (walk to the corner store with attention; breathe before opening a difficult email; press LV-3 while at a stop light) sustains because it does not compete for time.' },
  { principle: 'Held by cohort more often than held alone', detail: 'Solo practice works for the disciplined few. Cohort practice — the same time each week, with named other people, in a place that holds the practice — works for nearly everyone. The Marine Layer cohort form scales to all the body-practice modes documented in this paper.' },
  { principle: 'Body intelligence over technique perfection', detail: 'A 60% correct posture done with attention to breath and sensation produces more benefit than a 95% correct posture executed mechanically. The federation\'s working position is that practice is internal-listening + external-form, with internal-listening as the primary signal.' },
  { principle: 'Tradition over fashion', detail: 'The traditions documented in /living-body have been refined for ~2,000+ years. Contemporary practice innovations are sometimes valuable, sometimes shallow rebrandings, sometimes harmful. The federation\'s default is to teach traditional forms; innovation is opt-in not default.' },
  { principle: 'Honest scaling — start where you are', detail: 'Practice that begins beyond capacity injures and demotivates. The 8-week ladder below is intentionally easy in weeks 1-3. Members who can already do more should do more; members who cannot are not behind.' },
];

export const DAILY_PRACTICE_ATLAS = {
  description: 'A 24-hour structure for integrating practice across the day. Adopted in full or in part. Scaled to the cohort member\'s actual schedule.',
  morning: [
    { time: 'On waking', practice: 'Hand-rub (warm palms together for 30 seconds), face-wash (light face strokes from chin upward), eye-press (palms gently over closed eyes for 60 seconds). 90 seconds total. Foundational TCM-rooted morning awakening sequence.', tradition: 'TCM morning protocol; analogous to Yogic kapalbhati-after-rising' },
    { time: '15 min before commerce wakes', practice: '15-minute Marine Layer sit OR 15-minute body scan OR 15-minute slow walk in the marine layer. 4-7-8 breath for the first eight rounds, then natural breath.', tradition: '/marine-layer week-1 protocol; integrates with circadian-time practice from /time' },
    { time: 'After morning coffee/tea', practice: '5-minute joint warming sequence — wrists, ankles, neck, shoulders, hips. Not yoga asana; preparatory mobility. Prevents the desk-stiffening accumulation that hurts long-term posture.', tradition: 'qi gong joint sequence; analogous to vinyasa-style joint warming' },
  ],
  midday: [
    { time: 'Mid-morning (10-11 am)', practice: '60-second self-acupressure on LI-4 (between thumb and index finger) — for stress that has accumulated since waking. Both hands.', tradition: 'TCM acupressure foundational' },
    { time: 'Lunch', practice: 'No-screen meal. Eat slowly. Notice flavor, texture, fullness. 15-20 minutes. The body asks attention; the meal returns it.', tradition: 'embodied-time practice from /time; mindful-eating tradition' },
    { time: 'Post-lunch (1:30-2:30 pm)', practice: '20-30 minute slow walk outside. No earbuds. Notice five things you can see, four you can hear, three you can feel. Returns attention to the body after digestive transition.', tradition: 'walking meditation; analogous to Vipassana walking practice' },
  ],
  afternoon: [
    { time: 'When stress spikes', practice: '4-7-8 breath × 4 rounds. In through the nose for 4, hold 7, out through the mouth for 8. Reset of the nervous system; takes ~90 seconds.', tradition: 'pranayama (Andrew Weil popularization of yogic technique)' },
    { time: 'Mid-afternoon (3-4 pm)', practice: '5-minute neck-and-shoulder release. Slow neck circles (both directions, 4 each). Shoulder rolls (forward 8, backward 8). Trapezius press (squeeze the shoulder muscle for 30 seconds, both sides).', tradition: 'qi gong neck sequence; common in modern restorative yoga' },
  ],
  evening: [
    { time: 'Pre-dinner (5-6 pm)', practice: '20-minute movement practice — choose one: yoga asana sequence, qi gong form, tai chi short form, or slow stretching. Not for fitness; for tissue release.', tradition: 'depends on practice chosen' },
    { time: 'After dinner', practice: '15-minute slow walk. Different from midday walk. Evening walk is digestion + transition-out-of-work-mode.', tradition: 'TCM digestive support; common-sense embodied practice' },
    { time: 'Pre-sleep (30-60 min before bed)', practice: 'Dim lights, no screens, light reading or music. 5-minute body scan in bed before sleep — head to toe, naming each region, releasing each region. Sleep follows the scan.', tradition: 'yoga nidra rooted; modern body-scan meditation' },
  ],
  weekly: [
    { event: 'One cohort gathering', practice: 'A 60-90 minute Marine Layer sit, qi gong session, yoga class, or self-acupressure circle with a cohort. The same time each week. The named other people are the practice.', tradition: 'corridor cohort form; transferable to any practice mode' },
    { event: 'One Sabbath day', practice: '25-hour disconnect (per /time and /sabbatical). Body practices integrate naturally — slower meals, longer walks, no work-screens, more movement and more stillness both.', tradition: 'Shabbat tradition adapted secularly' },
  ],
};

export type Practice = {
  id: string;
  name: string;
  mode: 'movement' | 'stillness' | 'breath' | 'acupressure';
  duration: string;
  difficulty: 'beginner' | 'intermediate' | 'experienced';
  tradition: string;
  whatYouDo: string;
  whatItDoes: string;
  cautions: string;
};

export const MOVEMENT_PRACTICES: Practice[] = [
  { id: 'walking', name: 'Walking with Attention', mode: 'movement', duration: '20-60 min', difficulty: 'beginner', tradition: 'Vipassana walking meditation; common-sense embodied practice', whatYouDo: 'Walk at 60-80% of your normal pace. Eyes soft, looking ahead about 6 feet. Feel each footfall: heel-strike, mid-foot, toe-off. Notice arm swing, hip rotation, head position. When the mind wanders, return to footfall. No earbuds, no phone, no destination focus.', whatItDoes: 'Re-establishes proprioception (body-position awareness) eroded by desk work. Activates the parasympathetic nervous system. Pairs perfectly with marine-layer hours.', cautions: 'Mind narrow streets and cross-traffic; the practice is internal-attention but external-vigilance is still required.' },
  { id: 'qi-gong', name: 'Qi Gong (Eight Brocades / Ba Duan Jin)', mode: 'movement', duration: '15-25 min', difficulty: 'beginner', tradition: 'Traditional Chinese qi gong, Eight Brocades sequence (Ba Duan Jin) c. 12th c. CE', whatYouDo: 'Eight movement sequences performed slowly, each 8-16 repetitions. Coordinated with breath. Examples: "Two Hands Hold Up the Heavens" (slow overhead arm raise on inhale, lower on exhale), "Drawing the Bow on Both Sides" (lateral arm extension, archer-stance lower body). Standard sequence widely taught and freely available.', whatItDoes: 'Improves circulation, joint mobility, and body-mind coordination. Daily practice for centuries by hundreds of millions; the longevity claims are over-stated in some popularizations but the basic restorative benefits are well-supported.', cautions: 'Modify for any joint condition. The Eight Brocades is unusually safe; not a replacement for diagnostic medical care.' },
  { id: 'tai-chi', name: 'Tai Chi (Short Form)', mode: 'movement', duration: '15-30 min', difficulty: 'intermediate', tradition: 'Yang-style short form (Cheng Man-ch\'ing 37-posture) widely taught', whatYouDo: 'Continuous slow flowing sequence. Weight transfer between feet emphasized. Hands move in arcs. Standard short form completes in ~10-15 minutes once learned. Best learned in person from a teacher; video supplementary not primary.', whatItDoes: 'Documented benefits for balance, fall prevention in elderly populations (multiple RCTs), Parkinson\'s symptoms, low-back pain, depression. The most clinically-studied of the movement practices.', cautions: 'Knee protection critical — keep knees aligned over toes; never let knees collapse inward. Learn proper form from a teacher before practicing independently.' },
  { id: 'yoga-asana', name: 'Yoga Asana (Slow Sequence)', mode: 'movement', duration: '30-60 min', difficulty: 'beginner', tradition: 'Modern Hatha yoga; many lineages (Iyengar precise alignment, Krishnamacharya breath-led, Yin holds, etc.)', whatYouDo: 'A sequence of postures (asanas) typically including standing poses (mountain, warrior I/II/III, triangle), seated poses (forward fold, twist), backbends (cobra, bridge), inversions (legs-up-the-wall is the gentle entry), and savasana (corpse pose) to close. Breath coordinated with movement.', whatItDoes: 'Improves flexibility, strength, balance, breath capacity. Cumulative benefit substantial across weeks of practice.', cautions: 'Many beginning-level injuries from over-pushing. Federation-cohort recommendation: start with a teacher-led class for at least 8 weeks before independent practice. Avoid aggressive heated-power-yoga formats early; injury rate higher.' },
  { id: 'pickleball', name: 'Pickleball (as practice)', mode: 'movement', duration: '60-90 min', difficulty: 'beginner', tradition: 'Modern sport (1965); the corridor frames it as Court Craft cohort practice', whatYouDo: 'Doubles or singles match. Federation framing: the game is the practice. Footwork attention, paddle-face awareness, breath between points. The competitive frame holds the body-attention practice that solo movement work struggles to sustain.', whatItDoes: 'Cardiovascular conditioning + skill-acquisition + cohort gathering + competitive engagement, all in one. The Honey League is the corridor\'s working pickleball cohort form.', cautions: 'Knee + ankle injuries common; warm up properly; modify intensity for fitness level.' },
  { id: 'swimming', name: 'Slow Swimming', mode: 'movement', duration: '30-45 min', difficulty: 'beginner', tradition: 'Common-sense embodied practice; integrates with the corridor\'s coastal context', whatYouDo: 'Swim at 50-70% of your maximum pace. Focus on stroke quality, breath rhythm, water sensation. Lap pool or open water (with safety precautions). Different from competitive lap swimming — the practice is attention-with-movement-in-water.', whatItDoes: 'Joint-low-impact movement; full-body engagement; respiratory training; integrates with Bath House (when funded) and existing corridor pool/beach access.', cautions: 'Open-water requires safety partner and conditions awareness; pool requires basic stroke competence.' },
  { id: 'stretching', name: 'Daily Stretching (10-min sequence)', mode: 'movement', duration: '10 min', difficulty: 'beginner', tradition: 'Common-sense; modern stretching synthesis', whatYouDo: 'Standard 10-minute sequence: standing forward fold (60s); calf stretch (30s/side); hip flexor (30s/side); seated spinal twist (30s/side); cat-cow (60s); child\'s pose (60s); chest opener doorway stretch (30s).', whatItDoes: 'Maintains the connective-tissue mobility that desk work erodes. The most accessible daily practice; barrier to entry near zero.', cautions: 'Never bounce; hold each stretch. Stop at edge of mild discomfort, never sharp pain.' },
  { id: 'walking-up-dunes', name: 'Sand Dune Climb (Manhattan Beach)', mode: 'movement', duration: '20-40 min', difficulty: 'intermediate', tradition: 'Corridor-specific; uses Sand Dune Park infrastructure', whatYouDo: 'Reservation-required during peak hours; free off-peak. Climb the 100ft sand dune at varied pace. The sand instability requires constant micro-balance corrections; this is the practice.', whatItDoes: 'Cardiovascular + balance + stability training in a way no flat-ground practice replicates. Pairs with corridor-cohort gatherings at the dune.', cautions: 'Knee impact from descent; ankle on uneven sand. Modify intensity; rest as needed.' },
];

export const STILLNESS_PRACTICES: Practice[] = [
  { id: 'sitting', name: 'Sitting (Marine Layer Form)', mode: 'stillness', duration: '15-30 min', difficulty: 'beginner', tradition: '/marine-layer week-1 protocol; rooted in Vipassana + Zen sitting traditions', whatYouDo: 'Sit on a cushion or chair. Spine upright but relaxed. Hands resting in lap or on knees. 4-7-8 breath for first 8 rounds, then natural breath. Notice thoughts; return attention to breath. Marine layer or candlelight as visual focus if helpful.', whatItDoes: 'Foundation of all corridor stillness practice. Cumulative benefits across weeks: stress reduction, attention regulation, baseline mood improvement, sleep quality.', cautions: 'First sits are often physically uncomfortable; this is normal. If you have back conditions, sit in a supportive chair rather than on the floor.' },
  { id: 'body-scan', name: 'Body Scan', mode: 'stillness', duration: '10-30 min', difficulty: 'beginner', tradition: 'Yoga nidra rooted; widely adapted in modern mindfulness (MBSR by Kabat-Zinn)', whatYouDo: 'Lie on your back. Slowly move attention through the body, head to toe (or toe to head). Name each region as you arrive: forehead, eyes, jaw, neck, shoulders, etc. Notice sensation without trying to change it. Release each region as you move past.', whatItDoes: 'Re-establishes interoception (sensing the internal state of the body). Excellent pre-sleep practice. Useful for chronic pain populations.', cautions: 'May surface trauma-held tension; for people with significant trauma history, work with a trauma-informed teacher rather than solo.' },
  { id: 'savasana', name: 'Savasana (Corpse Pose)', mode: 'stillness', duration: '5-20 min', difficulty: 'beginner', tradition: 'Yogic practice closing every yoga session', whatYouDo: 'Lie on your back, legs comfortably apart, arms at sides palms up, eyes closed. Body completely still. Breath natural. Mind soft and present. Often paired with audio guidance or silence.', whatItDoes: 'Allows the nervous system to integrate the preceding movement practice. Critical to yoga benefit; skipping savasana significantly reduces practice value.', cautions: 'Falling asleep is common and often fine; if you need to stay awake, sit instead.' },
  { id: 'yoga-nidra', name: 'Yoga Nidra', mode: 'stillness', duration: '30-45 min', difficulty: 'intermediate', tradition: 'Tantric yoga lineage; Satyananda Saraswati standardization 20th c.', whatYouDo: 'Lie down comfortably. Follow a recorded teacher (or live teacher) through structured stages: rotation of consciousness through body parts, breath awareness, opposite sensations (heavy/light, hot/cold), visualization, sankalpa (intention), gradual return.', whatItDoes: 'Documented benefits for stress reduction, sleep quality, recovery from trauma. One 45-minute session approximates 3 hours of regular sleep on some sleep-research metrics.', cautions: 'Quality of teacher recording matters substantially. Federation cohort can vet; AI-generated yoga nidra recordings are widely variable.' },
  { id: 'breath-counting', name: 'Breath Counting Sit', mode: 'stillness', duration: '10-30 min', difficulty: 'beginner', tradition: 'Zen breath-counting (susokukan)', whatYouDo: 'Sit comfortably. Count breaths 1 through 10. When you reach 10, return to 1. When you lose count, return to 1. The practice is the counting and the returning. Not the reaching of 10.', whatItDoes: 'Trains attention. Removes the question "how should I meditate?" by giving a single concrete task. Excellent for new sitters.', cautions: 'No injury risk. May feel boring; that\'s the practice.' },
  { id: 'walking-stillness', name: 'Stillness in Movement (Slow Walking)', mode: 'stillness', duration: '15-30 min', difficulty: 'beginner', tradition: 'Vipassana walking meditation; Zen kinhin', whatYouDo: 'Walk 20-30 feet, turn around, walk back. Move slowly enough to feel each phase of the step (lift, move, place). Hands clasped at heart center or behind back. No destination; the path is the practice.', whatItDoes: 'Bridge between sitting and ordinary walking. Useful for people who struggle with seated stillness; many find it easier to be still while moving slowly than to sit motionless.', cautions: 'Best done in private space; the practice looks unusual to outside observers and self-consciousness disrupts it.' },
  { id: 'gazing', name: 'Trataka (Candle Gazing)', mode: 'stillness', duration: '10-20 min', difficulty: 'intermediate', tradition: 'Hatha yoga shatkriya cleansing practice', whatYouDo: 'In a darkened room, place a candle at eye level approximately 2-3 feet away. Gaze at the flame without blinking until tears come. Close eyes; visualize the flame on the inner screen. When the after-image fades, open eyes and resume.', whatItDoes: 'Concentration practice; reportedly improves attention and visual-cortex processing. Subjective reports of clarity and calm.', cautions: 'Eye strain possible; do not do for extended periods. Discontinue if eye discomfort persists. Not for people with photosensitive epilepsy.' },
  { id: 'cold-plunge-stillness', name: 'Cold Exposure Stillness', mode: 'stillness', duration: '2-5 min', difficulty: 'intermediate', tradition: 'Wim Hof method popularization of Eastern European cold-water tradition; corridor frames as bath-house cold-plunge practice', whatYouDo: 'Cold shower (or cold plunge if available). Stay in cold water 2-5 minutes. Slow controlled breath; do not gasp. Notice the body\'s adaptation. Exit and dry. Allow body to warm naturally without bundling.', whatItDoes: 'Cold-stress hormesis; cardiovascular conditioning; mood elevation post-exposure (norepinephrine spike). Compounds benefit when paired with breath practice.', cautions: 'NOT safe for people with cardiovascular conditions; consult physician first. Open-water cold plunge requires safety partner and gradual conditioning. Stop if numbness or shivering becomes severe.' },
];

export const BREATH_PRACTICES: Practice[] = [
  { id: 'four-seven-eight', name: '4-7-8 Breath', mode: 'breath', duration: '90 sec - 5 min', difficulty: 'beginner', tradition: 'Pranayama; Andrew Weil popularization', whatYouDo: 'Inhale through nose for 4 counts. Hold for 7 counts. Exhale through mouth for 8 counts. One round = 19 seconds. Recommended dose: 4 rounds, 2-3 times daily. Marine Layer week-1 default.', whatItDoes: 'Activates parasympathetic nervous system rapidly. Useful before high-stress moments (difficult conversations, presentations) and as pre-sleep practice. Cumulative effect on baseline anxiety with daily practice.', cautions: 'May cause lightheadedness initially; sit or recline for first sessions. Modify counts (3-5-6) if 4-7-8 produces distress.' },
  { id: 'box', name: 'Box Breath', mode: 'breath', duration: '2-10 min', difficulty: 'beginner', tradition: 'Pranayama; military / first-responder adaptation', whatYouDo: 'Inhale 4. Hold 4. Exhale 4. Hold 4. Repeat. One "box" = 16 seconds. The held intervals are the practice; the equal ratio is the structure.', whatItDoes: 'Used by military operators and emergency responders for stress regulation in high-pressure situations. Trains the nervous system to maintain composure under load.', cautions: 'Hold-time may feel difficult initially; reduce to 3 counts if needed. Avoid if recent abdominal surgery.' },
  { id: 'alternate-nostril', name: 'Nadi Shodhana (Alternate Nostril)', mode: 'breath', duration: '5-15 min', difficulty: 'beginner', tradition: 'Pranayama, foundational hatha yoga', whatYouDo: 'Sit comfortably. Right hand: thumb closes right nostril, ring finger closes left. Inhale through left, close left, exhale right. Inhale right, close right, exhale left. That is one cycle. 7-21 cycles per session.', whatItDoes: 'Balances autonomic nervous system. Useful before sit practice; clears mental chatter. Subjective reports of mental clarity.', cautions: 'Not while congested (the closed nostril is the practice; congestion defeats it). Avoid during respiratory illness.' },
  { id: 'kapalabhati', name: 'Kapalabhati (Skull-Shining Breath)', mode: 'breath', duration: '2-5 min', difficulty: 'intermediate', tradition: 'Hatha yoga shatkriya; one of the six cleansing practices', whatYouDo: 'Sit comfortably. Sharp short exhales through the nose; passive inhales between. Each exhale is an abdominal contraction. Round of 30, then natural breath rest. 3 rounds total.', whatItDoes: 'Activating practice; energizing rather than calming. Useful morning practice or pre-sit. Stimulates abdominal core engagement.', cautions: 'NOT for pregnancy, recent abdominal surgery, hypertension, or heart conditions. Lightheadedness common initially; rest between rounds.' },
  { id: 'coherent', name: 'Coherent Breathing (5-5)', mode: 'breath', duration: '5-20 min', difficulty: 'beginner', tradition: 'Modern HRV-coherence research; Stephen Elliott / Heart Math protocols', whatYouDo: 'Breathe in for 5 seconds, out for 5 seconds. Equal ratio, no holds. Continuous. 6 breaths per minute is the target rate.', whatItDoes: 'Maximizes heart-rate variability (HRV) coherence. Documented effects on autonomic balance, mood, sleep quality. Easiest practice to combine with other tasks (walking, light stretching).', cautions: 'No risks. May feel slow; the slowness is the practice.' },
  { id: 'bhramari', name: 'Bhramari (Humming Bee Breath)', mode: 'breath', duration: '5-10 min', difficulty: 'beginner', tradition: 'Pranayama, vagus-nerve stimulating practice', whatYouDo: 'Sit comfortably. Plug ears with index fingers. Inhale through nose. Exhale through nose with a humming sound (like a bee). Vibration in the head. 6-12 rounds.', whatItDoes: 'Vagus nerve stimulation via vocal cord vibration. Documented effects on stress reduction, blood pressure modulation. Subjective reports of mental quieting.', cautions: 'No risks. Best done private since the humming is audible.' },
  { id: 'long-exhale', name: 'Extended Exhale (1:2 Ratio)', mode: 'breath', duration: '3-10 min', difficulty: 'beginner', tradition: 'Common pranayama; Iyengar lineage emphasis', whatYouDo: 'Inhale for 4 counts. Exhale for 8 counts. The exhale is twice the inhale. 10-20 rounds.', whatItDoes: 'Strong parasympathetic activation. The most reliable single technique for "calm down NOW." Used by anesthesiologists pre-procedure.', cautions: 'May cause initial feeling of breath restriction; this is normal. Reduce ratio to 1:1.5 if needed.' },
  { id: 'natural-breath', name: 'Natural Breath Awareness', mode: 'breath', duration: '5-30 min', difficulty: 'beginner', tradition: 'Vipassana foundational practice (anapanasati)', whatYouDo: 'Do not change the breath. Just notice it. Where do you feel it most clearly — nostrils, chest, belly? Stay with that location. When attention drifts, return.', whatItDoes: 'Foundation of vipassana practice. Trains attention without manipulating physiology. The practice is the noticing, not the breath itself.', cautions: 'May seem boring or pointless initially; the seeming-pointlessness is the practice.' },
];

export const ACUPRESSURE_PROTOCOLS = [
  { code: 'LI-4 (Hegu)', when: 'general stress, headaches, tension', how: 'Squeeze the fleshy mound between thumb and index finger of one hand using the thumb and index finger of the other hand. Firm pressure, not painful. 60-90 seconds each side.', tradition: 'TCM; the most-used self-acupressure point' },
  { code: 'PC-6 (Neiguan)', when: 'nausea (motion sickness, pregnancy, post-meal), anxiety, heart palpitations', how: 'Three finger-widths above the inner wrist crease, between the two tendons. Press firmly with thumb. 60-90 seconds each arm. Sea-Bands wrist bracelets target this point.', tradition: 'TCM; the most clinically-validated acupressure point' },
  { code: 'GB-20 (Fengchi)', when: 'tension headaches, neck stiffness, eye fatigue', how: 'At the base of the skull, in the hollow between the trapezius and sternocleidomastoid muscles (where the head meets the neck). Press with thumbs upward and inward. 60-90 seconds.', tradition: 'TCM; foundational tension-headache point' },
  { code: 'LV-3 (Taichong)', when: 'irritability, stress, tension, eye strain', how: 'On top of the foot, in the depression between the first and second metatarsal bones (between big toe and second toe, about 2 finger-widths back from the webbing). Firm pressure with thumb. 60-90 seconds each foot.', tradition: 'TCM; partners with LI-4 as the "Four Gates" general stress combination' },
  { code: 'KI-1 (Yongquan)', when: 'grounding, sleep, anxiety, feet-cold', how: 'On the sole of the foot, in the depression at the front (when toes curl, the depression appears). Press firmly with thumb or use a ball/foot-roller. 60-90 seconds each foot. Excellent pre-sleep practice.', tradition: 'TCM; the only acupuncture point on the sole of the foot' },
  { code: 'GV-20 (Baihui)', when: 'mental clarity, headaches, fatigue', how: 'On the crown of the head (the highest point). Light pressure with fingertips, or simply hand cupped over the crown. 30-60 seconds.', tradition: 'TCM; the meeting of yang energies' },
  { code: 'CV-17 (Shanzhong)', when: 'chest tightness, anxiety, grief, breath restriction', how: 'On the midline of the chest, at approximately the level of the fourth intercostal space (about 4 finger-widths below the collarbone notch). Firm circular pressure. 60-90 seconds.', tradition: 'TCM; the "Sea of Qi" point' },
  { code: 'ST-36 (Zusanli)', when: 'fatigue, digestive issues, low energy, immune support', how: 'Four finger-widths below the kneecap, lateral to the shinbone (one finger-width to the outside of the bone). Firm pressure. 60-90 seconds each leg. Daily practice classically said to give "the energy to walk three more miles."', tradition: 'TCM; foundational tonifying point' },
  { code: 'SP-6 (Sanyinjiao)', when: 'gynecological conditions, sleep, anxiety, digestive issues', how: 'Four finger-widths above the inner ankle bone, just behind the shinbone. Firm pressure. 60-90 seconds each leg.', tradition: 'TCM; intersection of three yin meridians', },
  { code: 'BL-23 (Shenshu)', when: 'lower back pain, fatigue, kidney support', how: 'Lower back, two finger-widths lateral to the spine at the level of L2 (just above the iliac crest). Press inward and upward; partner work easier than self-work. 60-90 seconds.', tradition: 'TCM; foundational kidney-tonification point' },
];

export const EIGHT_WEEK_BEGINNER_LADDER = [
  { week: 1, theme: 'Walking attention', practice: '20-minute walk daily, no earbuds. Notice footfall, breath, surroundings. The whole practice for week 1.' },
  { week: 2, theme: 'Add breath', practice: 'Continue walking. Add 4-7-8 breath × 4 rounds, twice daily (morning + pre-sleep). 90 seconds each session.' },
  { week: 3, theme: 'Add stillness', practice: 'Continue walking + breath. Add 10-minute sit, 5 days/week. Marine Layer protocol: 4-7-8 for 8 rounds, then natural breath.' },
  { week: 4, theme: 'Add stretching', practice: 'Continue prior. Add 10-minute morning stretching sequence, 5 days/week. Standing forward fold, calf stretch, hip flexor, spinal twist, cat-cow, child\'s pose, doorway chest opener.' },
  { week: 5, theme: 'Add acupressure', practice: 'Continue prior. Add daily LI-4 (60 sec each hand) and LV-3 (60 sec each foot). Total addition: 4 minutes/day.' },
  { week: 6, theme: 'Extend stillness', practice: 'Continue prior. Sit increases from 10 to 15 minutes. Add a body scan before sleep, 5 minutes.' },
  { week: 7, theme: 'Cohort engagement', practice: 'Continue prior. Add one cohort gathering this week — Marine Layer sit, qi gong class, yoga class, Living Body Open Hours. Choose what fits your schedule.' },
  { week: 8, theme: 'Synthesize and choose', practice: 'Continue prior. Write a 200-word reflection: which practices to keep, which to release, which cohort form to commit to next quarter. The first 8 weeks are the practice menu; from here, you choose.' },
];

export const COHORT_OFFERINGS_EXTENDED = [
  { offering: 'Daily Walking Cohort (rolling)', format: 'Tuesday + Thursday + Saturday, 6:30am, Strand at 30th Street MB / Hermosa Pier alternate days. Walk 45 minutes, return for coffee. No fee. Drop-in.', whoLeads: 'Rotating volunteer cohort members; no formal teacher required.' },
  { offering: 'Marine Layer 8-week Sit Cohort', format: 'Per /marine-layer; 8-week place-based sit cycle. Sundays 6am at host city anchor. Cap 12. Fee: $40 per 8-week cycle (sliding scale).', whoLeads: 'Trained Marine Layer Layer (rotating; principal cohort member with prior cycle completion).' },
  { offering: 'Qi Gong Foundations (4-week intro)', format: 'Tuesdays 7am, 4 weeks. Eight Brocades sequence. Cap 12. Fee: federation cohort rate $80 per 4-week cycle.', whoLeads: 'Vetted qi gong teacher (corridor practitioner network).' },
  { offering: 'Tai Chi Year-One (44-week cohort)', format: 'Saturdays 9am, year-long. Yang-style short form. Cap 12. Fee: federation cohort rate $400 per year (vs ~$1,200 commercial equivalent).', whoLeads: 'Vetted tai chi teacher; year-long commitment to one teacher critical.' },
  { offering: 'Yoga Asana Drop-in (weekly)', format: 'Wednesdays 6:30pm, ongoing. Slow vinyasa or yin alternation. Cap 16. Fee: $15 drop-in / $50 monthly unlimited.', whoLeads: 'Vetted 500+ hour Yoga Alliance teacher.' },
  { offering: 'Acupressure Circle (monthly)', format: 'Second Saturday of each month, 90 min. Self + partner acupressure across 10 foundational points. No fee for cohort members; $20 visitors.', whoLeads: 'Vetted licensed acupuncturist (LAc).' },
  { offering: 'Breath Lab (4-week intro)', format: 'Thursdays 7pm, 4 weeks. Survey of 8 breath practices documented above. Cap 12. Fee: $80 per 4-week cycle.', whoLeads: 'Vetted teacher with pranayama-specific training.' },
  { offering: 'Yoga Nidra Drop-in (bi-weekly)', format: 'First and third Sundays 4pm, 60 min. Recorded session with held space. Cap 20. Fee: free for cohort; $15 visitors.', whoLeads: 'Yoga teacher or vetted recording.' },
  { offering: 'Living Body Open Hours (monthly)', format: 'Per /living-body; first Saturday of each month, 9am-12pm. All-traditions conversation + demonstration + peer learning. Free for cohort; $20 visitors.', whoLeads: 'Rotating among practitioner network members.' },
  { offering: 'Court Craft / Honey League pickleball (ongoing)', format: 'Per existing corridor pickleball cohort. Federation framing of pickleball as movement-attention practice rather than sport-only.', whoLeads: 'Existing pickleball cohort leadership.' },
];

export const TEACHER_REFERENCES = {
  description: 'Vetted practitioners across the corridor for the practice modes documented above. The federation does not take referral fees and is not a medical authority. The list is a starting point; cohort members are encouraged to interview teachers before committing.',
  vettingCriteria: [
    'Acupuncturists: California LAc with NCCAOM certification, minimum 5 years clinical practice, comfort with skeptical first-time patients, refers to Western medicine when appropriate.',
    'Yoga teachers: 500+ hour Yoga Alliance certification or equivalent traditional lineage credential, demonstrated teaching depth (not all 200-hour teachers have this), commitment to honest framing.',
    'Qi gong / tai chi teachers: minimum 10 years personal practice, minimum 5 years teaching experience, willingness to start beginners gently.',
    'Pranayama teachers: yoga-teacher background with pranayama-specific training (the Iyengar tradition is particularly rigorous on breath instruction).',
    'TCM practitioners: California LAc + dedicated TCM herbal-medicine training (DACM, DAOM, or equivalent).',
  ],
  howToFindOne: [
    'Federation referral: email mh@pointcast.xyz with the practice mode you are interested in. Federation will share network practitioners with capacity.',
    'NCCAOM directory (acupuncturists): nccaom.org/find-a-practitioner.',
    'Yoga Alliance directory (yoga teachers): yogaalliance.org/Directory.',
    'Local recommendation: Marine Layer cohort, Living Body Open Hours, federation council members are good first sources.',
    'Avoid: anonymous online reviews; certificate-mill teachers (200-hour Yoga Alliance certification alone is insufficient for most practice modes); celebrity teachers without lineage citation.',
  ],
};

export const REFERENCES = [
  { id: 'pointcast-living-body', cite: 'University of El Segundo. (2026). *The Living Body*. UES-WP-2026-18. https://pointcast.xyz/living-body. (Parent paper.)' },
  { id: 'pointcast-marine', cite: 'University of El Segundo. (2026). *Marine Layer*. UES-WP-2026-01. https://pointcast.xyz/marine-layer.' },
  { id: 'pointcast-time', cite: 'University of El Segundo. (2026). *Time*. UES-WP-2026-16. https://pointcast.xyz/time.' },
  { id: 'pointcast-bath', cite: 'University of El Segundo. (2026). *The Bath House*. UES-WP-2026-14. https://pointcast.xyz/bath-house.' },
  { id: 'pointcast-sabbatical', cite: 'University of El Segundo. (2026). *Sabbatical Infrastructure*. UES-Federation-07. https://pointcast.xyz/sabbatical.' },
  { id: 'kabat-zinn', cite: 'Kabat-Zinn, J. (1990). *Full Catastrophe Living: Using the Wisdom of Your Body and Mind to Face Stress, Pain, and Illness*. Delta. The MBSR foundational text; body-scan and sit instruction.' },
  { id: 'iyengar', cite: 'Iyengar, B. K. S. (1966). *Light on Yoga*. Schocken Books. The foremost reference on alignment-precise yoga asana.' },
  { id: 'iyengar-pranayama', cite: 'Iyengar, B. K. S. (1981). *Light on Pranayama*. Crossroad Publishing. The foremost reference on pranayama practice.' },
  { id: 'cohen-tai-chi', cite: 'Cohen, K. S. (1997). *The Way of Qigong: The Art and Science of Chinese Energy Healing*. Ballantine Books. Comprehensive accessible qi gong reference.' },
  { id: 'cheng', cite: 'Cheng, Man-ch\'ing. (1981). *Cheng Tzu\'s Thirteen Treatises on T\'ai Chi Ch\'uan*. Blue Snake Books. The 37-posture short-form lineage reference.' },
  { id: 'satyananda-nidra', cite: 'Satyananda Saraswati. (1976). *Yoga Nidra*. Bihar School of Yoga. The standardization of modern yoga nidra practice.' },
  { id: 'feuerstein', cite: 'Feuerstein, G. (2008, 3rd ed.). *The Yoga Tradition: Its History, Literature, Philosophy and Practice*. Hohm Press.' },
  { id: 'wong-tcm', cite: 'Wong, K. K. (1996). *The Complete Book of Chinese Medicine*. Cosmos. Accessible TCM theory reference.' },
  { id: 'maciocia', cite: 'Maciocia, G. (1989, 3rd ed. 2015). *The Foundations of Chinese Medicine*. Elsevier. Foremost English-language clinical reference.' },
  { id: 'nccam-tai-chi', cite: 'National Center for Complementary and Integrative Health. (2016). *Tai Chi: In Depth*. NIH NCCIH systematic review. nccih.nih.gov/health/tai-chi.' },
  { id: 'wayne-tai-chi-balance', cite: 'Wayne, P. M., et al. (2014). *Effect of tai chi on cognitive performance in older adults: systematic review and meta-analysis*. Journal of the American Geriatrics Society, 62(1), 25-39.' },
  { id: 'porges', cite: 'Porges, S. W. (2011). *The Polyvagal Theory*. W.W. Norton. Theoretical foundation for breath-vagal-tone practice claims.' },
  { id: 'craig', cite: 'Craig, A. D. (2003). *Interoception: the sense of the physiological condition of the body*. Current Opinion in Neurobiology, 13(4), 500-505.' },
  { id: 'weil-breath', cite: 'Weil, A. (1995-Continuing). *4-7-8 Breathing Technique*. drweil.com/breathing. The popularization of the practice.' },
];

export const PAPER_NOTES = {
  uesNote: 'V2 of /living-body. The first paper documents traditions; this paper documents practices. Cohort members can use either or both; the relationship is complementary not sequential. Federation cohort offerings extend across both papers.',
  invitation: 'If you are a vetted practitioner interested in joining the federation network (acupuncturist, yoga teacher, qi gong/tai chi instructor, pranayama teacher, TCM practitioner) or a cohort member ready to begin the 8-week beginner ladder, email mh@pointcast.xyz with subject line "Practice · {role}". Cohort offerings are scheduled per /commons calendar; first cycles begin autumnal-equinox 2026 quarter regardless of federation council formation.',
  closingNote: 'Practice is small. Practice is daily. Practice is embodied. Practice is held by cohort. Practice is older than every contemporary therapeutic system, refined by hundreds of millions of practitioners across thousands of years. The corridor\'s contribution is not innovation; it is access. We make the practice forms available, the cohort form available, the teacher network available — at federation rates, in corridor places, with the discipline of weekly continuity. Begin with one walk before commerce wakes tomorrow morning. The rest unfolds from there.',
};
