import {shuffledPieces,placement,piecePosition,PIECES} from './puzzle-state.mjs';
export function setupPuzzleWorld(){
  const filter=document.querySelector<HTMLFormElement>('#p-filter');
  if(filter && !filter.dataset.ready){
    filter.dataset.ready='true';filter.addEventListener('submit',e=>e.preventDefault());
    const apply=()=>{const category=(document.querySelector('#p-category') as HTMLSelectElement).value;const count=(document.querySelector('#p-count') as HTMLSelectElement).value;let visible=0;document.querySelectorAll<HTMLElement>('[data-concept]').forEach(card=>{const pieces=Number(card.dataset.pieces);const match=(category==='all'||card.dataset.category===category)&&(count==='all'||(count==='gentle'&&pieces<=500)||(count==='middle'&&pieces>=750&&pieces<=1000)||(count==='advanced'&&pieces===1500));card.hidden=!match;if(match)visible++;});document.querySelector('#p-filter-status')!.textContent=`${visible} ${visible===1?'concept':'concepts'}`;};
    filter.addEventListener('change',apply);filter.addEventListener('reset',()=>setTimeout(apply,0));
  }
  const demo=document.querySelector<HTMLElement>('#p-demo');if(!demo||demo.dataset.ready)return;demo.dataset.ready='true';
  const tray=demo.querySelector<HTMLElement>('#p-tray')!;const board=demo.querySelector<HTMLElement>('#p-board')!;const status=demo.querySelector<HTMLElement>('#p-demo-status')!;const hints=demo.querySelector<HTMLInputElement>('#p-piece-hints')!;const reset=demo.querySelector<HTMLButtonElement>('#p-reset')!;const guideButton=demo.querySelector<HTMLButtonElement>('#p-show-guide')!;const guide=demo.querySelector<HTMLElement>('#p-guide')!;
  let selected:number|null=null;let placed:number[]=[];let order:number[]=[];
  const picture='/images/puzzles/01-tidepool-atlas.webp';
  const label=(id:number)=>{const p=piecePosition(id);return hints.checked?`Piece ${order.indexOf(id)+1}; target row ${p.row}, column ${p.column}`:`Piece ${order.indexOf(id)+1}`;};
  const paint=(button:HTMLButtonElement,id:number)=>{const p=piecePosition(id);button.style.backgroundImage=`url('${picture}')`;button.style.backgroundPosition=`${p.x}% ${p.y}%`;};
  const updateLabels=()=>{tray.querySelectorAll<HTMLButtonElement>('button').forEach(b=>{const id=Number(b.dataset.piece);b.setAttribute('aria-label',label(id));const p=piecePosition(id);b.querySelector('span')!.textContent=hints.checked?`${order.indexOf(id)+1} · R${p.row} C${p.column}`:String(order.indexOf(id)+1);});};
  const start=()=>{selected=null;placed=[];order=shuffledPieces();tray.replaceChildren();board.replaceChildren();
    for(let i=0;i<PIECES;i++){const slot=document.createElement('button');slot.type='button';slot.className='p-slot';slot.dataset.slot=String(i);const p=piecePosition(i);slot.setAttribute('aria-label',`Empty space, row ${p.row}, column ${p.column}`);const text=document.createElement('span');text.textContent=`R${p.row} C${p.column}`;slot.append(text);slot.addEventListener('click',()=>{if(selected===null){status.textContent='Choose an available piece first.';return;}const result=placement(placed,selected,i);if(!result.ok){status.textContent='That piece belongs somewhere else. Try another space, or turn on row and column hints.';return;}placed=result.state;slot.classList.add('filled');paint(slot,i);slot.disabled=true;slot.setAttribute('aria-label',`Filled space, row ${p.row}, column ${p.column}`);slot.querySelector('span')!.textContent='✓';const used=tray.querySelector<HTMLButtonElement>(`[data-piece="${selected}"]`)!;used.disabled=true;used.setAttribute('aria-pressed','false');selected=null;status.textContent=placed.length===PIECES?'Complete. You made a little coast. Start again whenever you like.':`${placed.length} of ${PIECES} pieces placed. Choose another piece.`;const next=tray.querySelector<HTMLButtonElement>('button:not(:disabled)');(next||reset).focus();});board.append(slot);}
    order.forEach(id=>{const piece=document.createElement('button');piece.type='button';piece.className='p-piece';piece.dataset.piece=String(id);piece.setAttribute('aria-pressed','false');paint(piece,id);piece.append(document.createElement('span'));piece.addEventListener('click',()=>{selected=id;tray.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b===piece?'true':'false'));status.textContent=`${label(id)} selected. Choose a board space.`;board.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();});tray.append(piece);});updateLabels();status.textContent='0 of 12 pieces placed. Choose a piece to begin.';
  };
  hints.addEventListener('change',updateLabels);reset.disabled=false;reset.addEventListener('click',start);guideButton.addEventListener('click',()=>{guide.hidden=!guide.hidden;guideButton.setAttribute('aria-expanded',String(!guide.hidden));guideButton.textContent=guide.hidden?'Show picture guide':'Hide picture guide';});start();
}
