export type EngineeringLayer = 'architecture' | 'matter' | 'signal' | 'field' | 'proof' | 'operations';

export const ENGINEERING_CATALOG = {
  id: 'PC-BEACH-COMMONS-V18-ENGINEERING',
  title: 'ENG/25',
  subtitle: 'The Engineering Catalog',
  dek: 'A command-line field guide to the engineering capabilities, proof habits, qualification gates, and public learning doors inside the El Segundo-centered Radius 25.',
  url: 'https://pointcast.xyz/beach-commons/v18/engineering',
  jsonUrl: 'https://pointcast.xyz/beach-commons/v18/engineering.json',
  blockUrl: 'https://pointcast.xyz/b/0551',
  fieldStudy: '018.B',
  publishedAt: '2026-08-01',
  updatedAt: '2026-08-01T01:45:00-07:00',
  center: 'El Segundo, California',
  radius: 'roughly 25 straight-line miles',
  status: 'Independent editorial capability index and browser-local planning instrument. It is not a directory of people, firms, available facilities, jobs, procurement opportunities, qualified professionals, or approved work.',
} as const;

export const ENGINEERING_LAYERS = [
  { id: 'architecture', code: 'ARCH', title: 'Architecture', description: 'Frame the mission, requirements, interfaces, decisions, and configuration.' },
  { id: 'matter', code: 'MAT', title: 'Matter', description: 'Shape structures, mechanisms, materials, heat, fluids, and production.' },
  { id: 'signal', code: 'SIG', title: 'Signal', description: 'Power, sense, communicate, compute, control, and fail safely.' },
  { id: 'field', code: 'FLD', title: 'Field', description: 'Work with sites, water, coasts, infrastructure, chemistry, and living conditions.' },
  { id: 'proof', code: 'PRF', title: 'Proof', description: 'Measure, inspect, test, verify, validate, and name uncertainty.' },
  { id: 'operations', code: 'OPS', title: 'Operations', description: 'Move, commission, maintain, repair, retire, and return.' },
] as const;

export const ENGINEERING_CAPABILITIES = [
  {
    id: 'systems', code: 'SYS.ARCH', layer: 'architecture', title: 'Systems architecture + interfaces',
    summary: 'Turn a broad mission into requirements, interfaces, states, budgets, decisions, and a configuration everyone can inspect.',
    usefulWhen: ['more than one discipline must finish together', 'a change in one part can break another', 'the project needs a clear stop rule'],
    inputs: ['mission and users', 'operating environment', 'constraints and unknowns'],
    outputs: ['requirements tree', 'interface control sheet', 'state and failure map'],
    proof: ['every requirement has an owner and verification method', 'interfaces are versioned', 'unknowns and rejected assumptions remain visible'],
    tools: ['SysML or diagrams', 'requirements table', 'decision log', 'configuration baseline'],
    interfaces: ['all disciplines'],
    flags: ['qualified review may still be required by the discipline that signs the final work'],
    keywords: ['requirements mission interface architecture configuration traceability integration system-of-systems'],
  },
  {
    id: 'mechanical', code: 'MEC.DES', layer: 'matter', title: 'Mechanical design + mechanisms',
    summary: 'Design moving, fastening, folding, carrying, sealing, latching, and serviceable physical assemblies.',
    usefulWhen: ['something moves or bears repeated use', 'parts must assemble by hand', 'repair access matters'],
    inputs: ['loads and motion', 'users and tools', 'materials and environment'],
    outputs: ['drawings and tolerances', 'assembly sequence', 'service and spare-parts plan'],
    proof: ['fit check', 'cycle test', 'tool-access review'],
    tools: ['CAD', 'GD&T', 'kinematics', 'prototype fixtures'],
    interfaces: ['structures', 'materials', 'manufacturing', 'maintenance'],
    flags: ['California mechanical engineering practice may require an appropriately licensed professional'],
    keywords: ['mechanism hinge latch cart folding fastener seal enclosure assembly tolerance repair'],
  },
  {
    id: 'structures', code: 'STR.LOAD', layer: 'matter', title: 'Structures + loads',
    summary: 'Make gravity, wind, impact, fatigue, anchorage, stability, and load paths explicit before a structure meets people.',
    usefulWhen: ['people stand under, on, or beside it', 'wind or moving loads matter', 'failure could injure someone'],
    inputs: ['geometry', 'materials', 'load cases and combinations'],
    outputs: ['load path', 'analysis assumptions', 'details and inspection points'],
    proof: ['independent calculation check', 'controlled load test when appropriate', 'documented wind and stop limits'],
    tools: ['hand calculations', 'FEA', 'codes and standards', 'test instrumentation'],
    interfaces: ['civil-site', 'materials', 'safety', 'manufacturing'],
    flags: ['public structural work may require licensed civil or structural engineering, permits, and inspection'],
    keywords: ['structure load wind anchorage frame foundation fatigue impact stability shade shelter'],
  },
  {
    id: 'materials', code: 'MAT.SALT', layer: 'matter', title: 'Materials + corrosion',
    summary: 'Select and join materials for salt, sun, abrasion, fire behavior, cleaning, reuse, and an honest end of life.',
    usefulWhen: ['the environment attacks the object', 'dissimilar materials meet', 'surface treatment drives service life'],
    inputs: ['exposure profile', 'joining method', 'maintenance interval'],
    outputs: ['material and finish schedule', 'compatibility map', 'coupon-test plan'],
    proof: ['traceable material callout', 'exposure coupons', 'inspection and replacement threshold'],
    tools: ['material databases', 'microscopy', 'coating tests', 'failure analysis'],
    interfaces: ['mechanical', 'structures', 'manufacturing', 'coastal-water'],
    flags: ['hazardous coatings, composites, batteries, and treated materials need appropriate handling and disposal'],
    keywords: ['salt air corrosion coating galvanic stainless aluminum polymer textile UV abrasion fire composite'],
  },
  {
    id: 'thermal-fluids', code: 'THR.FLD', layer: 'matter', title: 'Thermal + fluid systems',
    summary: 'Model and test heat, airflow, pumps, piping, pressure, cooling, ventilation, and fluid handling.',
    usefulWhen: ['temperature or flow changes performance', 'pressure stores energy', 'comfort and ventilation are design inputs'],
    inputs: ['heat and flow budgets', 'fluid properties', 'boundary conditions'],
    outputs: ['flow schematic', 'thermal model', 'pressure and relief plan'],
    proof: ['instrumented temperature and flow test', 'leak and pressure test', 'relief and shutdown verification'],
    tools: ['CFD', 'thermal imaging', 'flow and pressure meters', 'psychrometrics'],
    interfaces: ['mechanical', 'power', 'process', 'safety'],
    flags: ['pressurized, fueled, refrigerated, or occupied systems require applicable codes and qualified review'],
    keywords: ['heat thermal fluid airflow ventilation pump pressure cooling HVAC shade comfort'],
  },
  {
    id: 'power', code: 'ELE.PWR', layer: 'signal', title: 'Electrical power + energy',
    summary: 'Budget, distribute, protect, isolate, charge, ground, and monitor electrical energy from source to load.',
    usefulWhen: ['a battery or solar source enters the system', 'fault energy can harm people or equipment', 'runtime must be known'],
    inputs: ['load profile', 'source limits', 'environment and duty cycle'],
    outputs: ['one-line diagram', 'power budget', 'protection and isolation plan'],
    proof: ['measured load and runtime', 'fault protection test', 'labeling and safe shutdown'],
    tools: ['circuit analysis', 'multimeters and scopes', 'battery testers', 'power-quality logging'],
    interfaces: ['embedded', 'RF', 'controls', 'safety'],
    flags: ['building or public electrical work may require licensed electrical engineering and electrical contracting'],
    keywords: ['electrical power energy battery solar charging grounding protection runtime inverter'],
  },
  {
    id: 'embedded', code: 'EMB.SNS', layer: 'signal', title: 'Embedded systems + instrumentation',
    summary: 'Connect sensors, actuators, microcontrollers, timing, calibration, logging, and physical controls.',
    usefulWhen: ['the physical world needs to be measured', 'a small controller must respond locally', 'the proof needs time-stamped data'],
    inputs: ['measurand and range', 'sample rate', 'power and environment'],
    outputs: ['sensor chain', 'firmware behavior', 'calibration and data schema'],
    proof: ['known reference comparison', 'fault injection', 'raw-data export with units'],
    tools: ['microcontrollers', 'DAQ', 'oscilloscopes', 'calibration fixtures'],
    interfaces: ['power', 'RF', 'controls', 'test-reliability'],
    flags: ['measurement is not certification; safety-critical sensing needs qualified architecture and verification'],
    keywords: ['sensor instrument microcontroller firmware data logger actuator calibration weather sound wave'],
  },
  {
    id: 'rf', code: 'RF.COMM', layer: 'signal', title: 'RF + communications',
    summary: 'Plan antennas, links, spectrum, interference, telemetry, networking, and graceful loss of communication.',
    usefulWhen: ['information must cross space without a wire', 'multiple radios share an environment', 'range and interference matter'],
    inputs: ['frequency and bandwidth', 'link geometry', 'regulatory and coexistence limits'],
    outputs: ['link budget', 'antenna and network plan', 'loss-of-link behavior'],
    proof: ['measured coverage', 'interference scan', 'fallback operation without the link'],
    tools: ['spectrum analyzer', 'VNA', 'link simulation', 'network test tools'],
    interfaces: ['power', 'embedded', 'controls', 'systems'],
    flags: ['RF devices and experiments may require FCC authorization, licensed spectrum, or compliant equipment'],
    keywords: ['radio RF wireless antenna network telemetry spectrum interference link wifi lora bluetooth'],
  },
  {
    id: 'controls', code: 'CTL.SW', layer: 'signal', title: 'Software + controls + autonomy',
    summary: 'Define observable state, control loops, algorithms, interfaces, cybersecurity boundaries, and safe degraded behavior.',
    usefulWhen: ['software changes physical behavior', 'automation must remain understandable', 'the system needs simulation before field use'],
    inputs: ['state model', 'sensor and actuator limits', 'human authority and hazard analysis'],
    outputs: ['control logic', 'simulation and test harness', 'fallback and update plan'],
    proof: ['repeatable test vectors', 'hardware-in-the-loop or bounded simulation', 'manual override and failure recovery'],
    tools: ['version control', 'simulation', 'HIL', 'static analysis', 'threat modeling'],
    interfaces: ['systems', 'embedded', 'RF', 'safety'],
    flags: ['no autonomous system should make an unreviewed safety, access, employment, or environmental decision'],
    keywords: ['software control autonomy robotics algorithm simulation cybersecurity digital twin human override'],
  },
  {
    id: 'manufacturing', code: 'MFG.TOOL', layer: 'matter', title: 'Manufacturing + tooling',
    summary: 'Convert design intent into repeatable parts, fixtures, processes, work instructions, and an inspectable small run.',
    usefulWhen: ['one prototype must become twelve', 'variation matters', 'assembly time or yield is unknown'],
    inputs: ['released drawing', 'material and process', 'quantity and acceptance criteria'],
    outputs: ['process plan', 'tooling and fixtures', 'work instructions and traveler'],
    proof: ['first-article inspection', 'repeatability across the run', 'scrap and rework record'],
    tools: ['CNC', 'welding', 'additive manufacturing', 'forming', 'CAM'],
    interfaces: ['mechanical', 'materials', 'quality-metrology', 'industrial-logistics'],
    flags: ['machine, welding, hot-work, lifting, and chemical processes require trained operators and safe facilities'],
    keywords: ['manufacturing CNC machining welding additive 3d print fixture tooling production assembly small run'],
  },
  {
    id: 'quality-metrology', code: 'QLT.MET', layer: 'proof', title: 'Quality + metrology',
    summary: 'Define what conforms, how it is measured, what uncertainty remains, and how nonconforming work is controlled.',
    usefulWhen: ['dimensions or performance must repeat', 'a supplier claim needs verification', 'measurement affects acceptance'],
    inputs: ['critical characteristics', 'tolerance and risk', 'measurement method'],
    outputs: ['inspection plan', 'measurement-system analysis', 'nonconformance and disposition record'],
    proof: ['calibrated equipment', 'traceable result with uncertainty', 'repeat and reproduce check'],
    tools: ['CMM', 'gages', 'calibration standards', 'statistical process control'],
    interfaces: ['manufacturing', 'test-reliability', 'materials', 'systems'],
    flags: ['a precise number is not automatically an accurate or appropriate acceptance criterion'],
    keywords: ['quality metrology tolerance inspection calibration CMM gauge uncertainty acceptance traceability'],
  },
  {
    id: 'test-reliability', code: 'TST.REL', layer: 'proof', title: 'Test + reliability',
    summary: 'Turn requirements and likely failures into controlled tests, evidence, limits, maintenance intervals, and learning.',
    usefulWhen: ['failure matters', 'the object repeats a cycle', 'weather and misuse should be represented'],
    inputs: ['requirements', 'failure modes', 'use and exposure profile'],
    outputs: ['verification matrix', 'test procedure', 'failure and corrective-action report'],
    proof: ['calibrated setup and raw data', 'predeclared pass/fail criteria', 'documented anomaly and retest logic'],
    tools: ['FMEA', 'DOE', 'environmental test', 'cycle rigs', 'root-cause analysis'],
    interfaces: ['all disciplines'],
    flags: ['tests must not expose participants, habitat, bystanders, or facilities to unreviewed hazards'],
    keywords: ['test reliability verification validation FMEA failure fatigue weather cycle proof evidence'],
  },
  {
    id: 'civil-site', code: 'CIV.SITE', layer: 'field', title: 'Civil + site + geotechnical',
    summary: 'Understand land, drainage, access, utilities, pavement, soil, surveying, construction sequence, and public interfaces.',
    usefulWhen: ['work touches ground or public passage', 'drainage and utilities matter', 'temporary use can still create site risk'],
    inputs: ['survey and records', 'soil and water conditions', 'codes, ownership, and access'],
    outputs: ['site and drainage plan', 'utility and access map', 'construction and restoration sequence'],
    proof: ['field verification by authorized people', 'code and permit matrix', 'restored site and closeout record'],
    tools: ['surveying', 'GIS', 'hydrology', 'geotechnical investigation', 'BIM'],
    interfaces: ['structures', 'coastal-water', 'safety', 'industrial-logistics'],
    flags: ['California civil engineering and surveying are regulated practices; site access and permits precede field work'],
    keywords: ['civil site geotechnical survey soil drainage utility pavement access foundation permit'],
  },
  {
    id: 'coastal-water', code: 'ENV.WTR', layer: 'field', title: 'Water + coastal + environmental',
    summary: 'Work with water quality, hydrology, waves, sediment, habitat, wastewater, monitoring, and environmental review.',
    usefulWhen: ['water or shoreline conditions drive the question', 'a discharge or sample is involved', 'habitat can be affected'],
    inputs: ['site jurisdiction', 'baseline conditions', 'sampling or model purpose'],
    outputs: ['monitoring plan', 'hydrology or coastal model', 'impact and avoidance matrix'],
    proof: ['approved method and chain of custody', 'quality-controlled data', 'avoidance, restoration, and reporting record'],
    tools: ['water sensors', 'sampling protocols', 'GIS', 'hydrodynamic models', 'environmental review'],
    interfaces: ['civil-site', 'materials', 'process', 'test-reliability'],
    flags: ['no collection, release, restoration, wildlife handling, or shoreline activity without the responsible authority and permits'],
    keywords: ['water coastal ocean marine wave wastewater stormwater habitat environmental sampling hydrology sediment'],
  },
  {
    id: 'process', code: 'CHM.PROC', layer: 'field', title: 'Chemical + process systems',
    summary: 'Define materials, reactions, mass balance, process conditions, containment, controls, and safe handling.',
    usefulWhen: ['chemistry changes matter', 'mixing, fermentation, treatment, fuel, or cleaning is involved', 'a process must scale safely'],
    inputs: ['material properties and SDS', 'process flow and conditions', 'hazards and waste path'],
    outputs: ['process flow diagram', 'mass and energy balance', 'containment and control plan'],
    proof: ['characterized inputs and outputs', 'controlled batch record', 'hazard and waste verification'],
    tools: ['process simulation', 'analytical chemistry', 'reactor and separation equipment', 'process controls'],
    interfaces: ['thermal-fluids', 'materials', 'embedded', 'safety'],
    flags: ['food, fuel, biological, hazardous, pressurized, and waste processes have distinct regulatory and facility requirements'],
    keywords: ['chemical process reaction treatment fermentation fuel cleaning batch mass balance containment biotech'],
  },
  {
    id: 'industrial-logistics', code: 'IND.FLOW', layer: 'operations', title: 'Industrial engineering + logistics',
    summary: 'Design flow, work cells, inventory, custody, ergonomics, routing, capacity, and reliable return.',
    usefulWhen: ['many handoffs create failure', 'equipment must arrive and leave intact', 'time, labor, and capacity shape the result'],
    inputs: ['demand and route', 'resources and constraints', 'handoff and return conditions'],
    outputs: ['process map', 'capacity and queue model', 'custody and return standard'],
    proof: ['timed real route', 'handoff error and damage record', 'complete inventory return'],
    tools: ['value-stream maps', 'simulation', 'barcodes and manifests', 'ergonomic analysis'],
    interfaces: ['manufacturing', 'systems', 'safety', 'commission-maintain'],
    flags: ['secure, airside, port, hazardous-material, and regulated transport operations are out of scope without authorization'],
    keywords: ['industrial logistics operations handoff route inventory case custody supply chain queue ergonomics'],
  },
  {
    id: 'safety-human', code: 'HFE.SAFE', layer: 'proof', title: 'Safety + human factors + accessibility',
    summary: 'Design controls, information, reach, force, error recovery, access, and stop conditions around real bodies and real authority.',
    usefulWhen: ['people can be hurt, excluded, confused, or overburdened', 'training is part of the control', 'a public interface must work under stress'],
    inputs: ['users and access needs', 'hazards and tasks', 'environment and emergency context'],
    outputs: ['hazard analysis', 'accessible task and interface review', 'controls and emergency plan'],
    proof: ['representative usability test with consent', 'verified stop and recovery', 'access findings resolved or openly logged'],
    tools: ['task analysis', 'hazard analysis', 'ergonomic tools', 'accessibility standards'],
    interfaces: ['all disciplines'],
    flags: ['Cal/OSHA distinguishes trained, competent, qualified, and when required licensed people; labels are not substitutes for those duties'],
    keywords: ['safety human factors accessibility ADA ergonomics hazard stop emergency training usability public'],
  },
  {
    id: 'commission-maintain', code: 'OPS.KEEP', layer: 'operations', title: 'Commissioning + maintenance + repair',
    summary: 'Prove a system is ready, make normal care legible, diagnose failure, control spares, and plan retirement or return.',
    usefulWhen: ['the handoff from builder to operator can fail', 'maintenance determines real service life', 'the project needs a clean ending'],
    inputs: ['as-built configuration', 'acceptance criteria', 'operating and service context'],
    outputs: ['commissioning script', 'maintenance card and spares list', 'decommission and return plan'],
    proof: ['functional performance test', 'repeat repair by someone other than the designer', 'complete closeout and material return'],
    tools: ['checklists', 'diagnostic instruments', 'CMMS or service log', 'spares and repair fixtures'],
    interfaces: ['all disciplines'],
    flags: ['only authorized and qualified people should energize, open, repair, or return regulated systems'],
    keywords: ['commission maintenance repair service diagnose spares closeout pack-out return operator lifecycle'],
  },
] as const;

export const ENGINEERING_MISSIONS = [
  {
    id: 'shade-return', command: 'stack shade-return', title: 'Shade That Returns',
    question: 'Build a calm hand-carried shade room whose joints, wind limits, access path, repair plan, and pack-out are inspectable.',
    capabilities: ['systems', 'structures', 'materials', 'manufacturing', 'test-reliability', 'safety-human', 'commission-maintain'],
    deliverables: ['requirements + wind stop rule', 'load path + joint details', 'material/finish schedule', 'three-assembly test log', 'access + complete pack-out record'],
    stop: 'No field assembly until the responsible site steward and appropriately qualified reviewers accept the location, wind rule, access plan, and setup method.',
  },
  {
    id: 'repair-bench', command: 'stack repair-bench', title: 'Salt-Air Repair Bench',
    question: 'Create one portable bench that can inspect, clean, patch, document, and return ordinary beach utility gear.',
    capabilities: ['mechanical', 'materials', 'manufacturing', 'quality-metrology', 'safety-human', 'commission-maintain'],
    deliverables: ['repair envelope + tool map', 'material compatibility card', 'fixture and work instructions', 'four repeat repair records', 'parts and waste return log'],
    stop: 'Exclude hazardous, pressurized, energized, life-safety, structural, or owner-restricted equipment unless the proper facility and qualified person take responsibility.',
  },
  {
    id: 'hard-thing', command: 'stack hard-thing', title: 'Explain the Hard Thing',
    question: 'Make one difficult regional system legible in ten minutes without hiding interfaces, uncertainty, or consequences.',
    capabilities: ['systems', 'controls', 'embedded', 'test-reliability', 'safety-human'],
    deliverables: ['system boundary + interface map', 'one tactile or simulated demonstration', 'source and uncertainty ledger', 'three retell tests', 'corrected field card'],
    stop: 'Do not expose secure, proprietary, private, or safety-sensitive details; explanation is not authorization to operate the represented system.',
  },
  {
    id: 'arrival-handoff', command: 'stack arrival-handoff', title: 'The Arrival Handoff',
    question: 'Test a public, accessible, multilingual handoff from a regional gateway to one local door without claiming control of either.',
    capabilities: ['systems', 'civil-site', 'industrial-logistics', 'controls', 'safety-human'],
    deliverables: ['route and interface map', 'timed physical rehearsal', 'accessible alternative', 'failure/recovery notes', 'versioned public card'],
    stop: 'Use only public, currently authorized routes and information; never enter secure areas or represent an agency, operator, venue, or transit provider.',
  },
  {
    id: 'field-sound', command: 'stack field-sound', title: 'Field Sound Line',
    question: 'Build a small consent-forward instrument for wind, waves, tools, and authored voices with honest levels and data.',
    capabilities: ['power', 'embedded', 'rf', 'controls', 'test-reliability', 'safety-human'],
    deliverables: ['signal and power chain', 'calibration tone + level limit', 'loss-of-link behavior', 'consent and credits card', 'twenty-minute sequence'],
    stop: 'No captured conversation without consent, no wildlife disturbance, no unapproved transmission, and no unsafe listening level.',
  },
  {
    id: 'elements-score', command: 'stack elements-score', title: 'Elements Score',
    question: 'Turn sun, wind, water, and changing light into fair rules for a reversible public game.',
    capabilities: ['systems', 'structures', 'embedded', 'coastal-water', 'test-reliability', 'safety-human', 'commission-maintain'],
    deliverables: ['four element rules', 'sensor or observation method', 'weather cancellation threshold', 'access adaptation', 'site restoration and pack-out check'],
    stop: 'A conceptual score is not an event permit. No installation, sampling, wildlife interaction, water entry, or gathering is implied.',
  },
] as const;

export const REGIONAL_ENGINEERING_DOORS = [
  { id: 'ssc', name: 'Space Systems Command', place: 'El Segundo', band: 'CENTER', kind: 'capability signal', capabilities: ['systems', 'rf', 'controls', 'test-reliability'], use: 'Official public evidence of mission integration, acquisition, interfaces, and resilient space systems.', access: 'Secure operating organization; public source only. No visitor, employment, partnership, or access claim.', url: 'https://www.ssc.spaceforce.mil/Portals/3/Documents/SSC_Command_Plan_2024_Final_04_02_2025_.pdf' },
  { id: 'aerospace', name: 'The Aerospace Corporation · El Segundo campus', place: 'El Segundo', band: 'CENTER', kind: 'capability signal', capabilities: ['systems', 'test-reliability', 'safety-human', 'controls'], use: 'Official evidence of an active engineering, research, and laboratory campus serving mission-critical space systems.', access: 'Major regional office and technical campus; not represented as publicly accessible.', url: 'https://aerospace.org/press-release/aerospace-shifts-corporate-headquarters-dc-area' },
  { id: 'spacex', name: 'SpaceX · Hawthorne engineering and production', place: 'Hawthorne', band: 'CENTER', kind: 'current role taxonomy', capabilities: ['mechanical', 'materials', 'thermal-fluids', 'power', 'embedded', 'controls', 'manufacturing', 'test-reliability'], use: 'Current official role taxonomy exposes the breadth of local manufacturing, propulsion, avionics, software, materials, test, and reliability work.', access: 'Career listings change. Presence is evidence of capability, not a claim that a particular role remains open.', url: 'https://www.spacex.com/careers/jobs' },
  { id: 'lmu', name: 'LMU Seaver engineering programs', place: 'Westchester', band: 'CENTER', kind: 'learning door', capabilities: ['civil-site', 'mechanical', 'power', 'embedded', 'controls'], use: 'Official program door for civil, computer, electrical, and mechanical engineering close to the radius center.', access: 'Academic program information; admission, lab access, and participation have their own requirements.', url: 'https://admission.lmu.edu/about/academics/majors/' },
  { id: 'sbwib', name: 'South Bay Workforce Investment Board apprenticeships', place: 'South Bay', band: 'NEAR', kind: 'workforce door', capabilities: ['manufacturing', 'quality-metrology', 'industrial-logistics', 'commission-maintain'], use: 'Official apprenticeship and pre-apprenticeship bridge for aerospace, advanced manufacturing, aviation, technology, and other sectors.', access: 'Programs, cohorts, eligibility, employers, and application periods change; verify on the official route.', url: 'https://southbaycities.org/perspective-building-the-south-bays-future-workforce-through-apprenticeships/' },
  { id: 'elcamino', name: 'El Camino College Manufacturing Technology', place: 'Torrance', band: 'NEAR', kind: 'learning door', capabilities: ['manufacturing', 'quality-metrology', 'mechanical', 'embedded'], use: 'Hands-on official pathway through CAD, machining, CNC, electronics, robotics, welding, measurement, and print reading.', access: 'Program and course requirements are controlled by El Camino College.', url: 'https://www.elcamino.edu/academics/areas-of-study/manufacturing-technology.html' },
  { id: 'csudh', name: 'CSUDH systems, quality, cybersecurity + safety programs', place: 'Carson', band: 'NEAR', kind: 'learning door', capabilities: ['systems', 'quality-metrology', 'controls', 'safety-human'], use: 'Official continuing and professional education evidence for systems engineering, quality assurance, cybersecurity, reliability, and occupational safety.', access: 'Offerings, formats, eligibility, and schedules change; confirm in the current catalog.', url: 'https://catalog.csudh.edu/general-information/division-academic-affairs/continuing-professional-education/continuing-professional-education.pdf' },
  { id: 'lawa', name: 'LAWA Design + Construction Handbook', place: 'LAX', band: 'CENTER', kind: 'open specification door', capabilities: ['systems', 'civil-site', 'structures', 'power', 'industrial-logistics', 'safety-human'], use: 'A rare public corpus of real airport project process, BIM, geospatial, wayfinding, design, construction, commissioning, and closeout requirements.', access: 'Reading specifications is public; airport work, access, procurement, and approvals are controlled by LAWA.', url: 'https://www.lawa.org/lawa-businesses/lawa-documents-and-guidelines/lawa-design-and-construction-handbook' },
  { id: 'portla', name: 'Port of Los Angeles Engineering Division', place: 'San Pedro', band: 'RING', kind: 'public infrastructure door', capabilities: ['civil-site', 'coastal-water', 'structures', 'industrial-logistics', 'commission-maintain'], use: 'Official public description of harbor design plans, specifications, contract documents, maintenance, repair, and redevelopment functions.', access: 'Port operations and projects are controlled environments; the link is for public orientation, not access.', url: 'https://portoflosangeles.org/about/contact/division-directory' },
  { id: 'ladwp', name: 'LADWP Student Engineer Program', place: 'Los Angeles', band: 'RING', kind: 'paid learning door', capabilities: ['civil-site', 'power', 'mechanical', 'process', 'systems'], use: 'Official paid program pairing eligible engineering students with infrastructure teams and project-related work.', access: 'Eligibility and application windows apply. The official page currently describes the 2026 cycle and future opening timing.', url: 'https://www.ladwp.com/who-we-are/careers/internships' },
  { id: 'usc', name: 'USC Viterbi departments + research centers', place: 'University Park', band: 'RING', kind: 'learning and research door', capabilities: ['systems', 'mechanical', 'civil-site', 'power', 'controls', 'process', 'industrial-logistics'], use: 'Official map of aerospace, mechanical, astronautical, biomedical, chemical, materials, civil, environmental, computing, electrical, and industrial systems work.', access: 'Academic and research programs have separate admission, participation, and facility rules.', url: 'https://viterbischool.usc.edu/research/departments-research-institutes-and-centers/' },
  { id: 'ucla', name: 'UCLA Samueli expertise directory', place: 'Westwood', band: 'RING', kind: 'learning and research door', capabilities: ['mechanical', 'materials', 'civil-site', 'coastal-water', 'power', 'controls', 'process'], use: 'Official department-level expertise map spanning bio, chemical, civil, environmental, computing, electrical, mechanical, aerospace, and materials engineering.', access: 'This catalog links only to the school-level public directory; it does not republish individual contact data.', url: 'https://samueli.ucla.edu/faculty-expertise-directory/' },
  { id: 'csulb', name: 'CSULB Hung Family College of Engineering', place: 'Long Beach', band: 'EDGE', kind: 'learning door', capabilities: ['mechanical', 'civil-site', 'coastal-water', 'power', 'embedded', 'controls', 'process'], use: 'Official applied programs in aerospace, biomedical, chemical, civil, computer, construction, electrical, environmental, engineering technology, and mechanical engineering.', access: 'Long Beach is an approximate edge door in this editorial radius; program rules and access remain with CSULB.', url: 'https://www.csulb.edu/hung-family-college-of-engineering/undergraduate-programs-0' },
  { id: 'bpelsg', name: 'California engineering licensure gate', place: 'Statewide', band: 'RULE', kind: 'qualification gate', capabilities: ['mechanical', 'structures', 'power', 'civil-site', 'process', 'industrial-logistics'], use: 'Official explanation of California practice acts, title acts, title authorities, experience, exams, and license verification.', access: 'Use the Board’s current rules and license lookup; ENG/25 does not determine who is qualified to practice.', url: 'https://bpelsg.ca.gov/applicants/appintrope.shtml' },
  { id: 'calosha', name: 'Cal/OSHA training + qualified-person requirements', place: 'Statewide', band: 'RULE', kind: 'safety gate', capabilities: ['safety-human', 'manufacturing', 'civil-site', 'commission-maintain'], use: 'Official index of training duties and the distinct competent-person and qualified-person concepts used in California work.', access: 'The page is a guide and not a substitute for Title 8 or a worksite-specific safety program.', url: 'https://dir.ca.gov/dosh/dosh_publications/trainingreq.htm' },
  { id: 'fcc', name: 'FCC equipment authorization + experimental radio', place: 'Federal', band: 'RULE', kind: 'spectrum gate', capabilities: ['rf', 'embedded', 'power'], use: 'Official regulatory door for RF equipment authorization and experimental operation.', access: 'Use compliant equipment and the applicable authorization; ENG/25 does not grant spectrum rights.', url: 'https://opendata.fcc.gov/Engineering-Technology/EAS-Equipment-Authorization-Grantee-Registrations/3b3k-34jp' },
  { id: 'abet', name: 'ABET accredited-program search', place: 'National', band: 'RULE', kind: 'education verification', capabilities: ['systems', 'mechanical', 'power', 'civil-site', 'process'], use: 'Official current search for accredited engineering and engineering-technology programs.', access: 'Accreditation applies to programs, not every individual course, person, employer, or project.', url: 'https://www.abet.org/' },
] as const;

export const ENGINEERING_PROOF_PACKET = [
  { code: '00', title: 'Mission', detail: 'One sentence naming the user, useful result, operating place, and finish line.' },
  { code: '01', title: 'Requirements', detail: 'Each requirement has a source, owner, priority, and verification method.' },
  { code: '02', title: 'Interfaces', detail: 'Every material, energy, signal, person, authority, and handoff crossing is visible.' },
  { code: '03', title: 'Assumptions', detail: 'Loads, conditions, distances, availability, access, and unknowns are versioned—not smuggled in.' },
  { code: '04', title: 'Build record', detail: 'Drawing, bill of materials, process, supplier, configuration, and deviations travel with the thing.' },
  { code: '05', title: 'Test record', detail: 'Setup, calibration, raw data, pass/fail criteria, anomaly, correction, and retest remain inspectable.' },
  { code: '06', title: 'Qualified gates', detail: 'Licenses, competent people, permits, owners, operators, and site stewards are named before their authority is used.' },
  { code: '07', title: 'Keep + close', detail: 'Operator, maintenance interval, repair door, spares, stop rule, pack-out, restoration, and end-of-life path are assigned.' },
] as const;

export const TERMINAL_COMMANDS = [
  { command: 'help', detail: 'Show the command reference.' },
  { command: 'ls skills', detail: 'Show all engineering man pages.' },
  { command: 'ls gateways', detail: 'Jump to official regional doors.' },
  { command: 'find salt air', detail: 'Search every capability field.' },
  { command: 'layer signal', detail: 'Filter by architecture, matter, signal, field, proof, or operations.' },
  { command: 'stack shade-return', detail: 'Compile one Radius 25 mission stack.' },
  { command: 'proof', detail: 'Jump to the eight-part proof packet.' },
  { command: 'export', detail: 'Copy the selected work order; PointCast receives nothing.' },
  { command: 'clear', detail: 'Reset filters and terminal output.' },
] as const;

export function capabilityById(id: string) {
  return ENGINEERING_CAPABILITIES.find((capability) => capability.id === id) ?? ENGINEERING_CAPABILITIES[0];
}

export function missionById(id: string) {
  return ENGINEERING_MISSIONS.find((mission) => mission.id === id) ?? ENGINEERING_MISSIONS[0];
}
