/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fed33b0868158afde8918aaa15541bf2)
interface __BaseEnv_Env {
	VISITS: KVNamespace;
	PC_ANALYTICS_KV: KVNamespace;
	USERS: KVNamespace;
	PC_PING_KV: KVNamespace;
	PC_QUEUE_KV: KVNamespace;
	PC_DROP_KV: KVNamespace;
	PC_POLLS_KV: KVNamespace;
	PC_RATES_KV: KVNamespace;
	PC_RACE_KV: KVNamespace;
	PC_STUDIO_KV: KVNamespace;
	PC_CHECKIN_KV: KVNamespace;
	PRESENCE: DurableObjectNamespace /* PresenceRoom from pointcast-presence */;
	DRUM_ROOM: DurableObjectNamespace /* DrumRoomV2 from pointcast-drum */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
