/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 693a8efaf85bde35e3b7167286f46b77)
interface __BaseEnv_Env {
	AUTH_DB: D1Database;
	SEAL_DRY_RUN: "false";
	SEAL_RPC: "https://mainnet.smartpy.io";
	SEAL_CONTRACT_V2: "";
	SEAL_V1_FROZEN: "0";
	PRESENCE_BUS: Fetcher /* pointcast-presence */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SEAL_DRY_RUN" | "SEAL_RPC" | "SEAL_CONTRACT_V2" | "SEAL_V1_FROZEN">> {}
}
