/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 27316bf70bf5866a1aa2b5bad8c724a2)
interface __BaseEnv_Env {
	AUTH_DB: D1Database;
	SEAL_DRY_RUN: "false";
	SEAL_RPC: "https://mainnet.smartpy.io";
	PRESENCE_BUS: Fetcher /* pointcast-presence */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SEAL_DRY_RUN" | "SEAL_RPC">> {}
}
