export function radiusBoundary(center,miles,step=5){const rad=Math.PI/180,lat=center.lat*rad,lon=center.lon*rad,d=miles/(6371.0088/1.609344);return Array.from({length:Math.ceil(360/step)},(_,i)=>{const b=i*step*rad,y=Math.asin(Math.sin(lat)*Math.cos(d)+Math.cos(lat)*Math.sin(d)*Math.cos(b)),x=lon+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(lat),Math.cos(d)-Math.sin(lat)*Math.sin(y));return [y/rad,x/rad];});}
export function haversineMiles(a,b){const r=6371.0088/1.609344,p=Math.PI/180;const dlat=(b.lat-a.lat)*p,dlon=(b.lon-a.lon)*p;const h=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*r*Math.asin(Math.sqrt(h));}
export function readSelection(search,atlas){const q=new URLSearchParams(search);return {season:atlas.seasons.some(s=>s.id===q.get('season'))?q.get('season'):'summer',zone:atlas.zones.some(z=>z.id===q.get('zone'))?q.get('zone'):'coast',purpose:['outdoor','comfort','home','water'].includes(q.get('purpose'))?q.get('purpose'):'outdoor'};}
export function initAtlas(root,atlas){if(!root)return ()=>{};root._atlasCleanup?.();const w=root.ownerDocument.defaultView;let state=readSelection(w.location.search,atlas);const cleanup=[];const on=(el,event,fn)=>{el.addEventListener(event,fn);cleanup.push(()=>el.removeEventListener(event,fn));};
 const paint=()=>{const season=atlas.seasons.find(s=>s.id===state.season),zone=atlas.zones.find(z=>z.id===state.zone);root.style.setProperty('--season',season.color);root.querySelectorAll('[data-season]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.season===state.season)));root.querySelectorAll('[data-purpose]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.purpose===state.purpose)));root.querySelectorAll('[data-zone]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.zone===state.zone)));root.querySelectorAll('[data-map-zone]').forEach(p=>p.classList.toggle('selected',p.dataset.mapZone===state.zone));
 const set=(key,value)=>{const el=root.querySelector(`[data-live="${key}"]`);if(el)el.textContent=value;};set('season',`${season.name} · ${season.months}`);set('title',season.title);set('summary',season.summary);set('zone',zone.name);set('places',zone.places);set('pattern',zone.pattern);set('evidence',zone.evidence);set('season-advice',season[state.purpose]);set('zone-advice',zone.advice[state.purpose]);set('status',`${season.name}, ${zone.name}, ${state.purpose==='home'?'ventilation':state.purpose}. Illustrative planning guidance.`);
 const list=root.querySelector('[data-kit]');list.replaceChildren(...[...new Set([...season.objects,...zone.objects])].map(id=>{const li=root.ownerDocument.createElement('li'),a=root.ownerDocument.createElement('a');a.href=`/object-library/#${id}`;a.textContent={turn:'TURN · focus / pause',glow:'GLOW · indoor rhythm',pip:'PIP · field notes',brim:'BRIM · shade reminder',pane:'PANE · window cue',shell:'SHELL · rain carry'}[id];li.append(a);return li;}));};
 const select=(key,id)=>{state[key]=id;const url=new URL(w.location.href);Object.entries(state).forEach(([k,v])=>url.searchParams.set(k,v));w.history.replaceState({},'',url);paint();};
 root.querySelectorAll('[data-season]').forEach(b=>on(b,'click',()=>select('season',b.dataset.season)));root.querySelectorAll('[data-purpose]').forEach(b=>on(b,'click',()=>select('purpose',b.dataset.purpose)));root.querySelectorAll('[data-zone]').forEach(b=>on(b,'click',()=>select('zone',b.dataset.zone)));
 root.querySelectorAll('[data-map-zone]').forEach(p=>{on(p,'click',()=>select('zone',p.dataset.mapZone));on(p,'keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();select('zone',p.dataset.mapZone);}});});
 const reset=()=>{state=readSelection(w.location.search,atlas);paint();};on(w,'popstate',reset);paint();root._atlasCleanup=()=>cleanup.forEach(f=>f());return root._atlasCleanup;
}
