/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 23666dfd3a3d8714aaf1bddf9da33700)
interface __BaseEnv_Env {
	VISITS: KVNamespace;
	DRUM_ATTEST_CHAIN_ID: "";
	DRUM_ATTEST_GENESIS: "";
	DRUM_ATTEST_ROOMS: "";
	DRUM_ROOM: DurableObjectNamespace<import("./src/index").DrumRoomV2>;
	DRUM_COUNTER: DurableObjectNamespace<import("./src/index").DrumCounter>;
	DRUM_ATTEST_ROOM: DurableObjectNamespace<import("./src/index").DrumAttestRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DrumRoom" | "DrumRoomV2" | "DrumCounter" | "DrumAttestRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DRUM_ATTEST_CHAIN_ID" | "DRUM_ATTEST_GENESIS" | "DRUM_ATTEST_ROOMS">> {}
}
