/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b72bf46de1bccf85b54bc47f0c9a437a)
interface __BaseEnv_Env {
	DRUM_ROOM: DurableObjectNamespace<import("./src/index").DrumRoomV2>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DrumRoom" | "DrumRoomV2";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
