/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8c9fd40aa242e85a1791ba4a39e38274)
interface __BaseEnv_Env {
	VISITS: KVNamespace;
	DRUM_ROOM: DurableObjectNamespace<import("./src/index").DrumRoomV2>;
	DRUM_COUNTER: DurableObjectNamespace<import("./src/index").DrumCounter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DrumRoom" | "DrumRoomV2" | "DrumCounter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
