name = "pointcast-drum"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[durable_objects.bindings]]
name = "DRUM_ROOM"
class_name = "DrumRoom"

[[migrations]]
tag = "v1"
new_classes = ["DrumRoom"]
