import{test}from'node:test';import assert from'node:assert/strict';import{initialState,placeBet,settle,quote,restore,standings,nextLap}from'../public/ai-grand-prix/engine.mjs';
test('stake enters pool and winning payout includes stake',()=>{const s=initialState(),q=quote(s,'bug','sol',50),b=placeBet(s,'bug','sol',50);assert.equal(q.payout,116);assert.equal(b.balance,950);assert.equal(s.balance,1000);const done=settle(b,'bug','sol');assert.equal(done.balance,1066);assert.equal(done.tickets[0].payout,116);assert.throws(()=>settle(done,'bug','sol'));assert.throws(()=>placeBet(done,'bug','sol',1));});
test('losing and void rounds; no repeat refunds',()=>{const b=placeBet(initialState(),'bug','opus',100);assert.equal(settle(b,'bug','sol').balance,900);const v=settle(b,'bug','void');assert.equal(v.balance,1000);assert.equal(v.tickets[0].status,'refunded');assert.throws(()=>settle(v,'bug','void'));});
test('invalid stakes and IDs never mutate balance',()=>{const s=initialState();for(const n of [0,-1,1.5,NaN,Infinity,1001,Number.MAX_SAFE_INTEGER])assert.throws(()=>placeBet(s,'bug','sol',n));assert.throws(()=>placeBet(s,'oops','sol',1));assert.throws(()=>placeBet(s,'bug','bad',1));assert.equal(s.balance,1000);assert.equal(s.tickets.length,0);});
test('all user bets settle using final pool and other rounds stay open',()=>{let s=placeBet(initialState(),'bug','sol',50);s=placeBet(s,'bug','opus',100);s=placeBet(s,'bug','sol',50);s=placeBet(s,'report','sol',100);const d=settle(s,'bug','sol');assert.equal(d.balance,950);assert.equal(d.tickets[0].payout,125);assert.equal(d.tickets[2].payout,125);assert.equal(d.tickets[3].status,'open');});
test('restore safe fallback and successful round trip',()=>{assert.equal(restore('bad').balance,1000);assert.equal(restore('{"version":1}').balance,1000);const b=placeBet(initialState(),'bug','sol',50);assert.deepEqual(restore(JSON.stringify(b)),b);});
test('joint winners share the pool; losing tickets get zero',()=>{let s=placeBet(initialState(),'budget','sol',50);s=placeBet(s,'budget','sonnet',50);s=placeBet(s,'budget','opus',50);const d=settle(s,'budget',['sol','sonnet']);assert.equal(d.balance,1000);assert.equal(d.tickets[0].payout,75);assert.equal(d.tickets[1].payout,75);assert.equal(d.tickets[2].payout,0);assert.throws(()=>settle(initialState(),'budget',[]));assert.throws(()=>settle(initialState(),'budget',['sol','sol']));});
test('older v1 sessions acquire the new practice race',()=>{const s=initialState();delete s.rounds.budget;assert.equal(restore(JSON.stringify(s)).rounds.budget.status,'open');});

test('season progression archives results and preserves bankroll without repeat payouts',()=>{let s=placeBet(initialState(),'budget','sol',50);assert.throws(()=>nextLap(s));s=settle(s,'budget',['sol','sonnet']);for(const r of ['bug','arcade','report'])s=settle(s,r,'void');const n=nextLap(s);assert.equal(n.balance,1020);assert.equal(n.lap,2);assert.equal(n.history[0].rounds.budget.winner,'sol,sonnet');assert.equal(n.rounds.budget.status,'open');assert.equal(n.tickets[0].lap,1);const after=settle(placeBet(n,'budget','sol',50),'budget',['sol','sonnet']);assert.equal(after.balance,1040);assert.equal(after.tickets[0].payout,70);assert.equal(after.tickets[1].lap,2);assert.equal(s.history.length,0);assert.deepEqual(restore(JSON.stringify(after)),after);});
test('constructors standings split ties, omit voids and include archived laps',()=>{let s=settle(initialState(),'budget',['sol','sonnet']);s=settle(s,'bug','opus');for(const r of ['arcade','report'])s=settle(s,r,'void');const rows=standings(nextLap(s));assert.equal(rows[0].id,'opus');assert.equal(rows[0].points,3);assert.equal(rows.find(r=>r.id==='sol').points,1.5);assert.equal(rows.find(r=>r.id==='sonnet').shared,1);assert.ok(rows.every(r=>r.entered===2));});
