import test from 'node:test';
import assert from 'node:assert/strict';
import { handleChimeLog, normalizeContribution } from '../functions/api/chime/log.ts';
import { CHIME_PROJECT, chimePrompt } from '../src/lib/chime.ts';
import { encodePacket, decodePacket, validateAck, FIXTURES } from '../public/chime/chime-packet.mjs';
class Store {
  data = new Map(); writes=[]; failRead=false; failWrite=false;
  async get(key,type) { if(this.failRead)throw Error('offline'); const v=this.data.get(key);return v===undefined?null:type==='json'?JSON.parse(v):v; }
  async put(key,value,options) { if(this.failWrite)throw Error('offline');this.data.set(key,value);this.writes.push({key,options}); }
  async list({prefix,limit,cursor}) {const names=[...this.data.keys()].filter(k=>k.startsWith(prefix)).sort();const start=Number(cursor||0),slice=names.slice(start,start+limit);return {keys:slice.map(name=>({name})),list_complete:start+limit>=names.length,cursor:String(start+limit)};}
}
const body={author:'Test researcher',ai:'Test AI',task:'air',kind:'proposal',text:'Local API test only.',url:'https://example.org/evidence',consent:true};
const env=()=>({VISITS:new Store(),PC_RATES_KV:new Store()});
const post=(b=body)=>new Request('https://pointcast.xyz/api/chime/log',{method:'POST',headers:{'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.7'},body:JSON.stringify(b)});
test('publish, receipt and isolated public read preserve a contribution',async()=>{const e=env();await e.VISITS.put('unrelated:private','secret');const res=await handleChimeLog(post(),e);assert.equal(res.status,201);const saved=await res.json();assert.equal(saved.entry.attribution,'self-reported');assert.equal(e.VISITS.writes.at(-1).options.expirationTtl,7776000);assert.equal((await(await handleChimeLog(new Request(saved.receipt),e)).json()).entry.text,body.text);const log=await(await handleChimeLog(new Request('https://pointcast.xyz/api/chime/log'),e)).json();assert.equal(log.entries.length,1);assert.equal(log.entries[0].author,body.author);assert.ok(!JSON.stringify(log).includes('secret'));});
test('public approval, types, bounds and https evidence are required',()=>{for(const patch of [{consent:false},{author:[]},{text:'x'.repeat(1801)},{task:'other'},{kind:'system'},{url:'javascript:alert(1)'},{url:'https://user:password@example.org'}])assert.throws(()=>normalizeContribution({...body,...patch}));assert.equal(normalizeContribution({...body,text:'<script>alert(1)</script>'}).text,'<script>alert(1)</script>');});
test('oversize and invalid media type never write',async()=>{const e=env();const oversized=new Request('https://pointcast.xyz/api/chime/log',{method:'POST',headers:{'Content-Type':'application/json'},body:' '.repeat(12001)});assert.equal((await handleChimeLog(oversized,e)).status,400);assert.equal((await handleChimeLog(new Request('https://pointcast.xyz/api/chime/log',{method:'POST',body:'{}'}),e)).status,400);assert.equal(e.VISITS.data.size,0);});
test('quota, missing bindings, and failed quota writes close the writer',async()=>{const e=env();for(let i=0;i<6;i++)assert.equal((await handleChimeLog(post(),e)).status,201);const blocked=await handleChimeLog(post(),e);assert.equal(blocked.status,429);assert.ok(Number(blocked.headers.get('Retry-After'))>0);assert.equal((await handleChimeLog(post(),{VISITS:new Store()})).status,503);const failed=env();failed.PC_RATES_KV.failWrite=true;assert.equal((await handleChimeLog(post(),failed)).status,503);assert.equal(failed.VISITS.data.size,0);});
test('failed persistent writes cannot return success',async()=>{const e=env();e.VISITS.failWrite=true;assert.equal((await handleChimeLog(post(),e)).status,503);});
test('paging returns all older entries and invalid receipt is rejected',async()=>{const e=env();for(let i=0;i<45;i++)await e.VISITS.put('chime:log:v1:'+String(i).padStart(3,'0'),JSON.stringify({id:String(i)}));const one=await(await handleChimeLog(new Request('https://pointcast.xyz/api/chime/log'),e)).json();assert.equal(one.entries.length,40);const two=await(await handleChimeLog(new Request('https://pointcast.xyz/api/chime/log?cursor='+one.nextCursor),e)).json();assert.equal(two.entries.length,5);assert.equal(two.nextCursor,null);assert.equal((await handleChimeLog(new Request('https://pointcast.xyz/api/chime/log?id=../../anything'),e)).status,400);});
test('CORS works for an agent client without cookies',async()=>{const r=await handleChimeLog(new Request('https://pointcast.xyz/api/chime/log',{method:'OPTIONS'}),env());assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'*');assert.equal(r.headers.get('Access-Control-Allow-Credentials'),null);});
test('AI brief keeps publication consent and evidence boundaries',()=>{assert.match(chimePrompt('headphones'),/Bluetooth/);assert.match(chimePrompt(),/before posting/);assert.equal(CHIME_PROJECT.contribution.retentionDays,90);assert.match(CHIME_PROJECT.status,/untested/);});
test('sample packet corruption and mismatched reply fail validation',()=>{const hello=encodePacket(FIXTURES.hello),ack=encodePacket(FIXTURES.ack);assert.equal(decodePacket(hello).sessionTag,FIXTURES.hello.sessionTag);validateAck(hello,ack);const bad=hello.slice();bad[9]^=1;assert.throws(()=>decodePacket(bad));assert.throws(()=>validateAck(hello,encodePacket({...FIXTURES.ack,sessionTag:'0000000000000000'})));});
