import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const KEY='pointcast.keyboard.notes.v1';
function app(garden=false,raw){const file=garden?'src/pages/keyboard/garden.astro':'src/pages/keyboard.astro';const html=readFileSync(file,'utf8').replace(/^---[\s\S]*?---\n/,'').replaceAll(' is:inline','');let downloads=[];const dom=new JSDOM(html,{url:'https://pointcast.xyz/keyboard',runScripts:'dangerously',beforeParse(w){if(raw)w.localStorage.setItem(KEY,raw);w.URL.createObjectURL=b=>{downloads.push(b);return 'blob:test'};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{}}});const w=dom.window,$=id=>w.document.getElementById(id);const input=(id,text)=>{$(id).value=text;$(id).dispatchEvent(new w.Event('input',{bubbles:true}))};return {w,$,input,downloads,close:()=>w.close(),saved:()=>JSON.parse(w.localStorage.getItem(KEY))}}
test('notes persist, search, trash and restore without destroying content',()=>{const a=app();try{a.input('title','Ocean thoughts');a.input('body','A note with two lines.\nSecond line.');const raw=a.w.localStorage.getItem(KEY);const b=app(false,raw);assert.equal(b.$('body').value,'A note with two lines.\nSecond line.');b.close();a.$('new').click();a.input('title','Different');a.input('search','Ocean');assert.equal(a.$('notes').children.length,1);a.input('search','');a.$('delete').click();assert.equal(a.saved().notes.filter(n=>n.deleted).length,1);a.$('trash').click();a.$('restore').click();assert.equal(a.saved().notes.filter(n=>n.deleted).length,0)}finally{a.close()}});
test('bad storage is preserved and export remains available',()=>{const a=app(false,'not json');try{a.input('body','Recovered writing');assert.equal(a.w.localStorage.getItem(KEY),'not json');a.$('export').click();assert.equal(a.downloads.length,1);assert.match(a.$('saved').textContent,/could not be loaded/)}finally{a.close()}});
test('quota errors report unsaved work',()=>{const a=app();try{a.w.Storage.prototype.setItem=()=>{throw Error('quota')};a.input('body','Keep this');assert.match(a.$('saved').textContent,/Could not save/);a.$('backup').click();assert.equal(a.downloads.length,1)}finally{a.close()}});
test('selection-only cross-tab changes do not stop saving, concurrent note edits are protected',()=>{const a=app();try{a.input('body','Local');const same=a.saved();same.selected='other';a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:KEY,newValue:JSON.stringify(same)}));a.input('body','Still saved');assert.equal(a.saved().notes[0].body,'Still saved');a.$('body').focus();const conflict=a.saved();conflict.notes[0].body='Other tab';a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:KEY,newValue:JSON.stringify(conflict)}));a.input('body','My draft');assert.match(a.$('saved').textContent,/changed in another tab/);assert.equal(a.saved().notes[0].body,'Still saved')}finally{a.close()}});
test('Garden suggests a scene, pins it independently of later edits, and survives backup/reload',()=>{const a=app(true);try{a.input('body','Ocean waves on the beach');assert.match(a.$('art-caption').textContent,/ocean/);a.$('attach-art').click();assert.equal(a.saved().notes[0].illustration.topic,'ocean');a.input('body','Mountains and a forest trail');assert.match(a.$('art-caption').textContent,/mountains/);assert.equal(a.saved().notes[0].illustration.topic,'ocean');const b=app(true,a.w.localStorage.getItem(KEY));assert.equal(b.$('attached').hidden,false);assert.match(b.$('attached-caption').textContent,/ocean/);b.close();a.$('export-page').click();a.$('save-art').click();assert.equal(a.downloads.length,2);a.$('remove-art').click();assert.equal(a.saved().notes[0].illustration,undefined)}finally{a.close()}});
test('note text is rendered safely, music never intercepts ordinary editing keys',()=>{const a=app(true);try{a.input('title','<img src=x onerror=alert(1)>');assert.equal(a.$('notes').querySelector('img'),null);for(const key of ['Enter','Backspace','Tab','ArrowLeft']){const event=new a.w.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true});a.$('body').dispatchEvent(event);assert.equal(event.defaultPrevented,false)}assert.equal(a.$('voice').options.length,8);assert.equal(a.$('skin').options.length,5);assert.equal(a.$('mood').options.length,4)}finally{a.close()}});
test('backup import merges without replacing existing notes and rejects malformed files',async()=>{const a=app(true);try{a.input('body','Keep this original');const incoming={version:1,notes:[{id:'imported',title:'Imported',body:'A flower',created:1,updated:1,deleted:false,illustration:{topic:'flowers',seed:42,growth:50}}]};Object.defineProperty(a.$('file'),'files',{configurable:true,value:[{size:100,text:async()=>JSON.stringify(incoming)}]});await a.$('file').onchange();assert.equal(a.saved().notes.length,2);assert.equal(a.saved().notes[0].body,'Keep this original');assert.notEqual(a.saved().notes[1].id,'imported');assert.equal(a.$('attached').hidden,false);Object.defineProperty(a.$('file'),'files',{configurable:true,value:[{size:100,text:async()=>'not JSON'}]});await a.$('file').onchange();assert.equal(a.saved().notes.length,2);assert.match(a.$('notice').textContent,/not a valid/)}finally{a.close()}});
test('illustrated export contains escaped text and its attached SVG',async()=>{const a=app(true);try{a.input('title','<script>bad()</script>');a.input('body','<img src=x onerror=bad()>');a.$('attach-art').click();a.$('export-page').click();const content=await new Promise((resolve,reject)=>{const r=new a.w.FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsText(a.downloads[0])});assert.match(content,/&lt;script&gt;/);assert.match(content,/&lt;img/);assert.match(content,/<svg/);assert.doesNotMatch(content,/<script>/)}finally{a.close()}});
