import assert from 'node:assert/strict'; import {createHash} from 'node:crypto'; import {readFile,readdir} from 'node:fs/promises'; import path from 'node:path'; import test from 'node:test'; import sharp from 'sharp';
const root=process.cwd(), json=async f=>JSON.parse(await readFile(path.join(root,f),'utf8')), sha=async f=>createHash('sha256').update(await readFile(path.join(root,f))).digest('hex');
const teams=await json('src/data/pointcast-signal-stamps.json'), contract=await json('src/data/saturday-signal-stamps-contract.json'), manifest=await json('public/collectibles/saturday-signal-stamps/provenance/manifest.json');
test('College 50 is complete and unique',()=>{assert.equal(teams.length,50);assert.equal(new Set(teams.map(t=>t.id)).size,50);assert.equal(new Set(teams.map(t=>t.slug)).size,50);assert.deepEqual(teams.map(t=>t.id),Array.from({length:50},(_,i)=>i));for(const t of teams){assert.match(t.designSourceUrl,/^https:\/\//);assert.ok(t.localSignal.split(',').length>=3)}});
test('press contains 150 exact outputs',async()=>{assert.equal((await readdir('public/images/pointcast-signal-stamps/stamps')).filter(x=>x.endsWith('.png')).length,50);assert.equal((await readdir('public/images/pointcast-signal-stamps/profiles')).filter(x=>x.endsWith('.png')).length,50);assert.equal((await readdir('public/images/pointcast-signal-stamps/wallpapers')).filter(x=>x.endsWith('.webp')).length,50);for(const t of teams){const [a,p,w]=await Promise.all([sharp(`public/images/pointcast-signal-stamps/stamps/${t.slug}.png`).metadata(),sharp(`public/images/pointcast-signal-stamps/profiles/${t.slug}.png`).metadata(),sharp(`public/images/pointcast-signal-stamps/wallpapers/${t.slug}.webp`).metadata()]);assert.deepEqual([a.width,a.height,a.format],[1024,1024,'png']);assert.deepEqual([p.width,p.height,p.format],[512,512,'png']);assert.deepEqual([w.width,w.height,w.format],[1920,1080,'webp'])}});
test('metadata binds artifacts and six studies',async()=>{assert.equal(manifest.items.length,50);assert.equal(manifest.masterStudies.length,6);assert.deepEqual(manifest.mint,{priceMutez:0,editionCapPerToken:100,onePerWalletPerToken:true,network:'Tezos Mainnet'});for(const t of teams){const m=await json(`public/collectibles/saturday-signal-stamps/metadata/${t.id}.json`);assert.equal(m.artifactSha256,await sha(`public/images/pointcast-signal-stamps/stamps/${t.slug}.png`));assert.equal(m.profileSha256,await sha(`public/images/pointcast-signal-stamps/profiles/${t.slug}.png`));assert.equal(m.wallpaperSha256,await sha(`public/images/pointcast-signal-stamps/wallpapers/${t.slug}.webp`))}});
test('contract stays unsigned until applied origination',()=>{assert.equal(contract.entrypoint,'mint_signal');assert.equal(contract.priceMutez,0);assert.equal(contract.editionCapPerToken,100);if(contract.live){assert.match(contract.kt1,/^KT1/);assert.ok(contract.operationHash)}else{assert.equal(contract.kt1,'');assert.equal(contract.operationHash,null)}});
test('compiled artifacts match receipt',async()=>{const r=await json('public/admin/_artifacts/saturday-signal-stamps-receipt.json');assert.equal(r.signed,false);assert.equal(r.constructor.editionCap,100);assert.equal(r.sha256.contract,await sha('public/admin/_artifacts/saturday-signal-stamps-contract.json'));assert.equal(r.sha256.storage,await sha('public/admin/_artifacts/saturday-signal-stamps-storage.json'));assert.equal(r.sha256.source,await sha('contracts/v2/saturday_signal_stamps_fa2.py'))});
test('surface preserves affiliation and custody boundaries',async()=>{const [lib,page,mint,source]=await Promise.all(['src/lib/pointcast-signal-stamps.ts','src/pages/25/collect/signal-stamps.astro','src/components/MintButton.astro','contracts/v2/saturday_signal_stamps_fa2.py'].map(f=>readFile(f,'utf8')));assert.match(lib,/No official logos or mascot artwork/);assert.match(page,/AWAITS CREATOR SIGNATURE/);assert.match(mint,/ep\.mint_signal/);assert.match(source,/NO_PAYMENT_ACCEPTED/);assert.match(source,/EDITION_SOLD_OUT/);assert.match(source,/ALREADY_CLAIMED/)});
