import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {study,methodology,queryStudy} from '../src/lib/real-estate-study.mjs';
import {STUDY_CENTER,localMarkets,radiusBoundary,haversineMiles} from '../src/lib/real-estate-local.mjs';
import {parseFhfaCsv,normalizeUsgs} from '../src/lib/real-estate-feeds.mjs';
import {realEstateRequest,boundedText} from '../functions/_lib/real-estate-api.mjs';
import {REAL_ESTATE_TOOLS,runRealEstateTool} from '../src/lib/real-estate-agent.mjs';
const request=(path,method='GET')=>new Request(`https://pointcast.xyz/api/real-estate/${path}`,{method});
const csv='"Los Angeles, CA",31084,2025,2,100,(1.0)\n"Los Angeles, CA",31084,2026,1,110,(1.0)\n"Los Angeles, CA",31084,2026,2,120,(1.0)\n"Other, CA",12345,2026,2,900,(1.0)';
const event=(type='earthquake',lon=STUDY_CENTER.lon,lat=STUDY_CENTER.lat)=>({id:'test',properties:{type,mag:1.2,time:1700000000000,updated:1700000001000,place:'Test event',url:'https://earthquake.usgs.gov/earthquakes/eventpage/test'},geometry:{type:'Point',coordinates:[lon,lat,5]}});
test('source graph resolves, dated scope matches18anchors, map circle closes and remains25mi',()=>{
  assert.equal(localMarkets.length,18);assert.match(methodology.scope,/18/);const ids=new Set(study.sources.map(s=>s.id));assert.equal(ids.size,study.sources.length);
  for(const entry of [...study.localMarkets,...study.globalMarkets,...study.glossary,...study.players,...study.history,...study.propertyTiers])for(const id of entry.sourceIds)assert.ok(ids.has(id),id);
  for(const s of study.sources){assert.match(s.url,/^https:\/\//);assert.equal(s.checkedAt,'2026-10-03');}
  for(const m of localMarkets)assert.ok(haversineMiles(STUDY_CENTER.lat,STUDY_CENTER.lon,m.lat,m.lon)<=25);
  const boundary=radiusBoundary();assert.ok(haversineMiles(boundary[0].lat,boundary[0].lon,boundary.at(-1).lat,boundary.at(-1).lon)<1e-8);for(const p of boundary)assert.ok(Math.abs(haversineMiles(STUDY_CENTER.lat,STUDY_CENTER.lon,p.lat,p.lon)-25)<1e-8);
});
test('local type/search and global region filtering preserve sourced records',()=>{const r=queryStudy({q:'carson',type:'Industrial',region:'local'});assert.equal(r.localMarkets.length,1);assert.equal(r.globalMarkets.length,0);assert.equal(r.localMarkets[0].id,'carson');assert.ok(r.sourceIds.length);assert.equal(queryStudy({q:'singapore',region:'global'}).globalMarkets.length,1);assert.equal(queryStudy({q:'no such market'}).localMarkets.length,0);});
test('FHFA quoted-comma CSV parses only31084 and compares calendar quarter/year',()=>{const r=parseFhfaCsv(csv,'dated');assert.equal(r.latest.index,120);assert.equal(r.observationPeriod,'2026 Q2');assert.equal(r.records.length,3);assert.ok(Math.abs(r.quarterChangePct-100/11)<1e-8);assert.ok(Math.abs(r.yearChangePct-20)<1e-8);assert.equal(r.retrievedAt,'dated');assert.throws(()=>parseFhfaCsv('<html>unavailable</html>'));});
test('USGS counts earthquakes only within25mi, retains dates, rejects unsafe source links',()=>{const unsafe=event();unsafe.properties.url='https://evil.example/';const r=normalizeUsgs({metadata:{generated:1700000000000},features:[event(),event('quarry blast'),event('earthquake',0,0),unsafe]},STUDY_CENTER,haversineMiles,'retrieved');assert.equal(r.events.length,2);assert.equal(r.events[1].url,null);assert.equal(r.retrievedAt,'retrieved');assert.equal(r.generatedAt,'2023-11-14T22:13:20.000Z');assert.throws(()=>normalizeUsgs({},STUDY_CENTER,haversineMiles));const malformed=event();delete malformed.properties.type;assert.throws(()=>normalizeUsgs({metadata:{generated:1700000000000},features:[malformed]},STUDY_CENTER,haversineMiles));});
test('scenario API preserves valid zeroes and rejects bad, duplicate, unknown inputs',async()=>{const good=await realEstateRequest(request('scenario?capital=0&annualContribution=0&interestRate=0&downPaymentPct=100'));assert.equal(good.status,200);assert.equal((await good.json()).results[1].final.netLiquidation,0);for(const params of ['capital=NaN','capital=Infinity','capital=-1','capital=','capital=1&capital=2','loanYears=1.2','__proto__=5','broker=abc'])assert.equal((await realEstateRequest(request(`scenario?${params}`))).status,400,params);});
test('read-only API rejects mutations and invalid query/feed parameters',async()=>{assert.equal((await realEstateRequest(request('scenario','POST'))).status,405);assert.equal((await realEstateRequest(request('query?region=delete'))).status,400);assert.equal((await realEstateRequest(request('query?account=abc'))).status,400);assert.equal((await realEstateRequest(request('feed?source=https://evil.example'))).status,400);assert.equal((await realEstateRequest(request('feed?source=fhfa&url=https://evil.example'))).status,400);assert.equal((await realEstateRequest(request('query','OPTIONS'))).status,204);assert.equal((await realEstateRequest(request('query','HEAD'))).status,200);});
test('feed edge cache reuses derived result and keeps retrieval date with3600sTTL',async()=>{let calls=0,stored,ttl;const cache={match:async()=>stored?.clone(),put:async(key,value)=>{stored=value;ttl=value.headers.get('Cache-Control');}};const fetcher=async(url)=>{assert.equal(url,'https://www.fhfa.gov/hpi/download/quarterly_datasets/hpi_at_metro.csv');calls++;return new Response(csv);};const a=await(await realEstateRequest(request('feed?source=fhfa'),fetcher,cache)).json(),b=await(await realEstateRequest(request('feed?source=fhfa'),fetcher,cache)).json();assert.equal(calls,1);assert.equal(a.status,'fetched');assert.equal(b.status,'cached');assert.equal(a.retrievedAt,b.retrievedAt);assert.equal(b.automaticRefresh,false);assert.equal(ttl,'public, max-age=3600');});
test('USGS edge response uses60seconds and outage returns datedfallback explicitly',async()=>{let ttl;const cache={match:async()=>undefined,put:async(k,r)=>{ttl=r.headers.get('Cache-Control');}};const p={metadata:{generated:1700000000000},features:[event()]};assert.equal((await(await realEstateRequest(request('feed?source=usgs'),async()=>new Response(JSON.stringify(p)),cache)).json()).status,'fetched');assert.equal(ttl,'public, max-age=60');const failed=await(await realEstateRequest(request('feed?source=fhfa'),async()=>{throw new Error('offline');})).json();assert.equal(failed.status,'snapshot-fallback');assert.equal(failed.retrievedAt,'2026-10-03T17:33:26Z');assert.equal(failed.automaticRefresh,false);});
test('bounded response reader stops declared and streamed oversize sources',async()=>{await assert.rejects(boundedText(new Response('large',{headers:{'Content-Length':'999'}}),5));await assert.rejects(boundedText(new Response('123456'),5));assert.equal(await boundedText(new Response('12345'),5),'12345');});
test('MCP feature tools only study/query/calculate fixed sources, strictarguments',async()=>{assert.deepEqual(REAL_ESTATE_TOOLS.map(t=>t.name),['real_estate_study','real_estate_scenario','real_estate_feed']);assert.equal(REAL_ESTATE_TOOLS[1].inputSchema.properties.inputs.properties.loanYears.type,'integer');assert.equal((await runRealEstateTool('real_estate_study',{q:'carson',region:'local'})).localMarkets.length,1);assert.equal((await runRealEstateTool('real_estate_scenario',{inputs:{capital:0,annualContribution:0}})).results[1].final.netLiquidation,0);await assert.rejects(runRealEstateTool('real_estate_feed',{source:'evil'},()=>{}));await assert.rejects(runRealEstateTool('real_estate_scenario',{inputs:{broker:'x'}}));await assert.rejects(runRealEstateTool('real_estate_scenario',{inputs:null}));const code=readFileSync(new URL('../functions/api/mcp.ts',import.meta.url),'utf8');assert.match(code,/\.\.\.REAL_ESTATE_TOOLS/);assert.match(code,/case 'real_estate_feed'/);const writeNames=code.slice(code.indexOf('const WRITE_TOOL_NAMES'),code.indexOf('function toolTitle'));assert.doesNotMatch(writeNames,/real_estate_/);});
