import { articles, articleWordCount, practiceUrl } from './articles.js';

const esc = (value = '') => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const safeUrl = (value = '') => /^(https:\/\/|\/(?!\/)|#)/.test(value) ? esc(value) : '#';
const sourceId = (value) => `pbv2-source-${String(value).replace(/[^a-z0-9-]/g, '-')}`;
const refs = (ids = [], sources = []) => ids.map(id => sources.find(source => source.id === id)).filter(Boolean).map(source => `<a class="pbv2-ref" href="#${sourceId(source.id)}" aria-label="Source: ${esc(source.title)}">[${sources.indexOf(source) + 1}]</a>`).join(' ');
const paragraph = (item, sources) => `<p>${esc(typeof item === 'string' ? item : item.text)}${typeof item === 'string' ? '' : ` ${refs(item.sourceIds, sources)}`}</p>`;
const diagram = (item) => item ? `<figure class="pbv2-diagram"><a href="${safeUrl(item.src)}" aria-label="Open ${esc(item.title)} diagram"><img src="${safeUrl(item.src)}" alt="${esc(item.alt)}" width="${Number(item.width) || 1200}" height="${Number(item.height) || 800}" loading="lazy" /></a><figcaption><b>${esc(item.title)}.</b> ${esc(item.caption)}</figcaption>${item.legend?.length ? `<ul class="pbv2-legend">${item.legend.map(text => `<li>${esc(text)}</li>`).join('')}</ul>` : ''}</figure>` : '';

/** Static escaped article markup. BlockLayout supplies the document and its single main. */
export function renderPickleballArticle(article) {
  if (!article) throw new TypeError('A known pickleball article is required.');
  const sources = article.sources || [];
  const next = articles.find(other => other.slug !== article.slug);
  return `<article class="pbv2-article" aria-labelledby="pbv2-article-title">
    <header class="pbv2-article-masthead"><a href="/pickleball/home" class="pbv2-article-brand">PointCast<span>PICKLEBALL</span></a><nav aria-label="Pickleball article navigation"><a href="/pickleball/home#pb-learn">Learn</a><a href="/pickleball/home#pb-courts">Courts</a><a href="${safeUrl(practiceUrl(article))}">Practice</a><a href="https://tez-rally.pages.dev/">RALLY ↗</a></nav></header>
    <nav class="pbv2-breadcrumb" aria-label="Breadcrumb"><a href="/">PointCast</a><span aria-hidden="true">/</span><a href="/pickleball/home#pb-v2-articles">Practice files</a><span aria-hidden="true">/</span><span>${esc(article.shortTitle || article.title)}</span></nav>
    <header class="pbv2-article-hero"><div><p class="pbv2-article-kicker">THE PRACTICE FILES / ${esc(article.number)}</p><h1 id="pbv2-article-title">${esc(article.title)}</h1><p class="pbv2-article-dek">${esc(article.dek)}</p><div class="pbv2-article-meta"><span>By PointCast Editorial</span><time datetime="${esc(article.publishedAt)}">October 3, 2026</time><span>${esc(article.readingMinutes)} min read</span></div><a class="pbv2-article-button" href="${safeUrl(practiceUrl(article))}">Build a ${esc(article.goalLabel)} practice <span aria-hidden="true">↗</span></a></div><figure><img src="${safeUrl(article.image)}" alt="${esc(article.heroAlt)}" width="${Number(article.imageWidth) || 1200}" height="${Number(article.imageHeight) || 800}" fetchpriority="high" /><figcaption>${esc(article.heroCaption)}</figcaption></figure></header>
    <div class="pbv2-article-layout"><aside class="pbv2-article-toc"><p class="pbv2-article-kicker">IN THIS FILE</p><nav aria-label="Article contents">${article.sections.map(section => `<a href="#${esc(section.id)}">${esc(section.title)}</a>`).join('')}<a href="#pbv2-article-sources">Sources & notes</a></nav><p>One useful cue. A repeatable setup. Then a game to see what holds.</p></aside><div class="pbv2-article-body">${(article.introduction || []).map(item => paragraph(item, sources)).join('')}${article.sections.map(section => `<section id="${esc(section.id)}" aria-labelledby="${esc(section.id)}-title"><h2 id="${esc(section.id)}-title">${esc(section.title)}</h2>${(section.paragraphs || []).map(item => paragraph(item, sources)).join('')}${section.list?.length ? `<ol class="pbv2-practice-steps">${section.list.map(item => `<li>${esc(typeof item === 'string' ? item : item.text)} ${typeof item === 'string' ? '' : refs(item.sourceIds, sources)}</li>`).join('')}</ol>` : ''}${(section.afterParagraphs || []).map(item => paragraph(item, sources)).join('')}${diagram(section.diagram)}${section.cue ? `<p class="pbv2-article-cue"><span>TAKE IT TO COURT</span>${esc(section.cue)}</p>` : ''}</section>`).join('')}
      <section id="pbv2-article-sources" class="pbv2-article-sources" aria-labelledby="pbv2-source-title"><p class="pbv2-article-kicker">CHECKED ${esc(article.checkedAt)}</p><h2 id="pbv2-source-title">Sources & coaching notes.</h2><p>${esc(article.editorialNote)}</p><ol>${sources.map(source => `<li id="${sourceId(source.id)}"><a href="${safeUrl(source.url)}">${esc(source.title)} <span aria-hidden="true">↗</span></a><p>${esc(source.note)}<span> Checked ${esc(source.checkedAt || article.checkedAt)}.</span></p></li>`).join('')}</ol><p class="pbv2-article-small">Original PointCast editorial guidance and diagrams. Practice targets are suggested checkpoints; they do not award a rating or promise a result. ${articleWordCount(article)} words · <a href="${safeUrl(article.url)}.json">Read the article JSON</a>.</p></section>
      <section class="pbv2-article-next" aria-labelledby="pbv2-next-title"><p class="pbv2-article-kicker">YOUR NEXT SESSION</p><h2 id="pbv2-next-title">Make the cue a habit.</h2><p>Choose your time, setup, and focus in the adaptive practice planner. Start with a manageable feed and change one thing at a time.</p><a class="pbv2-article-button" href="${safeUrl(practiceUrl(article))}">Plan a ${esc(article.goalLabel)} session <span aria-hidden="true">↗</span></a></section>
      <nav class="pbv2-article-related" aria-label="Related pickleball resources"><a href="/pickleball/home#pb-courts"><span>GET OUT THERE</span>Find a sourced court ↗</a><a href="/paddles"><span>THE RESEARCH DESK</span>Explore paddle evidence ↗</a><a href="https://tez-rally.pages.dev/tonight/"><span>PLAY WITH THE CREW</span>Run open play on RALLY ↗</a>${next ? `<a href="${safeUrl(next.url)}"><span>READ NEXT</span>${esc(next.title)} ↗</a>` : ''}</nav>
    </div></div><footer class="pbv2-article-footer"><a href="/pickleball/home">Back to the pickleball home ↑</a><span>PointCast Editorial · Practice generously.</span></footer>
  </article>`;
}
