/** @jsxRuntime classic */
import * as React from "react";
"use client";
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowDown, Download, Image as ImageIcon, Search, SlidersHorizontal, Check, ChartNoAxesColumn, Vote, ClipboardList } from 'lucide-react';
import { sampleCards, type CanvasItem, type ResearchResult, type ResearchPart } from './lib/canvas';
type Props={items:CanvasItem[];state:string;enabled:boolean;setEnabled:(v:boolean)=>void;canGenerate:boolean;imageBusy:boolean;onAnswer:(card:CanvasItem,answer:string)=>void;onImage:(card:CanvasItem)=>Promise<void>;onResearch:(card:CanvasItem)=>Promise<ResearchResult>;};
const icons={poll:Vote,slider:SlidersHorizontal,survey:ClipboardList,chart:ChartNoAxesColumn,confirmation:Check,image:ImageIcon,research:Search};
export function CanvasPanel(p:Props){
 const [samples,setSamples]=useState(false),[follow,setFollow]=useState(true),[answerNotice,setAnswerNotice]=useState('');
 const feed=useRef<HTMLDivElement>(null),last=useRef(0);
 const items=p.items.length?p.items:samples?sampleCards():[];
 useEffect(()=>{if(follow&&p.items.length>last.current&&feed.current)feed.current.scrollTop=feed.current.scrollHeight;last.current=p.items.length;},[p.items.length,follow]);
 return <section className="canvas-panel panel" aria-labelledby="canvas-title">
  <div className="panel-heading"><span className="eyebrow">THE CONVERSATION CANVAS</span><span className="canvas-count">{p.items.length?'LIVE CONVERSATION':samples?'SAMPLE / NO API COST':'READY'} · {items.length} pieces</span></div>
  <div className="canvas-heading"><h2 id="canvas-title">Ideas land here.</h2><button className="text-button" aria-pressed={p.enabled} onClick={()=>p.setEnabled(!p.enabled)}>{p.enabled?'Auto · on':'Auto · paused'}</button></div>
  <p className="section-note" role="status">{p.state} {p.enabled?'New pieces follow the conversation, usually in 15–30 seconds.':'Resume to create new pieces from the conversation.'}</p>
  <div className="canvas-feed" ref={feed} tabIndex={0} aria-label="Conversation canvas">
   {!items.length?<div className="canvas-welcome"><span className="ready-prompt">COME ON IN</span><h3>What shall we make?</h3><p>A picture. A question. A small possibility.</p><p>Start a call and think out loud. Or explore a few things this room can do.</p><button className="small-button" onClick={()=>setSamples(true)}>Explore the room</button></div>:items.map(card=><Piece key={card.id} card={card} canGenerate={p.canGenerate&&!card.sample} imageBusy={p.imageBusy} onAnswer={answer=>{if(card.sample){setAnswerNotice('Sample answer recorded here. A live call sends choices into the next canvas update.');return;}p.onAnswer(card,answer);setAnswerNotice('Your answer will shape the next canvas update.');}} onImage={()=>p.onImage(card)} onResearch={()=>p.onResearch(card)}/>)}
  </div>
  <div className="canvas-bottom"><button className="text-button" aria-pressed={follow} onClick={()=>{setFollow(!follow);if(!follow&&feed.current)feed.current.scrollTop=feed.current.scrollHeight;}}><ArrowDown size={14}/>{follow?'Following new pieces':'Follow new pieces'}</button><span>Kept in this page · resets with a new call</span></div>
  <p className="section-note" role="status">{answerNotice||'Choices inform the canvas. They do not send messages, spend money, or approve outside actions.'}</p>
 </section>;
}
function Piece({card:c,canGenerate,imageBusy,onAnswer,onImage,onResearch}:{card:CanvasItem;canGenerate:boolean;imageBusy:boolean;onAnswer:(s:string)=>void;onImage:()=>Promise<void>;onResearch:()=>Promise<ResearchResult>}){
 const [choice,setChoice]=useState(''),[value,setValue]=useState(c.value),[answers,setAnswers]=useState<string[]>([]),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[research,setResearch]=useState<ResearchResult|null>(null);
 const Icon=icons[c.kind];
 const respond=(s:string)=>{setChoice(s);onAnswer(s);};
 return <article className={'canvas-piece piece-'+c.kind}>
  <div className="piece-label"><span><Icon size={15}/>{c.kind==='confirmation'?'direction check':c.kind}</span><span>{c.sample?'SAMPLE':c.basis==='illustrative'?'ILLUSTRATIVE':'FROM THE CONVERSATION'}</span></div>
  <h3>{c.title}</h3><p className="piece-description">{c.text}</p>
  {c.kind==='poll'&&<div className="poll-options" role="group" aria-label={c.title}>{c.options.map(option=><button key={option} aria-pressed={choice===option} onClick={()=>respond(option)}><span>{choice===option?'■':'□'}</span>{option}</button>)}<small>{choice?'Your choice: '+choice:'One response in this browser. No group totals.'}</small></div>}
  {c.kind==='slider'&&<div className="canvas-slider"><output htmlFor={'range-'+c.id}>{value}{c.unit?' '+c.unit:''}</output><input id={'range-'+c.id} aria-label={c.title} type="range" min={c.min} max={c.max} step={c.step} value={value} onChange={e=>{setValue(Number(e.target.value));setSent(false);}}/><div className="range-labels"><span>{c.lowLabel||c.min}</span><span>{c.highLabel||c.max}</span></div><button className="small-button" disabled={sent} onClick={()=>{onAnswer(`${value} ${c.unit} on a range ${c.min}–${c.max} (${c.lowLabel} to ${c.highLabel})`);setSent(true);}}>{sent?'Choice recorded':'Use this setting'}</button></div>}
  {c.kind==='chart'&&<div className="canvas-chart" role="img" aria-label={c.title+'. '+c.points.map(p=>`${p.label}: ${p.value} ${c.unit}`).join(', ')}>{c.points.map((point,i)=>{const max=Math.max(...c.points.map(p=>Math.abs(p.value)),1);return <div key={i}><div><span>{point.label}</span><strong>{point.value.toLocaleString()} {c.unit}</strong></div><div className="chart-track"><span style={{width:`${Math.abs(point.value)/max*100}%`}}/></div></div>;})}<p className="section-note">{c.basis==='illustrative'?'Illustrative values to explore; not measured results.':'Values discussed in the conversation; not independently verified.'}</p></div>}
  {c.kind==='survey'&&<form className="canvas-survey" onSubmit={e=>{e.preventDefault();if(answers.filter(a=>a?.trim()).length<c.questions.length)return;onAnswer(c.questions.map((q,i)=>`${q} ${answers[i]}`).join('\n'));setSent(true);}}>{c.questions.map((q,i)=><label key={i}>{q}<textarea required maxLength={300} value={answers[i]||''} onChange={e=>{setAnswers(old=>{const next=[...old];next[i]=e.target.value;return next;});setSent(false);}}/></label>)}<button className="small-button" disabled={sent}>{sent?'Answers recorded':'Use these answers'}</button></form>}
  {c.kind==='confirmation'&&<div className="confirmation-options">{['Yes, this direction','Keep exploring'].map(option=><button key={option} className="small-button" aria-pressed={choice===option} onClick={()=>respond(option)}>{choice===option&&<Check size={15}/>} {option}</button>)}<small>Records a preference only. No external action.</small></div>}
  {c.kind==='image'&&<div className="canvas-image">{c.imageUrl?<><img src={c.imageUrl} alt={c.prompt}/><a href={c.imageUrl} download="shwa-canvas.webp"><Download size={15}/>Save image</a></>:<><p className="art-prompt">{c.prompt}</p><button className="small-button" disabled={!canGenerate||imageBusy||busy} onClick={()=>{setBusy(true);setError('');void onImage().catch(e=>setError(e.message||'Image unavailable')).finally(()=>setBusy(false));}}><ImageIcon size={16}/>{busy?'Making art…':'Make this image · ~0.5¢'}</button>{!canGenerate&&<small>{c.sample?'Sample prompt. Live conversation pieces can create images.':'Start a call to use image creation.'}</small>}</>}</div>}
  {c.kind==='research'&&<div className="canvas-research">{research?<div>{research.parts.map((part,i)=><p key={i} className="research-text"><CitedText part={part}/></p>)}<small>Web research via OpenAI · {new Date().toLocaleDateString()}</small></div>:<><p className="research-query">{c.prompt}</p><button className="small-button" disabled={!canGenerate||busy} onClick={()=>{setBusy(true);setError('');void onResearch().then(setResearch).catch(e=>setError(e.message||'Research unavailable')).finally(()=>setBusy(false));}}><Search size={16}/>{busy?'Looking it up…':'Research this · up to 2¢ + tokens'}</button>{!canGenerate&&<small>{c.sample?'Sample question. Live conversation pieces can search.':'Start a call to use research.'}</small>}</>}</div>}
  {error&&<p className="section-note attention" role="alert">{error}</p>}
 </article>;
}
export function CitedText({part}:{part:ResearchPart}){let at=0;const nodes:ReactNode[]=[];for(const c of part.citations){if(c.start<at)continue;nodes.push(part.text.slice(at,c.start));nodes.push(<a key={c.start} href={c.url} target="_blank" rel="noopener noreferrer" title={c.title}>[{c.title||new URL(c.url).hostname}]</a>);at=c.end;}nodes.push(part.text.slice(at));return <>{nodes}</>;}
