/** @jsxRuntime classic */
import * as React from "react";
"use client";
import { lazy, Suspense, useEffect, useRef, useState, type ReactNode } from 'react';
import { Sparkles, Music2, Download, Radio, X, MessageCircle, Image as ImageIcon, Layers, Wallet, ArrowUpRight } from 'lucide-react';
import { dollars, type Caption, type Notes, type Line } from './lib/station';
import { CanvasPanel } from './canvas-panel';
import type { CanvasItem, ResearchResult } from './lib/canvas';
import { RoomAccount, RoomMusic } from './account-panel';
const WalletPanel=lazy(()=>import('./wallet-panel').then(module=>({default:module.WalletPanel})));
type Props={canvas:CanvasItem[];canvasEnabled:boolean;setCanvasEnabled:(v:boolean)=>void;contextState:string;onActivity:(key:string,value:string)=>void;onAnswer:(card:CanvasItem,answer:string)=>void;onCanvasImage:(card:CanvasItem)=>Promise<void>;onResearch:(card:CanvasItem)=>Promise<ResearchResult>;phase:string;line:Line|null;message:string;seconds:number;muted:boolean;signals:{input:number;output:number;inputPath:string;outputPath:string};captions:Caption[];notes:Notes|null;notesState:string;costs:{voice:number;notes:number;images:number;research:number};prompt:string;setPrompt:(value:string)=>void;images:{url:string;prompt:string}[];imageState:string;imageBusy:boolean;canGenerate:boolean;generate:()=>void;children:ReactNode};
export function StationPanels(p:Props){
 const [focus,setFocus]=useState<'canvas'|'images'|'music'>('canvas'),[drawer,setDrawer]=useState<'thread'|'cost'|'wallet'|null>(null),[clock,setClock]=useState(Date.now()),[sceneOnly,setSceneOnly]=useState(false),[walletOpened,setWalletOpened]=useState(false);
 useEffect(()=>{if(drawer==='wallet')setWalletOpened(true);},[drawer]);
 useEffect(()=>{p.onActivity('view',sceneOnly?'The visitor is looking at the room scenery with tool panels tucked away.':'The visitor selected the '+focus+' panel. Images are at the top right on desktop and in the Images sheet on phones.');},[focus,sceneOnly,p.onActivity]);
 const thread=useRef<HTMLDivElement>(null),drawerRef=useRef<HTMLDivElement>(null),previousFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(thread.current)thread.current.scrollTop=thread.current.scrollHeight;},[p.captions,drawer]);
 useEffect(()=>{if(!drawer)return;previousFocus.current=document.activeElement as HTMLElement;drawerRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawer(null);if(e.key==='Tab'){const nodes=Array.from(drawerRef.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input,textarea,[tabindex="0"]')||[]).filter(node=>!node.closest('[hidden]'));if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===drawerRef.current||!drawerRef.current?.contains(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);previousFocus.current?.focus();};},[drawer]);
 const live=p.phase==='connected',input=live&&!p.muted&&p.signals.input>.055,output=live&&p.signals.output>.055;
 const activity=live?output?'Shwa is speaking':input?'Listening to you':p.muted?'Microphone muted':'I’m here. Take your time.':p.phase==='connecting'?'Opening the line…':p.phase==='ending'?'Closing the call…':p.line?.available?'A little room to think out loud.':'The line is resting.';
 const total=p.costs.voice+p.costs.notes+p.costs.images+p.costs.research,wait=p.line?.retryAt?Math.max(0,Math.ceil((p.line.retryAt-clock)/1000)):0;
 const last=p.captions.at(-1);
 function choose(next:typeof focus){setFocus(next);setSceneOnly(false);}
 return <main className={'shwa-room room-focus-'+focus+' phase-'+p.phase+(sceneOnly?' scene-only':'')}>
  <div className="room-landscape" aria-hidden="true"/><div className="room-shade" aria-hidden="true"/>
  <header className="room-header"><div className="room-identity"><a href="/" className="pointcast-back">POINTCAST <ArrowUpRight size={11}/></a><h1>shwa<span>a little room for possibility</span></h1></div><div className="room-header-actions"><button className="cost-chip" onClick={()=>setDrawer('cost')} aria-label={'Estimated cost '+dollars(total)}>{dollars(total)} <span>est.</span></button><RoomAccount onActivity={p.onActivity} live={live||p.phase==='connecting'||p.phase==='ending'}/></div></header>
  <div className="room-coordinate"><span className={'room-light '+(live?'on':'')}/>{live?'SHWA IS HERE':'SOMEWHERE BETWEEN IDEAS'}<button onClick={()=>setSceneOnly(!sceneOnly)} aria-pressed={sceneOnly}>{sceneOnly?'Show the room':'Just the view'}</button></div>
  <button className="mobile-image-peek" onClick={()=>choose('images')} aria-label="Open image studio">{p.images[0]?<img src={p.images[0].url} alt="Latest generated image"/>:<ImageIcon size={22}/>}<span>{p.imageBusy?'Creating…':p.images.length?'New image':'Picture an idea'}</span></button>
  <div className="room-workspace">
   <div className="room-canvas-zone"><CanvasPanel items={p.canvas} state={p.notesState} enabled={p.canvasEnabled} setEnabled={p.setCanvasEnabled} canGenerate={p.canGenerate} imageBusy={p.imageBusy} onAnswer={p.onAnswer} onImage={p.onCanvasImage} onResearch={p.onResearch}/>{p.notes&&<div className="room-thought"><span>IN THE AIR</span><p>{p.notes.summary}</p><div>{p.notes.topics.slice(0,3).map(topic=><button key={topic} onClick={()=>{p.setPrompt('Create an image inspired by '+topic);choose('images');}}>{topic}<ArrowUpRight size={12}/></button>)}</div></div>}</div>
   <aside className="room-image-zone panel" aria-labelledby="image-title"><div className="panel-heading"><span className="eyebrow"><Sparkles size={14}/> IMAGE STUDIO</span><span>{p.images.length?`${p.images.length} made`:'OPENAI'}</span></div><h2 id="image-title">Let’s see it.</h2>
    {p.images[0]?<div className="generated-image"><img src={p.images[0].url} alt={p.images[0].prompt}/><a href={p.images[0].url} download="shwa.webp" aria-label="Save generated image"><Download size={18}/></a></div>:<div className={'image-empty '+(p.imageBusy?'is-making':'')}><div className="image-spark"><Sparkles size={25}/></div><p>{p.imageBusy?'Something is taking shape…':'From a passing thought\nto something you can keep.'}</p></div>}
    {p.images.length>1&&<div className="image-history" aria-label="Images from this call">{p.images.slice(1).map((image,i)=><a key={i} href={image.url} download={'shwa-'+(i+1)+'.webp'}><img src={image.url} alt={image.prompt}/></a>)}</div>}
    {p.notes?.imageIdea&&<button className="idea-button" onClick={()=>p.setPrompt(p.notes!.imageIdea)}><Sparkles size={13}/>Use the idea we’re talking about</button>}
    <label className="sr-only" htmlFor="image-prompt">Describe an image</label><textarea id="image-prompt" value={p.prompt} maxLength={1600} onChange={event=>p.setPrompt(event.target.value)} placeholder="A tiny world, an impossible room…" rows={2}/><div className="image-actions"><button className="small-button primary" disabled={!p.canGenerate||!p.prompt.trim()||p.imageBusy} onClick={p.generate}><Sparkles size={15}/>{p.imageBusy?'Creating…':'Create image'}</button><span>~0.5¢ + prompt</span></div><p className="section-note image-status" role="status">{p.imageState||(!p.canGenerate?'Start a call, then make something together.':'Two image attempts per call. Tap when you’re ready.')}</p>
   </aside>
   <aside className="room-music-zone panel"><RoomMusic onActivity={p.onActivity} live={live||p.phase==='connecting'||p.phase==='ending'}/></aside>
  </div>
  <div className="room-conversation"><button className="floating-caption" onClick={()=>setDrawer('thread')} aria-label="Open conversation transcript"><span>{last?(last.speaker==='you'?'YOU':'SHWA'):'SHWA'}</span><p>{last?last.text:activity}</p><MessageCircle size={16}/></button><p className="room-context" role="status">{live?p.contextState:'Voice, images, research & a few happy accidents.'}</p></div>
  <nav className="room-tabs" aria-label="Room tools"><button aria-pressed={focus==='canvas'&&!sceneOnly} onClick={()=>choose('canvas')}><Layers size={17}/>Canvas{p.canvas.length>0&&<b>{p.canvas.length}</b>}</button><button aria-pressed={focus==='images'&&!sceneOnly} onClick={()=>choose('images')}><ImageIcon size={17}/>Images{p.imageBusy&&<i/>}</button><button aria-pressed={focus==='music'&&!sceneOnly} onClick={()=>choose('music')}><Music2 size={17}/>Music</button><button onClick={()=>setDrawer('wallet')} aria-label="Open wallet"><Wallet size={17}/><span>Wallet</span></button></nav>
  <section className="room-call-dock" aria-label="Talk with Shwa"><div className="call-presence"><div className={'signal-dot '+(live?'live':'')}/><div><strong>Shwa</strong><span>{live?(Math.floor(p.seconds/60)+':'+String(p.seconds%60).padStart(2,'0')+' left'):'AI companion'}</span></div><svg viewBox="0 0 320 72" preserveAspectRatio="none" aria-label="Live voice activity"><polyline points={output?p.signals.outputPath:p.signals.inputPath} fill="none"/></svg></div><div className="compact-call">{p.children}</div><button className="thread-button" onClick={()=>setDrawer('thread')} aria-label="Read conversation"><MessageCircle size={19}/></button></section>
  <p className={'room-call-notice '+(p.phase==='error'?'attention':'')} role="status">{p.message}{wait>0&&` Try again in ${Math.floor(wait/60)}:${String(wait%60).padStart(2,'0')}.`}</p>
  {(drawer||walletOpened)&&<div hidden={!drawer} style={{display:drawer?'flex':'none'}} className="room-modal-backdrop" onClick={()=>setDrawer(null)}><div className="room-drawer panel" role="dialog" aria-modal="true" aria-label={drawer==='thread'?'Conversation':drawer==='cost'?'Cost of this visit':'Wallet'} tabIndex={-1} ref={drawerRef} onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setDrawer(null)} aria-label="Close panel"><X size={20}/></button>{drawer==='thread'?<><span className="eyebrow">THE LIVE THREAD</span><h2>As it happens.</h2><div className="caption-feed" ref={thread}>{p.captions.length?p.captions.map(row=><div key={row.id} className={'caption '+row.speaker}><span>{row.speaker==='you'?'YOU':'SHWA'}</span><p>{row.text}</p></div>):<p>Start talking. Both voices appear here.</p>}</div><p className="section-note">Captions can contain errors. Kept in this page only; cleared with each new call. OpenAI processes audio and live notes.</p></>:drawer==='cost'?<><span className="eyebrow">THIS VISIT</span><h2>{dollars(total)} <small>estimated</small></h2><dl className="cost-details">{Object.entries(p.costs).map(([key,value])=><div key={key}><dt>{key==='notes'?'Notes + canvas':key}</dt><dd>{dollars(value)}</dd></div>)}</dl><p className="section-note">Voice is estimated at 5¢ per minute. Unfinished requests and extra voice reasoning may add charges; final billing can differ. Wallet payments are separate.</p><p className="section-note">{p.line?.remainingCalls??'—'} trial calls remain. Each call lasts up to two minutes.</p></>:null}{walletOpened&&<div hidden={drawer!=='wallet'}><Suspense fallback={<p>Opening wallet…</p>}><WalletPanel/></Suspense></div>}</div></div>}
 </main>;
}
