/** @jsxRuntime classic */
import * as React from "react";
"use client";
import { lazy, Suspense, useEffect, useRef, useState, type ReactNode } from 'react';
import { Sparkles, Music2, Download, Radio, X, MessageCircle, Image as ImageIcon, Layers, Wallet, ArrowUpRight, Grid2X2, BookOpen, Waves, Pencil, Check, Pause, Play, Users } from 'lucide-react';
import { dollars, type Caption, type Notes, type Line } from './lib/station';
import { CanvasPanel } from './canvas-panel';
import type { CanvasItem, ResearchResult } from './lib/canvas';
import { RoomAccount, RoomMusic } from './account-panel';
import type { VoicePlaybackState } from "./lib/voice-playback";
import { VoiceOverview } from './voice-overview';
import { useSharedRoom, SharedRoomBoard } from './shared-room';
type Background='studio'|'grid'|'reading'|'radio';
const backgroundNames:Record<Background,string>={studio:'Studio',grid:'Grid',reading:'Reading',radio:'Radio'};
const backgroundHelp:Record<Background,string>={studio:'Room to wander. Pin the ideas worth keeping.',grid:'Line ideas up. Compare, choose, and make a plan.',reading:'A quiet page. More room for every thought.',radio:'Tune into the conversation. Watch each voice travel.'};
const WalletPanel=lazy(()=>import('./wallet-panel').then(module=>({default:module.WalletPanel})));
type Props={workState?:string;voicePlayback?:VoicePlaybackState;onRetrySound?:()=>void;canvas:CanvasItem[];canvasEnabled:boolean;setCanvasEnabled:(v:boolean)=>void;contextState:string;onActivity:(key:string,value:string)=>void;onAnswer:(card:CanvasItem,answer:string)=>void;onCanvasImage:(card:CanvasItem)=>Promise<void>;onResearch:(card:CanvasItem)=>Promise<ResearchResult>;phase:string;line:Line|null;message:string;seconds:number;muted:boolean;signals:{input:number;output:number;inputPath:string;outputPath:string};captions:Caption[];notes:Notes|null;notesState:string;costs:{voice:number;reasoning?:number;notes:number;images:number;research:number};prompt:string;setPrompt:(value:string)=>void;images:{url:string;prompt:string}[];imageState:string;imageBusy:boolean;canGenerate:boolean;generate:(prompt?:string)=>void;children:ReactNode};
export function StationPanels(p:Props){
 const group=useSharedRoom(),[groupOpen,setGroupOpen]=useState(()=>!!(typeof window!=='undefined'&&window.location.hash.includes('room=')));
 useEffect(()=>{p.onActivity('room',group.room?`This browser joined a room with ${group.room.members.length} humans. They share a text board and votes. Voice is local to this browser. Each participant chooses a resource preference, not a funding authorization. Shared text is sent only when this visitor chooses Discuss with Shwa.`:'This visitor is on their own board.');},[group.room?.members.length,p.onActivity]);
 const [focus,setFocus]=useState<'canvas'|'images'|'music'>('canvas'),[drawer,setDrawer]=useState<'thread'|'cost'|'wallet'|'voice'|null>(null),[clock,setClock]=useState(Date.now()),[sceneOnly,setSceneOnly]=useState(false),[walletOpened,setWalletOpened]=useState(false);
 const [micPreview,setMicPreview]=useState({active:false,level:0,path:'0,36 320,36'});
 const [background,setBackground]=useState<Background>(()=>{try{const saved=localStorage.getItem('pc:shwa:background:v1');return saved&&Object.hasOwn(backgroundNames,saved)?saved as Background:'studio';}catch{return 'studio';}}),[motion,setMotion]=useState(true),[tuning,setTuning]=useState(50),[backdrop,setBackdrop]=useState(''),[editingImage,setEditingImage]=useState(false);
 useEffect(()=>{try{localStorage.setItem('pc:shwa:background:v1',background);}catch{}},[background]);
 useEffect(()=>{if(!p.images.some(image=>image.url===backdrop))setBackdrop('');},[p.images,backdrop]);
 useEffect(()=>{if(drawer==='wallet')setWalletOpened(true);},[drawer]);
 useEffect(()=>{p.onActivity('view',sceneOnly?'The visitor tucked away the board to look at the background.':`The visitor is using the ${backgroundNames[background]} background: ${backgroundHelp[background]} Selected tool: ${focus}. The desktop board scrolls as a whole. Image ideas have a Greenlight button underneath; images require that explicit click. Radio waves are visual feedback, not an actual broadcast.`);},[focus,sceneOnly,background,p.onActivity]);
 const thread=useRef<HTMLDivElement>(null),drawerRef=useRef<HTMLDivElement>(null),previousFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(thread.current)thread.current.scrollTop=thread.current.scrollHeight;},[p.captions,drawer]);
 useEffect(()=>{if(!drawer)return;previousFocus.current=document.activeElement as HTMLElement;drawerRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawer(null);if(e.key==='Tab'){const nodes=Array.from(drawerRef.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input,textarea,[tabindex="0"]')||[]).filter(node=>!node.closest('[hidden]'));if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===drawerRef.current||!drawerRef.current?.contains(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);previousFocus.current?.focus();};},[drawer]);
 const live=p.phase==='connected',input=live&&!p.muted&&p.signals.input>.055,output=live&&p.signals.output>.055;
 const activity=live?output?'Shwa is speaking':input?'Listening to you':p.muted?'Microphone muted':'I’m here. Take your time.':p.phase==='connecting'?'Opening the line…':p.phase==='ending'?'Closing the call…':p.line?.available?'A little room to think out loud.':'The line is resting.';
 const total=p.costs.voice+(p.costs.reasoning||0)+p.costs.notes+p.costs.images+p.costs.research,wait=p.line?.retryAt?Math.max(0,Math.ceil((p.line.retryAt-clock)/1000)):0;
 const last=p.captions.at(-1),effectivePrompt=p.prompt.trim()||p.notes?.imageIdea||'',latestImage=p.images[0];
 const signalMode=live?(output?'transmitting':input?'receiving':'quiet'):micPreview.active?'testing':'ambient';
 function useBackdrop(){if(!latestImage||!/^data:image\/webp;base64,[A-Za-z0-9+/=]+$/.test(latestImage.url))return;setBackdrop(latestImage.url);setBackground('studio');p.onActivity('view','The visitor set their generated image as the Studio background. You know its prompt, not its pixels: '+latestImage.prompt);}
 function choose(next:typeof focus){setFocus(next);setSceneOnly(false);if(next==='images')document.getElementById('image-title')?.scrollIntoView({block:'nearest'});}
 return <main className={'shwa-room room-focus-'+focus+' phase-'+p.phase+' board-'+background+(motion?'':' motion-paused')+(sceneOnly?' scene-only':'')}>
  <div className="room-landscape" aria-hidden="true" style={backdrop?{backgroundImage:`url("${backdrop}")`}:undefined}/><div className={"radio-field signal-"+signalMode} aria-hidden="true" style={{"--signal-strength":live?Math.min(1,Math.max(p.signals.input,p.signals.output)*3):micPreview.active?Math.min(1,micPreview.level*3):.35,"--wave-time":(14-tuning/10)+"s","--wave-size":(50+tuning/2)+"vw"} as React.CSSProperties}><div className="radio-origin"><i/><i/><i/><i/><i/></div><div className="radio-horizon"/><div className="radio-grain"/></div><div className="room-shade" aria-hidden="true"/>
  <header className="room-header"><div className="room-identity"><a href="/" className="pointcast-back">POINTCAST <ArrowUpRight size={11}/></a><h1>shwa<span>a little room for possibility</span></h1></div><div className="room-header-actions"><button className="room-group-button" aria-pressed={groupOpen} onClick={()=>{setGroupOpen(group.room?true:!groupOpen);choose('canvas');document.querySelector('.room-workspace')?.scrollTo({top:0,behavior:'smooth'});}}><Users size={15}/>{group.room?group.room.members.length+'/5':'For five'}</button><button className="cost-chip" onClick={()=>setDrawer('cost')} aria-label={'Estimated cost '+dollars(total)}>{dollars(total)} <span>est.</span></button><RoomAccount onActivity={p.onActivity} live={live||p.phase==='connecting'||p.phase==='ending'}/></div></header>
  <div className="board-toolbar">
   <div className="background-switch" role="group" aria-label="Functional backgrounds">{(Object.keys(backgroundNames) as Background[]).map(name=>{const Icon=name==='studio'?Layers:name==='grid'?Grid2X2:name==='reading'?BookOpen:Radio;return <button key={name} aria-pressed={background===name} onClick={()=>{setBackground(name);setSceneOnly(false);}}><Icon size={15}/>{backgroundNames[name]}</button>;})}</div>
   <p className="background-purpose">{backgroundHelp[background]}</p>
   <button className="board-view-toggle" onClick={()=>setSceneOnly(!sceneOnly)} aria-pressed={sceneOnly}>{sceneOnly?'Show the board':'Just the background'}</button>
  </div>
  <div className="radio-tuner"><span className={'room-light '+(live?'on':'')}/><span>{live?output?'SHWA · VOICE SIGNAL':input?'YOU · VOICE SIGNAL':'CONNECTED · QUIET':micPreview.active?'LOCAL MICROPHONE · NOT SENT':'AMBIENT · VISUAL PREVIEW'}</span><label htmlFor="radio-tuning">Wavelength<input id="radio-tuning" aria-label="Visual wavelength" type="range" min="0" max="100" value={tuning} onChange={event=>setTuning(Number(event.target.value))}/></label><button aria-label={motion?'Pause background animation':'Play background animation'} onClick={()=>setMotion(!motion)}>{motion?<Pause size={14}/>:<Play size={14}/>}</button></div>
  <button className="mobile-image-peek" onClick={()=>choose('images')} aria-label="Open image studio">{p.images[0]?<img src={p.images[0].url} alt="Latest generated image"/>:<ImageIcon size={22}/>}<span>{p.imageBusy?'Creating…':p.images.length?'New image':'Picture an idea'}</span></button>
  <div className="room-workspace">
   <div className="room-canvas-zone"><SharedRoomBoard group={group} open={groupOpen} setOpen={setGroupOpen} houseAvailable={!!p.line?.available} onImageIdea={text=>{p.setPrompt(text);setEditingImage(true);choose('images');}} onDiscuss={text=>p.onActivity('shared-choice',text)} onWallet={()=>setDrawer('wallet')} latestNote={p.notes?.summary}/><CanvasPanel background={background} items={p.canvas} state={p.workState||p.notesState} enabled={p.canvasEnabled} setEnabled={p.setCanvasEnabled} canGenerate={p.canGenerate} imageBusy={p.imageBusy} onAnswer={p.onAnswer} onImage={p.onCanvasImage} onResearch={p.onResearch}/>{p.notes&&<div className="room-thought"><span>IN THE AIR</span><p>{p.notes.summary}</p><div>{p.notes.topics.slice(0,3).map(topic=><button key={topic} onClick={()=>{p.setPrompt('Create an image inspired by '+topic);choose('images');}}>{topic}<ArrowUpRight size={12}/></button>)}</div></div>}</div>
   <aside className="room-image-zone" aria-labelledby="image-title">
    <div className="image-board-label"><span><Sparkles size={14}/> IMAGE STUDIO</span><span>{p.imageBusy?'DEVELOPING':latestImage?'MADE WITH OPENAI':'AN IDEA, THEN AN IMAGE'}</span></div>
    <div className="image-paper"><h2 id="image-title">{latestImage?'Look what turned up.':'Picture this.'}</h2>
     {latestImage?<div className="generated-image"><img src={latestImage.url} alt={latestImage.prompt}/></div>:<div className={'image-empty '+(p.imageBusy?'is-making':'')}><div className="image-spark"><Sparkles size={28}/></div><p>{p.imageBusy?'Your image is taking shape…':effectivePrompt?'An image idea is ready below.':'A thought becomes a picture.'}</p><small>{p.imageBusy?'OpenAI is generating it.':'Greenlight an idea to generate it.'}</small></div>}
     <p className="image-idea-text">{latestImage?.prompt||effectivePrompt||'As we talk, Shwa will suggest something to see. You can also write an idea of your own.'}</p>
    </div>
    <div className="image-actions"><button className="small-button greenlight" disabled={!p.canGenerate||!effectivePrompt||p.imageBusy} onClick={()=>p.generate(effectivePrompt)}><Check size={16}/>{p.imageBusy?'Generating…':'Greenlight image'}<span>~0.5¢</span></button><button className="small-button image-edit" aria-expanded={editingImage} onClick={()=>setEditingImage(!editingImage)}><Pencil size={14}/>{editingImage?'Close editor':'Edit idea'}</button></div>
    {editingImage&&<div className="image-editor"><label htmlFor="image-prompt">Your image idea</label><textarea id="image-prompt" value={p.prompt} maxLength={1600} onChange={event=>p.setPrompt(event.target.value)} placeholder={p.notes?.imageIdea||'A tiny world, an impossible room…'} rows={3}/>{p.notes?.imageIdea&&<button className="idea-button" onClick={()=>p.setPrompt(p.notes!.imageIdea)}><Sparkles size={13}/>Use the conversation’s idea</button>}</div>}
    {latestImage&&<div className="image-keep-actions"><a className="small-button" href={latestImage.url} download="shwa.webp"><Download size={14}/>Save image</a><button className="small-button" onClick={useBackdrop} aria-pressed={backdrop===latestImage.url}><ImageIcon size={14}/>Use as backdrop</button>{backdrop&&<button className="text-button" onClick={()=>setBackdrop('')}>Restore island</button>}</div>}
    {p.images.length>1&&<div className="image-history" aria-label="Images from this call">{p.images.slice(1).map((image,i)=><a key={i} href={image.url} download={'shwa-'+(i+1)+'.webp'}><img src={image.url} alt={image.prompt}/></a>)}</div>}
    <p className="section-note image-status" role="status">{p.imageState||(!p.canGenerate?(p.line?.available?'Start a call to generate. Your idea will stay here.':'Image generation needs an eligible call. You can still prepare an idea.'):'Greenlight generates one image. Two attempts per call; prompt cost is extra.')}</p>
   </aside>
   <aside className="room-music-zone panel"><RoomMusic onActivity={p.onActivity} live={live||p.phase==='connecting'||p.phase==='ending'}/></aside>
  </div>
  <div className="room-conversation"><button className="floating-caption" onClick={()=>setDrawer('thread')} aria-label="Open conversation transcript"><span>{last?(last.speaker==='you'?'YOU':'SHWA'):'SHWA'}</span><p>{last?last.text:activity}</p><MessageCircle size={16}/></button><p className="room-context" role="status">{live?(p.workState||p.contextState):'Voice, images, research & a few happy accidents.'}</p></div>
  <nav className="room-tabs" aria-label="Room tools"><button aria-pressed={focus==='canvas'&&!sceneOnly} onClick={()=>choose('canvas')}><Layers size={17}/>Board{p.canvas.length>0&&<b>{p.canvas.length}</b>}</button><button aria-pressed={focus==='images'&&!sceneOnly} onClick={()=>choose('images')}><ImageIcon size={17}/>Images{p.imageBusy&&<i/>}</button><button aria-pressed={focus==='music'&&!sceneOnly} onClick={()=>choose('music')}><Music2 size={17}/>Music</button><button onClick={()=>{setBackground('radio');setDrawer('voice');}} aria-label="Voice overview"><Radio size={17}/>Voice</button><button onClick={()=>setDrawer('wallet')} aria-label="Open wallet"><Wallet size={17}/><span>Wallet</span></button></nav>
  <section className="room-call-dock" aria-label="Talk with Shwa"><div className="call-presence"><div className={'signal-dot '+(live?'live':'')}/><div><strong>Shwa</strong><span>{live?(Math.floor(p.seconds/60)+':'+String(p.seconds%60).padStart(2,'0')+' left'):'AI companion'}</span></div><svg viewBox="0 0 320 72" preserveAspectRatio="none" aria-label="Live voice activity"><polyline points={output?p.signals.outputPath:p.signals.inputPath} fill="none"/></svg></div><div className="compact-call">{p.children}</div><button className="thread-button" onClick={()=>setDrawer('thread')} aria-label="Read conversation"><MessageCircle size={19}/></button></section>
  <p className={'room-call-notice '+(p.phase==='error'?'attention':'')} role="status">{live&&p.voicePlayback&&['blocked','interrupted','ended'].includes(p.voicePlayback.status)?'Sound needs attention · tap the speaker or open Voice.':p.message}{wait>0&&` Try again in ${Math.floor(wait/60)}:${String(wait%60).padStart(2,'0')}.`}</p>
  {(drawer||walletOpened)&&<div hidden={!drawer} style={{display:drawer?'flex':'none'}} className={'room-modal-backdrop'+(drawer==='voice'?' voice-overview-backdrop':'')} onClick={()=>setDrawer(null)}><div className="room-drawer panel" role="dialog" aria-modal="true" aria-label={drawer==='thread'?'Conversation':drawer==='cost'?'Cost of this visit':drawer==='voice'?'Voice overview':'Wallet'} tabIndex={-1} ref={drawerRef} onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setDrawer(null)} aria-label="Close panel"><X size={20}/></button>{drawer==='thread'?<><span className="eyebrow">THE LIVE THREAD</span><h2>As it happens.</h2><div className="caption-feed" ref={thread}>{p.captions.length?p.captions.map(row=><div key={row.id} className={'caption '+row.speaker}><span>{row.speaker==='you'?'YOU':'SHWA'}</span><p>{row.text}</p></div>):<p>Start talking. Both voices appear here.</p>}</div><p className="section-note">Captions can contain errors. Kept in this page only; cleared with each new call. OpenAI processes audio and live notes.</p></>:drawer==='cost'?<><span className="eyebrow">THIS VISIT</span><h2>{dollars(total)} <small>estimated</small></h2><dl className="cost-details">{Object.entries(p.costs).map(([key,value])=><div key={key}><dt>{key==='notes'?'Notes + canvas':key==='reasoning'?'Astra reasoning':key}</dt><dd>{dollars(value)}</dd></div>)}</dl><p className="section-note">Voice is estimated at 5¢ per minute. Astra reasoning uses reported tokens at $10/M input, $1/M cached input, and $50/M output. Unfinished requests or missing usage may add charges; final billing can differ. Wallet payments are separate.</p><p className="section-note">{p.line?.remainingCalls??'—'} trial calls remain. Each call lasts up to two minutes.</p></>:drawer==='voice'?<VoiceOverview live={live||p.phase==='connecting'||p.phase==='ending'} onPreview={setMicPreview} callAudio={live?{playback:p.voicePlayback,heardYou:p.captions.some(row=>row.speaker==='you'),replySeen:p.captions.some(row=>row.speaker!=='you'),retry:p.onRetrySound}:undefined}/>:null}{walletOpened&&<div hidden={drawer!=='wallet'}><Suspense fallback={<p>Opening wallet…</p>}><WalletPanel/></Suspense></div>}</div></div>}
 </main>;
}
