import data from './public.json' with {type:'json'};
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const source=id=>data.sources.find(s=>s.id===id);
const link=(id,label)=>`<a href="${escape(source(id).url)}" rel="noopener">${escape(label||source(id).title)} ↗</a>`;
const pixelMark=(label,index)=>`<svg viewBox="0 0 96 64" aria-hidden="true"><rect x="8" y="8" width="80" height="48" fill="none" stroke="currentColor" stroke-width="4"/><path d="M48 8v48M8 32h80M8 24h80M8 40h80" fill="none" stroke="currentColor" stroke-width="2"/><rect x="${16+index*16}" y="${index%2?42:14}" width="8" height="8" fill="currentColor"/></svg>`;
export function renderPaddleCourtStation(){
 const p=data.publication;const card=data.interactive_court_card;const product=data.official_product_card;
 const note=p.source_reading_note||p.related_reading_note;
 const reading=data.sourceReadingPending?`<div class="paddle-reading-grid"><article><p class="paddle-kicker">REQUESTED READING / VERIFICATION PENDING</p><h3>${escape(source('johnkew-newsletter').title)}</h3><p>${escape(source('johnkew-newsletter').access_note)} We have not inferred its two thresholds from the headline.</p>${link('johnkew-newsletter',p.reading_cta.label)}</article>${note?`<article><p class="paddle-kicker">SEPARATE SOURCE / SEPTEMBER 30, 2026</p><h3>${escape(note.title)}</h3><p>${escape(note.text)}</p><p class="paddle-disclosure">${escape(note.scope_note)}</p>${link(note.source_id)}</article>`:''}</div>`:`<article class="paddle-verified-reading"><p class="paddle-kicker">ATTRIBUTED READING / VERIFIED PUBLIC NEWSLETTER</p><h3>${escape(note?.title||source('johnkew-newsletter').title)}</h3><p>${escape(note?.text||'')}</p>${note?.scope_note?`<p class="paddle-disclosure">${escape(note.scope_note)}</p>`:''}${link('johnkew-newsletter',p.reading_cta.label)}</article>`;
 return `<section class="paddle-station" id="paddle-court-station" data-paddle-court aria-labelledby="paddle-station-title">
 <header class="paddle-station-header"><div><p class="paddle-kicker">${escape(p.hero_kicker)} / ORIGINAL COURT METHOD</p><h2 id="paddle-station-title">${escape(p.title)}</h2><p>${escape(p.subtitle)}</p></div><a class="paddle-button" href="#paddle-court-card">Open the court card ↓</a></header>
 <p class="paddle-disclosure">${escape(p.disclosure)}</p>
 ${reading}
 <details class="paddle-product"><summary>Manufacturer record: ${escape(product.title)} · checked ${escape(product.as_of_date)}</summary><p><strong>$${product.listed_price.amount.toFixed(2)} ${escape(product.listed_price.currency)}</strong> — ${escape(product.listed_price.label)}</p><dl class="paddle-specs">${product.specifications.map(s=>`<div><dt>${escape(s.label)}</dt><dd>${escape(s.value)}${s.note?`<small>${escape(s.note)}</small>`:''}</dd></div>`).join('')}</dl><p>${link(product.source_id,'Official product specifications')}</p>${product.certification_records.map(r=>`<p><strong>${escape(r.body)}:</strong> ${escape(r.status)}. ${escape(r.model)}${r.model_number?` (${escape(r.model_number)})`:''}; added ${escape(r.added_date)}. ${link(r.source_id)}${r.verification_note?`<span class="paddle-disclosure">${escape(r.verification_note)}</span>`:''}</p>`).join('')}<p class="paddle-disclosure">${escape(product.certification_caution)}</p></details>
 <div class="paddle-method">${p.method.map((s,i)=>`<details class="paddle-method-step"${i===0?' open':''}><summary>${escape(s.title)}</summary>${s.paragraphs.map(text=>`<p>${escape(text)}</p>`).join('')}</details>`).join('')}</div>
 <section class="paddle-court-card" id="paddle-court-card" aria-labelledby="paddle-card-title"><p class="paddle-kicker">CURRENT-TAB WORKSHEET / SELF-REPORTED</p><h3 id="paddle-card-title">${escape(card.title)}</h3><p>Use the same A, B, B, A blocks and twenty attempts per station. Enter successes as whole numbers from 0 to 20. Blank fields are missing data. The weights are PointCast’s proposed preferences.</p><p class="paddle-disclosure">${escape(card.storage)}</p>
 <div class="paddle-print-setup"><p>Blank court worksheet / proposed personal comparison</p><p>Paddle A model / thickness / setup: __________________________</p><p>Paddle B model / thickness / setup: __________________________</p><p>Ball, court and conditions: _________________________________</p><p>Feed setup / replayed feeds: _________________________________</p></div><div class="paddle-station-grid">${card.fields.map((s,i)=>`<fieldset><legend>${escape(s.label)} · ${s.weight}% weight</legend>${pixelMark(s.label,i)}<p>${escape(s.success_label)} / ${s.attempts} attempts</p>${['a','b'].map(paddle=>`<label for="court-${paddle}-${s.id}">Paddle ${paddle.toUpperCase()} successes<input type="number" id="court-${paddle}-${s.id}" data-court-count data-paddle="${paddle}" data-station="${s.id}" min="0" max="20" step="1" inputmode="numeric" autocomplete="off" aria-describedby="court-${paddle}-${s.id}-error"/><span class="paddle-field-error" id="court-${paddle}-${s.id}-error" hidden>Use a whole number from 0 to 20.</span></label>`).join('')}</fieldset>`).join('')}</div>
 <p class="paddle-formula">Score = 30 × CONTROL / 20 + 35 × RESET / 20 + 20 × HANDS / 20 + 15 × CHOOSE / 20</p>
 <div class="paddle-actions"><button type="button" class="paddle-button" data-court-calculate>Calculate</button><button type="button" data-court-demo>Load fictional example</button><button type="button" data-court-clear>Clear card</button><button type="button" data-court-print>Print blank court card</button></div>
 <p data-court-mode class="paddle-disclosure">Your own observations. No fictional data loaded.</p><p data-court-status role="status" aria-live="polite">${escape(card.empty_state)}</p><div data-court-result></div>
 <div class="paddle-notes">${card.notes_fields.map((label,i)=>`<label for="court-note-${i}">${escape(label)}<textarea id="court-note-${i}" maxlength="280" rows="2" placeholder="Practice cue only — optional"></textarea></label>`).join('')}</div><p class="paddle-disclosure">${escape(card.score_interpretation)}</p><noscript><p>The complete method and blank tally card work without JavaScript. Calculate with the formula above; interactive calculation and printing need JavaScript.</p></noscript></section>
 <details class="paddle-source-trail"><summary>Sources and verification limits · checked October 6, 2026</summary><ol>${data.sources.map(s=>`<li>${link(s.id)}<p>${escape(s.publisher)} · ${escape(s.published_date||s.checked_date)}</p>${s.author_byline?`<p>${escape(s.author_byline)} · signed ${escape(s.signed_by)}</p>`:''}${s.id==='johnkew-newsletter'?'':s.supports.map(text=>`<p>${escape(text)}</p>`).join('')}${s.access_note?`<p>${escape(s.access_note)}</p>`:''}${s.scope?`<p>${escape(s.scope)}</p>`:''}</li>`).join('')}</ol></details>
 </section>`;
}
