import { c as createComponent } from './astro-component_DWMcTjG3.mjs';
import 'piccolore';
import { m as maybeRenderHead, b as addAttribute, a as renderTemplate } from './prerender_CmTjnOuJ.mjs';
import 'clsx';

const $$DrumNav = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$props, $$slots);
  Astro2.self = $$DrumNav;
  const { current } = Astro2.props;
  const links = [
    { id: "v1", href: "/drum", label: "classic", sub: "v1" },
    { id: "v2", href: "/drum-v2", label: "collab", sub: "v2" },
    { id: "v3", href: "/drum-v3", label: "spotify", sub: "v3" },
    { id: "v4", href: "/drum-v4", label: "orchestra", sub: "v4" },
    { id: "v5", href: "/drum-v5", label: "loops", sub: "v5" },
    { id: "v6", href: "/drum-v6", label: "choir", sub: "v6" },
    { id: "v7", href: "/drum-v7", label: "big", sub: "v7 · 30" },
    { id: "v8", href: "/drum-v8", label: "symphony", sub: "v8 · 42" },
    { id: "v9", href: "/drum-v9", label: "lounge", sub: "v9 · sax" },
    { id: "v10", href: "/drum-v10", label: "theremin", sub: "v10 · gesture" },
    { id: "v11", href: "/drum-v11", label: "bells", sub: "v11 · chimes" },
    { id: "v12", href: "/drum-v12", label: "organ", sub: "v12 · pipes" },
    { id: "v13", href: "/drum-v13", label: "strings", sub: "v13 · pizz/arco" },
    { id: "v14", href: "/drum-v14", label: "marimba", sub: "v14 · mallets" },
    { id: "v15", href: "/drum-v15", label: "hang", sub: "v15 · handpan" },
    { id: "v16", href: "/drum-v16", label: "808", sub: "v16 · machine" },
    { id: "v17", href: "/drum-v17", label: "harp", sub: "v17 · gliss" },
    { id: "v18", href: "/drum-v18", label: "rhodes", sub: "v18 · ep" },
    { id: "potato", href: "/drum-potato", label: "potato", sub: "game" },
    { id: "jam", href: "/drum-jam", label: "jam", sub: "3+ jams" },
    { id: "pulse", href: "/drum-pulse", label: "pulse", sub: "heartbeat" },
    { id: "agents", href: "/drum-agents", label: "agents", sub: "hall" },
    { id: "agents-board", href: "/drum-agents-board", label: "board", sub: "leaderboard" },
    { id: "quintet", href: "/drum-quintet", label: "quintet", sub: "5-ai composition" },
    { id: "altars", href: "/drum-altars", label: "altars", sub: "noun tribute" },
    { id: "altars-tv", href: "/drum-altars-tv", label: "altars·tv", sub: "cast view" },
    { id: "bell-fall", href: "/drum-bell-fall", label: "bell fall", sub: "pentatonic rain" },
    { id: "bell-jar", href: "/drum-bell-jar", label: "bell jar", sub: "shake the glass" },
    { id: "pendulum", href: "/drum-pendulum", label: "pendulum", sub: "meditative bell" },
    { id: "vespers", href: "/drum-vespers", label: "vespers", sub: "bells on the hour" },
    { id: "saint", href: "/drum-saint", label: "saint", sub: "patron noun" },
    { id: "fives", href: "/drum-fives", label: "fives", sub: "wing index" },
    { id: "shrine", href: "/drum-shrine", label: "shrine", sub: "noun of the day" },
    { id: "rosary", href: "/drum-rosary", label: "rosary", sub: "20 beads" },
    { id: "koan", href: "/drum-koan", label: "koan", sub: "noun + phrase" },
    { id: "prayer-flag", href: "/drum-prayer-flag", label: "flags", sub: "nine in the wind" },
    { id: "mantra", href: "/drum-mantra", label: "mantra", sub: "type, set, hold" },
    { id: "aurora", href: "/drum-aurora", label: "aurora", sub: "oklch breath" },
    { id: "lantern", href: "/drum-lantern", label: "lantern", sub: "release into sky" },
    { id: "bath", href: "/drum-bath", label: "bath", sub: "12-min daylight" },
    { id: "meditate", href: "/drum-meditate", label: "meditate", sub: "5-min breath" },
    { id: "holding-back", href: "/drum-holding-back", label: "holding back", sub: "simply red · em pent" },
    { id: "station", href: "/drum-station", label: "station", sub: "5 intentions" },
    { id: "zen", href: "/drum-zen", label: "zen", sub: "rake the sand" },
    { id: "tide", href: "/drum-tide", label: "tide", sub: "pink-noise ocean" },
    { id: "tape", href: "/drum-tape", label: "tape", sub: "60-noun reel" },
    { id: "grid", href: "/nouns-grid", label: "grid", sub: "144 nouns" },
    { id: "stamps", href: "/nouns-stamps", label: "stamps", sub: "noun postage" },
    { id: "agent-room", href: "/drum-agent", label: "agent room", sub: "machine" },
    { id: "meet", href: "/drum-meet", label: "meet", sub: "welcome" },
    { id: "tv-meet", href: "/drum-tv-meet", label: "tv·meet", sub: "projection" },
    { id: "press", href: "/drum-press", label: "press", sub: "catalog" },
    { id: "birthday", href: "/drum-birthday", label: "birthday", sub: "hub" },
    { id: "cake", href: "/drum-cake", label: "cake", sub: "candles" },
    { id: "card", href: "/drum-card", label: "card", sub: "signatures" },
    { id: "pinata", href: "/drum-pinata", label: "pinata", sub: "burst" },
    { id: "vs", href: "/drum-vs", label: "vs", sub: "1v1 tug" },
    { id: "league", href: "/drum-league", label: "league", sub: "this week" },
    { id: "solo", href: "/drum-solo", label: "solo", sub: "campaign" },
    { id: "portrait", href: "/drum-portrait", label: "portrait", sub: "fingerprint" },
    { id: "relay", href: "/drum-relay", label: "relay", sub: "4-beat chain" },
    { id: "daily", href: "/drum-daily", label: "daily", sub: "beat of day" },
    { id: "stickers", href: "/drum-stickers", label: "stickers", sub: "binder" },
    { id: "postcard", href: "/drum-postcard", label: "postcard", sub: "receipt" },
    { id: "confessional", href: "/drum-confessional", label: "soft", sub: "one-line" },
    { id: "shout", href: "/drum-shout", label: "shout", sub: "mic" },
    { id: "applause", href: "/drum-applause", label: "clap", sub: "meter" },
    { id: "letters", href: "/drum-letters", label: "letters", sub: "next visitor" },
    { id: "bulletin", href: "/drum-bulletin", label: "bulletin", sub: "pinboard" },
    { id: "walkie", href: "/drum-walkie", label: "walkie", sub: "ptt 4ch" },
    { id: "graffiti", href: "/drum-graffiti", label: "graffiti", sub: "wall" },
    { id: "emoji-mesh", href: "/drum-emoji-mesh", label: "emoji", sub: "storm" },
    { id: "buttons", href: "/drum-buttons", label: "buttons", sub: "one-shots" },
    { id: "trophies", href: "/drum-trophies", label: "trophies", sub: "on-chain" },
    { id: "apr26", href: "/drum-apr26", label: "sequencer", sub: "apr 26" },
    { id: "tv", href: "/drum-tv", label: "tv", sub: "cast mode" },
    { id: "tv2", href: "/drum-tv-v2", label: "venue", sub: "tv v2" },
    { id: "tv-bingo", href: "/drum-tv-bingo", label: "bingo", sub: "tv game" },
    { id: "tv-gauntlet", href: "/drum-tv-gauntlet", label: "gauntlet", sub: "tv 60s race" },
    { id: "tv-roulette", href: "/drum-tv-roulette", label: "roulette", sub: "tv wheel" },
    { id: "viz", href: "/drum-viz", label: "viz", sub: "tv v3" },
    { id: "marquee", href: "/drum-marquee", label: "marquee", sub: "tv min" },
    { id: "radio", href: "/drum-radio", label: "radio", sub: "96.1 fm" },
    { id: "radio2", href: "/drum-radio-v2", label: "radio v2", sub: "the dial" },
    { id: "mcp", href: "/api/mcp", label: "mcp", sub: "agents" },
    { id: "room", href: "/drum-room", label: "room", sub: "live chamber" },
    { id: "echo", href: "/drum-echo", label: "echo", sub: "call & response" },
    { id: "procession", href: "/drum-procession", label: "procession", sub: "collective advance" },
    { id: "now", href: "/drum-now", label: "now", sub: "wing presence" },
    { id: "lobby-tv", href: "/drum-lobby-tv", label: "lobby tv", sub: "big-screen" },
    { id: "scorebook", href: "/drum-scorebook", label: "scorebook", sub: "machine-readable ledger" },
    { id: "agent-altar", href: "/drum-agent-altar", label: "agent altar", sub: "control surface" },
    { id: "conductor", href: "/drum-conductor", label: "conductor", sub: "ops console" },
    { id: "threshold", href: "/drum-threshold", label: "threshold", sub: "arrival candles" },
    { id: "offering", href: "/drum-offering", label: "offering", sub: "intentions" },
    { id: "reception-tv", href: "/drum-reception-tv", label: "reception", sub: "projection" },
    { id: "table", href: "/drum-table", label: "table", sub: "5-seat instrument" },
    { id: "name-card", href: "/drum-name-card", label: "name card", sub: "shareable welcome" },
    { id: "yee-choir", href: "/yee-choir", label: "yee choir", sub: "collective confetti" },
    { id: "radio-room", href: "/drum-radio-room", label: "radio room", sub: "shared dial" },
    { id: "duel-hr", href: "/drum-duel", label: "duel", sub: "1v1 tap race" },
    { id: "warhol-live", href: "/drum-warhol-live", label: "warhol live", sub: "24 shared tiles" },
    { id: "relay-2", href: "/drum-relay-2", label: "relay 2", sub: "pass-the-beat chain" }
  ];
  return renderTemplate`${maybeRenderHead()}<nav class="drum-nav" aria-label="Drum room variants"> <span class="drum-nav__label">drum room</span> <ul class="drum-nav__list" role="list"> ${links.map((l) => renderTemplate`<li class="drum-nav__item"> <a${addAttribute(l.href, "href")}${addAttribute(`drum-nav__pill${l.id === current ? " drum-nav__pill--active" : ""}`, "class")}${addAttribute(l.id === current ? "page" : void 0, "aria-current")}> <span class="drum-nav__pill-label">${l.label}</span> <span class="drum-nav__pill-sub">${l.sub}</span> </a> </li>`)} </ul> </nav>`;
}, "/Users/michaelhoydich/Documents/join us yee/pointcast-shipping/src/components/DrumNav.astro", void 0);

export { $$DrumNav as $ };
