import { c as createComponent } from './astro-component_DWMcTjG3.mjs';
import 'piccolore';
import { m as maybeRenderHead, b as addAttribute, a as renderTemplate, c as renderSlot } from './prerender_CmTjnOuJ.mjs';
import 'clsx';

const $$MicroAppShell = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$props, $$slots);
  Astro2.self = $$MicroAppShell;
  const { app, headline, dek, images = [], stats = [], links = [] } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<main class="micro-app" data-astro-cid-6t7dfeyw> <nav class="crumb" aria-label="Breadcrumb" data-astro-cid-6t7dfeyw> <a href="/" data-astro-cid-6t7dfeyw>Home</a> <span aria-hidden="true" data-astro-cid-6t7dfeyw>/</span> <a href="/apps" data-astro-cid-6t7dfeyw>apps</a> <span aria-hidden="true" data-astro-cid-6t7dfeyw>/</span> <span data-astro-cid-6t7dfeyw>${app.slug}</span> </nav> <header class="micro-hero" data-astro-cid-6t7dfeyw> <div class="micro-hero__copy" data-astro-cid-6t7dfeyw> <p class="kicker" data-astro-cid-6t7dfeyw>${app.channel} · ${app.kicker}</p> <h1 data-astro-cid-6t7dfeyw>${headline}</h1> <p data-astro-cid-6t7dfeyw>${dek}</p> <div class="micro-actions"${addAttribute(`${app.name} routes`, "aria-label")} data-astro-cid-6t7dfeyw> <a${addAttribute(app.path, "href")} data-astro-cid-6t7dfeyw>App</a> <a href="/apps" data-astro-cid-6t7dfeyw>Index</a> ${links.map((link) => renderTemplate`<a${addAttribute(link.href, "href")} data-astro-cid-6t7dfeyw>${link.label}</a>`)} </div> </div> <figure class="micro-hero__visual"${addAttribute(`${app.name} preview`, "aria-label")} data-astro-cid-6t7dfeyw> ${images.length > 0 ? renderTemplate`<div class="micro-mosaic"${addAttribute(Math.min(images.length, 6), "data-count")} data-astro-cid-6t7dfeyw> ${images.slice(0, 6).map((image, index) => renderTemplate`<img${addAttribute(image.src, "src")}${addAttribute(image.alt, "alt")} width="1024" height="1024"${addAttribute(index < 2 ? "eager" : "lazy", "loading")} decoding="async" data-astro-cid-6t7dfeyw>`)} </div>` : renderTemplate`<div class="micro-signal" aria-hidden="true" data-astro-cid-6t7dfeyw> <span data-astro-cid-6t7dfeyw></span><span data-astro-cid-6t7dfeyw></span><span data-astro-cid-6t7dfeyw></span><span data-astro-cid-6t7dfeyw></span> </div>`} </figure> </header> ${stats.length > 0 && renderTemplate`<section class="micro-stats"${addAttribute(`${app.name} stats`, "aria-label")} data-astro-cid-6t7dfeyw> ${stats.map((stat) => renderTemplate`<article data-astro-cid-6t7dfeyw> <span data-astro-cid-6t7dfeyw>${stat.label}</span> <strong data-astro-cid-6t7dfeyw>${stat.value}</strong> </article>`)} </section>`} ${renderSlot($$result, $$slots["default"])} </main>`;
}, "/Users/michaelhoydich/Documents/join us yee/pointcast-shipping/src/components/MicroAppShell.astro", void 0);

export { $$MicroAppShell as $ };
