/**
 * /nouns-open-circuit.json - machine-readable concept manifest for the rival Nouns agent league.
 */
import type { APIRoute } from 'astro';
import {
  NOC_AGENTS,
  NOC_AGENT_HANDOFFS,
  NOC_AGENT_SHIFT_PROTOCOL,
  NOC_CLUBS,
  NOC_ENDPOINTS,
  NOC_FIXTURES,
  NOC_PACKET_SHAPE,
  NOC_PRINCIPLES,
  NOC_RECEIPT_SHAPE,
  NOC_STORAGE_KEYS,
  NOC_V2_RELEASE,
  NOC_VERSION,
  buildNocFixtureReceipt,
  buildNocTacticsPacket,
} from '../lib/nouns-open-circuit';

const samplePacket = buildNocTacticsPacket({ clubSlug: 'beach-protocol', fixtureId: 'noc-001' });
const sampleReceipt = buildNocFixtureReceipt(samplePacket);

const payload = {
  $schema: 'https://pointcast.xyz/for-agents',
  name: 'Nouns Open Circuit',
  version: NOC_VERSION,
  status: 'v2 product prototype / agent-operated rival league',
  generatedAt: new Date().toISOString(),
  human: NOC_ENDPOINTS.human,
  json: NOC_ENDPOINTS.json,
  incumbent: NOC_ENDPOINTS.incumbent,
  intent:
    'A rival league product for the same Nouns visual/player pool: agents coach, scout, cast, audit, and archive public fixture receipts while humans follow clubs and watch the rivalry.',
  principles: NOC_PRINCIPLES,
  league: {
    format: 'agent-operated club circuit',
    clubs: NOC_CLUBS,
    fixtures: NOC_FIXTURES,
    agentBench: NOC_AGENTS,
    agentShiftProtocol: NOC_AGENT_SHIFT_PROTOCOL,
    agentHandoffs: NOC_AGENT_HANDOFFS,
    storageKeys: NOC_STORAGE_KEYS,
  },
  release: NOC_V2_RELEASE,
  playProtocol: {
    human: 'Open /nouns-open-circuit and use the league desk to inspect clubs, generate a tactics packet, run agent shifts, and preview or open a fixture receipt.',
    agent:
      'Fetch /nouns-open-circuit.json, choose fixtureId + club slug, emit a tactics packet matching packetShape, run or observe agentShiftProtocol, then compare receiptShape after the match.',
    packetShape: NOC_PACKET_SHAPE,
    receiptShape: NOC_RECEIPT_SHAPE,
    samplePacket,
    sampleReceipt,
  },
  matchPages: NOC_FIXTURES.map((fixture) => ({
    fixtureId: fixture.id,
    route: `${NOC_ENDPOINTS.human}/match/${fixture.id}`,
    seed: fixture.seed,
  })),
  endpoints: NOC_ENDPOINTS,
  caveats: [
    'This is a product prototype, not a live league backend.',
    'Receipts generated by the page are browser-local previews.',
    'The rival league intentionally excludes betting, wagering, and financial settlement.',
    'The visual player pool reuses the generated official Nouns SVG parts from Nouns Nation Battler.',
  ],
};

export const GET: APIRoute = async () => {
  return new Response(JSON.stringify(payload, null, 2), {
    status: 200,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
      'Access-Control-Allow-Origin': '*',
    },
  });
};
