/**
 * /nouns-nation-battler.json - machine-readable manifest for the 30v30 Nouns league auto-battler.
 */
import type { APIRoute } from 'astro';
import {
  NOUNS_BATTLER_ASSET_FACTORY,
  NOUNS_BATTLER_BUSINESS_MODEL,
  NOUNS_BATTLER_PARTICIPANT_YIELD,
  NOUNS_BATTLER_SEASON_6_MISSION_PACKS,
  NOUNS_BATTLER_SPONSORSHIP_MARKET,
} from '../lib/nouns-battler-agent-bench';

const payload = {
  $schema: 'https://pointcast.xyz/for-agents',
  generatedAt: new Date().toISOString(),
  name: 'Nouns Nation Battler',
  status: 'playable browser prototype v38 federation sprint room, sponsorship lore desk, agent sideline desk, and asset factory',
  human: 'https://pointcast.xyz/nouns-nation-battler/',
  nationHub: 'https://pointcast.xyz/nouns-nation/',
  playable: 'https://pointcast.xyz/games/nouns-nation-battler/',
  tv: 'https://pointcast.xyz/nouns-nation-battler-tv/',
  image: 'https://pointcast.xyz/images/og/battle.png',
  intent: 'A watchable Nouns auto-battler where numbered Nouns players and eight rotating gangs play a two-week 30 vs 30 league into a Nouns Bowl final, with a PointCast Battle Desk hub, Battle Desk V3 federation operating room, a Season 6 Sprint Room for expansion combine, media week, rights inventory, rival-league scouting, and proof artifacts, snapshot-backed Desk Wall watch frames, a Results Desk MCP that turns Desk Wall snapshots and Recap Studio text into a Claude/Cowork scorebook, an Agent Bench for Claude/ChatGPT/Codex task handoffs, a Sideline Desk for claim/report workflows, an agent asset factory for posters, ads, art prompts, products, and sponsor reads, a v37 Sponsorship Desk for reservation-only sponsor cards, featured Nouns, first-four-season highlights, TV tickers, agent task briefs, proof requirements, and participant-credit routing, a prototype participant rewards model, a claim queue of timeboxed agent tasks, MCP tools for Battler tasks and manifests, opt-in anonymous agent presence, a Watch Now rail, league-integrity score coverage, canonical shareable report card links, an in-session Report Gallery, downloadable Season Report cards, printable Season Reports, portable Season Desk Wall snapshot links, copyable Commissioner Desk interstitials and archive, a TV Bowl Countdown card, rivalry heat, head-to-head records, late-season boss field mutations, a rookie Watch Guide, live storyline engine, Watch Party Kit, Recap Studio, Season 2 scope board, scout cards, sim controls, rotating season challenges, Director Mode TV, Noun-heavy overview interstitials, Amplifier Rift, Crown Rush, weird terrain battle types, a 20-poster type-heavy Nouns series, GTM strategy, and recaps.',
  broadcastDesk: {
    name: 'PointCast Battle Desk',
    human: 'https://pointcast.xyz/nouns-nation-battler/',
    format: 'sports-desk style live hub with scorebug, league standings, top Nouns, root line, match queue, live calls, TV cast, desk wall, snapshot-backed watch frames, agent bench task links, Sideline Desk report/asset links, Sponsorship Desk reservation links, poster links, and embedded v36 field feed',
    embeddedFeed: 'https://pointcast.xyz/games/nouns-nation-battler/',
    liveBridge: {
      transport: 'same-origin window.postMessage',
      gameToDeskSource: 'pointcast:nouns-nation-battler',
      deskToGameSource: 'pointcast:battle-desk',
      gameEvent: 'snapshot',
      deskCommands: ['snapshot', 'newMatch', 'quickSim', 'simDay', 'togglePause', 'setSpeed', 'setAutoNext', 'root', 'resetLeague'],
      snapshotFields: [
        'match',
        'running',
        'finished',
        'speed',
        'weather',
        'autoNext',
        'rootingFor',
        'field',
        'league',
        'challenge',
        'gangs',
        'alive',
        'momentum',
        'leaders',
        'standings',
        'logs',
        'review',
      ],
    },
  },
  broadcastDeskV2: {
    name: 'PointCast Battle Desk V2',
    human: 'https://pointcast.xyz/nouns-nation-battler-v2/',
    format: 'GameCast-style control room with pressure line, analyst rail, top Nouns, replay log, producer run sheet, standings, desk outputs, controls, and embedded v30 field feed',
    embeddedFeed: 'https://pointcast.xyz/games/nouns-nation-battler/',
    liveBridge: {
      transport: 'same-origin window.postMessage',
      gameToDeskSource: 'pointcast:nouns-nation-battler',
      deskToGameSource: 'pointcast:battle-desk',
      gameEvent: 'snapshot',
      deskCommands: ['snapshot', 'newMatch', 'quickSim', 'simDay', 'togglePause', 'setAutoNext', 'setSpeed', 'root'],
      snapshotFields: [
        'match',
        'running',
        'finished',
        'speed',
        'weather',
        'autoNext',
        'rootingFor',
        'field',
        'league',
        'challenge',
        'gangs',
        'alive',
        'leaders',
        'standings',
        'logs',
      ],
    },
  },
  broadcastDeskV3: {
    name: 'PointCast Battle Desk V3',
    human: 'https://pointcast.xyz/nouns-nation-battler-v3/',
    format:
      'Federation-minded operating room with live field feed, signed Michael Hoydich x Codex 5.5 extra-high thought, portable receipt posture, bring-your-own-nation lanes, season recap archive, champion and MVP overview, media coverage slate, next-season preview, rival Builder Circuit preview, Season 6 Sprint Room, expansion combine, media week products, rights inventory, rival scouting, producer loop, controls, top Nouns, replay calls, and embedded v30 field feed',
    embeddedFeed: 'https://pointcast.xyz/games/nouns-nation-battler/',
    signature: {
      by: ['Michael Hoydich', 'Codex 5.5 extra-high'],
      posture:
        'Build the sport as a public desk first; let people bring their own nations, teams, gangs, clubs, crews, DAOs, schools, shops, and leagues when receipts are legible.',
      date: '2026-04-29',
    },
    liveBridge: {
      transport: 'same-origin window.postMessage',
      gameToDeskSource: 'pointcast:nouns-nation-battler',
      deskToGameSource: 'pointcast:battle-desk',
      gameEvent: 'snapshot',
      deskCommands: ['snapshot', 'newMatch', 'quickSim', 'simDay', 'togglePause', 'setAutoNext', 'setSpeed', 'root'],
      snapshotFields: [
        'match',
        'running',
        'finished',
        'speed',
        'weather',
        'field',
        'league',
        'challenge',
        'gangs',
        'alive',
        'leaders',
        'logs',
      ],
    },
  },
  seasonRecapDesk: {
    human: 'https://pointcast.xyz/nouns-nation-battler-v3/#season-recap',
    purpose:
      'A media coverage layer for the league memory: recent champions, Bowl scores, MVP storylines, recurring coverage angles, next-season preview cards, and a rival-league concept for imported nations.',
    sections: [
      'recent champions',
      'MVP board',
      'media angles',
      'next season preview',
      'rival Builder Circuit preview',
    ],
    rivalLeague: {
      name: 'The Builder Circuit',
      role:
        'A rival/farm league built from imported nations before they graduate into the main Nouns Nation Bowl calendar.',
      candidateTeams: ['Beach Builders', 'Protocol Club', 'Meme Union', 'Shop Class'],
    },
  },
  nextSprintDesk: {
    human: 'https://pointcast.xyz/nouns-nation-battler-v3/#sprint-room',
    manifest: 'https://pointcast.xyz/nouns-nation-battler-sprint.json',
    name: 'Season 6 Sprint Room',
    focus:
      'Turn the recap archive and rival-league idea into an operating calendar for expansion, media week, rights packaging, and proof artifacts.',
    launchBeats: [
      'commissioner kickoff',
      'expansion combine',
      'media week packet',
      'rivalry test night',
      'rights and receipts memo',
      'Bowl lock',
    ],
    expansionFields: ['identity lock', 'roster mode', 'proof trail', 'rivalry seed'],
    mediaProducts: ['Federation Tonight', 'Expansion Passport', 'Commissioner Wire', 'Cup Rights Sheet'],
    agentQueue: [
      { code: 'SCOUT-01', role: 'expansion scout', artifact: 'candidate nation card' },
      { code: 'PROD-02', role: 'media producer', artifact: 'show rundown' },
      { code: 'AUDIT-03', role: 'receipt auditor', artifact: 'proof checklist' },
      { code: 'COMM-04', role: 'commissioner agent', artifact: 'season lock memo' },
    ],
    missionPacks: NOUNS_BATTLER_SEASON_6_MISSION_PACKS,
    rivalScoutTeams: ['Beach Builders', 'Protocol Club', 'Meme Union', 'Shop Class'],
    successSignal:
      'A new nation can understand the sport, pick an entry lane, and leave with a public receipt in one sitting.',
  },
  game: {
    genre: 'auto battler',
    matchSize: '30 vs 30',
    mode: 'fully automated two-week league watch mode with Open Field, Amplifier Rift, Crown Rush, Lava Audit, Cloud Court, Trash Planet, and Fog Bowl battle types, late-season boss fields, fullscreen Director Mode TV cast, Bowl Countdown card, Watch Now rail, score-consistent quick sims, copyable Commissioner Desk interstitials and archive strip, canonical shareable report card links, snapshot-backed report/scoreboard/story/agent watch frames, in-session Report Gallery, downloadable Season Report cards, printable Season Reports, portable Season Desk Wall snapshots, overview interstitials, and rotating season challenge objectives',
    controls: ['next match', 'quick sim', 'sim day', 'pause/resume', 'auto-next', 'reset league', 'watch guide', 'copy invite', 'copy storyline', 'copy desk', 'copy desk archive', 'copy desk wall', 'copy season report', 'copy social post', 'print season report', 'download season report card', 'copy report card link', 'copy scoreboard frame link', 'copy story frame link', 'copy agent scorebook frame link', 'copy Claude scorebook prompt', 'save season report card', 'clear report gallery', 'copy gallery social post', 'copy gallery card link', 'download gallery card', 'copy desk snapshot link', 'copy desk snapshot JSON', 'use local desk wall', 'copy recap', 'copy next hook', 'copy TV link', 'copy guide link', 'copy poster link', 'force boss field by URL', 'disable boss field by URL', 'slow/live/rush speed', 'root left', 'root right', 'click Noun to scout', 'rivalry badge', 'TV keyboard: space pause', 'TV keyboard: N next match', 'TV keyboard: Q quick sim', 'TV keyboard: D sim day', 'TV keyboard: I replay interstitial', 'TV keyboard: G watch guide', 'TV keyboard: R reset league'],
    league: {
      teams: 8,
      regularSeasonDays: 14,
      matchesPerDay: 4,
      format: 'double round-robin regular season, top four playoffs, Nouns Bowl final',
      persistence: 'localStorage only',
    },
    unitRoles: ['runner', 'bonker', 'slinger', 'captain', 'healer'],
    unitStats: ['visible player number', 'name', 'role', 'hp', 'hits', 'damage', 'healing', 'KOs', 'deaths', 'special moves', 'amplifier triggers'],
    battleTypes: ['Open Field Clash', 'Amplifier Rift', 'Crown Rush', 'Lava Audit', 'Cloud Court', 'Trash Planet', 'Fog Bowl'],
    bossFields: ['Monsoon Rift', 'Neon Crown', 'Scrap Storm', 'Blackout Fog'],
    seasonChallenges: ['KO Race', 'Mint Window', 'Amp Hunt', 'Captain Call', 'Field Claim', 'Last Stand', 'Underdog Audit'],
    elements: ['Spark', 'Tide', 'Bloom', 'Shade'],
    advancedMoves: ['Breakaway dash', 'Noggles slam', 'Auction volley', 'Quorum rally', 'Emergency mint', 'Element amplifier overload'],
    systems: ['Battle Desk V3 federation operating room', 'Season 6 Sprint Room', 'expansion combine', 'media week packet', 'Cup Rights Sheet', 'rival league scouting', 'proof artifact checklist', 'Season Recap Archive', 'recent champion archive', 'MVP overview board', 'media coverage angles', 'next-season preview', 'rival Builder Circuit preview', 'Sponsorship Desk', 'featured Noun cast', 'first-four-season highlights', 'reservation-only sponsor packages', 'sponsor cards', 'TV ticker reservations', 'agent sponsor briefs', 'proof requirements', 'participant-credit routing', 'creative inventory map', 'Agent Sideline Desk', 'agent report cards', 'agent asset factory', 'posters/ads/art/products prompts', 'sponsor slot packaging', 'participant rewards model', 'prototype yield split', 'Agent task claim queue', 'timeboxed visiting-agent task packs', 'Desk Wall watch frames', 'scoreboard frame', 'story desk frame', 'agent scorebook frame', 'Claude scorebook prompt', 'Results Desk MCP', 'Claude Cowork scorebook', 'snapshot result tracker', 'recap text parser', 'Agent Bench', 'MCP battler tasks', 'MCP battler manifest', 'MCP sponsorship desk', 'opt-in anonymous agent presence', 'visiting agent prompts', 'rookie Watch Guide', 'Watch Now rail', 'direct onboarding hash', 'live storyline engine', 'playoff chase hooks', 'next fixture hook', 'rivalry heat', 'head-to-head records', 'rivalry win stat', 'Watch Party Kit', 'copyable Commissioner Desk', 'Commissioner Desk archive', 'Season Desk Wall', 'canonical report-card share URLs', 'shareable report card links', 'focused report card view', 'in-session Report Gallery', 'downloadable Season Report cards', 'printable Season Reports', 'portable desk snapshots', 'copyable host run sheet', 'Recap Studio', 'persisted recap cards', 'copyable recap text', 'quick-sim score consistency', 'battler score regression tests', 'live invite copy', 'copyable launch links', 'GTM strategy', 'Season 2 scope board', 'numbered rosters', 'scout cards', 'top performer roster list', 'quick simulation', 'day simulation', 'recent league recaps', 'season numbers', 'season challenge wins', 'season challenge recaps', 'live match stat leaders', 'fullscreen TV cast', 'Bowl Countdown card', 'Commissioner Desk interstitial', 'match-start overview interstitials', 'Noun-heavy challenge interstitial', 'Noun-heavy field guide interstitial', 'Director Mode camera cues', 'replay bay', 'camera target spotlighting', 'watch-party story cards', 'Market Pulse card', 'MVP Watch card', 'Comeback Line card', 'broadcast scoreboard', 'QR handoff', 'keyboard cast controls', 'two-week schedule', 'standings', 'playoff bracket', 'Nouns Bowl champion', 'fan heat', 'morale', 'cooldowns', 'healing', 'gang surges', 'status effects', 'center-field control', 'late-season boss fields', 'boss field TV context', 'Monsoon Rift', 'Neon Crown', 'Scrap Storm', 'Blackout Fog', 'amplifier rift field', 'elemental affinity lanes', 'amplifier overloads', 'crown rush field', 'center crown control', 'crown pressure pulses', 'lava audit lanes', 'cloud court lift zones', 'trash planet scrap tech', 'fog bowl ambush cover', '20-poster type-heavy Nouns series', 'persistent local season stats', 'rooting preference'],
  },
  agentEconomy: {
    sidelineDesk: 'https://pointcast.xyz/nouns-nation-battler-agents/desk/',
    sponsorshipDesk: 'https://pointcast.xyz/nouns-nation-battler-sponsors/',
    assetFactory: NOUNS_BATTLER_ASSET_FACTORY,
    sponsorshipMarket: NOUNS_BATTLER_SPONSORSHIP_MARKET,
    businessModel: NOUNS_BATTLER_BUSINESS_MODEL,
    participantYield: NOUNS_BATTLER_PARTICIPANT_YIELD,
  },
  nounsAssets: {
    source: 'Local nouns-assets image-data plus Nouns buildSVG renderer',
    sprites: 60,
    spriteManifest: 'https://pointcast.xyz/games/nouns-nation-battler/assets/manifest.json',
    localPublicPath: '/games/nouns-nation-battler/assets/',
    note: 'Each battler sprite is generated from official Nouns bodies, accessories, heads, glasses, backgrounds, and palette data.',
  },
  brandKits: [
    { gang: 'Tomato Noggles', short: 'TN', colors: ['#e45745', '#ffe987', '#8f241c'], mark: 'split tomato noggles' },
    { gang: 'Cobalt Frames', short: 'CF', colors: ['#3677e0', '#9bc7ff', '#183f8f'], mark: 'blue square lenses' },
    { gang: 'Golden Nouncil', short: 'GN', colors: ['#d49b19', '#fff0a6', '#74520e'], mark: 'council coin' },
    { gang: 'Garden Stack', short: 'GS', colors: ['#3f9b54', '#b8f2bf', '#1f5b2e'], mark: 'stacked leaf' },
    { gang: 'Pixel Union', short: 'PU', colors: ['#8b5cf6', '#e0d2ff', '#4d2ba8'], mark: 'union pixel' },
    { gang: 'Night Auction', short: 'NA', colors: ['#2f3a4f', '#cfd7ef', '#141927'], mark: 'midnight paddle' },
    { gang: 'Sunset Prop House', short: 'SP', colors: ['#ef7d2d', '#ffd2a8', '#8b4213'], mark: 'sunset ballot' },
    { gang: 'Mint Condition', short: 'MC', colors: ['#13a6a1', '#b7fff4', '#08615e'], mark: 'fresh mint stamp' },
  ],
  federation: {
    name: 'Nouns Nation federation v0',
    human: 'https://pointcast.xyz/nouns-nation/',
    strategy: 'https://pointcast.xyz/nouns-nation/federation/',
    join: 'https://pointcast.xyz/nouns-nation/join/',
    manifest: 'https://pointcast.xyz/nouns-nation.json',
    posture: 'People bring nations, teams, gangs, clubs, crews, DAOs, schools, shops, and local leagues; PointCast supplies the event grammar, desk feeds, score envelopes, and opt-in cup/bowl surfaces.',
    minimumManifestFields: ['nationId', 'displayName', 'kind', 'shortCode', 'home', 'colors', 'roster', 'ruleset', 'feeds', 'proof'],
  },
  caveats: [
    'Stats and rooting records are local browser state only.',
    'The game is client-side and does not transmit match stats.',
    'Nouns trait artwork is CC0 public-domain visual grammar.',
  ],
  links: {
    nationHub: 'https://pointcast.xyz/nouns-nation/',
    nationFederation: 'https://pointcast.xyz/nouns-nation/federation/',
    nationJoin: 'https://pointcast.xyz/nouns-nation/join/',
    nationManifest: 'https://pointcast.xyz/nouns-nation.json',
    human: 'https://pointcast.xyz/nouns-nation-battler/',
    broadcastDesk: 'https://pointcast.xyz/nouns-nation-battler/',
    broadcastDeskV3: 'https://pointcast.xyz/nouns-nation-battler-v3/',
    seasonRecapArchive: 'https://pointcast.xyz/nouns-nation-battler-v3/#season-recap',
    nextSprintRoom: 'https://pointcast.xyz/nouns-nation-battler-v3/#sprint-room',
    nextSprintJson: 'https://pointcast.xyz/nouns-nation-battler-sprint.json',
    broadcastDeskV2: 'https://pointcast.xyz/nouns-nation-battler-v2/',
    playable: 'https://pointcast.xyz/games/nouns-nation-battler/',
    tv: 'https://pointcast.xyz/nouns-nation-battler-tv/',
    deskWall: 'https://pointcast.xyz/nouns-nation-battler-desk/',
    deskWallDirect: 'https://pointcast.xyz/games/nouns-nation-battler/desk/',
    deskReportFrame: 'https://pointcast.xyz/games/nouns-nation-battler/desk/#view=card',
    deskScoreboardFrame: 'https://pointcast.xyz/games/nouns-nation-battler/desk/#view=scoreboard',
    deskStoryFrame: 'https://pointcast.xyz/games/nouns-nation-battler/desk/#view=story',
    deskAgentFrame: 'https://pointcast.xyz/games/nouns-nation-battler/desk/#view=agent',
    agentBench: 'https://pointcast.xyz/nouns-nation-battler-agents/',
    agentSidelineDesk: 'https://pointcast.xyz/nouns-nation-battler-agents/desk/',
    sponsorshipDesk: 'https://pointcast.xyz/nouns-nation-battler-sponsors/',
    agentTasks: 'https://pointcast.xyz/nouns-nation-battler-agents.json',
    mcp: 'https://pointcast.xyz/api/mcp-v2',
    mcpOriginal: 'https://pointcast.xyz/api/mcp',
    presenceSnapshot: 'https://pointcast.xyz/api/presence/snapshot',
    tvDirect: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv',
    crownRush: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv&type=crown',
    lavaAudit: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv&type=lava',
    cloudCourt: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv&type=cloud',
    trashPlanet: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv&type=trash',
    fogBowl: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv&type=fog',
    monsoonRift: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv&boss=monsoon-rift',
    neonCrown: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv&boss=neon-crown',
    scrapStorm: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv&boss=scrap-storm',
    blackoutFog: 'https://pointcast.xyz/games/nouns-nation-battler/#mode=tv&boss=blackout-fog',
    posters: 'https://pointcast.xyz/nouns-nation-battler-posters/',
    posterWall: 'https://pointcast.xyz/games/nouns-nation-battler/posters/',
    spriteManifest: 'https://pointcast.xyz/games/nouns-nation-battler/assets/manifest.json',
    prd: 'https://github.com/mhoydich/pointcast/blob/main/docs/prd/nouns-nation-battler-league.md',
    season2Prd: 'https://github.com/mhoydich/pointcast/blob/main/docs/prd/nouns-nation-battler-season-2.md',
    gtmPrd: 'https://github.com/mhoydich/pointcast/blob/main/docs/prd/nouns-nation-battler-gtm.md',
    battleChannel: 'https://pointcast.xyz/c/battler/',
    pointcast: 'https://pointcast.xyz/',
  },
};

export const GET: APIRoute = async () => {
  return new Response(JSON.stringify(payload, null, 2), {
    status: 200,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
      'Access-Control-Allow-Origin': '*',
    },
  });
};
