/**
 * /api/tezos-metadata/coffee-mugs/[tokenId] — TZIP-21 metadata for the
 * Coffee Mugs FA2 contract (KT1JQ3AjzFvMnjZ9mGqrM13aj8LQBx9JpoXt).
 *
 * Contract concatenates metadata_base_uri + "/" + tokenId + ".json"
 * (see contracts/v2/coffee_mugs_fa2.py register_tokens). The on-chain
 * metadata_base_uri was set via set_metadata_base_uri() to
 *   https://pointcast.xyz/api/tezos-metadata/coffee-mugs
 * so this endpoint answers requests like:
 *   https://pointcast.xyz/api/tezos-metadata/coffee-mugs/0.json
 *
 * Renders TZIP-12/-21 metadata that wallets (Kukai), explorers (TzKT,
 * better-call.dev), and marketplaces (objkt, teia) consume. Image URIs
 * point to static pixel-art SVGs at /images/coffee-mugs/<slug>.svg —
 * generated by scripts/generate-coffee-mug-svgs.mjs from the same data
 * that drives the /coffee page.
 */

interface Env {}

type Slug = 'ceramic' | 'espresso' | 'latte' | 'paper' | 'bistro';

interface MugMeta {
  slug: Slug;
  name: string;
  rarity: string;
  edition: number;
  threshold: number;
  description: string;
}

const TOKEN_ID_TO_MUG: Record<number, MugMeta> = {
  0: {
    slug: 'ceramic',
    name: 'Ceramic Mug',
    rarity: 'common',
    edition: 333,
    threshold: 1,
    description:
      'The first cup. White ceramic with the dark band of fresh pour at the rim. ' +
      'Common-tier, claimed for any visitor who pours their first cup at /coffee. ' +
      'Edition cap 333 — the threshold of becoming a regular.',
  },
  1: {
    slug: 'espresso',
    name: 'Espresso Cup',
    rarity: 'uncommon',
    edition: 144,
    threshold: 3,
    description:
      'Tiny porcelain. Heavy crema. Sits on a saucer. Uncommon-tier mug for ' +
      'visitors who pour 3 cups — the rhythm of someone who keeps coming back. ' +
      'Edition cap 144.',
  },
  2: {
    slug: 'latte',
    name: 'Latte Glass',
    rarity: 'rare',
    edition: 64,
    threshold: 7,
    description:
      'Tall glass, layered foam → milk → coffee. Rare-tier for the visitor who ' +
      'pours seven cups — long enough that the room knows your face. Edition cap 64.',
  },
  3: {
    slug: 'paper',
    name: 'Paper Cup',
    rarity: 'ultra-rare',
    edition: 21,
    threshold: 15,
    description:
      'Sleeve, lid, sip-hole. Coffee on the move. Ultra-rare-tier earned at ' +
      '15 cumulative cups — you take PointCast with you. Edition cap 21.',
  },
  4: {
    slug: 'bistro',
    name: 'Bistro Cup',
    rarity: 'legendary',
    edition: 8,
    threshold: 30,
    description:
      'Wide, low, French. Always with a saucer. The cup of someone who has been ' +
      'pouring for thirty rounds and is still here. Legendary-tier — only 8 ever.',
  },
};

const ARTIST = 'tz2FjJhB1gb9Xc2qNB7QgFkdBZkGCCRMxdFw'; // Mike's mainwallet
const CONTRACT_KT1 = 'KT1JQ3AjzFvMnjZ9mGqrM13aj8LQBx9JpoXt';

export const onRequestGet: PagesFunction<Env> = async ({ params }) => {
  const raw = (params.tokenId as string) ?? '';
  // Strip optional .json — the on-chain URI ends in .json but the route
  // captures the literal segment.
  const m = raw.match(/^(\d+)(?:\.json)?$/);
  if (!m) {
    return new Response(JSON.stringify({ error: 'invalid tokenId' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    });
  }
  const tokenId = Number(m[1]);
  const mug = TOKEN_ID_TO_MUG[tokenId];
  if (!mug) {
    return new Response(
      JSON.stringify({ error: 'tokenId out of range', valid: '0..4' }),
      { status: 404, headers: { 'Content-Type': 'application/json' } },
    );
  }

  const imageUri = `https://pointcast.xyz/images/coffee-mugs/${mug.slug}.svg`;

  const body = {
    name: `PointCast ${mug.name} #${tokenId}`,
    symbol: 'PCMUG',
    decimals: 0,
    isBooleanAmount: false,
    description: mug.description,
    displayUri: imageUri,
    thumbnailUri: imageUri,
    artifactUri: imageUri,
    mime: 'image/svg+xml',
    creators: [ARTIST],
    contributors: [ARTIST],
    publishers: ['PointCast'],
    date: '2026-04-25T20:33:00Z', // origination timestamp
    language: 'en',
    rights: 'No License / All Rights Reserved',
    rightsUri: 'https://pointcast.xyz/about',
    attributes: [
      { name: 'rarity', value: mug.rarity },
      { name: 'edition', value: String(mug.edition) },
      { name: 'threshold', value: `${mug.threshold} cup${mug.threshold === 1 ? '' : 's'}` },
      { name: 'collection', value: 'Coffee Mugs' },
    ],
    tags: ['pointcast', 'coffee-mugs', 'tezos', 'fa2', 'pixel-art', mug.rarity, mug.slug],
    royalties: {
      decimals: 4,
      shares: { [ARTIST]: 750 }, // 7.5%
    },
    formats: [
      {
        uri: imageUri,
        mimeType: 'image/svg+xml',
        dimensions: { value: '512x512', unit: 'px' },
      },
    ],
    homepage: 'https://pointcast.xyz/coffee',
    externalUri: `https://objkt.com/asset/${CONTRACT_KT1}/${tokenId}`,
  };

  return new Response(JSON.stringify(body, null, 2), {
    status: 200,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      // Cache for 1 hour at the edge — metadata changes are rare.
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
      'Access-Control-Allow-Origin': '*',
    },
  });
};
