const w="pc:reactSessionId";function q(){try{let e=localStorage.getItem(w);return e||(e=crypto.randomUUID?.()??`s-${Date.now()}-${Math.random().toString(36).slice(2,10)}`,localStorage.setItem(w,e)),e}catch{return`s-${Date.now()}-${Math.random().toString(36).slice(2,10)}`}}const H=q();function R(){const e=document.getElementById("vv-clock");if(!e)return;const t=new Date;e.textContent=t.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}R();setInterval(R,3e4);const E=[{id:"stadium",label:"The Stadium"},{id:"theater",label:"The Theater"},{id:"lounge",label:"The Lounge"},{id:"underground",label:"Underground"}],I=document.getElementById("vv-root"),b=document.getElementById("vv-venue-name");let g=0;function P(e){g=e%E.length;const t=E[g];I&&(I.dataset.venue=t.id),b&&(b.textContent=t.label)}P(0);setInterval(()=>P(g+1),45e3);const d=new Map;function O(e){let t=0;for(let n=0;n<e.length;n++)t=(t<<5)-t+e.charCodeAt(n);const o=Math.abs(t)%6;return o<2?"front":o<4?"mid":"back"}const V=document.getElementById("vv-tier-front"),_=document.getElementById("vv-tier-mid"),z=document.getElementById("vv-tier-back"),S=document.getElementById("vv-crowd-empty"),T=document.getElementById("vv-cap"),B=document.getElementById("vv-cap-sub");function U(){const e=Array.from(d.values()),t=e.length;T&&(T.textContent=String(t)),B&&(B.textContent=t>=20?"standing room only":t>=5?"crowd is forming":"in attendance"),S&&(S.hidden=t>0),["front","mid","back"].forEach(o=>{const n=o==="front"?V:o==="mid"?_:z;if(!n)return;const s=new Map;n.querySelectorAll("[data-pid]").forEach(r=>s.set(r.dataset.pid||"",r));const i=new Set;e.filter(r=>r.tier===o).forEach(r=>{if(i.add(r.pid),!s.has(r.pid)){const a=document.createElement("div");a.className="vv-seat joining",a.dataset.pid=r.pid,a.dataset.noun=String(r.nounId),a.innerHTML=`
            <img src="https://noun.pics/${r.nounId}.svg" alt="" loading="lazy" />
            <span class="vv-seat-dot" aria-hidden="true"></span>
          `,n.appendChild(a),setTimeout(()=>a.classList.remove("joining"),720)}}),s.forEach((r,a)=>{i.has(a)||(r.classList.add("leaving"),setTimeout(()=>r.remove(),240))})})}function J(e){if(!e)return;const t=document.querySelector(`.vv-seat[data-pid="${e}"]`);t&&(t.classList.remove("cheering"),t.offsetWidth,t.classList.add("cheering"),setTimeout(()=>t.classList.remove("cheering"),800),Y(t))}function Y(e){const t=document.getElementById("vv-beams");if(!t)return;const o=t.getBoundingClientRect(),n=e.getBoundingClientRect(),s=n.left+n.width/2-o.left;if(s<0||s>o.width)return;const i=document.createElement("div"),r=["#ec4899","#f59e0b","#8b5cf6","#06b6d4","#22c55e"],a=r[Math.floor(Math.random()*r.length)];i.className="vv-beam",i.style.left=`${s-2}px`,i.style.setProperty("--beam-color",a),t.appendChild(i),setTimeout(()=>i.remove(),800)}const u=document.getElementById("vv-performer-img"),x=document.getElementById("vv-performer-name"),C=document.getElementById("vv-performer-sub"),f=document.getElementById("vv-performer");let $="";function j(e,t,o,n){e===$&&Date.now()-v<800||(v=Date.now(),$=e,u&&(u.style.opacity="0",setTimeout(()=>{u.src=`https://noun.pics/${t}.svg`,u.style.opacity="1"},200)),x&&(x.textContent=n),C&&(C.textContent=`noun #${t} · ${o}`),f&&(f.classList.remove("changing"),f.offsetWidth,f.classList.add("changing")))}let v=0;async function W(){try{const e=await fetch("/api/visit");if(!e.ok)return;const t=await e.json(),n=(Array.isArray(t.present)?t.present:[]).filter(i=>i.type==="human"&&i.pid).map(i=>({pid:i.pid,nounId:Number(i.nounId)||42})),s=new Set(n.map(i=>i.pid));for(const i of n)d.has(i.pid)||d.set(i.pid,{pid:i.pid,nounId:i.nounId,tier:O(i.pid)});for(const i of[...d.keys()])s.has(i)||d.delete(i);U()}catch{}}W();setInterval(W,8e3);let m="connecting",l=null,M=Date.now();const D=document.getElementById("vv-stream"),k=document.getElementById("vv-stream-sub");function y(e,t){m=e,D&&(D.textContent=e==="ws"?"live · ws":e==="poll"?"live · 150ms":"connecting…"),k&&(k.textContent=t)}y("connecting","resolving transport");const c=[],h=document.getElementById("vv-energy");function G(){const e=Date.now();for(c.push(e);c[0]&&c[0]<e-6e4;)c.shift();h&&(h.textContent=String(c.length))}function Q(){const e=Date.now();c.filter(o=>e-o<2e3).length>=5&&X()}let L=0;function X(){if(Date.now()-L<6e3)return;L=Date.now();const e=document.getElementById("vv-confetti");if(!e)return;const t=["#ec4899","#f59e0b","#8b5cf6","#06b6d4","#22c55e","#fbbf24"];for(let o=0;o<60;o++){const n=document.createElement("span"),s=t[Math.floor(Math.random()*t.length)];n.style.cssText=`
        position: absolute;
        left: ${Math.random()*100}%;
        top: -50px;
        width: 8px;
        height: 14px;
        background: ${s};
        --cx: ${(Math.random()-.5)*200}px;
        --rot: ${(Math.random()-.5)*720}deg;
        animation: vv-confetti-fall ${2200+Math.random()*1500}ms ease-in forwards;
        animation-delay: ${Math.random()*800}ms;
        pointer-events: none;
      `,e.appendChild(n),setTimeout(()=>n.remove(),4500)}}function F(e){if(!e||typeof e!="object")return;const t=e.type;let o=42,n="tap",s="stage";if(t==="drum")o=42,n="Drumming",s="classic";else if(t==="orchestra")o=200,n=String(e.inst||e.cellKey||"Orchestra"),s="orchestra";else if(t==="choir"||t==="choir-chord")o=888,n=String(e.voice||e.chord||"Choir"),s="choir";else if(t==="lounge")o=77,n=String(e.voice||"Saxophone"),s="lounge";else if(t==="symphony")o=88,n=String(e.seatKey||e.family||"Symphony"),s="symphony";else return;n=n.charAt(0).toUpperCase()+n.slice(1).replace(/-/g," "),e.pid&&!d.has(e.pid)&&(d.set(e.pid,{pid:e.pid,nounId:o,tier:O(e.pid)}),U()),e.pid&&J(e.pid),e.pid&&j(e.pid,o,s,n),G(),Q()}function K(){try{const t=`${window.location.protocol==="https:"?"wss:":"ws:"}//${window.location.host}/api/drum/room?sid=${encodeURIComponent(H)}`;l=new WebSocket(t),l.addEventListener("open",()=>y("ws","~30–60ms p50")),l.addEventListener("message",o=>{try{F(JSON.parse(o.data))}catch{}}),l.addEventListener("close",()=>{m==="connecting"?p("ws unavailable · 150ms poll"):m==="ws"&&setTimeout(K,2e3)}),l.addEventListener("error",()=>{m==="connecting"&&p("ws error · 150ms poll")})}catch{p("ws not supported · 150ms poll")}}function p(e){y("poll",e),setInterval(()=>{document.visibilityState==="visible"&&Z()},150)}async function Z(){try{const e=await fetch(`/api/sounds?since=${M}`);if(!e.ok)return;const t=await e.json();typeof t.now=="number"&&(M=t.now);const o=Array.isArray(t.events)?t.events:[];for(const n of o)F(n)}catch{}}K();setTimeout(()=>{m==="connecting"&&p("ws timeout · 150ms poll")},1500);setInterval(()=>{const e=Date.now();for(;c[0]&&c[0]<e-6e4;)c.shift();h&&(h.textContent=String(c.length))},2e3);const A=[{id:42,name:"The House Drum",surface:"classic"},{id:888,name:"The Choir",surface:"choir"},{id:77,name:"Songbird",surface:"lounge"},{id:200,name:"The Bass",surface:"orchestra"},{id:808,name:"The Big",surface:"big"},{id:88,name:"The Symphony",surface:"symphony"}];let N=0;setInterval(()=>{if(Date.now()-v<8e3)return;const e=A[N%A.length];N++,j("idle",e.id,e.surface,e.name)},5e3);
