const d=document.querySelector(".marketplace"),f=d?.getAttribute("data-marketplace-kt1")||"",$=Number(d?.getAttribute("data-platform-bps")||"250"),m=d?.getAttribute("data-treasury")||"",b=d?.getAttribute("data-royalty-receiver")||m,l=t=>`${Number(t||0).toLocaleString(void 0,{maximumFractionDigits:6})} ꜩ`,i=t=>t?`${t.slice(0,7)}…${t.slice(-5)}`:"pending",h=t=>`https://api.tzkt.io/v1/contracts/${t}/storage`;function E(t){const e=t.token_id??t.tokenId??0,n=String(t.fa2_contract||t.fa2||"").toLowerCase(),o="KT1LP1oTBuudRubAYQDErH7i7mSwazVdohxh".toLowerCase(),c="KT1JQ3AjzFvMnjZ9mGqrM13aj8LQBx9JpoXt".toLowerCase(),a=["ceramic","espresso","latte","paper","bistro"];return n===o?`/api/tezos-token-card/${e}.svg`:n===c?`/images/coffee-mugs/${a[Number(e)]||"ceramic"}.svg`:"/images/og/og-home-v2.png"}function B(t){const e=String(t||"").toLowerCase();return e==="kt1lp1otbuudrubayqderh7i7mswazvdohxh"?"Visit Nouns":e==="kt1jq3ajzfvmnjz9mgqrm13aj8lqbX9jpoxt".toLowerCase()?"Coffee Mugs":"PointCast NFT"}async function w(){const t=document.getElementById("marketplace-asks"),e=document.getElementById("contract-status"),n=document.getElementById("status-dot");if(!(!t||!e||!n)){if(!f.startsWith("KT1")){e.textContent="marketplace contract pending",t.innerHTML='<li class="empty mono">contract pending · deploy from /admin/deploy</li>';return}try{const o=await fetch(h(f)).then(r=>r.json());n.setAttribute("data-live",String(!o.paused)),e.textContent=o.paused?"contract paused":`live · next ask ${o.next_ask_id}`;const c=o.asks,a=await fetch(`https://api.tzkt.io/v1/bigmaps/${c}/keys?active=true&limit=12&sort.desc=id`).then(r=>r.json());if(!Array.isArray(a)||a.length===0){t.innerHTML='<li class="empty mono">no open asks yet · list the first token on /market</li>';return}t.innerHTML=a.map(r=>{const s=r.value||{},g=r.key??r.id,I=Number(s.amount_mutez||0)/1e6,y=s.token_id??0,u=B(s.fa2_contract);return`
          <li class="ask-card">
            <img src="${E(s)}" alt="${u} #${y}" loading="lazy" />
            <div>
              <p class="mono">${u} · ask ${g} · seller ${i(String(s.seller||""))}</p>
              <h3>${u} #${y}</h3>
              <p class="mono">${l(I)} · royalty ${(Number(s.royalty_bps||0)/100).toFixed(2)}%</p>
            </div>
            <a class="button button--dark mono" href="/market#ask-${g}">Buy / inspect</a>
          </li>
        `}).join("")}catch(o){console.error(o),e.textContent="status unavailable",t.innerHTML='<li class="empty mono">could not load TzKT asks · open /market directly</li>'}}}function k(){const t=Number(document.getElementById("calc-price")?.value||0),e=Number(document.getElementById("calc-royalty")?.value||0),n=Number(document.getElementById("calc-referral")?.value||0),o=t*($/1e4),c=t*(e/100),a=t*(n/100),r=Math.max(0,t-o-c-a);document.getElementById("split-seller").textContent=l(r),document.getElementById("split-platform").textContent=`${l(o)} → ${i(m)}`,document.getElementById("split-royalty").textContent=`${l(c)} → ${i(b)}`,document.getElementById("split-referral").textContent=l(a)}function p(t,e){navigator.clipboard?.writeText(t).catch(()=>{}),e&&(e.textContent=t)}function v(){const t=document.getElementById("trade-tickets");if(!t)return;const e=JSON.parse(localStorage.getItem("pc:marketplace:tickets:v1")||"[]");t.innerHTML=e.length?e.map(n=>`
        <li class="ticket-card">
          <div>
            <p class="mono">${i(n.wallet)} · ${new Date(n.createdAt).toLocaleDateString()}</p>
            <strong>Offering ${n.offer||"open offer"} for ${n.want||"best PointCast trade"}</strong>
          </div>
          <button class="button mono" type="button" data-ticket-share="${n.id}">Share</button>
        </li>
      `).join(""):'<li class="empty mono">no local trade tickets yet</li>',t.querySelectorAll("[data-ticket-share]").forEach(n=>{n.addEventListener("click",()=>{const o=e.find(a=>a.id===n.getAttribute("data-ticket-share"));if(!o)return;const c=`${location.origin}/marketplace?ticket=${encodeURIComponent(o.id)}&offer=${encodeURIComponent(o.offer)}&want=${encodeURIComponent(o.want)}`;p(c,document.getElementById("share-output"))})})}document.getElementById("fee-calc")?.addEventListener("input",k);document.getElementById("copy-market-link")?.addEventListener("click",()=>{p(`${location.origin}/marketplace`,document.getElementById("share-output"))});document.getElementById("ref-form")?.addEventListener("submit",()=>{const t=document.getElementById("ref-wallet")?.value||m,e=document.getElementById("ref-target")?.value||"/marketplace",n=`${location.origin}${e}?ref=${encodeURIComponent(t)}`;p(n,document.getElementById("share-output"))});document.getElementById("trade-form")?.addEventListener("submit",()=>{const t=JSON.parse(localStorage.getItem("pc:marketplace:tickets:v1")||"[]");t.unshift({id:`pc-trade-${Date.now().toString(36)}`,wallet:document.getElementById("trade-wallet")?.value||m,offer:document.getElementById("trade-offer")?.value||"",want:document.getElementById("trade-want")?.value||"",createdAt:new Date().toISOString()}),localStorage.setItem("pc:marketplace:tickets:v1",JSON.stringify(t.slice(0,12))),document.getElementById("trade-offer").value="",document.getElementById("trade-want").value="",v()});k();v();w();
