/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: b171e1d678533029b1b657cea9491c8c)
interface __BaseEnv_Env {
	VOICE_ENABLED: string;
	SITE_ORIGIN: string;
	POINTCAST_ORIGIN: string;
	ENVIRONMENT: string;
	MAX_SESSIONS: string;
	EXPERIMENT_END: string;
	VOICE_SUPERVISOR: DurableObjectNamespace<import("./src/index").VoiceSupervisor>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "VoiceSupervisor";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VOICE_ENABLED" | "SITE_ORIGIN" | "POINTCAST_ORIGIN" | "ENVIRONMENT" | "MAX_SESSIONS" | "EXPERIMENT_END">> {}
}
