export async function onRequest(context: EventContext<Env, any, any>) {
  // Serve the domain-level Mini App manifest required by Farcaster clients.
  // Public account association generated by Farcaster Developer Tools for
  // pointcast.xyz. Cloudflare env can override it without a code deploy.
  let accountAssociation: unknown = {
    header: "eyJmaWQiOjQ1NDExMSwidHlwZSI6ImN1c3RvZHkiLCJrZXkiOiIweEIxNTA0NmM4RTdEY2ExNjJiQTJEODU1MUE5OTBhMTI4NThjNUY0NzUifQ",
    payload: "eyJkb21haW4iOiJwb2ludGNhc3QueHl6In0",
    signature: "BZfGZt2LTnf3Yg1FcePEBe/yEgb1IuUJwGyicKqHxVcLU01Dkl7Jy53erCqR0Y4PxmesBV9andvdc0O8qM+jchw="
  };
  const rawAccountAssociation = (context.env as any).POINTCAST_FARCASTER_ACCOUNT_ASSOCIATION;
  if (typeof rawAccountAssociation === "string" && rawAccountAssociation.trim()) {
    try {
      accountAssociation = JSON.parse(rawAccountAssociation);
    } catch {
      accountAssociation = null;
    }
  }

  const manifest = {
    ...(accountAssociation ? { accountAssociation } : {}),
    miniapp: {
      version: "1",
      name: "Noun Drum Rack",
      iconUrl: "https://pointcast.xyz/images/drum-icon.png",
      splashImageUrl: "https://pointcast.xyz/images/drum-splash.png",
      splashBackgroundColor: "#ffffff",
      homeUrl: "https://pointcast.xyz/drum",
      subtitle: "A collaborative drum rack",
      description: "Play drums with the Farcaster community and track your hits in real-time.",
      primaryCategory: "entertainment",
      tags: ["music", "drums", "social", "nouns"],
      heroImageUrl: "https://pointcast.xyz/images/drum-og.png",
      ogTitle: "Noun Drum Rack",
      ogDescription: "Play drums with the Farcaster community and track your hits in real-time.",
      ogImageUrl: "https://pointcast.xyz/images/drum-og.png"
    }
  };

  return new Response(JSON.stringify(manifest), {
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*"
    }
  });
}
