/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/shwa-rooms/wrangler.jsonc --include-runtime=false --strict-vars=false workers/shwa-rooms/worker-configuration.d.ts` (hash: 6df00ce75923b004c3bec91d8e10312d)
interface __BaseEnv_Env {
	CREATION_LIMIT: RateLimit;
	JOIN_LIMIT: RateLimit;
	ROOMS: DurableObjectNamespace<import("./src/index").ShwaRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ShwaRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
