import type { APIRoute } from 'astro';
import {
  AUDIO_COMPANIONS,
  PASS_25,
  PASSPORT_DOORS,
  PASSPORT_LENSES,
  PASSPORT_STAMPS,
  PINTEREST_BOARDS,
  PINTEREST_PINS,
  SPOTIFY_SERIES,
  TREASURE_ROUTES,
} from '../../../lib/radius25-passport';

export const GET: APIRoute = () => new Response(JSON.stringify({
  ...PASS_25,
  premise: 'A public-place check-in can record an act of attention without collecting location, identity, media, or social proof.',
  lenses: PASSPORT_LENSES,
  stamps: PASSPORT_STAMPS,
  treasureRoutes: TREASURE_ROUTES,
  doors: PASSPORT_DOORS,
  audioCompanions: AUDIO_COMPANIONS,
  spotifySeries: SPOTIFY_SERIES,
  pinterest: {
    boards: PINTEREST_BOARDS,
    pinCount: PINTEREST_PINS.length,
    pins: PINTEREST_PINS,
  },
  interaction: {
    availability: 'human HTML companion only',
    checkIn: 'manual visitor selection of a public door, lens, and completed observation stamp',
    defaultPersistence: 'page memory for the current session',
    optionalPersistence: 'browser localStorage only after the visitor presses Save on this device',
    export: 'user-controlled local JSON download',
    erase: 'user-controlled removal of the pointcast.pass25.v1 localStorage key',
    audio: 'gesture-started Web Audio oscillator sketches; no samples, recording, microphone, upload, or autoplay',
    geolocation: false,
    account: false,
    camera: false,
    microphone: false,
    cookies: false,
    analytics: false,
    networkWrites: false,
    automaticSharing: false,
  },
  boundaries: {
    official: false,
    liveConditions: false,
    routePlanning: false,
    permit: false,
    reservation: false,
    safetyCheck: false,
    geofence: false,
    collection: 'Observe, draw, listen, and remember. Do not remove shells, rocks, plants, animals, artifacts, tide life, or site material.',
    publicDoor: 'A listed door has a direct official or operating-steward source in OPEN/25. It does not guarantee current access or availability of every feature.',
    providerAudio: 'Spotify supplies its own music, metadata, account gates, and playback. PointCast does not proxy or restream Spotify audio.',
  },
}, null, 2), {
  headers: {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'public, max-age=300, s-maxage=3600',
    'Access-Control-Allow-Origin': '*',
    Link: '<https://pointcast.xyz/beach-commons/v18/passport>; rel="alternate"; type="text/html"',
  },
});
