name = "pointcast-keyboard-studio"
main = "src/index.ts"
compatibility_date = "2026-09-24"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[durable_objects.bindings]]
name = "KEYBOARD_STUDIO"
class_name = "KeyboardStudioRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["KeyboardStudioRoom"]
